// ACTUALIZED Profile — Young Adult (18–29)
// Parser Profile™ © 2026 Cognition Blocks LLC

export const actualizedyaProfile = {
  "name": "ACTUALIZED",
  "tagline": "The one who's building the person they're becoming",

  "overview": "There's a version of you that lives a little ahead of where you are now. Not a daydream—more like a person you can feel. Steadier. Sharper. More like who you actually are when you stop second-guessing. You can't fully describe them, but you can feel the gap between you and them, and closing that gap is basically what you do all day.\n\nWhile your friends are letting life kind of happen to them—drifting into whatever major was easiest, dating whoever, taking the job that fell in their lap—you're doing it on purpose. The 6am workouts nobody asked you to do. The skill you're teaching yourself off YouTube at midnight. The hard conversation you had with yourself about a habit that was holding you back. To you it's all the same project: building the person you're going to be.\n\nYour head moves easy between the big dream and the next small step. You can hold the whole vision—where you want to be in five years—and also break it down into what you're doing this week, today, in the next hour. That bridge between \"someday\" and \"right now\" isn't some mystery to you. You're laying bricks on it constantly.\n\nPeople call you driven, ambitious, intense. They think it's about winning, about flexing, about beating everyone else. But you know it's quieter than that. It's not about being better than anyone. It's about becoming. The hustle they see is really just you treating your own life like something worth building well.",

  "howYouLearn": "A class only sticks when you can see how it moves you toward who you're trying to become. If it doesn't connect to your trajectory, it slides off—you'll cram it for the exam and forget it by Friday. But show you how a skill actually serves the future you're building, and you'll go way past the syllabus. You'll watch the extra videos, do the reps nobody assigned, dig until you really get it.\n\nYou need both the why and the how. Pure theory with no application feels useless; a hack with no understanding behind it feels hollow. You want the principle AND the move. When something connects into the bigger picture of your own growth, it locks in. When it's just floating facts for a grade, it never does.\n\nYou'll grind on things that won't pay off for years, and that's rare for someone your age. While friends need the dopamine hit of an instant result, you can stay locked onto a self that doesn't exist yet and let that pull you through the boring middle part—the certification, the unpaid hours, the slow skill that takes a thousand reps.\n\nWatch this, though: your filter can get too tight. You write off anything that doesn't obviously serve your plan, and sometimes the growth you actually need comes sideways—through a class you thought was pointless, through helping someone else, through a detour that wasn't in your roadmap. The future you is probably built partly from stuff your current filter wants to skip.",

  "howYouCommunicate": "You talk with a direction baked in. Even hanging out, there's usually something you're reaching toward—an idea you're testing, a connection you're making, info you're after. It's not calculated or fake. It's just how your brain runs. You're aware of where a conversation is going almost before it gets there.\n\nYou shift how you talk depending on who you're with—concrete when someone needs the specifics, big-picture when that lands better. You actually notice whether you're getting through, and you adjust. Getting your point across matters to you, so you pay attention to what's working.\n\nYou talk about the future way more than the past. Plans, goals, what's next, what you're working toward—that's your natural lane. When a conversation gets stuck too long in \"remember when\" or even just venting about right now, you can feel yourself getting restless to steer it toward what you're going to do about it. Heads up, though: not everyone wants a plan. Sometimes a friend just wants you to hear them, not optimize them.\n\nYou're comfortable talking about yourself—your goals, what you're working on, how you're thinking. That's not ego, it's just your home base. But notice when you've taken up the whole conversation. Get genuinely curious about where they're headed, what they're building. People feel the difference when you actually want to know.",

  "phrase": "You're not chasing a trophy. You're building yourself, on purpose, brick by brick. The ambition everyone sees is really just you taking your own life seriously.",

  "secret": "Some nights, lying there, you get hit with it: what if you do everything right and still don't become who you're trying to be?\n\nYou've got the plan. You're putting in the work. You believe in the process. But underneath all that intention is a fear that's hard to say out loud—what if it doesn't work? What if you spend your whole twenties grinding toward some better version of yourself and you get there and you're still... this. Still figuring it out. Still not the person you can see so clearly in your head.\n\nDeeper than that: what if the gap never closes? What if \"becoming\" is just a treadmill—the finish line always moving back the second you get close, so you spend your entire life almost-there and never actually arrived?\n\nAnd the one you really don't say: what if you've built your whole life around chasing a version of yourself that isn't even real? What if all this hustle is just a fancy way of refusing to be okay with who you already are right now, today?\n\nThe doubt doesn't stop you—you keep building because that's just how you're wired. But it sits underneath, whispering in the quiet that maybe you're allowed to just exist sometimes, that maybe being here is part of it too. You almost never tell anyone this, because it sounds like you're questioning everything you've built. But questioning isn't quitting. You can hold the doubt and keep building anyway. That's the grown version of this.",

  "whatOthersGetWrong": "They think you've got something to prove—that some voice from your past told you that you weren't enough, and all this drive is you trying to shut it up. They see how hard you go and assume you must be running from something, because why else would anyone work this hard on themselves.\n\nSometimes there's a grain of truth in that. But mostly it's not it. The whole \"who could I become?\" thing is genuinely interesting to you—not a wound, just how your mind naturally points. You're not fixing yourself like you're broken. You're building yourself because building is what you do.\n\nThey think being future-focused means you hate the present, that you're miserable now. Not true. You can be totally fine with who you are today and still be excited about who you're becoming. Those two things live together fine.\n\nThey think your focus on your own growth means you don't care about people. Your friends sometimes feel like they're competing with your goals for your attention. But caring and attention aren't the same thing—you can love people deeply and still have your focus mostly on your own path. The miss is real, though, and worth watching.\n\nAnd the big one: because you've got direction, people assume you've got certainty. They see someone who knows exactly where they're going. But you know how much of it is best-guessing, course-correcting, building the plane while you fly it. The clarity is real; the certainty underneath is mostly faith.",

  "hiddenSuperpower": "You can grind toward something far off in a way that would burn out almost anyone else.\n\nMost people your age need the quick win—the like, the grade, the immediate payoff—or their motivation just dies. They literally can't stay pointed at a goal that doesn't reward them this week. You can. You can connect to a future version of yourself so clearly that it fuels you across months, years, the whole slog where nothing visible is happening yet.\n\nThat's not normal, and it's not small. The ability to keep moving toward something you can't see, might not even reach, and won't benefit from for years—that's the engine behind basically everything worth building. The degree, the craft, the business, the body, the recovery—all of it needs someone who can stay motivated way past where the average person taps out.\n\nYou've got that built in. Where your friends need accountability buddies and habit apps and someone breathing down their neck, you've got an internal compass that holds its direction even when the destination is over the horizon and nobody's watching. The future you is real enough to you that skipping the party to study, or saving instead of spending, doesn't feel like deprivation—it feels like obvious investment.\n\nThis lets you play long games other people can't even start. You can make moves that won't pay off for years because you're actually connected to the person who'll collect on them. You can sit through the unglamorous preparation phase that breaks short-term thinkers, because you know exactly what it's for.",

  "blindSpot": "You probably don't see how much your focus-on-future-you costs the people who are with you right now.\n\nFrom the inside, working on yourself feels obviously right. Of course you'd invest in your growth. Of course you'd protect your routine, your goals, your trajectory. The future you are building is going to be better—better for you, and you assume better for everyone around you too.\n\nBut from the outside—from your partner, your roommate, your closest friend—it can feel different. They feel your attention being split. They feel like they're getting the half of you that's left over after the project. Sometimes they feel like a side character in your movie instead of the lead in their own. The friend who texts and gets a slow reply because you were locked in. The partner who wishes you were actually here, not half-planning the next thing.\n\nAnd here's the hard part: they're not totally wrong. Your setup does center your own growth. It does quietly make relationships feel a little like investments. It does put your trajectory at the top. That's not you being a bad person—it's just how you're wired. But it has a cost, and you're often not counting it because it's paid by them, not you.\n\nWatch for: people drifting away without any actual fight. A friend who slowly stops reaching out. Someone telling you you're \"hard to reach\" or \"always somewhere else.\" Those are the signals that your eyes-on-the-horizon thing is costing more than you realize, right here in the present where the people you love actually live.",

  "frictionPatterns": "You butt heads with the people who are anchored in what's already been proven while you're reaching for what could be. They go \"this is just how it works,\" and you go \"yeah but here's how it could work better.\" Their caution feels like a wall to you; your optimism feels reckless to them. You're both kind of right, you just trust different things—they trust track record, you trust trajectory.\n\nThe present-focused people are their own friction. The friend who genuinely just wants to be here, chilling, no agenda—your constant \"okay but what's the plan\" feels like you can't ever land. And to you, their being-here-now can read like they're just coasting, not building anything. Neither read is fair, but that gap is real.\n\nThe other-focused people sometimes can't connect with how self-directed you are. They're tracking everyone's feelings, the whole group's vibe, while you're tracking your own path. Different games, different rules. They might quietly read your focus as not caring, and you might quietly read their focus as having no direction. Both wrong.\n\nWhat you actually bring to all this is direction—when someone's lost, your clarity can help them find their own (not yours, theirs). The thing to watch is treating past-focus and other-focus like they're just failures to be as evolved as you. They're not. They're different operating systems with their own real value, and you actually get more complete by learning the parts that don't come naturally to you. The worst version of you assumes everyone should just be running your program.",

  "energyPatterns": "What drains you:\n- Being stuck somewhere with zero room to grow or move forward\n- People demanding you be present in a way that means abandoning what you're building\n- Friends or partners who need you smaller, less driven, less \"intense\"\n- Getting clowned for caring about your future or having goals\n- Constant interruptions that knock you off your trajectory\n- Maintenance-mode jobs where every day is identical to the last\n\nWhat charges you:\n- Real, visible progress toward a goal that actually means something to you\n- Uninterrupted time and space to work on yourself or a skill\n- A late-night conversation about potential, growth, where you're all headed\n- People who are also building something and get the grind\n- A clear path with room to level up, not a ceiling you hit in month one\n- Hitting a milestone you set for yourself months ago and feeling it click",

  "workEnvironments": "Where you thrive:\n- Places with a real growth track, where year two looks nothing like year one\n- Roles that reward self-direction and let you run with things\n- Startups, early-career mastery tracks, creative or technical fields with a clear ladder\n- Anywhere your personal growth and the job's demands pull in the same direction\n- Mentors who invest in your development, not just your output\n\nWhere you suffocate:\n- A job that's the exact same task forever with no path up or out\n- All present-grind, no future, no \"where is this going\"\n- Places that won't let you grow as a person alongside the work\n- Roles with a hard ceiling you hit in the first few months\n- Bosses who see ambition as a threat instead of an asset",

  "topCareers": [
    {
      "title": "Early-Career Mastery Track (Specialist / Apprentice)",
      "description": "You're drawn to work where today's you is visibly less skilled than next-year's you, and that gap is the whole point. Pick a field with a real mastery path—coding, design, a craft, a technical specialty—and the long climb that bores other people becomes the thing that fuels you. You'll out-grind the people who need instant wins because you're connected to the version of you who's actually good at this. The drive that made every dead-end job feel like slow death is exactly what a mastery track is built to reward."
    },
    {
      "title": "Founder / Build-Your-Own-Thing",
      "description": "Every habit you've built, every skill you've taught yourself, every hard talk you've had with yourself has been construction toward who you're becoming. Starting something of your own runs on that exact wiring—building deliberately toward a future that doesn't exist yet, with your growth and the thing's growth pulling together. Start small: a side hustle, a freelance gig, a little business in your dorm or apartment. You don't wait for life to shape you, you architect it, and that restlessness in any capped role is the founder's whole engine."
    },
    {
      "title": "Coaching / Personal Training / Development Roles",
      "description": "You've spent your own life navigating by a felt sense of who you could become, and you build toward it on purpose instead of drifting. Entry-level coaching or training turns that lived skill outward—helping someone else see their own next-level self and assemble it choice by choice. You genuinely know the difference between coasting and constructing because you live on the building side. Start with a certification and a few clients; the compass you've been using on yourself becomes the thing you hand to people who've never had one."
    }
  ],

  "blockIndicators": "Your Parser Profile suggests the following CBI block accessibility pattern:\n\nLikely High-Accessibility Blocks:\n- Self-Reference Processing (continuous self-monitoring and development)\n- Pattern Recognition (tracking patterns in your own growth and trajectory)\n- Sequential Processing (planning and implementing development paths)\n\nLikely Moderate-Accessibility Blocks:\n- Symbolic Manipulation (working with abstract frameworks for self-development)\n- Generative Creation (envisioning future selves, creating development approaches)\n- Spatial Relationships (mapping trajectories and pathways)\n\nLikely Lower-Accessibility Blocks:\n- Social Signal Processing (other-focus isn't foregrounded)\n- Perceptual Discrimination (present-moment sensory detail may be under-attended)\n\nThis pattern suggests your cognitive architecture is optimized for deliberate self-development and long-term personal achievement, with room to grow in being fully present and tuning into what the people around you are actually carrying.\n\nACTUALIZED",

  "strengths": [
    {
      "title": "You Build On Purpose",
      "description": "You don't leave your growth to luck. You figure out who you want to become and reverse-engineer the path—skills to learn, habits to build, experiences to chase. You bring to your own life the kind of strategy most people only use on a project for class. You're your own most important thing you're working on, and you treat it that way."
    },
    {
      "title": "Big Picture, Next Step",
      "description": "You can hold the whole vision and the very next move at the same time. You're not just an inspiring dreamer with no plan, and you're not just a to-do list with no direction. You connect today's small action to the long arc, which is why your goals actually move instead of just sounding good in your notes app."
    },
    {
      "title": "Motivation From Inside",
      "description": "Because your focus is on your own becoming, your fuel comes from within. You're not running on likes, comparison, or someone else's expectations—you've got your own standards and your own reasons. That makes your drive way steadier than the friends who need constant outside hype to keep going, and it doesn't crash when the validation dries up."
    },
    {
      "title": "You Can Wait For It",
      "description": "You'll trade comfort now for a payoff later without it feeling like torture, because you're genuinely connected to the future getting the reward. You can skip the thing, save the money, do the boring reps. That ability to invest now and collect way later is the quiet superpower behind basically everything big you'll ever build."
    },
    {
      "title": "You Catch Yourself Drifting",
      "description": "Because you're always low-key watching your own trajectory, you notice when you're off course. A habit slipping, a strategy not working, a direction that stopped fitting—you clock it and adjust instead of blindly grinding the wrong plan for months. Your self-focus doubles as a built-in course-correct that keeps you from waking up two years deep in the wrong thing."
    },
    {
      "title": "You Know Where You're Going",
      "description": "You've got a sense of direction most people your age are still hunting for. That clarity organizes your choices, filters out the noise, and makes decisions that paralyze everyone else feel simple. \"Does this move me toward who I'm becoming?\" is a compass that keeps you oriented while your friends are stuck in the existential scroll, not sure what they even want."
    }
  ],

  "challenges": [
    {
      "title": "Missing The Moment You're In",
      "challenge": "Your eyes are so locked on what's next that you blow right past now. The meal, the conversation, the random good night with friends—it passes without you fully there, because your head's already on the next milestone. The present starts feeling like just a means to an end, only worth something for what it's building.",
      "remedy": "Treat being present as a skill the future you needs—because it is. Reframe \"just being here\" as part of the build, not a break from it. Try one thing fully unoptimized a day: a meal with no phone, a walk with no podcast, a hangout with no agenda. The person you're becoming presumably wants to actually be able to enjoy their life."
    },
    {
      "title": "Friends As Afterthought",
      "challenge": "Your focus on your own path can quietly turn people into add-ons to your main project (you) instead of part of it. You might invest in friends who clearly help your growth and underinvest in the ones who don't obviously fit your plan—and they feel it, even when you don't mean it.",
      "remedy": "Get that who you become is shaped massively by who you're around. Connection isn't separate from self-development—it's one of the main ways it happens. Protect a couple of relationships that aren't \"useful,\" just real. The most actualized people aren't lone-wolf grinders; they're people who learned to grow through actually letting others in."
    },
    {
      "title": "Never Feeling Done",
      "challenge": "A self that's always becoming can never just be. There's always another level, another gap between who you are and who you're trying to be. That's a great engine, but it's also a low-key chronic dissatisfaction—you never feel arrived, never feel like enough, never feel finished.",
      "remedy": "Build in finish lines along the way. Actually celebrate the thing you hit, not just the next thing you're chasing. You'll never be \"done\" growing, but you can be \"done for now\"—the you that exists today is a real, valid person, not just a rough draft. Some nights, just rest in being before you go back to becoming."
    },
    {
      "title": "Thinking You Control Everything",
      "challenge": "Your whole wiring assumes you can shape who you become through effort. But some stuff is just out of your hands—health, timing, your family situation, luck, a pandemic, the economy. When effort doesn't produce results, you can spiral into blaming yourself for things that were never yours to control.",
      "remedy": "Learn the difference between influence and control. You can influence your path a ton; you can't control it completely. Building the ability to handle the stuff you can't control—without falling apart or trashing yourself—is itself part of becoming. The future you needs to be someone who can face the uncontrollable and keep standing."
    },
    {
      "title": "The Comparison Spiral",
      "challenge": "Your focus on your own growth gets tangled up with watching everyone else's, mostly online. Their wins become proof you're behind; their pace becomes the bar you're failing to clear. Your internal project quietly becomes externally graded against people whose highlight reels you only see the polished version of.",
      "remedy": "Keep coming back to your definition of who you're becoming—not one you absorbed from someone's feed. Comparison is fine for learning a tactic, poison for fueling your drive. When you catch yourself measuring against a stranger's post, redirect to measuring against last-year-you. That's the only fair fight."
    },
    {
      "title": "When A Setback Feels Like You're Nothing",
      "challenge": "When your identity is tied to where you're headed, a setback doesn't just slow you down—it feels like a hit to who you are. The failed class, the rejection, the plan that fell apart whispers, \"if you're not moving toward who you're becoming, then who even are you right now?\" There's a real fragility hiding under all that drive.",
      "remedy": "Build an identity that includes your trajectory but is bigger than it. You're not only who you're becoming—you're also just who you are, today, and that person has worth that isn't conditional on progress. Practice identifying with the process of growing, not only the outcomes. That's what keeps you standing when the wins don't show up on schedule."
    }
  ]
};
