// ACTUALIZED Profile
// Parser Profile™ © 2026 Cognition Blocks LLC
// Balanced • Future • Self

export const actualizedProfile = {
  "name": "ACTUALIZED",
  "code": "Balanced • Future • Self",
  "tagline": "The one who builds toward who they're becoming",

  "overview": "You've always had a sense of someone you could become. Not a vague hope—a felt sense. A version of yourself that's clearer, stronger, more fully realized. That future self isn't fantasy. It's the compass you navigate by.\n\nYou don't wait for life to shape you. You've noticed how passive that approach leaves people—drifting into careers, relationships, habits they didn't choose. That's not you. You're building deliberately. Every skill you develop, every habit you cultivate, every hard conversation you have with yourself—it's construction. You're assembling the person you intend to be.\n\nYour thinking moves fluidly between the practical and the conceptual. When you imagine who you're becoming, you can hold the vision and also break it down into steps. What needs to happen this year. This month. Today. The bridge between aspiration and action isn't mysterious to you—you build it constantly.\n\nYour attention lives in the future, but it's personal future. You're not primarily imagining better societies or transformed communities. You're imagining a better you. This isn't selfishness—it's scope. You understand that the only development you actually control is your own. So that's where you focus.\n\nPeople have probably called you driven, ambitious, focused. They see the forward motion and assume it's about achievement. But you know it's deeper than that. It's not about winning—it's about becoming. The ambition they see is really craftsmanship applied to your own existence.",

  "howYouLearn": "Learning lands for you when it connects to who you're becoming. Information without relevance to your trajectory slides off. But show you how something serves your development—how this skill, this knowledge, this understanding moves you toward your future self—and you'll absorb it hungrily.\n\nYou need both the concept and the application. Theory without practice feels incomplete. Technique without underlying principle feels hollow. You want to understand why something works and how to use it. Your learning has to be integrated—pieces that fit into a larger picture of your own growth.\n\nYou're willing to learn things that won't pay off for years. Future-investment comes naturally to you. Where others need immediate returns to stay motivated, you can connect to a self that doesn't exist yet and let that connection sustain effort across long timelines.\n\nSelf-directed learning suits you. You have your own curriculum—the skills and knowledge your development requires. External structures that don't align with your trajectory feel like detours. You learn best when you control what you're learning and why.\n\nBe aware that your self-focus can narrow what you consider worth learning. Some of the most important growth happens through serving others, contributing to things larger than yourself. Don't let your filter screen out knowledge that serves the collective—that kind of learning might be exactly what your future self needs.",

  "howYouCommunicate": "You communicate with direction. Your conversations have purpose—information you're gathering, perspectives you're exploring, connections you're building. This isn't calculation—it's how your mind works. You're naturally aware of what you're trying to accomplish, even in casual interaction.\n\nYour adaptability shows in how you speak. You can get concrete when someone needs specifics and stay conceptual when that serves better. You adjust based on what works. Effective communication matters to you, so you pay attention to what lands and what doesn't.\n\nYou probably talk about the future more than the past. Plans, possibilities, directions, goals—these are natural topics. When conversations stay too long in history or even in current circumstances, you might feel impatient to get to what's next. Your temporal orientation shapes what feels worth discussing.\n\nYou're comfortable talking about yourself—your goals, your development, your thinking. This isn't arrogance; it's your native frame. But be aware that others may need more space in conversations than you naturally create. Practice genuine curiosity about their futures, their development, their aspirations.\n\nIn professional settings, your clarity of direction often makes you appear confident and compelling. You seem like someone who knows where they're going. Use this carefully. Your vision is genuinely yours—it's not necessarily the right direction for others.",

  "phrase": "You're not chasing external prizes. You're sculpting yourself. The ambition others see is really craftsmanship applied to your own becoming.",

  "secret": "Sometimes you're terrified that you'll do everything right and still not become who you're trying to be.\n\nYou have the plan. You're doing the work. You believe in the process. But underneath the intentionality lives a fear that haunts future-oriented self-developers: What if it doesn't work? What if you invest decades in becoming someone and arrive at the future to find you're still... this? Still ordinary. Still incomplete. Still not the person you can see so clearly in your mind.\n\nDeeper: What if the gap between who you are and who you're becoming never closes? What if becoming is a treadmill, not a path—the destination always receding, arrival perpetually deferred? What if you spend your whole life in transit and never actually arrive?\n\nAnd deeper still: What if you've oriented your entire existence around a self that's a fantasy? What if all this effort is elaborate avoidance of accepting yourself as you already are?\n\nThese doubts don't stop you. You keep building anyway—forward motion is how you're wired. But the doubts live underneath, surfacing in quiet moments, whispering that maybe presence is what you need and all this becoming is just sophisticated refusing to be.\n\nYou rarely voice this because it sounds like questioning everything you've built your life around. But questioning isn't abandoning. You can hold the doubt and keep building. The most mature version of your architecture does both.",

  "whatOthersGetWrong": "They assume you're trying to prove something—to them, to the world, to some critical voice from your past. They see your drive and assume it's compensation for inadequacy, as though no one would work this hard at self-development unless they were running from something.\n\nSometimes that's partly true. But often it's not. Your orientation toward becoming is native, not reactive. You're not fixing yourself because you're broken—you're building yourself because that's what your cognitive architecture does. The question \"who could I become?\" is genuinely interesting to you, not just a response to \"you're not enough.\"\n\nThey assume your future-focus means you're unhappy with the present. But future-orientation isn't present-rejection. You can be content with who you are while also being engaged with who you're becoming. These aren't contradictions.\n\nThey assume your self-focus means you don't care about others. Your investment in your own development looks like indifference to theirs. What they miss is that your self-reference is about attention, not care. You can genuinely care about others while attending primarily to your own path.\n\nAnd they assume that because you have direction, you have certainty. Your clarity of trajectory looks like confidence in destination. But you know how much uncertainty lives inside the apparent clarity—how much you're navigating by best guess, course-correcting constantly, building while flying.",

  "hiddenSuperpower": "You can sustain effort toward distant outcomes that would exhaust anyone else.\n\nMost people need immediate feedback, visible progress, near-term rewards. Their motivation requires regular reinforcement or it fades. You can connect to a future version of yourself so clearly that it provides fuel across years, even decades.\n\nThis is extraordinary. The ability to maintain direction and effort toward outcomes you can't see, may never achieve, and won't benefit from for years—this is the engine beneath every significant human achievement. Everything meaningful that's ever been built required people who could sustain investment across timespans that exceed normal motivational range.\n\nYou have this capacity naturally. Where others need systems and accountability and external pressure to keep moving toward distant goals, you have an internal compass that stays oriented even when the destination is over the horizon. Your future self is real to you in a way that makes present sacrifice feel like obvious investment rather than painful deprivation.\n\nThis superpower lets you play long games that others can't play. You can make choices that won't pay off for years because you're genuinely connected to the person who'll receive the payoff. You can endure preparation phases that would break shorter-term thinkers because you know what the preparation is for.\n\nThe world needs people who can sustain this kind of effort. Most of what matters takes longer to build than most people can stay motivated. Your capacity to stay connected to distant futures makes you capable of building things that require exactly that capacity.",

  "blindSpot": "You may not recognize how much your future-self-focus costs your present relationships.\n\nFrom inside your architecture, investing in your own becoming feels obviously right. Why wouldn't you work on yourself? Why wouldn't you prioritize development? The future self you're building will be better—better for you, and presumably better for everyone you're in relationship with.\n\nBut from outside, from the perspective of people who love you now, it can feel different. They experience your attention as divided, your presence as partial, your investment in them as secondary to your investment in yourself. They may feel like supporting characters in your story rather than protagonists in their own.\n\nAnd they're not entirely wrong. Your self-referential future-focus does center your own development. It does make relationships somewhat instrumental. It does create a hierarchy where your trajectory matters most.\n\nThis isn't malicious. It's architecture. But it has costs you may not be counting because they're paid by others rather than by you. The partner who wishes you were more present. The friend who feels like a project rather than a priority. The people who learn that your growth matters more than their experience of being with you.\n\nWatch for: people pulling away without clear conflict. Resentment building in relationships you thought were fine. Others describing you as \"hard to reach\" or \"always somewhere else.\" These signals suggest your future-self-focus is costing more than you're aware of in the relational present.",

  "frictionPatterns": "You'll clash with people anchored in concrete past experience while you're building toward abstract personal futures. They draw from what's been proven; you reach toward what could be. Their \"this is how it actually works\" meets your \"but here's how it could work better.\" Their experience-based caution meets your possibility-based optimism.\n\nYou'll struggle with heavily present-oriented profiles who want to be here now rather than building toward later. Your forward motion feels like refusal to land; their presence feels like stagnation to you.\n\nAnd other-oriented profiles may find your self-focus hard to connect with. They're tracking collective experience while you're tracking personal trajectory—different games with different rules.\n\nYour gift in these frictions: Your clarity of direction can help others find their own direction, even if it differs from yours.\n\nYour growth edge: Recognizing that past-focus and other-focus aren't failures to develop your architecture—they're different architectures with their own validity. You can become more complete by learning from orientations that aren't native to you.",

  "energyPatterns": "What drains you:\n- Stagnation—situations where growth feels impossible\n- Demands for presence that prevent future-building\n- Relationships that need you to be smaller or less directed\n- Environments that punish ambition or pathologize self-investment\n- Constant interruption of your development trajectory\n\nWhat charges you:\n- Clear progress toward meaningful personal goals\n- Time and space for deliberate self-development work\n- Conversations about growth, potential, and possibility\n- Environments that support long-term investment over short-term comfort\n- Relationships that support your becoming without requiring you to abandon it",

  "workEnvironments": "Where you thrive:\n- Environments that support long-term growth\n- Roles that reward self-direction and personal development\n- Entrepreneurship, leadership development, creative fields with mastery trajectories\n- Any role where your own growth and the role's demands align\n- Coaching, particularly around achievement and development\n\nWhere you suffocate:\n- Purely maintenance-focused roles with no growth trajectory\n- Constant present-focus without future-building\n- Environments that don't allow personal development alongside professional performance\n- Roles without clear growth pathways or autonomy over your development",

  "topCareers": [
    {
      "title": "Development / Achievement Coach",
      "description": "You've always navigated by a felt sense of who you could become, and you build toward it deliberately instead of drifting. Development coaching is that lived skill turned outward—helping someone else see their own future self clearly and assemble it choice by choice. You know the difference between passive drift and deliberate construction because you've lived on the building side. The compass you used on your own life becomes the thing you hand to people stuck without one."
    },
    {
      "title": "Entrepreneur / Founder",
      "description": "Every skill, every habit, every hard conversation with yourself has been construction toward the person you intend to be. Entrepreneurship rewards that exact orientation—building deliberately toward a future that doesn't exist yet, with your own growth and the venture's growth pulling in the same direction. You don't wait for life to shape you; you architect. The relentless becoming that made any static, maintenance-only role feel like a slow death is the founder's whole engine."
    },
    {
      "title": "Creative / Mastery-Track Professional",
      "description": "You're drawn to work with a trajectory—where today's self is visibly less than next year's, and the gap is the point. Creative and craft fields with real mastery paths reward that: the long arc of becoming better, the development that never tops out. You thrive where your personal growth is allowed to run alongside the performance, not bolted on after. The drive to keep building yourself, restless in any capped role, is exactly what a mastery path is for."
    }
  ],

  "blockIndicators": "Your Parser Profile suggests the following CBI block accessibility pattern:\n\nLikely High-Accessibility Blocks:\n- Self-Reference Processing (continuous self-monitoring and development)\n- Pattern Recognition (tracking patterns in your own growth and trajectory)\n- Sequential Processing (planning and implementing development paths)\n\nLikely Moderate-Accessibility Blocks:\n- Symbolic Manipulation (working with abstract frameworks for self-development)\n- Generative Creation (envisioning future selves, creating development approaches)\n- Spatial Relationships (mapping trajectories and pathways)\n\nLikely Lower-Accessibility Blocks:\n- Social Signal Processing (other-focus isn't foregrounded)\n- Perceptual Discrimination (present-moment sensory detail may be under-attended)\n\nThis pattern suggests your cognitive architecture is optimized for deliberate self-development and long-term personal achievement. Your developmental opportunities lie in present-moment awareness and other-oriented attention—building the capacity to be fully here and to attend to others' experience with the same quality of attention you bring to your own becoming.\n\nACTUALIZED",

  "strengths": [
    {
      "title": "Intentional Self-Development",
      "description": "You don't leave your growth to chance. You identify who you want to become and reverse-engineer the path. Skills to develop, habits to build, experiences to seek—you approach your own evolution with strategic thinking others reserve for external projects. You are your own most important project."
    },
    {
      "title": "Flexible Planning",
      "description": "Your balanced processing lets you work at multiple levels of abstraction. You can hold the big picture of your trajectory while also getting concrete about next steps. Your plans aren't just inspiring visions or just task lists—they're integrated systems connecting daily action to long-term direction."
    },
    {
      "title": "Intrinsic Motivation",
      "description": "Because your focus is self-referential, your motivation comes from within. You're not dependent on external validation, social comparison, or others' expectations to fuel your drive. You have your own standards, your own vision, your own reasons. This makes your motivation more stable than externally-derived drive."
    },
    {
      "title": "Delayed Gratification Capacity",
      "description": "Your future-orientation makes you naturally willing to sacrifice present comfort for future benefit. You can endure current difficulty because you're connected to what it's building toward. This capacity to invest now for later payoff is foundational to significant achievement."
    },
    {
      "title": "Course Correction Ability",
      "description": "Your ongoing attention to your own development means you notice when you're drifting off course. You're tracking your trajectory, not just executing plans blindly. When something isn't working—a habit, a strategy, a direction—you catch it and adjust. Your self-focus is also self-monitoring."
    },
    {
      "title": "Clarity of Direction",
      "description": "You have a sense of where you're heading that many people lack. This clarity organizes your choices, filters your opportunities, and simplifies decisions that paralyze others. \"Does this move me toward who I'm becoming?\" is a compass that keeps you oriented when others are lost."
    }
  ],

  "challenges": [
    {
      "title": "Present-Moment Disconnection",
      "challenge": "Your future-focus can pull you out of current experience. You may be so busy becoming that you forget to be. Meals, conversations, moments of beauty—they pass without full presence because your attention is on the horizon. The present becomes merely instrumental, valuable only for what it builds.",
      "remedy": "Practice deliberate presence as a skill your future self needs. Reframe being fully here as part of becoming who you want to be—not as a departure from your project but as essential to it. The person you're building presumably wants to be capable of presence; start practicing now."
    },
    {
      "title": "Relationship as Secondary",
      "challenge": "Your self-referential orientation can make relationships feel like additions to your primary project (yourself) rather than central to it. You may invest in people strategically based on what they contribute to your development, or underinvest in relationships that don't obviously serve your trajectory.",
      "remedy": "Recognize that who you become is shaped profoundly by who you're in relationship with. Connection isn't separate from self-development—it's a primary vehicle for it. The most actualized people aren't isolated achievers; they're people who've learned to grow through authentic interdependence."
    },
    {
      "title": "Perpetual Incompleteness",
      "challenge": "A self focused on becoming can never simply be. There's always another level, another gap between current and aspirational self. This creates an engine for growth but also a kind of chronic dissatisfaction—you're never arrived, never enough, never finished becoming.",
      "remedy": "Build in markers of completion along the way. Celebrate arrivals, not just departures. You'll never be \"done\" becoming, but you can be \"done for now\"—acknowledging that the person you are today is a valid self, not just a draft of a future version. Sometimes rest in being before returning to becoming."
    },
    {
      "title": "Control Illusion",
      "challenge": "Your architecture assumes high personal agency—that you can shape who you become through deliberate action. But some of what shapes us is outside our control: health, circumstance, timing, luck. Your belief in self-determination may leave you unprepared for the uncontrollable and prone to self-blame when things don't respond to effort.",
      "remedy": "Distinguish between influence and control. You can influence your trajectory profoundly; you cannot control it completely. Building resilience for when effort doesn't produce results is itself part of becoming—the ability to face the uncontrollable without collapsing is a capacity your future self needs."
    },
    {
      "title": "Comparison Trap",
      "challenge": "Your focus on your own development can become entangled with comparison to others' development. Their achievements become evidence of your inadequacy; their pace becomes the standard you judge yourself against. The internal project becomes externally benchmarked, which undermines its authenticity.",
      "remedy": "Keep returning to your definition of who you're becoming—not a definition imported from others' paths. Comparison is useful for learning, toxic for motivation. When you notice yourself measuring against others, redirect to measuring against your own prior self and your own vision."
    },
    {
      "title": "Identity Contingency",
      "challenge": "When identity is tied to future achievement, present self-worth becomes contingent on progress. Setbacks don't just slow you down—they threaten your sense of self. \"If I'm not moving toward who I'm becoming, who am I right now?\" This can create fragility beneath the apparent drive.",
      "remedy": "Develop identity that includes but exceeds your trajectory. You are not only who you're becoming; you're also who you are. The builder is valuable, not just the building. Practice identifying with the process of growth, not just its outcomes—this creates resilience when outcomes don't arrive on schedule."
    }
  ]
};
