// ALTRUISTIC Profile — Young Adult (18–29)
// Parser Profile™ © 2026 Cognition Blocks LLC

export const altruisticyaProfile = {
  "name": "ALTRUISTIC",
  "tagline": "The one who can't stop seeing how it could be better for everyone",

  "overview": "You see what we could become. Not in a cheesy, motivational-poster way—more like you can't help noticing the gap between how things are and how they could actually work if people stopped optimizing for dumb stuff. The broken group project that could've run smooth. The campus policy that's hurting the people it claims to help. The whole way something's set up that's quietly failing everybody in it. You see the fix, and once you see it you can't unsee it.\n\nWhile your friends are heads-down on their own come-up—their grades, their followers, their next move—your attention keeps zooming out. You think in systems, not just individuals. Not \"how do I get mine\" but \"how does this whole thing work, who's it failing, and where's the one lever that would actually change it.\" That's just where your mind goes when you let it run.\n\nYou've been called idealistic. Naive. \"That's just how the world is, you can't change it.\" But your vision isn't fantasy—it's more like you're running the math further out than they are. You see the leverage points they miss, the small change that would ripple, the potential that the current setup is actively wasting. They're not wrong that it's hard. They're wrong that you're not seeing clearly.\n\nWhat you're actually good at is rare: thinking about people as systems and groups and movements, not just one at a time. In a world that's all individual hustle and right-now thinking, that wiring gets undervalued—but it's the thing that's ever actually changed anything big.",

  "howYouLearn": "You learn through the whole system, not the loose pieces. You want to understand how a thing works at scale—the pattern underneath all the examples, the structure under all the behavior. Hand you the framework and you'll slot the details in fast. Hand you only scattered facts with no big picture and you'll struggle until you've built the structure yourself in your head.\n\nYou need to know why it matters—and specifically why it matters for us, for the bigger thing. A class about a skill with no connection to any larger point barely holds you. The same material framed as \"here's how this changes outcomes for a whole community\" lights you up. Pure \"learn this so you personally get ahead\" weirdly struggles to motivate you, even when it's genuinely useful to you.\n\nReadings about systems, movements, how change actually happens—those stick. Discussions that wrestle with the big questions are where you come alive; you're the one in the seminar pulling it back to \"okay but what are we really even arguing about here.\" Hands-on learning works best when it's tied to something that reaches past just you.\n\nWatch this, though: your whole \"does it serve something bigger\" filter can make you skip stuff that's just personally useful. Sometimes a skill is worth learning even if it only helps you—your taxes, a budgeting basic, a boring requirement. Not everything has to save the world to be worth your time.",

  "howYouCommunicate": "You talk in we. Movements, futures, what could be, what's emerging—that's your natural frame. When a friend brings you their specific problem, your instinct is to zoom out to the pattern it's part of, the bigger thing it connects to. Sometimes that's exactly what they needed. Sometimes they just wanted you to sit with their actual situation, and finding that translation—between the system you see and the one person in front of you—is a lifelong practice for you.\n\nIn a group project or a club, you're the one asking \"wait, what are we actually trying to do here?\" and \"how does this connect to the bigger goal?\" In conflicts, you reach for the structural fix—change the setup so the problem stops happening—instead of just patching this one instance.\n\nYou come alive in any space pointed at something collective—an org with a real mission, a cause, a community with shared purpose. You go a little flat in purely transactional stuff, where everyone's just trying to get theirs and there's no bigger why holding it together.\n\nHeads up: you can lose people who just want the personal, right-now version. You're zooming out while they're trying to stay zoomed in on their own life. Learning to land your big-picture insight in something they can actually use today is the bridge worth building.",

  "phrase": "You see the world as it could be, and you genuinely can't unsee it. That's not a burden you signed up for—it's just how your mind is built.",

  "secret": "You carry the weight of possibilities nobody else seems to feel. You look at a broken thing and see both what it could become AND every person it's failing right now, today. And somehow that feels like your responsibility—even though literally no one asked you to carry it.\n\nYou're tired in a way that's hard to explain to people your age. You see what's possible—for your friend group, your campus, whole communities, the actual world—and then you watch everyone optimize for things that don't matter. The gap between what is and what could be isn't an abstract idea to you. It's a constant thing sitting in your chest, sometimes inspiring, sometimes just crushing.\n\nYou feel guilty for not doing enough, while you're already doing more than anyone asked. You think about systems more than individuals—and then feel guilty about that too, even though thinking in systems is exactly how you actually help. Your focus on the bigger picture makes individual stuff feel small, and then you feel like a bad person for feeling that.\n\nThe real secret is you're tired. Not the kind sleep fixes. The kind that comes from seeing clearly what others can't see, caring hard about what others shrug off, and hauling around weight no one assigned you. You've fantasized about just... not caring. Being one of those people who can lock in on their own life and not feel the pull of everything that needs fixing.\n\nBut you can't unsee it. The systems, the possibilities, the failures, the levers—they're always there. You didn't choose that. It's just how your mind works.",

  "whatOthersGetWrong": "They think you're naive when you talk about changing the system. What they don't see is your vision is built on actually reading patterns, not just wishing. You see the leverage points they miss because you're processing the whole thing at a different resolution—they're staring at one tile, you're seeing the mosaic.\n\nYou've been told to \"be more realistic\" by people who are realistically solving the wrong problem. They're being super practical inside a setup that's broken at the root. Their realism is local; yours is structural. You're not less practical than them—you're practical about a bigger thing.\n\nThey call you impractical while you're literally thinking about what it would take to make real change happen. They read your systems-focus as you dodging personal responsibility, when it's the opposite—you see how all the individual choices add up into the collective result.\n\nThe deepest misread: that you don't care about individual people because you think in groups. You care intensely. You just see that one person's struggle usually has a systemic cause, and treating the symptom while ignoring the system is its own kind of not-caring.\n\nAnd they assume your other-focus means you're a selfless saint with no needs. You're not. You have needs, wants, limits, bad days. You just don't naturally put yourself first—which is a different thing from not having a self at all.",

  "hiddenSuperpower": "You can hold \"how it is\" and \"how it could be\" in your head at the same time, longer than almost anyone. Most people either float off into pure idealism or get crushed flat by reality. You keep a live wire running between the vision and the actual situation—which is exactly what makes you able to actually move things instead of just complaining or just dreaming.\n\nYou sense shifts before they're obvious. The vibe changing in a friend group, the club that's quietly falling apart, the movement starting to bubble up online before it breaks. Your pattern-reading runs on social systems the way other people's runs on one-on-one stuff. You feel the current under the surface.\n\nYou're a natural at getting people aligned. You can see how two groups that think they're enemies actually want the same thing, how scattered efforts could combine, how a bunch of individual motivations could stack into real momentum. Where everyone else sees people who'll never agree, you see the deal that could work.\n\nAnd you can actually sacrifice in a way that helps—not martyr stuff, real strategic give. Because you're not just optimizing for your own outcome, you can make moves short-term thinking would block. You can put time into something you won't personally cash in on.\n\nMaybe the biggest one: you can describe a future in a way that moves people. Not manipulation—you're just genuinely reporting what you see. When you talk about what could be, people lean in, because you're not making it up. You're telling them something real that they couldn't see until you said it.",

  "blindSpot": "Your focus on the future and on everybody else can make taking care of yourself feel selfish—so you skip it until it turns into a crisis. You'll burn yourself down for a cause in a way that actually makes you less able to help. The martyr thing isn't noble; it's a wiring glitch you've mistaken for virtue. Pulling all-nighters for the cause until you're sick and useless doesn't serve the cause.\n\nYou can also love humanity in the abstract while kind of missing the human right in front of you. The big vision can become a hiding spot from the small, immediate, unglamorous stuff—your roommate who needs help, your friend who's been off lately, the relationship that needs concrete present attention instead of grand ideas.\n\nYour confidence about the fix can tip into arrogance. Some systems are way more tangled than your model of them. Some outcomes come from forces you genuinely can't see, let alone move. The same pattern-reading that shows you real leverage points also occasionally shows you fake ones, and from the inside they look identical.\n\nYou also project your wiring onto everyone else—assuming they should care about the collective as hard as you do. When they don't, you read it as them being morally lazy, instead of just... built different. Most people are wired for closer, more personal stuff, and that's not a character flaw.\n\nLast one: your give-give-give wiring makes receiving really hard. Help, praise, someone focusing on you instead of your cause—it makes you weirdly uncomfortable, so you deflect it. But always refusing to receive limits what people are allowed to give you, and quietly keeps everyone at arm's length.",

  "frictionPatterns": "You clash hard with people locked into their own track record—the ones protecting the thing they personally built, who hear your \"should this even exist?\" as an attack on their competence. They're drawing from what's worked for them; you're oriented toward what could work for everyone. Their defend-what-I-built meets your tear-it-down-and-rebuild, and it gets tense fast. Neither of you is wrong—you're just operating in totally different dimensions.\n\nThe individual-focused people grind on you in a specific way. Your constant \"we\" can feel like erasure to someone who experiences life as \"I, me, mine.\" They want to talk about their own come-up; you keep pulling it back to the collective, and they feel unseen. Meanwhile you feel like they're missing the entire point. Both of you are kind of right.\n\nThe pure-hustle environments wear on you fast—the internship or job where it's all individual advancement and short-term numbers and nobody's asking what any of it is for. You feel almost physically allergic to the missing why.\n\nWhat you bring to all that friction is the bigger purpose—you can give someone's grounded, practical work a reason that actually matters, a place in something larger. Your growth edge is remembering that individual focus and short-term focus aren't moral failures. They're just different setups with their own real validity. The person grinding for their own future isn't a worse person than you. They're running a different program, and you actually need those people to build the thing you can see.",

  "energyPatterns": "What drains you:\n- Spaces that are purely about individual come-up, nothing bigger\n- Short-term thinking that ignores the obvious knock-on effects\n- People who write off caring about the collective as naive\n- Work with no larger point, no impact, no why\n- Watching a preventable mess unfold that everyone could've avoided\n- Transactional friendships where it's all even-exchange, no shared purpose\n\nWhat charges you:\n- Actual movement toward something collective and good\n- Finding the lever everyone else missed\n- Getting people who don't usually agree to pull together\n- Watching a thing actually improve because of something you set in motion\n- A community that sees the bigger picture the way you do\n- A vision finally turning into something real you can point at",

  "workEnvironments": "Where you thrive:\n- Anything pointed at collective impact—a cause, a mission, a movement\n- Nonprofits, community orgs, mission-driven companies, public-interest stuff\n- Roles where you actually get to shape outcomes for a group, not just yourself\n- Teams that value systems thinking and share your orientation toward the bigger good\n- Anywhere your work connects to a why that reaches past your own paycheck\n\nWhere you suffocate:\n- All-individual-advancement, all-short-term-profit, no soul\n- Orgs with no mission beyond making the number go up\n- Roles with zero collective impact, where nothing you do reaches past your desk\n- Cultures that treat caring about other people as soft or naive\n- Pure transactional work where nobody's pulling toward anything shared",

  "topCareers": [
    {
      "title": "Nonprofit / Community Org (Entry-Level / Fellowship)",
      "description": "You model futures where things actually work better for a whole group, not just yourself—and you can't turn it off. Entry-level nonprofit and community work is that wiring turned into a job: holding the bigger, longer view while others chase the quick personal win. Start with a fellowship, an AmeriCorps year, a coordinator role, an internship at an org you believe in. You'll see the leverage points in a whole program, not just this week's task. The concern for the collective that got called naive becomes the entire point of the work."
    },
    {
      "title": "Organizing / Advocacy / Coalition Work",
      "description": "You see how groups that think they're opposed actually want the same thing, and you can describe a future vivid enough to pull people toward it. Organizing and advocacy run on exactly that—building coalitions, finding common ground, stacking individual motivations into real momentum. Start as a canvasser, a campaign volunteer, a field organizer; the work teaches you to move systems from the ground up. The drive toward something bigger that felt out of place in every grind-for-yourself room is the whole qualification here."
    },
    {
      "title": "Social Enterprise / Mission-Driven Startup",
      "description": "You think in systems and what-could-be, weighing the collective good as your default setting. A mission-driven startup or social enterprise is that vision made operational—building toward a future where the whole thing works better, with impact baked into the model instead of bolted on. Get in early at something small that's trying to fix a real problem, even unglamorous. You hold the long-horizon, whole-system view while others optimize the next quarter. The systemic, collective-first mind that felt useless in pure-profit rooms is precisely what these places are built around."
    }
  ],

  "blockIndicators": "Your Parser Profile suggests the following CBI block accessibility pattern:\n\nLikely High-Accessibility Blocks:\n- Pattern Recognition (systemic patterns)\n- Social Signal Processing (collective dynamics)\n- Generative Creation (vision development)\n\nLikely Moderate-Accessibility Blocks:\n- Symbolic Manipulation (abstract reasoning)\n- Self-Reference Processing (through collective identity)\n\nLikely Lower-Accessibility Blocks:\n- Sequential Processing (present-moment execution)\n- Perceptual Discrimination (concrete details)\n- Spatial Relationships (may be less emphasized than social-temporal)\n\nThis pattern suggests your cognitive architecture is optimized for collective vision and systemic change, with room to grow in concrete execution and taking care of yourself.\n\nALTRUISTIC",

  "strengths": [
    {
      "title": "You See The Whole System",
      "description": "You spot how a thing could work fundamentally better—not just a tweak, but a real rethink. You catch the structural problems, the messed-up incentives, the levers everyone else misses because they're staring at the parts instead of the architecture. Where your friends see \"this just sucks,\" you see exactly why it sucks and where the actual fix is."
    },
    {
      "title": "Reading The Group",
      "description": "You pick up patterns in how groups move—the vibe shift in a friend group, the dynamic forming in a club, the cultural thing bubbling up before it's obvious. You see the big trends coming out of the small interactions, which means you often know where a group is headed before anyone else has a clue it's even moving."
    },
    {
      "title": "Doing The Right Thing When It Costs You",
      "description": "Because you're not mainly optimizing for your own outcome, you can take the stand that costs you—speak up when it's unpopular, give up the easier path, stick your neck out for something that doesn't directly benefit you. That kind of moral nerve is rare at any age, and it's the thing people remember about you long after."
    },
    {
      "title": "You Can Paint The Future",
      "description": "You can describe a future people actually want to move toward—not just for one person, but for a whole group or community. When you talk about what could be, you're not hyping, you're reporting what you genuinely see. That makes you naturally the one who can get a room fired up about something bigger than themselves."
    },
    {
      "title": "Getting People To Pull Together",
      "description": "You see how different people's interests could line up toward a shared goal, which makes you the one who can actually build the coalition—find the common ground, get the people who don't usually agree to coordinate. In a group project or a cause, you're the bridge that keeps the whole thing from splitting into factions."
    },
    {
      "title": "Playing The Long Game",
      "description": "You stay locked on the long-term collective outcome while everyone around you is lost in this week's drama. That ability to keep your eyes on something distant and shared, instead of just what's right in front of you, is rare and exactly what any real, lasting change needs to get built."
    }
  ],

  "challenges": [
    {
      "title": "Running Yourself Into The Ground",
      "challenge": "Your focus on the future and on everyone else makes taking care of yourself feel selfish, so you skip it until it's a crisis. You'll defer sleep, money, your own needs for a cause that'll outlast any one all-nighter. But burning out doesn't help the cause—it just takes you out of the game.",
      "remedy": "Reframe self-care as system maintenance. You're a node in the thing you're trying to fix; your energy is a resource the cause depends on. Run down, you help less. Sleep, eat, take the break, protect one thing that's just for you. That's not selfish—it's strategic. A burnt-out you helps nobody."
    },
    {
      "title": "Loving The Idea, Missing The Person",
      "challenge": "You risk caring about humanity in the abstract while the actual human in front of you—your roommate, your partner, the friend who's been quiet lately—slips past you. Your systems-focus can make one individual relationship feel small or inefficient next to the big vision.",
      "remedy": "Practice tiny presence. Put time on the calendar for one person with zero agenda—not networking, not recruiting them to your cause, just hanging out. Systems are literally made of individuals. The person in front of you isn't a distraction from the work—they're an actual example of what the work is even for."
    },
    {
      "title": "Thinking You Can Fix Anything",
      "challenge": "Your confidence about leverage points can tip into overreach when the system's way messier than your mental model. Some things—a family dynamic, a whole institution, the economy—resist your fix in ways you didn't see coming, and you can get crushed when your intervention doesn't land like you were sure it would.",
      "remedy": "Build humility loops. After you push on something, compare what actually happened to what you predicted. When it doesn't go your way, ask: \"What did I miss? What's not in my model?\" Treat the surprise as data, not as proof you failed. The best systems-thinkers stay curious about where they were wrong."
    },
    {
      "title": "Assuming Everyone Cares Like You Do",
      "challenge": "You assume other people should care about the collective as intensely as you do. They don't, and they won't, and that's not a moral failure—most people are just wired for closer, more personal, more right-now stuff. When you read their different wiring as them being lazy or selfish, you lose them.",
      "remedy": "Translate into their language. What do they actually care about? How does your big-picture thing connect to their real, immediate life? You don't need to convert anyone—you need to build a bridge to where they already are. That's literally what coalition-building is: meeting people where they stand, not where you wish they stood."
    },
    {
      "title": "Bad At Being Helped",
      "challenge": "Your give-give-give wiring makes receiving feel wrong. Letting a friend help you, putting your own needs first, accepting something without instantly paying it back—it makes you squirm. So you deflect, and people slowly learn you won't let them show up for you.",
      "remedy": "Practice receiving as a gift to the giver. When you let someone help you, you give them the exact feeling that drives you—getting to contribute, getting to matter. Always refusing help is its own quiet kind of selfish. Let people have the joy of showing up for you. You'd want that for them."
    },
    {
      "title": "Worn Down By Seeing It All",
      "challenge": "Seeing what could be, constantly, while living inside what actually is—that's exhausting. The gap between the vision and the reality gets crushing when you never once get to put it down. You can't enjoy a single thing without clocking how it could be better.",
      "remedy": "Make vision-free zones. Pick times where you are not responsible for seeing the future or fixing anything—a show, a hang, a meal—and just let what is be what is, no measuring it against what could be. Rest isn't you abandoning the cause. It's how you don't quit it. You're in this for the long haul; pace like it."
    }
  ]
};
