// ATTUNED Profile — Young Adult (18–29)
// Parser Profile™ © 2026 Cognition Blocks LLC

export const attunedyaProfile = {
  "name": "ATTUNED",
  "tagline": "The one who felt the room before anyone said a word",

  "overview": "You walked into the party and you just knew. Nobody had said anything yet. But you already felt it—who was tense, who was faking the smile, which two people had clearly just fought in the car. The information showed up before anyone opened their mouth.\n\nYou spent years thinking everyone could do this. That reading a room was basic, like hearing or breathing. Then it slowly hit you: they're not ignoring the tension. They literally don't feel it. Your friend genuinely had no idea the host was upset, even though to you it was the loudest thing in the room.\n\nPeople call you \"sensitive.\" Like it's a personality quirk. Like it's something you could just turn down.\n\nIt's not a quirk. It's a channel. You're picking up signals other people aren't even tuned to. The little face-flicker that doesn't match the words. The way someone's posture shifts when a certain name comes up in the group chat. The thing between two friends that neither of them has admitted yet. You catch all of it. You can't not catch it.\n\nThe gift is you see what's actually going on in rooms full of people who only hear what's being said out loud. The cost is you can't switch it off—and nobody seems to notice you're the one quietly carrying all of it.",

  "howYouLearn": "You remember who taught you long after you've forgotten what they taught. The professor's voice, the way they leaned in, whether they actually saw you sitting there—that's what your memory kept, and the actual content kind of rode in on the back of it. The material arrived through the person, or it barely arrived at all.\n\nThe online class didn't stick. Same slides, same info, and it slid right off—because there was no one on the other end of it, no face to read, no warmth to lock onto. Then someone you actually clicked with taught you the exact same thing in person, and it became permanent. You learned more from how they said it than from what they said.\n\nGroup study works for you, but only when the group's actually okay. In a good vibe you soak up everything—the side comments, the energy, the little corrections passing between people. Put you in a study group with an undercurrent—two people who clearly don't like each other—and you're done; you're too busy tracking the tension to absorb a single thing. One-on-one beats all of it: full signal, no noise, nothing to manage but the two of you.\n\nAnd some of what you know, you picked up without anyone ever naming it. You watched a manager handle the angry customer, or a friend defuse a fight before it caught fire, and your body just filed the whole pattern. You didn't learn their words—you learned them.",

  "howYouCommunicate": "You're watching their face the whole time you're talking, adjusting word by word to what it tells you. A flicker of confusion and you double back. A little closing-off and you soften. You know the second they stop listening—usually before they know it themselves—and you've already changed course by the time their attention drifts back.\n\n\"Does that make sense?\" isn't a verbal tic for you. You're actually checking. You need the read coming back to know if it landed, which is why texting can feel like shouting into a void—the silence gives you nothing to calibrate against, and you're left re-reading their three-word reply forty times guessing at a tone you'd normally just feel in person.\n\nIn a group, you're tracking like four emotional states at once and somehow talking to all of them—pitching what you say to the room as it actually is, not just to the loudest person in it. People rarely notice you're doing it. They just feel, somehow, that you said exactly the thing they needed to hear.\n\nAnd then there's everything you didn't say. You've held back so much you clearly saw, because you could feel the person wasn't ready to hear it yet. The restraint isn't you being fake—it's timing. You read that the truth would land wrong in this exact moment, so you waited for a better one. You've got a whole archive of things you saw and chose not to name.",

  "phrase": "You don't just empathize. You perceive. And you can't stop perceiving just because it's inconvenient.",

  "secret": "You absorb what you pick up. Their anxiety becomes your anxiety. Their drama sits in your chest hours after you left. You've walked out of hangouts wiped for no reason you could name—until you realized you'd been quietly carrying everyone else's weight the whole night.\n\nYour system doesn't filter well. It just takes everything in, all at once, all the time.\n\nYou've lost yourself more than once. So locked onto what they were feeling that you completely forgot to check what you were feeling. So busy managing the room's mood that you neglected your own. People call you \"so selfless\" and you smile and take it, but you know the truth: it's not all virtue. Sometimes it's just forgetting that you exist too.\n\nThe deepest part: sometimes you straight up resent it. You've wondered what it'd be like to walk into a room and just... not know. Not feel the undercurrent. Not catch the crack in someone's mask. Not haul around feelings that aren't even yours. To be one of those people who can just have a normal night without picking up everyone's static.\n\nIt looks kind of peaceful from where you're standing. Being oblivious.",

  "whatOthersGetWrong": "They think you're just nice. You're not nice—or not only that. You're reading them whether you want to or not. What you do with the read is a choice; getting the read never was. The kindness they give you credit for is mostly just accuracy they've mistaken for sweetness.\n\n\"Too sensitive\" is the label, and it's exactly backwards. You're not fragile—you're high-resolution. You catch the shake in someone's voice, the micro-shift when a certain ex gets mentioned, the thing two people aren't saying to each other across the table. That's not thin skin. That's precision they don't have, and being seen that clearly makes some people uneasy. \"You care too much\" usually comes from people who care too little to even notice what you're noticing.\n\nThey assume your other-focus means you're selfless and have no needs of your own. You do. You just lose track of them in all the signal coming off everyone else, and by the time you find your needs again they've gone urgent. And they think, because you read feelings, that you always want to talk about feelings—when half the time you're completely saturated and would kill for something concrete and impersonal to do instead, like a task or a game or literally anything that isn't another emotion.\n\nThe deepest misread: they take your attunement for agreement. You can feel exactly what someone feels and still completely disagree with their take. Understanding the room from the inside isn't the same as being on its side—but to people who can't tell perception from endorsement, those two look identical.",

  "hiddenSuperpower": "You see the invisible wiring of social situations. Who actually has power versus who just has the title. Who's really aligned versus who's performing it. Where the resistance actually lives. Where it's all about to crack.\n\nYou know things about people they've never told anyone—sometimes things they haven't even admitted to themselves. Not from snooping. From pattern completion. They can't help broadcasting, and you can't help receiving. A friend will be three sentences into a story and you already know the part they're not going to say.\n\nYou make people feel safe without even trying. People relax around you and have no idea why. They don't realize you're actively tracking their state and adjusting in real time. You're not just reading the room—you're quietly steadying it.\n\nAnd you can translate. You get what people actually mean, not just the words they used. You're the one who can stand between two friends who are technically saying the same thing in two different languages and go, \"okay, I think you both actually want the same thing here.\" You bridge gaps other people don't even see exist.",

  "blindSpot": "Sometimes the person genuinely wasn't broadcasting anything, and you filled in a signal that wasn't there. Your system is built to receive, so when nothing's coming in, it can manufacture a read out of your own expectation—and you act on it with full confidence, because your reads are usually right. That \"usually\" is the trap. When you're wrong, the very accuracy you trust is exactly what stops you from double-checking.\n\nYou over-function. You saw a friend's discomfort so clearly that you jumped in to smooth it—and quietly took away something they actually needed to sit in and feel for themselves. The instinct to fix the vibe is so fast you don't always notice you removed something by soothing it. Some growth only happens when someone's allowed to be uncomfortable, and you keep rescuing them from it.\n\nThere's a whole layer you miss because of where your attention lives. You read what's happening right now in incredible detail, which means the slow pattern—the one that only shows up over months—can slip right past you. The friend who's a little off every single week, the relationship that's slowly going somewhere bad—you're so tuned to this moment that the long arc can be invisible.\n\nAnd you forget the obvious one: you need to be read too. You're so reliably the one perceiving everyone else that nobody thinks to check on you, and you don't ask them to. Worse—some of the people you've felt most clearly have also felt exposed by it, seen in a way they never agreed to. The same gift that lets you meet people can, uninvited, make them want to hide from you.",

  "frictionPatterns": "You grind against the person so deep in their own head they don't notice the actual human sitting across from them. They'll run a whole conversation off their own internal logic while someone in the group is visibly falling apart, and not register a thing. To you the emotional reality is the single loudest fact in the room; to them it's not even data.\n\nThe self-focused ones wear on you in a specific way—not because they're cruel, but because they seem genuinely oblivious to their own impact. You can see the little wreckage they leave behind them, the small hurts they scatter without noticing, and you're usually the one quietly cleaning it up afterward, texting the person who got steamrolled to make sure they're okay. Meanwhile the group plows ahead with the plan while someone's clearly not fine, and you're the only one carrying the unspoken weight of it.\n\nFuture-focused conversations can do it too—everyone hyped about the trip next month or the five-year plan while a person right in front of them is hurting now, unaddressed. You feel the mismatch as almost physical: how are we talking about spring break when she's clearly about to cry?\n\nWhat you bring to that friction is the read no one else has—you can actually name what the room's feeling so the thing can move forward honestly instead of around the elephant. Your growth edge is remembering that their head-first or self-first wiring isn't them being a bad person or refusing to care. It's a different channel. They're not ignoring the signal to spite you. They genuinely just aren't receiving it.",

  "energyPatterns": "What drains you:\n- Rooms full of unspoken tension you can feel but aren't allowed to address\n- Being the only one who's reading the room\n- Group hangs that ignore the obvious emotional reality everyone's pretending not to see\n- Carrying feelings other people can't even feel while they stay denying them\n- Performing warmth and attentiveness when you're already running on empty\n- Becoming the group's unofficial therapist / emotional management system\n\nWhat charges you:\n- A deep conversation with someone who actually sees you back\n- A group that just flows, everyone in unspoken sync\n- Using your read to help someone who really needed to be seen\n- Two-way attunement—someone tuning into you the way you tune into them\n- Real alone time to discharge everything you've soaked up\n- Someone confirming your read instead of brushing it off as \"you're overthinking\"",

  "workEnvironments": "Where you thrive:\n- High people-content—support roles, peer counseling, coordinating, hosting, helping\n- Small teams with healthy, drama-free dynamics\n- Roles where reading and navigating people is literally the job\n- Collaborative places that actually value emotional intelligence\n- Environments where it feels psychologically safe\n\nWhere you suffocate:\n- Toxic team dynamics you can't escape and can't stop feeling\n- Isolated work with no human signal coming in at all\n- Aggressive, \"toughen up,\" thick-skin cultures\n- Cold abstract work totally disconnected from people\n- Roles that require you to ignore what you clearly perceive",

  "topCareers": [
    {
      "title": "Peer Support / Counseling Track (Entry-Level)",
      "description": "You walked in and knew—who was tense, who was faking it, who was about to crack—before anyone spoke. Support and counseling work runs on exactly that channel. You receive the signal others aren't tuned to, the shift in a face, the thing held back, and you respond to what's actually happening instead of just the words. Start as a peer support specialist, a crisis line volunteer, a residential aide, or in a psych or social-work program. What got called \"too sensitive\" your whole life becomes the actual instrument—the thing that lets you meet someone where they really are."
    },
    {
      "title": "Facilitator / Mediator / Coordinator",
      "description": "When a group's vibe curdles, you feel it in your body before anyone's named it—and you can name it. Facilitation, mediation, and coordination roles pay for that real-time read: sensing the unspoken tension, the person going quiet, the moment to slow it down. Start by running a club, coordinating volunteers, managing a small team, or assisting a mediator. You don't navigate people from a theory of how groups work—you navigate from what you're picking up live in the room. The perception you couldn't turn off becomes the reason the meeting doesn't fall apart."
    },
    {
      "title": "Coaching / Mentoring / People-First Roles",
      "description": "You read the room before the room knows it's been read, and people trust whoever actually sees them. Coaching and mentoring are built on that—meeting someone exactly where they are, catching the flicker of resistance or relief, working with the real human in front of you instead of the one on paper. Start by mentoring younger students, coaching a youth team, or training into a people-development role. The empathy that cost you in thick-skinned rooms is the core skill here. You were always doing this for free; this is the version that pays."
    }
  ],

  "blockIndicators": "Your Parser Profile suggests the following CBI block accessibility pattern:\n\nLikely High-Accessibility Blocks:\n- Social Signal Processing (your native mode)\n- Perceptual Discrimination (concrete present focus)\n- Self-Reference Processing (through other-awareness, paradoxically)\n\nLikely Moderate-Accessibility Blocks:\n- Sequential Processing (practical responsiveness)\n- Spatial Relationships (reading physical cues)\n\nLikely Lower-Accessibility Blocks:\n- Pattern Recognition (across time; present-focus limits)\n- Generative Creation (abstract ideation)\n- Symbolic Manipulation (theoretical reasoning)\n\nThis pattern suggests your cognitive architecture is optimized for social intelligence and reading people in real time, with room to grow in abstract reasoning and tuning back into your own signal the way you tune into everyone else's.\n\nATTUNED",

  "strengths": [
    {
      "title": "Reading The Room Live",
      "description": "You knew the group hang was off in the first five minutes. Everyone else figured it out hours later, if ever. You're reading what's happening while it's happening—not piecing it together after the fact on the drive home. By the time the tension actually surfaces, you've already been quietly tracking it the whole time."
    },
    {
      "title": "You Actually Know How They Feel",
      "description": "You know how someone feels because you're perceiving it, not guessing. Your reads are real data, not vibes. That's why you're the one friends come to when they need to feel understood, not just heard—you get it before they've even finished explaining, and they can tell."
    },
    {
      "title": "You Feel It Before It Blows Up",
      "description": "You sense tension before it surfaces—the unspoken beef in the group chat, the resentment building, the friendship quietly forming on the side. You feel the tremor way before the earthquake, which means you often see the falling-out coming while everyone else is still acting like things are fine."
    },
    {
      "title": "Connection That Actually Lands",
      "description": "People feel genuinely seen by you because you actually see them. Your attention responds to their real state in the moment, not some script. The connection isn't performed or polite—it's accurate. That's why people open up to you fast, sometimes telling you stuff they've never told anyone."
    },
    {
      "title": "Steering A Group Through The Hard Part",
      "description": "You can guide a group through a tense or awkward moment because you're tracking everyone at once. You know when to slow it down, when to change the subject, when to gently name the thing nobody's saying. In a room about to go sideways, you're the one who quietly keeps it together."
    },
    {
      "title": "You Tune The Room Without Trying",
      "description": "Spaces you're in tend to just function better. Not because you're working at it—because you're constantly reading and subtly adjusting, smoothing a thing here, drawing someone out there. You're tuning the whole room and nobody, including sometimes you, even notices it's happening."
    }
  ],

  "challenges": [
    {
      "title": "Hitting Full And Overflowing",
      "challenge": "You've hit the wall where you literally can't take in any more. The packed party, the high-drama group chat blowing up, the friend who dumps more on you than you can hold. Your system doesn't filter—it just fills until it spills over, and then you're fried for days.",
      "remedy": "Build discharge rituals. After something intense, schedule decompression: a walk, a workout, real solitude, anything that's about your own body instead of everyone else's feelings. And ask the key question: \"Is this feeling even mine?\" Just asking creates a little distance between you and the static you've absorbed."
    },
    {
      "title": "Losing Your Own Signal",
      "challenge": "You've checked in on literally everyone but you. By the time you notice your own needs, they've already gone urgent—you're starving, exhausted, about to cry, and you only just realized. You're so tuned to the room that you forget you're also a person in it.",
      "remedy": "Schedule self-check-ins. Actually, literally. A couple times a day, stop and ask: \"What do I need right now?\" Treat yourself like another person worth attuning to. And before you walk into anything social, check: \"How am I arriving? What've I got in the tank?\" before you spend it all on everyone else."
    },
    {
      "title": "The Read That Was Wrong",
      "challenge": "Your perception is right so often that when it's wrong, you might not catch it. You acted on a read with total confidence—and it was off. Not because you failed, but because some people just don't broadcast the way you expect, and your system filled in the gap with your own assumption.",
      "remedy": "Check it when it matters. \"Hey, I'm getting the sense you're upset—am I reading that right?\" That's not doubting your gift, it's calibrating it. A strong read survives being tested. The times it matters most are exactly the times worth saying out loud instead of just acting on the silent version."
    },
    {
      "title": "Keeping The Peace No Matter What",
      "challenge": "You feel conflict so intensely that you smooth it over before it can do its job. The hard conversation that actually needed to happen never happens, because you made everyone comfortable before the discomfort could lead anywhere. You'd rather absorb it than let it play out.",
      "remedy": "Reframe conflict as care. Naming the tension serves the friendship's actual health, not just this minute's comfort. Your perception is the gift—use it for clarity, not just for peace. Sometimes the kindest thing is letting the awkward moment breathe long enough for something real to come out of it."
    },
    {
      "title": "Doing Their Feelings For Them",
      "challenge": "You managed a friend's emotions because you could see them so clearly—and now they low-key rely on you to regulate stuff they should be handling themselves. Your help, given so fast and so well, quietly prevented them from building the muscle to do it on their own.",
      "remedy": "Let people feel their own discomfort sometimes. Perceiving it doesn't obligate you to fix it. Some of the kindest attunement is stepping back and trusting someone to find their own footing. You don't have to catch every feeling that falls—some of them are theirs to carry, and carrying them is how they grow."
    },
    {
      "title": "Seeing Someone Who Didn't Want To Be Seen",
      "challenge": "They felt seen in a way they never asked for. Your accuracy turned into intrusion—you reflected something back so precisely that it felt like you'd read their diary. Not everyone wants to be perceived that clearly, no matter how gently you do it.",
      "remedy": "Develop permission practices. Just because you see it doesn't mean you have to say it. Ask before you reflect something back. Hold your reads as guesses, not verdicts. \"Can I share something I'm noticing?\" gives them the choice. Sometimes the most generous use of your gift is just quietly holding what you see and saying nothing."
    }
  ]
};
