// ATTUNED Profile
// Parser Profile™ © 2026 Cognition Blocks LLC
// Concrete • Present • Other

export const attunedProfile = {
  "name": "ATTUNED",
  "code": "Concrete • Present • Other",
  "tagline": "The responsive presence who reads the room before entering",
  "overview": "You walk into a room and you know. You don't know how you know,\nthere's no conscious reasoning, no deliberate analysis. But you know\nwho's uncomfortable, who's pretending, who has unspoken conflict,\nwho's aligned and who's performing alignment. You feel the room before\nyou understand it.\n\nYour cognitive architecture prioritizes concrete reality over\nabstraction, present circumstances over past or future, and the\nexperience of others over your own internal states. The result is a\nconsciousness that serves as a living social barometer, perceiving\ninterpersonal dynamics at a resolution that others can't access.\n\nYou've probably been called \"sensitive\" or \"empathic\" like those\nare simple personality traits. They're not. You're running\nsophisticated social processing that operates below conscious awareness,\ndetecting micro-expressions, body language incongruencies, and energy\nshifts that others filter out. What they experience as intuition is\nactually perception, you're seeing signals they're missing.\n\nThe Attuned profile represents approximately 7% of the population.\nYou're the canary in the social coal mine, the first to notice when\nsomething's off, often before the people involved have noticed\nthemselves. This makes you invaluable for roles requiring interpersonal\nnavigation, but it also means you carry perceptual burdens that others\ndon't understand because they can't see what you see.\n\nYour cognitive architecture excels at real-time social reading, empathic\nattunement, and creating interpersonal harmony. You naturally smooth\nfriction, bridge gaps, and create environments where people feel seen.\nThis makes you essential in any context requiring human coordination.\n\nUnderstanding your profile means recognizing that your sensitivity\nisn't weakness, it's bandwidth. You're receiving more social\ninformation than most people, which is both gift and burden.",
  "howYouLearn": "You learn through relational context. Abstract information that comes\nwith no human connection tends to slide off; the same information\nembedded in relationship becomes permanent. You remember who taught you\nsomething and how they felt about it. The emotional channel carries the\ncontent.\n\nYour optimal learning environment is relational, responsive, and\npresent-focused. You learn best from people you're connected to, in\nreal-time interaction rather than asynchronous content. Live instruction\nbeats recorded. Conversation beats monologue. Relationship beats\ntransactions.\n\nYou learn poorly from isolated, abstract instruction without human\npresence. Online courses, solitary reading, and content without\nrelational containers may not engage your processing. You need the human\nsignal to carry the information signal.\n\nGroup learning works well when the group dynamics are healthy; poorly\nwhen they're not, you'll be too distracted by the interpersonal\nundercurrents to focus on content. One-on-one instruction is often\noptimal, giving you the relational channel without the complexity of\ngroup dynamics.",
  "howYouCommunicate": "You communicate with attention to how your message lands, not just what\nyour message says. You're watching for response as you speak, adjusting\nin real-time based on what you perceive. This makes you an adaptive\ncommunicator who can meet people where they are.\n\nYou struggle with broadcast communication, situations where you can't\nreceive feedback to calibrate against. Written communication, large\npresentations, and any format without real-time response leaves you\nwithout the signal you depend on. You may overcompensate by hedging\nexcessively.\n\nIn conversation, you're responsive, validating, and attuned. You\nreflect back what you're hearing, check understanding, and track\nemotional state throughout. This creates conversations that feel\nunusually satisfying to your partners, they feel genuinely heard.\n\nYou communicate best in intimate, real-time contexts where your social\nperception can operate fully. You communicate less effectively in large\ngroups, asynchronous formats, and situations where you're expected to\nassert without receiving response.",
  "phrase": "You don't just empathize, you perceive. It's not about being nice;\nit's about seeing what others literally can't.",
  "secret": "You walk into rooms and know things you shouldn't know. Who's fighting\nbut pretending they're fine. Who's about to quit? Who's lying about\nbeing, okay? Who secretly hates the project but won't say so? The\ninformation just arrives, not through analysis, but through a channel\nyou've never been able to fully explain.\n\nYou've possibly spent years thinking everyone could do this. That\nreading a room was a basic human skill, like walking or breathing. It\ntook you a long time to realize that other people are genuinely blind to\nsignals you can't miss. They're not ignoring the tension, they\nliterally don't feel it. Nevertheless, you feel it to the point that\nyou can't un-feel it.\n\nThe secret is that this gift is also a burden. You absorb what you\nperceive. Other people's anxiety becomes your anxiety. Their conflict\nbecomes your tension. You've left gatherings exhausted without knowing\nwhy, until you realized you'd been carrying everyone else's emotional\nweight for hours. Your system doesn't have good filters. It takes\neverything in.\n\nYou've probably lost yourself more than once. So attuned to others that\nyou forgot to check what you were feeling. So focused on managing the\nroom's experience that you neglected your own. People call you\n\"empathetic\" like it's a compliment, not realizing that your empathy\nisn't a choice. It's an involuntary read of signals you can't turn\noff.\n\nThe deepest secret: sometimes you resent it. You wish you could walk\ninto a room and just... not know. Not feel the undercurrent. Not notice\nthe micro-expressions. Not carry the weight of perceptions that aren't\neven yours. You've wondered what it would be like to be oblivious. It\nlooks peaceful.",
  "whatOthersGetWrong": "ABOUT YOU \n\nPeople think you're \"nice\" when you're actually perceptive. They\nassume your attunement is warmth, kindness, or performed consideration.\nIt's not, it's involuntary data acquisition. You're not trying to be\nconsiderate; you're processing information about them whether you want\nto or not. What you do with that information is a choice. That you\nreceive it is not.\n\nThey call you \"sensitive\" like it's a weakness, not realizing that\nsensitivity is just high-resolution perception. You're not fragile,\nyou're precise. The signals they miss entirely hit you with full force.\nThat's not a flaw in your system; it's a feature they don't have.\n\nYou've been told you \"care too much\" by people who care too little.\nYou've been dismissed as \"emotional\" when you were being\nobservational. You've been labeled \"too intense\" by people who\nexperience human connection at lower bandwidth. They're not wrong that\nyou're different, they're wrong about what the difference means.\n\nThe deepest misread is that your other-focus means you're selfless.\nYou're not. You have needs, preferences, and desires like anyone else.\nYou're just so calibrated to others' frequencies that your own signal\ncan get lost in the noise. Your selflessness isn't virtue; it's\nsometimes a failure to maintain your own signal strength.\n\nThey also assume you want to talk about feelings because you perceive\nthem so well. Sometimes you do. Often, you're exhausted by feelings and\nwould love to discuss something concrete and impersonal for once.",
  "hiddenSuperpower": "You can read group dynamics in real-time at a resolution others can't\naccess. You see the invisible architecture of social situations, who\nholds actual power versus formal power, who's aligned versus performing\nalignment, where real resistance lives, where genuine support is. This\nmakes you invaluable for anything requiring social navigation.\n\nYou know things about people that they've never told anyone, sometimes\nthings they haven't admitted to themselves. Not through intrusion or\ninvestigation, but through pattern completion of signals they can't\nhelp broadcasting. You see the composite picture that their fragments\ncreate. This can feel almost psychic, but it's just perception\noperating at a bandwidth others don't have.\n\nYour superpower extends into prediction. Because you track emotional and\nrelational dynamics so precisely, you can anticipate social outcomes\nbefore they unfold. You know which relationships are doomed. You know\nwhich teams will fracture. You know which leaders are losing their\npeople. You see the trajectory in the present-moment data.\n\nYou can also create safety. Your attunement means you notice when people\naren't okay, and your responsiveness means they feel seen. You're the\nperson others relax around without knowing why. They don't realize\nyou're actively tracking their state and adjusting your presence to\nwhat they need. You're not just perceiving; you're regulating the\nsocial field around you.\n\nPerhaps most valuable: you can translate between people. You understand\nwhat each person means, not just what they're saying. You can bridge\ngaps that others don't even see exist.",
  "blindSpot": "You may trust your social perception so completely that you miss it when\nit fails. Not everyone broadcasts readable signals. Some are genuinely\nopaque, not because you're failing, but because they're wired\ndifferently or have trained themselves to mask. When your read is wrong\nabout these people, you might not have backup systems to catch the\nerror.\n\nYour other-focus can become self-neglect. You're so attuned to everyone\nelse's needs that you may not notice your own until they've become\ncrises. Hunger, exhaustion, emotional depletion, these signals from\nyourself can get drowned out by the volume of signals from others. Your\nattunement to the room can become inattention to yourself.\n\nYou may also over-function in relationships, managing others' emotions\nbecause you can see them so clearly. This can create dependence, others\nrelying on you to regulate what they should be regulating themselves.\nYour helpfulness can prevent growth, both theirs and yours.\n\nYour present-focus means you might miss patterns that only emerge over\ntime. You're reading the room now with extraordinary accuracy, but you\nmight not track how the room has changed over months. Historical\npatterns and future trajectories can escape your notice while you're\nimmersed in immediate social data.\n\nFinally, your gift can become intrusive. Some people feel exposed by\nyour perception, seen in ways they didn't consent to be seen. Your\nattunement can feel like surveillance to those who prefer privacy. Not\neveryone wants to be read, no matter how accurately.",
  "frictionPatterns": "You clash most intensely with Abstract-Past-Self processors (Sentimental\nor Introspective profiles). They're lost in internal conceptual worlds,\npersonal memories, abstract self-reflection, theoretical frameworks,\nwhile you're tracking the living humans in front of you with immediate\nneeds. They seem disconnected from reality; you seem superficial to\nthem.\n\nThe friction is structural. They process through internal abstraction;\nyou process through external perception. They think you're missing the\ndeeper meaning; you think they're missing the actual people. Both of\nyou are right about what the other is missing.\n\nHigh-Abstract processors generally frustrate you. Their comfort with\nconcepts disconnected from immediate human reality feels cold, even\nnegligent. When they discuss systems without seeming to notice the\npeople in those systems, your attunement reads it as a failure of basic\nperception.\n\nSelf-focused processors across any configuration can also create\nfriction. Your orientation toward others makes their self-focus feel\noblivious or selfish, even when it's simply different architecture. You\nnotice their impact on others that they don't notice themselves, and\nit's hard not to judge the gap.\n\nFuture-focused processors may feel distant to you. You're here, now,\nwith these people. They're somewhere else, in a time that doesn't\nexist yet.",
  "energyPatterns": "What Drains You:\n\n-   Groups with unacknowledged tension that you feel but can't address\n\n-   Environments that ignore obvious emotional reality\n\n-   Being the only one reading the room\n\n-   Carrying group emotions without support\n\n-   People who deny what you clearly perceive\n\n-   Toxic dynamics you can't escape\n\n-   Performing attunement when you're depleted\n\n-   Being used as an emotional management tool\n\nWhat Charges You:\n\n-   Deep one-on-one connection with someone who sees you back\n\n-   Harmonious groups that flow with unspoken coordination\n\n-   Using your perception to help someone who needed to be seen\n\n-   Being understood, not just understanding\n\n-   Environments with healthy, acknowledged emotional dynamics\n\n-   Relationships with reciprocal attunement\n\n-   Time alone to discharge absorbed emotions\n\n-   People who validate your perceptions instead of dismissing them",
  "workEnvironments": "You thrive in environments with high interpersonal content, counseling,\ncoaching, HR, customer-facing roles, teaching, and any position where\nhuman dynamics are central. Small teams with healthy relationships fit\nyou better than large organizations with complex politics.\n\nYou struggle in environments with toxic interpersonal dynamics (you'll\nabsorb them), heavy isolation requirements (you'll starve for human\nsignal), or abstract work without human connection (you'll disengage).\nRoles requiring thick skin and aggressive competition may drain you\nfaster than you can recover.\n\nKey environmental factors: healthy team dynamics, interpersonal\nengagement, collaborative culture, emotional safety, and meaningful\nhuman connection in the work itself.",
  "blockIndicators": "Your Parser Profile suggests the following CBI block accessibility\npattern:\n\nLikely High-Accessibility Blocks:\n\n-   Social Signal Processing (your native mode)\n\n-   Perceptual Discrimination (concrete present focus)\n\n-   Self-Reference Processing (through other-awareness, paradoxically)\n\nLikely Moderate-Accessibility Blocks:\n\n-   Sequential Processing (practical responsiveness)\n\n-   Spatial Relationships (reading physical cues)\n\nLikely Lower-Accessibility Blocks:\n\n-   Pattern Recognition (across time; present-focus limits)\n\n-   Generative Creation (abstract ideation)\n\n-   Symbolic Manipulation (theoretical reasoning)\n\nThis pattern suggests your cognitive architecture is optimized for\nsocial intelligence and interpersonal effectiveness, with potential\ndevelopmental opportunities in abstract reasoning and self-focused\nprocessing.\n\nATTUNED",
  "strengths": [
    {
      "title": "Real-Time Social Perception You read social dynamics as they",
      "description": "happen, not retroactively. While others realize hours later that the\nmeeting went badly, you knew in the first five minutes. This real-time\nawareness allows you to navigate and influence social situations with\nunusual precision."
    },
    {
      "title": "Empathic Accuracy You know how people feel, not because you're",
      "description": "projecting, but because you're perceiving. Your emotional reads are\ndata, not guesses. This accuracy makes you a trusted confidant and an\neffective mediator."
    },
    {
      "title": "Conflict Detection You sense tension before it surfaces. Unspoken",
      "description": "conflicts, brewing resentments, hidden alliances, you detect these\nundercurrents while they're still invisible to others. This early\nwarning system is invaluable for preventing escalation."
    },
    {
      "title": "Connection Creation You know how to make people feel seen and",
      "description": "understood because you actually see and understand them. Your attention\nis genuinely responsive to their state, which creates a quality of\nconnection that feels rare and valuable to those who receive it."
    },
    {
      "title": "Group Facilitation You can guide groups through difficult",
      "description": "dynamics because you're tracking everyone's state simultaneously. You\nknow when to slow down, when to redirect, when to address the elephant,\nand when to let things play out."
    },
    {
      "title": "Environmental Harmony You naturally create and maintain",
      "description": "harmonious environments. Your awareness of when things are off, and your\nskill at addressing those imbalances, means spaces you inhabit tend to\nfunction better interpersonally."
    }
  ],
  "challenges": [
    {
      "title": "Empathic Overload*",
      "challenge": "Because you're constantly receiving social signals, you\ncan become saturated. Crowded spaces, high-conflict environments, and\nemotionally intense people can overwhelm your processing capacity. Your\nsystem doesn't have good filters. It takes everything in, often before\nyou realize what's happening.",
      "remedy": "Build deliberate discharge rituals. After high-intensity\nsocial exposure, schedule decompression: physical movement, time alone,\nactivities that are about your body rather than others' emotions. Learn\nto ask: \"Is this feeling mine?\" The question itself creates distance.\nYou can't stop absorbing, but you can process and release before it\naccumulates."
    },
    {
      "title": "Self-Neglect",
      "challenge": "Your other-focus can cause you to lose track of your own\nneeds, feelings, and boundaries. You're so attuned to others that you\nmay forget to check in with yourself until you're depleted or\nresentful.",
      "remedy": "Schedule self-check-ins. Literally set reminders to ask:\n\"What do I need right now?\" Treat yourself as another person you're\nattuned to, someone whose signals deserve reading. Start conversations\nwith yourself before entering social situations: \"How am I arriving?\nWhat's my current state?\" Make self-perception a deliberate practice."
    },
    {
      "title": "Unverified Interpretation",
      "challenge": "Your perception is usually accurate, but not always. When\nyou're wrong, you might not check because your reads usually work. This\ncan lead to acting on misinterpretation with the confidence of accurate\nperception.",
      "remedy": "Build verification habits. When your read matters, check it:\n\"I'm sensing some tension, am I reading that right?\" This isn't\ndoubting your perception; it's calibrating it. Even accurate\ninstruments need calibration. Your perception is strong enough to\nsurvive testing; test it anyway."
    },
    {
      "title": "Conflict Avoidance",
      "challenge": "Because you feel conflict so intensely, you may avoid\nnecessary confrontations. Your sensitivity to disharmony can lead to\npeace-keeping that actually prevents important issues from being\naddressed.",
      "remedy": "Reframe conflict as care. Addressing tension directly is a\nform of attunement, you're serving the relationship's health, not just\nthe moment's comfort. Practice small confrontations to build tolerance.\nName what you're sensing: \"I'm noticing tension here, can we talk\nabout it?\" Your perception is the gift; use it for clarity, not just\ncomfort."
    },
    {
      "title": "Abstract Processing Difficulty",
      "challenge": "Your concrete-present focus may struggle with abstract or\nfuture-oriented thinking. Problems that require stepping back from\nimmediate social reality into theoretical frameworks can feel\ninaccessible.",
      "remedy": "Anchor abstractions in people. When facing theoretical\ncontent, ask: \"Who does this affect? What would this look like for\nsomeone I know?\" Translate concepts into relational terms, your native\nlanguage. You're not avoiding abstraction; you're processing it\nthrough a channel that works for your architecture."
    },
    {
      "title": "Boundary Perception",
      "challenge": "Others may experience your attunement as intrusive, you see\nthings they're not ready to have seen. Your perception can feel like\nexposure to those who aren't comfortable being read so accurately.",
      "remedy": "Develop permission practices. Just because you perceive\nsomething doesn't mean you should name it. Ask before reflecting: \"Can\nI share what I'm noticing?\" Let others opt in. Hold your perceptions\nlightly, as hypotheses, not facts. Your accuracy doesn't obligate\ndisclosure. Sometimes the kindest use of perception is restraint.\n\n*"
    }
  ]
};
