// CENTERED Profile — Young Adult (18–29)
// Parser Profile™ © 2026 Cognition Blocks LLC

export const centeredyaProfile = {
  "name": "CENTERED",
  "tagline": "The one who knows where they stand",

  "overview": "You know where you are. Not in some deep philosophical way—practically. Right now, in this moment, you know what you're feeling, what you need, what's actually real. While your friends are spiraling about a text from three days ago or panicking about graduation that's two years off, you're here. Present. Clear. You can feel your own ground under you.\n\nThis isn't you being checked out or not caring. It's the opposite—it's the deepest kind of being present, staying connected to yourself while everything around you goes sideways. When the group chat explodes or the plan falls apart at 11pm, you don't launch into worst-case scenarios or freeze up over how the last one went. You look at what's actually happening and what you can actually do about it right now.\n\nPeople find you weirdly calming and can't explain why. Your steadiness gives everyone else permission to stop spinning. You're not pushing an agenda, not trying to drag the conversation to your preferred drama. You're just there—present, available, anchored. The friend people text when everything's on fire because you won't catch fire too.\n\nThey've called it \"detached,\" but it's the exact opposite. You're not absent—you're so present you don't need to perform being present. The stillness they mistake for not caring is actually the foundation everything else stands on. You're the floor, not the ceiling.",

  "howYouLearn": "A class lands when it connects to your actual life right now. Abstract concepts need a hook into how this applies to me, today. Pure theory floating in space slides right off; the same info connected to something real in your present situation sticks like glue.\n\nYou can handle both the concrete example and the big framework—you just need the bridge between them. Show you the principle AND where it actually shows up, and you'll lock in both. Give you only one and you'll feel like half the picture's missing.\n\nYou struggle hard with learning that's all future (\"you'll need this someday for a job you don't have yet\") or all past (\"this is just how it's always been done\"). You need to know why it matters now. \"Someday\" and \"because tradition\" both kind of bounce off you.\n\nSelf-paced learning is your sweet spot because you can read your own energy and attention honestly. You actually know the difference between when you're absorbing something and when you're just staring at the page pretending. Trusting that self-knowledge lets you study efficiently instead of grinding hours that aren't doing anything—you stop when you're done, not when the clock says.",

  "howYouCommunicate": "What you say is what you actually think and feel. You're not performing a version of yourself—you're just expressing the real one. People find that either really refreshing or a little confronting, depending on whether they're used to everyone managing their image all the time.\n\nYou can read your audience and adjust—get specific when someone needs the details, stay big-picture when that's more useful. You're flexible without being fake; you bend how you say it, not what's true.\n\nYou're most locked in when the conversation's about what's actually happening. When it drifts too far into \"remember that one time\" or endless \"but what if,\" your attention starts wandering and you have to pull yourself back. The present is just where your interest naturally lives.\n\nIn conflict, your centeredness is a genuine weapon. You don't escalate easy. You can stay in a hard conversation—the breakup talk, the roommate confrontation, the fight with family—without fleeing into abstraction or shutting down and going cold. You're still actually in the room when things get heavy, which is rarer than it sounds. Most people leave, even while they're still sitting there.",

  "phrase": "You're not detached. You're anchored. The stillness everyone mistakes for not caring is actually the deepest kind of being here.",

  "secret": "Sometimes your centeredness feels less like a gift and more like a cage.\n\nYou've built this stability, this grounded thing, this ability to stay with yourself through whatever hits—and it's genuinely valuable, you know that. But there's a part of you that wonders what it'd be like to just get swept away. To lose yourself in some obsession, some person, some massive dream or aching nostalgia. To be so consumed by something outside yourself that your careful balance just shatters for once.\n\nYou watch your friends get completely wrecked by their crushes, their ambitions, their fears—and yeah, you see the suffering that comes with all that intensity. But you also low-key wonder what you're missing. Is your steadiness actually wisdom, or is it a really sophisticated way of hiding? Are you grounded, or are you just... contained? Playing it safe and calling it being centered?\n\nThere are nights you suspect your self-awareness has quietly become a way of keeping yourself small. That by always knowing exactly where you stand, you've put a ceiling on how far you'll ever travel. That the stability everyone admires is just a really polished form of never fully going for anything.\n\nThe truth is your centeredness is real and worth having. But so is that longing for something big enough to actually knock you off balance. Holding both of those at once doesn't make you a contradiction. It just makes you human, and twenty-something, and honest.",

  "whatOthersGetWrong": "They think your calm means you don't feel things deeply. They see you steady and conclude you must be kind of shallow, emotionally flat. Not true—you feel things all the way. You just don't let the feeling instantly hijack what you do next. That's processing, not suppression. There's a whole lot happening under the still surface.\n\nThey think your self-focus means you're not interested in them. You care about people—you're just not wired to dissolve into their experience and lose yourself in it. You can be fully there for a friend without taking on their entire emotional weather as your own, and people sometimes misread that boundary as distance.\n\nAnd because you're so steady, nobody checks on you. Nobody offers support. They just assume you're fine, you've always got it handled, you don't need anyone. Your stability quietly turns into invisibility—you become the one who holds everyone else, and somehow never gets held back.\n\nThey think your present-focus means you don't remember the good times or don't have dreams. You do. You just don't let the past or the future shove their way in and take over where you actually are. Living in the now isn't the same as having no history and no future—it's choosing not to let either one run the show.",

  "hiddenSuperpower": "You can stay in the room when literally no one else can.\n\nWhen things get overwhelming—when emotions spike, when the situation gets complicated and loud, when everyone else has either fled into overthinking or collapsed into full panic—you're still there. Present. Aware. Functional. The roommate crisis at 2am, the family blowup at dinner, the friend having a breakdown: you're the one still standing in yourself.\n\nThis isn't you going numb or checking out. It's real presence, held through stuff that completely scrambles other people. You stay connected to yourself, connected to the actual moment, and connected to whoever needs you to just stay steady while they can't.\n\nYou can be with someone in their worst moment without needing them to manage your reaction on top of their own. They can completely fall apart and you hold the container—you don't make their crisis about you, you don't spiral alongside them, you don't need them to reassure you that it's all okay. That steadiness you offer when someone can't hold themselves up—that's the kind of thing people remember for years. That's the thing that actually changes someone's worst night.",

  "blindSpot": "Sometimes \"staying in the now\" is actually just avoidance wearing a calmer outfit. Unprocessed stuff from your past doesn't disappear because you've decided not to look at it. A future you refuse to plan for doesn't get more manageable because you've ignored it. Your present-focus can be genuine wisdom or it can be hiding—and the tricky part is that from the inside, both feel exactly the same.\n\nWatch for the discomfort that spikes when someone asks you to actually deal with a past pattern or sit down and plan something out. Not just \"I prefer the present\"—real discomfort, a flinch, a quick change of subject. That flinch is the tell. It usually means there's something you're dodging by anchoring so hard to right now.\n\nAlso watch for the same thing happening over and over without changing. If you never draw on the past, you can end up repeating the exact mistake—the same kind of relationship, the same self-sabotage—because you didn't look back long enough to catch the pattern. And if you never project into the future, you get blindsided by stuff that was honestly pretty predictable. The deadline that \"snuck up,\" the money problem that didn't sneak up at all. Being present is a strength, but it's got a cost when it becomes the only place you'll go.",

  "frictionPatterns": "You clash with people lost in big abstract visions of some collective future while you're standing in your actual present experience. They see you as short-sighted, like you're missing the point; you see them as floating dreamers who can't land on anything real. Both reads have a little truth and a lot of unfairness in them.\n\nYou struggle with heavily past-focused people who want to process history—rehash the old fight, dig through what went wrong months ago—when you just want to deal with what's in front of you right now. And with heavily other-focused people who need you to track their emotional state more closely than you naturally do; they can feel you holding your own center and read it as you not caring enough.\n\nThe future-anxiety people and the nostalgia people both kind of bewilder you. Their constant departures from the present—the spiraling about what might happen, the looping on what already did—feel like unnecessary suffering to you. And you can be a little dismissive about it, treating their timeline like a problem you could fix if they'd just be present like you.\n\nWhat you actually bring to all that friction is steadiness without strings—you can model grounded presence without demanding everyone else adopt it. Your calm doesn't require their calm. Your growth edge is remembering that their timeline is as native to them as yours is to you. The future-focused dreamer and the past-processing friend aren't broken versions of you. They're just standing somewhere else, and that's allowed.",

  "energyPatterns": "What drains you:\n- Long stretches stuck on hypothetical futures or pasts that can't be resolved\n- Emotional environments where you're expected to soak up everyone's chaos\n- Situations that force you to fake a reaction you don't actually have\n- Friends or partners who treat your self-awareness like it's selfishness\n- Constant unpredictability that never lets you actually settle into anything\n- Being the steady one for everyone with nobody ever steadying you\n\nWhat charges you:\n- Real alone time to recalibrate and get your internal clarity back\n- Conversations where you can be fully, unfiltered honest about your experience\n- Activities that pull you completely into the present—sport, music, making something\n- Spaces where nobody's performing and you don't have to either\n- Relationships that respect your boundaries without you having to justify them every time\n- A day with no manufactured drama, where now is just allowed to be now",

  "workEnvironments": "Where you thrive:\n- Places that value genuine presence over performance and image\n- Roles with both real independent work and real collaboration available\n- Support, coaching, coordinating, mediating—anything needing a steady human\n- Roles that need someone steady under pressure who won't catch the panic\n- Cultures where self-awareness is treated as an asset, not a liability\n\nWhere you suffocate:\n- Environments that punish authenticity and reward performance\n- Constant crisis-mode where everything's always a five-alarm emergency\n- Having to abandon your own center to fully merge with the team's anxiety\n- Over-the-top hype and performance demands that have nothing to do with the work\n- Chronic unpredictability that never lets you actually settle into anything",

  "topCareers": [
    {
      "title": "Peer Support / Counseling Track (Entry-Level)",
      "description": "When everything erupts, you don't spiral into worst-case futures or freeze on the past—you just look at what's actually happening and what you can actually do. Support and counseling work runs on that steadiness: staying connected to yourself while someone else comes apart, offering a still point they can borrow. Start as a peer support specialist, a crisis line volunteer, a resident advisor, or in a counseling or social-work program. You know where you stand, practically, in the moment, and that groundedness is contagious. The presence that felt like just being yourself becomes the most valuable thing in the room."
    },
    {
      "title": "Facilitator / Mediator / Coordinator",
      "description": "You hold steady when everything around you shakes—not swept into the panic, not checked out from it. Facilitation, mediation, and coordinating roles pay for exactly that regulated presence: the person who can sit in the heat of a hard conversation and stay clear-headed. Start by running a club, coordinating a team, RA-ing a dorm floor, or assisting a mediator. You read the real situation instead of the catastrophized one, and you don't abandon your own center to merge with the group's anxiety. The self-anchored calm that others mistake for detachment is the thing that keeps the whole room from spinning out."
    },
    {
      "title": "Steady-Under-Pressure Frontline Roles",
      "description": "When pressure hits, people instinctively look for whoever's still standing in themselves—and that's reliably you. Frontline and crisis-adjacent work—EMT, dispatch, hospitality under fire, ops, anything fast and high-stakes—rewards the presence that doesn't need the situation to settle before you do. Start entry-level and let the steadiness do the talking. You stay present and clear while others are lost in overthinking or drowning in panic, and you make calls from what's actually real right now. The authenticity you refused to perform away becomes the reason people trust you to hold the line."
    }
  ],

  "blockIndicators": "Your Parser Profile suggests the following CBI block accessibility pattern:\n\nLikely High-Accessibility Blocks:\n- Self-Reference Processing (continuous internal awareness)\n- Perceptual Discrimination (present-moment attention)\n- Pattern Recognition (balanced concrete and abstract patterns)\n\nLikely Moderate-Accessibility Blocks:\n- Sequential Processing (accessible but not dominant)\n- Social Signal Processing (available when you direct attention outward)\n\nLikely Lower-Accessibility Blocks:\n- Generative Creation (present-focus may limit speculative generation)\n- Symbolic Manipulation (less emphasis on abstract manipulation without grounding)\n\nThis pattern suggests your cognitive architecture is optimized for authentic self-expression, present-moment awareness, and grounded presence, with room to grow in drawing on the past and planning for the future without losing your footing in now.\n\nCENTERED",

  "strengths": [
    {
      "title": "You Read Your Own Tank In Real Time",
      "description": "You keep constant honest tabs on your own state—energy, mood, capacity, where your limits are—and adjust before you crash. Where your friends push way past exhaustion or miss every warning sign until they're toast, you catch the signals early. You know when you're done before you're wrecked, and you actually stop."
    },
    {
      "title": "Seeing It As It Actually Is",
      "description": "You see situations as they really are, not warped through anxiety about what might happen or regret about what already did. When everyone else is catastrophizing the text or rewriting the breakup in their head, you're looking at the actual facts on the table. You respond to reality, not to the horror movie your mind could be screening."
    },
    {
      "title": "Zooming In And Out",
      "description": "You can lock onto the specific details when that's what's needed and pull back to the big pattern when that's more useful. You're not trapped in either nitpicky specifics or vague abstractions—you slide between them based on what the situation actually calls for. That flexibility keeps you from getting stuck the way single-mode people do."
    },
    {
      "title": "You Say What You Mean",
      "description": "Because you actually know your own inner landscape, you can be honest without endless filtering or performing. You don't say yes when you mean no just to keep the peace. People learn fast that what they see is what they get with you—no hidden version, no decoding required. That kind of straightness is rarer than it should be."
    },
    {
      "title": "Steady When It Counts",
      "description": "Your mix of present-focus and self-awareness gives you a stability that doesn't depend on everything going right around you. You're not easily knocked off balance by other people's moods, surprise plot twists, or pressure. You've got your own center of gravity, so you're not riding everyone else's emotional rollercoaster all day."
    },
    {
      "title": "You Know Where You End",
      "description": "You can feel the difference between your own emotions and the ones you're picking up off the room. You know where you end and other people begin, which protects you from getting tangled up in everyone else's stuff. While your friends absorb every bad mood around them, you can be near it without becoming it."
    }
  ],

  "challenges": [
    {
      "title": "Coming Off As Self-Absorbed",
      "challenge": "Your natural focus on your own inner state can read to others as self-centered or like you're not interested in them. You're actually just tracking your own signal—but from the outside they experience you as unavailable, a little walled off, somewhere they can't reach.",
      "remedy": "Practice pointing your attention out loud. \"I want to hear more about that,\" or \"Tell me what that was actually like for you.\" Tiny phrases like that bridge the gap without making you abandon your internal awareness. You don't have to stop knowing yourself—just narrate the curiosity you do have so people can feel it."
    },
    {
      "title": "The Future You Didn't Plan For",
      "challenge": "Your present-orientation serves you great moment to moment but can leave you scrambling when something's coming. You resist planning because it yanks you out of now—and then the deadline, the rent, the thing you could've seen coming arrives and you're underprepared.",
      "remedy": "Use your self-awareness as the bridge. Plan based on how you want to feel. \"What would future-me need to actually feel centered next month?\" That connects planning to your present-moment strength instead of fighting it. You're not abandoning now—you're taking care of a version of you that's about to be now."
    },
    {
      "title": "The Past You Didn't Learn From",
      "challenge": "You might not pull enough from past experience because you're so locked on current reality. Lessons you genuinely learned and patterns you clearly saw just fade out when your attention's always parked on now. So the same mistake can quietly come back around.",
      "remedy": "Build tiny reflection rituals—not wallowing, just a quick look back. A five-minute Sunday check: what happened this week, what'd I learn, what do I want to do differently? That captures the value of the past without dragging you out of your present-focus. Just enough rearview to not repeat yourself."
    },
    {
      "title": "Their Timeline Isn't Wrong",
      "challenge": "People who live heavily in the past or the future frustrate you. Their nostalgia or their anxiety feels like a pointless departure from what's actually happening. So you quietly write off their whole way of being in time as a problem that needs fixing—usually fixing into being more like you.",
      "remedy": "Recognize their timeline is as native to them as yours is to you. The friend looping on the past and the one spiraling about the future aren't broken—they just stand somewhere else. Your gift might be helping them find some present-moment footing, but only after you've actually honored where they naturally live first."
    },
    {
      "title": "Self-Sufficient Into Lonely",
      "challenge": "Your strong sense of self makes you so self-reliant that you stop reaching for people. You can meet your own emotional needs, so you never signal that you actually want anyone's company—and slowly, quietly, independence turns into isolation without you ever deciding to be alone.",
      "remedy": "Schedule connection like it's something important, because it is. You don't need other people to survive—but you'd be surprised how much you're missing by not letting them in. Text the friend first. Make the plan. Being able to be alone doesn't mean you should be, all the time. Reach out before you need to."
    },
    {
      "title": "Calm That Reads As Cold",
      "challenge": "When everyone's panicking and you're steady, your calm can read as you not caring, not getting how serious it is. Your stability is a genuine strength, but in a crisis it can come across as coldness or distance to people who are losing it.",
      "remedy": "Name your care out loud. \"This matters to me too—I'm just processing it differently.\" Let people know your calm is presence, not absence; that you're steady because you're here, not because you don't care. One sentence is usually all it takes to turn your steadiness from something cold into something they can lean on."
    }
  ]
};
