// COHERENT Profile
// Parser Profile™ © 2026 Cognition Blocks LLC

export const coherentProfile = {
  "name": "COHERENT",
  "tagline": "The one who finds the thread that connects everything",

  "overview": "You were in a meeting once where everyone was arguing about what to do next, and you were the one who said, quietly, \"wait—this is the same argument we had two years ago.\" You remembered the last time. You could see the line running from that decision to this room. While everyone else treated the moment as if it had dropped out of the sky, you were tracing the thread back to where it actually started.\n\nThat's the thing you've always done. Where other people saw isolated events, you saw continuity—how this grew out of that, how the pattern had run before, how nothing arrived without a history behind it. You'd been the one asking \"how did we get here?\" while everyone else argued about where to go, because you'd learned that the path explains the position. You couldn't read where you were standing until you knew how you'd arrived.\n\nYour mind moved easily between the specific fact and the pattern it belonged to. You could name the exact meeting, the exact date, the thing that was actually said—and you could also see the larger shape those details made when you stepped back. The detail and the throughline, held in the same hand.\n\nAnd you tracked it on both sides of the line: your own history and everyone else's. You watched how your past and the group's past wound together, how a decision someone made before you arrived was still shaping the room you walked into. The story you were following had never been only yours, and it had never been only theirs—it was the whole tangle, and you were one of the few people actually reading it.\n\nThey called you thorough, sometimes \"too analytical,\" occasionally \"stuck in the past.\" What they couldn't see was that the context you carried was the thing that made the present legible—that the questions you asked about how it began were what kept the next decision from repeating the last mistake.",

  "howYouLearn": "It only stuck when it came with a history. A fact handed to you bare—just the current state, no story of how it got that way—was gone by the next week. But show you how something developed, what came before it, the wrong turn that led to the fix, and it became permanent. You learned genealogically: you wanted to know where a thing came from before you could hold onto what it was.\n\nYou needed the backstory to make sense of the content. The teachers who taught only the present tense of a subject—here's how it works now—lost you. The ones who walked you through how it came to work that way, the dead ends and the corrections, gave you something you could actually keep. The story was the structure your mind reached for.\n\nYou learned best from anything that moved through time: the case history, the biography, the long account of how a field argued its way to what it now believes. Watching one thing lead to another was how you filed it. And you'd test a new idea the same way—against what you'd already seen happen, checking whether it matched the pattern the past had shown you.\n\nThe watch-out: because context felt essential, you could chase it forever. Every cause had a cause behind it, and you'd follow the thread back past the point where it still mattered. At some point you'd already learned enough of the history to understand the present—and learning to feel where \"enough\" was became its own discipline.",

  "howYouCommunicate": "You explained things by bringing the backstory with you. When someone asked you a question, you didn't just hand over the answer—you walked them through how it came to be that way, what preceded it, where it fit in the larger pattern. That thoroughness served understanding, and it sometimes tested the patience of people who only wanted the conclusion.\n\nYou tended to show your work rather than just declare the result. Instead of stating where you'd landed, you traced how you'd gotten there—the evidence across time, the way one thing had led to the next. It made your reasoning easy to follow and, to the impatient, easy to mistake for slowness.\n\nWhat you were genuinely good at was finding the throughline when everyone else was lost in the pieces. When a group was drowning in scattered detail, you could name the pattern that organized all of it—the story underneath the noise. That was your value in any room trying to understand something complicated, and people felt it even when they couldn't have named it.\n\nWhere it got harder: the audiences that didn't want context at all. When someone needed the answer now, with no history attached, your thoroughness turned into an obstacle, and you had to learn to ration the backstory—offer it when it was wanted, in a size someone could actually swallow. You did your best work where depth was valued and people were willing to spend the time it took to genuinely understand.",

  "phrase": "You're not living in the past. You're reading the present through it. Where they saw isolated events, you saw the connected history that produced them.",

  "secret": "You saw connections other people missed—threads tying the present back to something earlier, invisible to anyone only looking at what was in front of them. You'd watched a group make a decision with no idea how they'd gotten into the situation it was meant to fix, and then watched them get blindsided by a consequence that anyone who knew the history could have called.\n\nThe quiet part is that carrying all that context could feel like a weight. You held backstory other people didn't—the precedents, the repetitions, the echoes nobody else heard. There were times you'd have liked to just react to the moment, clean, without knowing how three versions of the same moment had already played out.\n\nYou'd been the one who said \"this happened before,\" and watched people nod and ignore you until it happened again. Seeing the cycle without being able to stop it was its own particular frustration. You named the pattern; they insisted it was new; the pattern completed itself; and somehow no one drew the lesson but you.\n\nThere was a loneliness in that. You were working with more complete information than the people around you, and it was information they mostly didn't want—not until a crisis made it suddenly essential, by which point it was usually too late to use it well.\n\nSome days you wondered whether all the understanding even mattered. Other people seemed to get along fine without it, deciding with no sense of history at all and somehow surviving. Maybe, you thought, you were just making everything more complicated than it needed to be.\n\nYou never really believed that. But you'd wondered.",

  "whatOthersGetWrong": "They thought you were stuck in the past when you were actually anchored by it. They mistook your historical eye for a preference for old times. You weren't saying the past was better—you were saying it was relevant, that understanding where a thing came from wasn't nostalgia, it was method.\n\nThey called you an over-thinker when the truer word was thorough. They wanted the conclusion without the context, the answer without the understanding, and your synthesis felt like delay to people who hadn't yet learned that acting without understanding the situation usually cost more than the wait would have.\n\nYou got told to \"stop analyzing and just do something\" by people who then did the wrong something, because they hadn't understood what they were dealing with. The analysis was never the problem. Their impatience was.\n\nAnd they assumed your balance—your habit of weighing every side—meant you had no conviction. You did. You were convinced that context mattered, that history rhymed, that the situation in front of you had a cause you could actually find. Your evenhandedness wasn't indecision. It was the refusal to pretend the picture was simpler than it was.",

  "hiddenSuperpower": "You saw the thread that ran through time. Where other people treated each situation as its own island, you tracked the continuity—how a decision had led to an outcome, how a pattern had run before, how the present had grown directly out of a past you could point to. That was something the people around you simply couldn't access, because they'd never been looking.\n\nIt made you invaluable the moment anything got complicated. When a group was debating options without grasping the constraints, you could explain how those constraints had come to exist. When they were blindsided by a result, you could trace it back to its cause. When they were sure they were facing something brand new, you could show them the version of it that had already happened.\n\nThe synthesis itself was rare. You could take a pile of scattered history—dates, decisions, half-remembered events—and weave it into something coherent, the story that organized the data. Where others heard noise, you found the signal. And because your attention split evenly between yourself and everyone else, the picture you built wasn't lopsided toward your own view; you were tracking the whole field, not just your corner of it.\n\nYou probably held institutional memory that whole organizations leaned on without realizing it. The backstory, the \"how we got here,\" the reason a rule existed in the first place—that knowledge lived in you when it lived nowhere else. People usually only discovered how much they'd depended on it the day you weren't there to ask.",

  "blindSpot": "Your pattern recognition could tip into pattern imposition. Not everything actually repeated—some situations were genuinely without precedent—and when you forced the present into a template from the past, you could miss what was new in it and needed a fresh response. The parallel you saw wasn't always really there; sometimes it just rhymed.\n\nYour thoroughness could cost you the moment. Understanding was worth a great deal, but incomplete understanding plus a timely decision often beat complete understanding that arrived too late. Your need for the full context sometimes ran past the window that would have rewarded a faster move.\n\nYour evenhandedness, usually a strength, could blur into a refusal to commit. When you weighed the implications for yourself and for everyone else with exactly equal care, you didn't always end up advocating for either. Some situations needed you to take a side, and the balance that made your read so complete could leave you standing still when a choice was required.\n\nAnd the thread you traced so well backward—you didn't follow it forward with the same ease. You knew in fine detail how things had come to be, and gave a fraction of that attention to where they were heading or what was possible next. The same line that ran into the past extended into the future, and you tended to read only one direction of it.",

  "frictionPatterns": "You rubbed up against the people projecting forward from pure principle toward some goal, with no interest in how any of it had started. They wanted to picture where they were going; you wanted to understand how you'd all gotten here. To you context was the ground you stood on; to them it was dead weight slowing the launch.\n\nThe hard-charging future-focused wore on you. They were impatient with history, eager to move, treating everything behind them as irrelevant—and their speed looked like recklessness from where you sat, the same way your thoroughness looked like obstruction from where they sat.\n\nThe purely abstract thinkers didn't always share your respect for the concrete fact of what had actually happened. They wanted the framework; you wanted the precedent. They trusted the theory; you trusted the record of how it had played out before.\n\nWhat you brought to those frictions: your sense of history could ground someone else's forward motion in what had actually been learned, instead of what merely sounded good. Your growth edge: remembering that future-focus and present-focus weren't failures to understand—they were different orientations, each with its own real validity.",

  "energyPatterns": "What drained you:\n- Rooms that waved off history as beside the point\n- Being pushed to act before you understood the situation\n- Watching people make the same mistake again because no one had kept the record\n- Having to defend, one more time, why context mattered at all\n- Decisions made with no one checking what had happened last time\n- Organizations that kept no memory of themselves\n\nWhat charged you:\n- Tracing a pattern all the way across the years\n- The synthesis click—when the scattered pieces resolved into one thread\n- Being the person someone came to for the backstory\n- Finally understanding how a thing had actually come to be\n- A tangled history made coherent\n- A group that treated its own memory as worth keeping\n- The moment an old pattern called the current outcome exactly right",

  "workEnvironments": "Where you thrived:\n- Places that treated historical understanding and institutional memory as assets\n- Research, strategy, consulting, education, archives, analysis\n- Any work where knowing how things came to be this way changed the decision\n- Roles that rewarded depth of understanding over speed\n\nWhere you suffocated:\n- Places that counted only how fast you moved\n- Cultures of perpetual present, where nothing connected to anything before it\n- Organizations that treated history as irrelevant\n- \"Move fast and break things\" rooms with no memory of what already broke",

  "topCareers": [
    {
      "title": "Strategy Analyst / Consultant",
      "description": "Every hard call a group makes runs on a question you've been answering your whole life: how did we get here, and what does that tell us about where this goes? You can walk into a tangled situation, trace it back to the decision that actually caused it, and lay the thread out so the people in the room can finally see what they're standing on. You're not guessing at the future from a clean slate—you're reading it off the pattern the past already drew. That's the difference between advice that merely sounds good and advice that holds, and you learned it watching how many confident plans ignored the history that was about to repeat on them."
    },
    {
      "title": "Archivist / Historian",
      "description": "You were always the one who held the backstory when it lived nowhere else—the reason a rule existed, the meeting where everything turned, the version of this that already happened. This is that instinct made into a craft: keeping the record, organizing how a thing came to be, making sure the context survives the people who carried it around in their heads. You don't just preserve the past; you make it usable, so the next group doesn't have to relearn at full cost what an earlier one already paid for. The institutional memory you used to carry for free becomes the thing you're actually trusted to keep."
    },
    {
      "title": "Educator / Professor",
      "description": "You make complicated things make sense by showing how they came to be—not the bare current state, but the journey that produced it, the wrong turns and the corrections. That's exactly how you always wanted to be taught, and it's exactly how you teach: the case history, the throughline, the story that gives a fact somewhere to attach. You can take a field's long argument with itself and lay it out as one coherent line a student can actually follow. The thing you do without trying—finding the pattern under the noise—is the whole job, and people remember what they learned from you because you gave it a history to hang on."
    }
  ],

  "blockIndicators": "Your Parser Profile suggests the following CBI block accessibility pattern:\n\nLikely High-Accessibility Blocks:\n- Pattern Recognition (historical pattern detection)\n- Sequential Processing (chronological tracking and narrative)\n- Symbolic Manipulation (abstract pattern extraction)\n\nLikely Moderate-Accessibility Blocks:\n- Self-Reference Processing (balanced, accessible)\n- Social Signal Processing (balanced, accessible)\n- Perceptual Discrimination (concrete historical facts)\n\nLikely Lower-Accessibility Blocks:\n- Generative Creation (synthesis over generation)\n- Spatial Relationships (less emphasized)\n\nThis pattern suggests your cognitive architecture is optimized for historical synthesis, contextual understanding, and pattern recognition across time. Your developmental opportunities lie in future projection and present engagement—building capacity to follow the thread forward as naturally as backward.\n\nCOHERENT",

  "strengths": [
    {
      "title": "Contextual Intelligence",
      "description": "You understood things by where they came from. Hand you a situation and you'd immediately reach for what preceded it—the decision behind it, the pattern it belonged to, the larger shape it fit into. That contextual read gave you an accuracy the people skipping straight to the present never had: you saw the whole picture because you'd gone and found the picture's history."
    },
    {
      "title": "Historical Pattern Recognition",
      "description": "You watched patterns repeat that everyone else experienced as one-off events. The cycle they were sure was brand new, you'd seen before—or you'd seen its ancestor—and that recognition gave you something close to foresight. Knowing how the last version had played out told you, with uncomfortable accuracy, how this one probably would."
    },
    {
      "title": "Synthesis Capacity",
      "description": "You could take a pile of scattered history—dates, half-remembered decisions, contradictory accounts—and weave it into a single coherent story. Where other people saw a chaos of facts, you saw a structure with a throughline. That synthesis was what made complexity manageable for everyone around you; you found the one line that organized all the rest."
    },
    {
      "title": "Institutional Memory",
      "description": "You naturally held onto how things came to be, so in any group you became the person who knew the backstory. That memory was worth more than anyone usually noticed—it kept the same mistakes from being made twice and kept current decisions tied to what had actually been learned. People only measured it the day you weren't there and the history walked out with you."
    },
    {
      "title": "Balanced Perspective",
      "description": "Because your attention split evenly between yourself and everyone else, you tracked the shared history as carefully as your own. You weren't reconstructing just your side of how things got here; you were reconstructing the whole tangle. That balance was what made your synthesis trustworthy—you weren't missing half the story by only looking at one person's part in it."
    },
    {
      "title": "Continuity Awareness",
      "description": "You could see the line running from what had happened to what was happening now, the causes still alive in the present. Knowing why things were the way they were—not vaguely, but specifically—gave you the one thing that makes real change possible. You can't move what you don't understand, and you understood how it had gotten stuck."
    }
  ],

  "challenges": [
    {
      "title": "Analysis as Delay",
      "challenge": "The pull to understand before acting could push the acting off indefinitely. There was always more context to gather, one more piece of history to trace—and while you gathered it, the decision sat unmade and the window quietly closed.",
      "remedy": "Set an understanding budget. Give the historical dig a fixed amount of room, then decide with what you've got. Perfect context never arrives; sufficient context does. The question is \"Do I understand enough to act wisely?\"—not \"Do I understand everything?\""
    },
    {
      "title": "Pattern Over-Fitting",
      "challenge": "You could see historical patterns where there weren't any, forcing a present situation into a template from the past. Not everything was a repeat—some things were genuinely new—and your gift turned into a liability the moment it kept you from seeing what didn't fit.",
      "remedy": "Test the parallel before you trust it. When you catch the click of recognition, ask: \"What's actually different this time? What doesn't match the template?\" Let yourself find that a situation is genuinely unprecedented. The pattern you spot is a hypothesis to check, not a verdict to impose."
    },
    {
      "title": "Context Overload",
      "challenge": "Context was valuable and context was infinite. Every event had a cause, and that cause had a cause, and you could follow the thread backward forever without ever reaching a real beginning, because there wasn't one.",
      "remedy": "Draw the boundary on purpose. Ask: \"What history would actually change the decision in front of me—and what wouldn't?\" Some background is load-bearing; some is just interesting. Chase the part that changes the choice and let the rest go."
    },
    {
      "title": "Historical Determinism",
      "challenge": "Seeing so clearly how the present grew out of the past could start to feel like proof that nothing could change. You understood exactly how things had gotten stuck, and that understanding could quietly harden into the belief that stuck was permanent.",
      "remedy": "Understanding a cause isn't accepting it forever. History shows how you got here; it doesn't prove you can't go elsewhere. The same contextual knowledge that explains the constraint is the resource for loosening it—use it as a map forward, not a sentence."
    },
    {
      "title": "Communication Mismatch",
      "challenge": "Most people didn't share your orientation. You offered context and they wanted the conclusion; you traced the pattern and they wanted the recommendation. The synthesis that felt like rigor to you felt like delay to them.",
      "remedy": "Lead with the implication, then offer the history. Start with \"here's what I think we should do,\" and follow with \"here's why, based on what's happened before.\" Give people the answer they're asking for first, and the understanding they actually need second."
    },
    {
      "title": "Nostalgia Risk",
      "challenge": "Past-focus could slide into past-preference—a quiet sense that the earlier version was better, a resistance to change just because it departed from how things had been. Understanding history could curdle into attachment to it.",
      "remedy": "Separate understanding from preference. You can know exactly how something came to be without believing it should stay that way. Historical awareness is supposed to serve the road ahead. Ask: \"Is what I know about the past helping me move forward, or just anchoring me to it?\""
    }
  ]
};
