// COHERENT Profile — Young Adult (18–29)
// Parser Profile™ © 2026 Cognition Blocks LLC

export const coherentyaProfile = {
  "name": "COHERENT",
  "tagline": "The one who finds the thread that connects everything",

  "overview": "Your friend group was in the middle of some blowup—everyone taking sides, everyone sure it started last week—and you were the one who said, \"no, this actually goes back to that thing in October.\" You remembered. You could see the line running from that one moment to the fight everybody was having now. While everyone else treated it like it came out of nowhere, you were tracing it back to where it actually started.\n\nThat's the thing you've always done. Where other people see random events, you see how they connect—how this grew out of that, how the same thing already happened once, how nothing shows up without a backstory. You've been the one asking \"wait, how did we even get here?\" while everyone argues about what to do next, because you figured out early that the path explains the situation. You can't read where you're standing until you know how you got there.\n\nYour mind moves easily between the one specific memory and the bigger pattern under it. You can still picture the exact moment—who said what, where you were—and you can also name the theme it belonged to. The detail and the throughline, held in the same hand.\n\nAnd you track it on both sides: your own history and everyone else's. You watch how your story and your friends' stories wind together, how something that happened before you even showed up still shapes the group you're in now. The story you're following has never been only yours, and never only theirs—it's the whole tangle, and you're one of the only people actually reading it.\n\nPeople have called you the one with the memory, sometimes \"too analytical,\" sometimes the one who \"holds onto everything.\" What they don't see is that the context you carry is what makes the present make sense—that the questions you ask about how it started are what keep the group from walking into the same mistake twice.",

  "howYouLearn": "It only stuck when it came with a history. A fact handed to you bare—just how it is now, no story of how it got that way—was gone by the next week. But show you how something developed, what came before it, the wrong turn that led to the fix, and it locked in. You learn by where things come from; you want the origin before you can hold onto the thing itself.\n\nYou needed the backstory to make sense of the lesson. The teachers who only taught the current state lost you. The ones who walked you through how it came to be that way—the dead ends, the corrections—gave you something you could actually keep. The story was the shape your brain reached for.\n\nYou learn best from anything that moves through time: the documentary, the case history, the long explanation of how something became what it is. Watching one thing lead to the next is how you file it. And you test a new idea the same way—against what you've already seen happen, checking whether it matches the pattern.\n\nThe watch-out: because context feels essential, you can chase it forever. Every cause has a cause behind it, and you'll follow the thread back way past the point where it still matters. Sometimes you've already learned enough of the backstory to get the present—and knowing when \"enough\" is becomes its own skill.",

  "howYouCommunicate": "You explain things by bringing the whole backstory with you. Somebody asks a simple question and you don't just hand over the answer—you walk them through how it got to be that way, what came before, where it fits. That helps people actually understand, and it can also test the patience of someone who just wanted the short version.\n\nYou show your work instead of just stating the result. Rather than dropping a conclusion, you trace how you got there—the stuff that happened, the way one thing led to the next. It makes your thinking easy to follow and, to impatient people, easy to mistake for slow.\n\nWhat you're genuinely good at is finding the throughline when everyone else is lost in the pieces. When the group chat is chaos and nobody can agree on what's even going on, you're the one who can name the actual pattern underneath it. People feel that even when they can't name it.\n\nWhere it gets harder: people who don't want any context. When someone needs the answer right now, no history attached, your thoroughness turns into a roadblock, and you have to learn to ration the backstory—give it when it's wanted, in a size someone can actually take in. You do your best talking where depth is welcome and people will spend the time to really get it.",

  "phrase": "You're not living in the past. You're reading the present through it. Where they saw random events, you saw the connected history that produced them.",

  "secret": "You see connections other people miss—threads tying right now back to something earlier, invisible to anyone only looking at what's in front of them. You've watched your friends make a decision with no clue how they got into the situation it was supposed to fix, and then get blindsided by something anyone who knew the history could've called.\n\nThe quiet part is that carrying all that context can feel like a weight. You hold backstory other people don't—who did what, what already happened, the echoes nobody else hears. Sometimes you'd love to just react to the moment, clean, without knowing how three versions of it already played out.\n\nYou've been the one who said \"this happened before,\" and watched everyone nod and ignore you until it happened again. Seeing the loop without being able to stop it is its own kind of frustrating. You name the pattern; they swear it's different this time; it plays out exactly the same; and somehow you're the only one who learned anything.\n\nThere's a loneliness in that. You're working with more complete information than the people around you, and it's information they mostly don't want—not until something blows up and it's suddenly the most important thing, by which point it's too late to use it right.\n\nSome days you wonder if all the understanding even matters. Other people seem fine without it, deciding with zero sense of history and somehow getting by. Maybe, you think, you're just making everything more complicated than it needs to be.\n\nYou don't really believe that. But you've wondered.",

  "whatOthersGetWrong": "They think you're stuck on the past when you're actually standing on it. They mix up your memory for the backstory with some preference for old times. You're not saying before was better—you're saying it's relevant, that knowing where a thing came from isn't living in the past, it's how you actually understand it.\n\nThey call you an over-thinker when the truer word is thorough. They want the conclusion with no context, the answer with no understanding, and your way of connecting things feels like a delay to people who haven't figured out yet that acting without understanding usually costs more than the wait would've.\n\nYou get told to \"stop analyzing and just do something\" by people who then do the wrong something, because they didn't actually understand what was going on. The analyzing was never the problem. The impatience was.\n\nAnd they assume that because you weigh every side, you don't have any conviction. You do. You're convinced that context matters, that history repeats, that whatever's in front of you has a cause you can actually find. Your evenhandedness isn't you being wishy-washy. It's you refusing to pretend the situation is simpler than it is.",

  "hiddenSuperpower": "You see the thread that runs through time. Where everyone else treats each situation like its own island, you track how it connects—how a choice led to a result, how the same thing already happened once, how right now grew straight out of a past you can point to. Most people your age aren't even looking for that, so they just don't see it.\n\nIt makes you the person to have around when things get complicated. When the group is arguing about options without getting why the limits are even there, you can explain how those limits showed up. When everyone's blindsided, you can trace it back to the cause. When they're sure this is brand new, you can show them the version that already happened.\n\nThe way you pull it together is genuinely rare. You can take a pile of scattered history—who said what, half-remembered events, conflicting versions—and turn it into one story that actually makes sense. Where others hear noise, you find the signal. And because your attention splits evenly between you and everyone else, the picture you build isn't lopsided toward your own side—you're reading the whole thing.\n\nYou're probably already the keeper of your group's memory without anyone deciding it. The backstory, the \"how this started,\" the reason things are the way they are—it lives in you when it lives nowhere else. People usually only notice how much they leaned on it the day you're not there to ask.",

  "blindSpot": "Your pattern recognition can tip into pattern imposition. Not everything actually repeats—some things really are first-time—and when you force the present into a template from the past, you can miss what's new in it and needs a fresh response. The parallel you see isn't always really there; sometimes it just rhymes.\n\nYour thoroughness can cost you the moment. Understanding is worth a lot, but understanding-it-halfway plus actually deciding often beats understanding-it-completely too late. Your need for the full backstory sometimes runs past the window where a faster move would've won.\n\nYour evenhandedness, usually a strength, can blur into never committing. When you weigh what it means for you and for everyone else with exactly equal care, you don't always end up taking a side at all. Some situations need you to pick one, and the balance that makes your read so complete can leave you frozen when a choice is required.\n\nAnd the thread you trace so well backward—you don't follow it forward as easily. You know in detail how things came to be, and give a fraction of that to where they're heading, which matters a lot more when most of your life is still ahead of you. The same line that runs into the past runs into the future too, and you tend to read only one direction.",

  "frictionPatterns": "You rub up against people who are sprinting toward the next thing with zero interest in how any of it started. They want to picture where they're going; you want to understand how you all got here. To you, context is the ground you stand on; to them it's dead weight slowing things down.\n\nThe relentlessly future-focused wear on you. They're impatient with history, always onto the next plan, treating everything behind them like it doesn't count—and their speed looks like recklessness from where you sit, the same way your thoroughness looks like stalling from where they sit.\n\nThe pure-idea people don't always share your respect for what actually, concretely happened. They want the theory; you want the real example. They trust how it should work; you trust how it actually went last time.\n\nWhat you bring to it: your sense of history can keep a friend's big plans grounded in what's actually been learned, instead of what just sounds good. Your growth edge: remembering that being future-focused or people-focused isn't a failure to understand—it's just a different way of paying attention, and it's got its own real value.",

  "energyPatterns": "What drains you:\n- Groups that wave off history like it doesn't matter\n- Being pushed to act before you understand what's going on\n- Watching people make the same mistake again because nobody kept track\n- Having to explain, again, why context even matters\n- Decisions made with no one asking what happened last time\n- Friend groups or places with no memory of themselves\n\nWhat charges you:\n- Tracing a pattern all the way back across the years\n- That click when the scattered pieces line up into one thread\n- Being the person someone comes to for the backstory\n- Finally understanding how something actually came to be\n- A tangled, messy history turned into something that makes sense\n- People who treat their own memory as worth keeping\n- The moment an old pattern calls exactly what happens next",

  "workEnvironments": "Where you thrive:\n- Places that treat understanding-the-backstory and memory as strengths\n- Research, strategy, consulting, teaching, archives, analysis\n- Work where knowing how things got this way actually changes the call\n- Roles that reward depth over speed\n\nWhere you suffocate:\n- Places that only count how fast you move\n- Settings where nothing connects to anything before it\n- Groups that treat history like it's irrelevant\n- \"Move fast and break things\" spots with no memory of what already broke",

  "topCareers": [
    {
      "title": "Strategy Analyst / Consultant",
      "description": "Every hard call a team makes runs on the question you've been answering your whole life: how did we get here, and what does that tell us about where this goes? You can take a messy situation, trace it back to the thing that actually caused it, and lay the thread out so people can finally see what they're dealing with. If this pulls at you, the path is real—analyst roles, consulting, ops, anything where someone gets paid to figure out why things are the way they are. You already do it for free in your friend group; this is just the version with a paycheck."
    },
    {
      "title": "Archivist / Historian / Researcher",
      "description": "You're already the one who holds the backstory when it lives nowhere else—why things are the way they are, the moment everything turned, the version of this that already happened. Made into a job, that's keeping the record: organizing how something came to be so it survives the people who carried it around in their heads. History, library science, research, archives—they're all real paths, and they all run on the exact instinct you've had since you were a kid. And you don't just save the past; you make it usable, so nobody has to relearn it the hard way."
    },
    {
      "title": "Educator / Teacher",
      "description": "You make complicated stuff make sense by showing how it came to be—not just how it is now, but the journey, the wrong turns, the corrections. That's exactly how you always wished you'd been taught, and it's how you'd teach. You can take a tangled mess and lay it out as one clear line someone can follow. You're probably already the friend who explains the thing nobody else could—that's the early version of the whole job, and the path from here is real if you want it."
    }
  ],

  "blockIndicators": "Your Parser Profile suggests the following CBI block accessibility pattern:\n\nLikely High-Accessibility Blocks:\n- Pattern Recognition (historical pattern detection)\n- Sequential Processing (chronological tracking and narrative)\n- Symbolic Manipulation (abstract pattern extraction)\n\nLikely Moderate-Accessibility Blocks:\n- Self-Reference Processing (balanced, accessible)\n- Social Signal Processing (balanced, accessible)\n- Perceptual Discrimination (concrete historical facts)\n\nLikely Lower-Accessibility Blocks:\n- Generative Creation (synthesis over generation)\n- Spatial Relationships (less emphasized)\n\nThis pattern suggests your cognitive architecture is optimized for historical synthesis, understanding things in context, and spotting patterns across time. You've got room to grow in pointing all that backward-looking skill forward—learning to follow the thread into the future as naturally as you follow it into the past.\n\nCOHERENT",

  "strengths": [
    {
      "title": "Contextual Intelligence",
      "description": "You understand things by where they come from. Hand you a situation and you immediately reach for what led to it—the choice behind it, the pattern it fits, the bigger shape around it. That gives you an accuracy people skipping straight to \"what now\" never get: you see the whole picture because you went and found the picture's history."
    },
    {
      "title": "Historical Pattern Recognition",
      "description": "You watch patterns repeat that everyone else experiences as one-off events. The drama your friends are sure is brand new, you've seen before—or you've seen its ancestor—and that recognition gives you something close to calling it early. Knowing how the last version played out tells you, with kind of uncomfortable accuracy, how this one probably will too."
    },
    {
      "title": "Synthesis Capacity",
      "description": "You can take a pile of scattered history—who did what, half-remembered moments, conflicting stories—and turn it into one story that actually holds together. Where other people see a mess of facts, you see a structure with a throughline. That's what makes complicated things manageable for everyone around you: you find the one line that organizes the rest."
    },
    {
      "title": "Institutional Memory",
      "description": "You naturally hold onto how things came to be, so in any group you become the person who knows the backstory. That's worth way more than people notice—it keeps the same mistakes from happening twice and keeps decisions tied to what's actually been learned. People usually only clock it the day you're not around and the history walks out with you."
    },
    {
      "title": "Balanced Perspective",
      "description": "Because your attention splits evenly between you and everyone else, you track the shared history as carefully as your own. You're not reconstructing just your side of how things got here; you're reconstructing the whole tangle. That balance is what makes people trust your read—you're not missing half the story by only looking at your own part in it."
    },
    {
      "title": "Continuity Awareness",
      "description": "You can see the line running from what happened to what's happening now, the causes still alive in the present. Knowing why things are the way they are—specifically, not vaguely—gives you the one thing that makes real change possible. You can't move what you don't understand, and you understand how it got stuck."
    }
  ],

  "challenges": [
    {
      "title": "Analysis as Delay",
      "challenge": "The pull to understand before you act can push the acting off forever. There's always more backstory to dig up, one more thing to trace—and while you dig, the decision just sits there and the window quietly closes.",
      "remedy": "Give yourself an understanding budget. Let the digging have a set amount of time, then decide with what you've got. Perfect context never shows up; enough context does. The question is \"do I get this enough to act smart?\"—not \"do I get all of it?\""
    },
    {
      "title": "Pattern Over-Fitting",
      "challenge": "You can see patterns where there aren't any, forcing something new into a template from the past. Not everything's a repeat—some things really are first-time—and your gift turns into a problem the second it keeps you from seeing what doesn't fit.",
      "remedy": "Test the parallel before you trust it. When you feel that click of \"this again,\" ask: \"what's actually different this time? what doesn't match?\" Let yourself find that something is genuinely new. The pattern you spot is a guess to check, not a verdict to drop on it."
    },
    {
      "title": "Context Overload",
      "challenge": "Context is valuable and also infinite. Every event has a cause, and that cause has a cause, and you can follow the thread back forever without ever hitting a real beginning, because there isn't one.",
      "remedy": "Draw the line on purpose. Ask: \"what backstory would actually change what I do right now—and what wouldn't?\" Some background matters; some is just interesting. Chase the part that changes the call and let the rest go."
    },
    {
      "title": "Historical Determinism",
      "challenge": "Seeing so clearly how the present grew out of the past can start to feel like proof that nothing can change. You understand exactly how things got stuck, and that can quietly harden into believing stuck is permanent—which hits harder when you're young and a lot still isn't settled.",
      "remedy": "Understanding a cause isn't accepting it forever. History shows how you got here; it doesn't prove you can't go somewhere else. The same knowledge that explains why things are stuck is the tool for unsticking them—use it as a map forward, not a sentence."
    },
    {
      "title": "Communication Mismatch",
      "challenge": "Most people don't share your wiring. You offer context and they want the conclusion; you trace the pattern and they want the recommendation. The connecting-it-all that feels like being thorough to you feels like stalling to them.",
      "remedy": "Lead with the takeaway, then offer the history. Start with \"here's what I think we should do,\" then \"here's why, based on what already happened.\" Give people the answer they're asking for first, and the understanding they actually need second."
    },
    {
      "title": "Nostalgia Risk",
      "challenge": "Past-focus can slide into past-preference—a quiet sense that before was better, a pushback on change just because it's different from how things were. Understanding history can turn into being attached to it.",
      "remedy": "Keep understanding and preference separate. You can know exactly how something came to be without thinking it should stay that way. Knowing the history is supposed to serve where you're going. Ask: \"is what I know about the past helping me move forward, or just keeping me parked?\""
    }
  ]
};
