// COHERENT Profile
// Parser Profile™ © 2026 Cognition Blocks LLC
// Balanced • Past • Balanced

export const coherentProfile = {
  "name": "COHERENT",
  "code": "Balanced • Past • Balanced",
  "tagline": "The one who finds the thread that connects everything",

  "overview": "You see how things connect to what came before—even when others don't notice there's a thread. While people around you treat each moment as isolated, you're tracking continuity. How the present emerged from the past. How patterns repeat. How everything links to something earlier.\n\nYou've probably been the person who asks \"how did we get here?\" when everyone else is arguing about where to go next. Not because you're avoiding the future, but because understanding the path reveals options invisible to people who only see the current position. Context is your instrument. History is your lens.\n\nYour thinking moves fluidly between concrete facts and abstract patterns. You can recall specific events with clarity and also see the themes they reveal. This gives you access to both what happened and what it meant—the details and the throughline.\n\nYour attention naturally turns toward what's already occurred. Not with nostalgia, but as method. You believe understanding requires context, and context requires history. You're not looking backward because you prefer the past; you're looking backward because that's where understanding comes from.\n\nYour reference point balances self and other. You track historical patterns affecting you and affecting everyone else with equal attention. You're seeing how collective histories and personal histories interweave—how the story includes everyone.\n\nPeople have called you thorough, sometimes \"too analytical,\" occasionally \"stuck in the past.\" They see the historical orientation and assume you're avoiding the present or future. What they don't see is that your contextual awareness is what makes present decisions wise and future plans grounded.",

  "howYouLearn": "Learning lands for you when it comes with history. Facts without backstory don't stick; information with lineage becomes permanent. Your learning is genealogical—you want to know where this came from, how it developed, what preceded it.\n\nYou need the context to make sense of the content. Don't just teach the current state; teach the evolution that produced it. Don't just present findings; present the journey of discovery. History is how you organize and retain information.\n\nYou learn well from narrative structures—accounts that move through time, showing how one thing led to another. Case histories, biographical approaches, evolutionary explanations all engage your processing. The story is the structure your mind wants.\n\nYou learn poorly from decontextualized facts, ahistorical presentations, and information delivered as if it sprang into existence fully formed. Without the historical thread, you have nowhere to attach the knowledge. It floats without anchor.\n\nBe aware that your contextual learning style might cause you to pursue history indefinitely. At some point, you know enough context to understand the present. Learning to recognize \"enough\" is part of your growth.",

  "howYouCommunicate": "You communicate through context and connection. When you explain something, you naturally include backstory—how it came to be, what preceded it, where it fits in larger patterns. This thoroughness serves understanding but can test the patience of people who just want the point.\n\nYou tend toward synthesis rather than assertion. Instead of declaring conclusions, you show how conclusions emerge from evidence across time. This makes your reasoning transparent but can make your communication feel slow to people who prefer direct statements.\n\nYou're good at explaining complexity by finding the throughline. When others are lost in scattered details, you can articulate the pattern that organizes everything. This synthesis is your value in any group trying to understand something complicated.\n\nYou may struggle with audiences that don't value context. When they want the answer now, without the history, your thoroughness becomes obstacle. Learning to offer context selectively—when it's wanted, in amounts that are digestible—is ongoing calibration.\n\nYou communicate best in contexts that value depth and are willing to invest in understanding—strategic planning, analysis, education, anywhere that rewards seeing the full picture.",

  "phrase": "You're not living in the past. You're understanding the present through the past. They see isolated events; you see connected history.",

  "secret": "You see connections that others miss—threads linking present to past that are invisible to people who only look at what's in front of them. You've watched groups make decisions without understanding how they got into the current situation, then be surprised by consequences that were predictable to anyone who knew the history.\n\nThe secret is that your contextual awareness can feel like a burden. You carry information others don't—backstory, patterns, precedents. You see the repetitions they don't see, the echoes they don't hear. Sometimes you'd like to just react to the present without the weight of knowing how similar presents have played out before.\n\nYou've probably been the person who says \"this happened before\" and watches people ignore you until it happens again. The pattern-recognition without pattern-response is its own kind of frustration. You see the cycle; they insist it's new; the cycle completes; no one learns.\n\nThere's a loneliness in contextual awareness. You're operating with different information than people around you—more complete information, but information they don't want. The context you carry isn't valued until crisis makes it essential, and then it's too late to use it properly.\n\nSometimes you wonder if understanding matters. Others seem to function fine without it. They make decisions with no historical awareness and somehow survive. Maybe your contextual processing is just making everything more complicated than it needs to be.\n\nYou don't believe that, not really. But you've wondered.",

  "whatOthersGetWrong": "They think you're stuck in the past when you're actually anchored by it. They confuse your historical orientation with backward-looking preference. You're not saying the past was better; you're saying the past is relevant. Understanding history isn't nostalgia; it's method.\n\nThey call you \"over-thinker\" when you're actually thorough-thinker. They want conclusions without context, answers without understanding. Your synthesis feels like delay to people who haven't learned that uncontextualized action usually costs more than contextualized delay.\n\nYou've been told to \"stop analyzing and just do something\" by people who then did the wrong something because they didn't understand the situation. Your analysis wasn't the problem; their impatience was.\n\nThey assume your balanced perspective means you lack conviction. You have conviction—conviction that understanding matters, that context is essential, that history predicts. Your balance isn't indecision; it's completeness.\n\nThe deepest misread is that your historical awareness is passive. It isn't. Synthesis is active work. Finding the throughline in complex history takes effort. Holding context while others lose it requires capacity. You're not just remembering the past; you're actively using it to understand the present.",

  "hiddenSuperpower": "You see the thread that connects things across time. While others treat each situation as isolated, you're tracking continuity—how decisions led to outcomes, how patterns repeat, how the present emerges from the past. This historical vision gives you understanding that decontextualized thinkers can't access.\n\nThis makes you invaluable for any complex decision. When others are debating options without understanding constraints, you can explain how those constraints arose. When they're surprised by consequences, you can trace the causes. When they think they're facing novelty, you can show them the precedent.\n\nYour synthesis capacity is genuinely rare. You can take scattered historical information and weave it into coherent narrative—finding the story that organizes the data. Where others see noise, you see signal. Where they see chaos, you see pattern.\n\nYou probably hold institutional memory that organizations depend on without knowing it. The backstory, the context, the \"how we got here\"—this knowledge lives in you when it lives nowhere else. When you leave a group, they often discover how much they were depending on your historical awareness.\n\nYour balanced perspective means your synthesis isn't biased toward self or other, concrete or abstract. You're building a complete picture, not a partial one.",

  "blindSpot": "Your pattern recognition can become pattern imposition. Not everything repeats; some situations are genuinely unprecedented. When you force-fit the present into historical templates, you might miss what's actually new and requires fresh response.\n\nYour contextual thoroughness can delay necessary action. Understanding is valuable, but incomplete understanding plus timely action often beats complete understanding too late. Your drive for full context might cause you to miss windows that reward faster response.\n\nYour balanced reference, while generally an asset, might diffuse responsibility. When you track both self and other implications equally, you might not advocate strongly for either. Some situations require taking sides; your balance can become paralysis when choice is required.\n\nYou might also undervalue the present and future. Your past-focus gives you historical grounding but can leave you less attuned to what's happening now or what's possible next. The thread you're tracing backward also extends forward, but you might not follow it that direction as naturally.\n\nFinally, your synthesis might impose coherence that isn't there. Not all histories make sense; some are genuinely chaotic, contradictory, or random. Your drive to find the throughline might create narrative where there's actually just noise.",

  "frictionPatterns": "You'll clash with people projecting forward from conceptual principles toward personal goals—history-free, purely future-oriented. You want to understand how we got here; they want to envision where we're going. You see context as essential; they see it as constraint.\n\nFuture-focused profiles will frustrate you. They're impatient with historical context, eager to move forward, treating the past as irrelevant weight. Their speed feels like recklessness to you; your thoroughness feels like obstruction to them.\n\nAbstract-only processors might not share your appreciation for concrete historical facts. They want principles; you want precedents. They trust theoretical frameworks; you trust empirical patterns.\n\nYour gift in these frictions: Your historical awareness can ground others' forward motion in what's actually been learned.\n\nYour growth edge: Recognizing that future-focus and present-focus aren't failures of understanding—they're different orientations with their own validity.",

  "energyPatterns": "What drains you:\n- Environments that dismiss history as irrelevant\n- Pressure to act without understanding\n- People who make the same mistakes repeatedly without learning\n- Having to justify why context matters\n- Decisions made without consulting precedent\n- Organizations with no institutional memory\n\nWhat charges you:\n- Tracing patterns across time\n- Synthesis—finding the thread that connects\n- Being consulted for historical context\n- Understanding how things came to be\n- Complex histories made coherent\n- Groups that value institutional memory\n- The moment when historical pattern predicts current outcome",

  "workEnvironments": "Where you thrive:\n- Environments that value historical understanding and institutional memory\n- Research, strategy, consulting, education, archives, analysis\n- Any domain where understanding how things got to be this way matters\n- Roles where depth of understanding translates into better decisions\n\nWhere you suffocate:\n- Environments that only value speed\n- Cultures of perpetual present where nothing connects to anything before\n- Organizations that dismiss history as irrelevant\n- \"Move fast and break things\" contexts",

  "blockIndicators": "Your Parser Profile suggests the following CBI block accessibility pattern:\n\nLikely High-Accessibility Blocks:\n- Pattern Recognition (historical pattern detection)\n- Sequential Processing (chronological tracking and narrative)\n- Symbolic Manipulation (abstract pattern extraction)\n\nLikely Moderate-Accessibility Blocks:\n- Self-Reference Processing (balanced, accessible)\n- Social Signal Processing (balanced, accessible)\n- Perceptual Discrimination (concrete historical facts)\n\nLikely Lower-Accessibility Blocks:\n- Generative Creation (synthesis over generation)\n- Spatial Relationships (less emphasized)\n\nThis pattern suggests your cognitive architecture is optimized for historical synthesis, contextual understanding, and pattern recognition across time. Your developmental opportunities lie in future projection and present engagement—building capacity to follow the thread forward as naturally as backward.\n\nCOHERENT",

  "strengths": [
    {
      "title": "Contextual Intelligence",
      "description": "You understand things in context—where they came from, what preceded them, how they connect to larger patterns. This contextual processing gives you insight that decontextualized thinkers miss. You see the whole picture because you see the picture's history."
    },
    {
      "title": "Historical Pattern Recognition",
      "description": "You see patterns repeating across time that others experience as unique events. The cycle they think is new, you've seen before—or you've seen its ancestor. This pattern recognition gives you predictive power: knowing what happened last time helps you anticipate what happens next time."
    },
    {
      "title": "Synthesis Capacity",
      "description": "You can take complex, scattered historical information and weave it into coherent narrative. Where others see chaos of facts, you see story with structure. This synthesis makes complexity manageable—you find the throughline that organizes everything else."
    },
    {
      "title": "Institutional Memory",
      "description": "You naturally retain and organize information about how things came to be. In any group, organization, or community, you become the person who knows the backstory. This memory is invaluable—it prevents repeated mistakes and grounds current decisions in what's been learned."
    },
    {
      "title": "Balanced Perspective",
      "description": "Your balanced reference means you track patterns affecting self and others equally. You're not just understanding your own history; you're understanding shared history. This balance makes your synthesis more complete—you're not missing half the data by focusing only on one perspective."
    },
    {
      "title": "Continuity Awareness",
      "description": "You see how present connects to past in ways others miss. The link between current situation and historical cause is visible to you, which gives you understanding of why things are the way they are. This causal awareness is foundation for meaningful change."
    }
  ],

  "challenges": [
    {
      "title": "Analysis as Delay",
      "challenge": "Your drive to understand before acting can delay action indefinitely. There's always more context to gather, more history to examine, more patterns to trace. Meanwhile, decisions need making and opportunities pass.",
      "remedy": "Set understanding budgets. Allocate specific time for historical analysis, then decide with available understanding. Perfect context is never available; sufficient context is the goal. Ask: \"Do I understand enough to act wisely?\" rather than \"Do I understand everything?\""
    },
    {
      "title": "Pattern Over-Fitting",
      "challenge": "You might see historical patterns where they don't actually exist, forcing present situations into past templates. Not everything is repetition; some things are genuinely new. Pattern recognition becomes liability when it prevents seeing novelty.",
      "remedy": "Test your patterns. When you recognize a historical parallel, check: \"What's different this time? What doesn't fit the template?\" Be willing to discover that this situation is actually unprecedented. Your pattern recognition is a hypothesis to test, not a conclusion to impose."
    },
    {
      "title": "Context Overload",
      "challenge": "Understanding context is valuable, but context is infinite. Every event has prior causes that have prior causes. You can follow the thread backward forever without ever reaching the \"real\" beginning, because there isn't one.",
      "remedy": "Define relevant context boundaries. Ask: \"What historical understanding would change my current decision? What wouldn't?\" Focus on context that matters for the choice at hand. Some background is essential; some is interesting but not actionable."
    },
    {
      "title": "Historical Determinism",
      "challenge": "Deep understanding of how the present emerged from the past can feel deterministic—as if current constraints are fixed because they have history. You might underestimate capacity for change because you see so clearly how things got stuck.",
      "remedy": "Remember: understanding causes isn't accepting permanence. History shows how we got here; it doesn't prove we can't go elsewhere. Your contextual knowledge is a resource for change, not an argument against it."
    },
    {
      "title": "Communication Mismatch",
      "challenge": "Most people don't share your historical orientation. When you offer context, they want conclusions. When you trace patterns, they want recommendations. Your synthesis feels like delay to people who process without history.",
      "remedy": "Lead with implications, follow with history. Start with \"here's what I think we should do\" then offer \"here's why, based on what's happened before.\" Give them the answer they want, then the understanding they need."
    },
    {
      "title": "Nostalgia Risk",
      "challenge": "Past-focus can slide into preferring the past, believing earlier times were better, resisting change because it departs from history. Your understanding of history can become attachment to history.",
      "remedy": "Separate understanding from preference. You can understand how things came to be without believing they should stay that way. Historical awareness serves the future, not just the past. Ask: \"Is my historical knowledge helping me navigate forward, or anchoring me backward?\""
    }
  ]
};
