// COLLABORATIVE Profile — Young Adult (18–29)
// Parser Profile™ © 2026 Cognition Blocks LLC

export const collaborativeyaProfile = {
  "name": "COLLABORATIVE",
  "tagline": "The one who sees what you could all build together",

  "overview": "You think in \"we\" without even trying. Someone drops a half-baked idea in the group chat and your brain is already three steps ahead—who'd be good at what, who you'd text to make it real, how the people who barely know each other could actually click. Where everyone else sees a random group of people, you see a thing that could exist if someone just pulled the threads together.\n\nYou notice the group that wants to form before it knows it wants to form. The two people in your friend circle who'd obviously hit it off. The classmate with the skills who'd be perfect for the thing your roommate is trying to start. You introduce people, you connect dots, you make the room feel like a team instead of a bunch of strangers waiting for the awkward to end.\n\nAnd you can get real about it, not just dreamy. You hold the hyped vision—\"we could actually do something here\"—and the boring logistics at the same time. Who's bringing what. Who's flaky. What it'll actually take to not fall apart by week three. You're not lost in some fantasy of everyone holding hands; you can see how the holding-together actually works.\n\nPeople call you a team player, a connector, the glue. It's true, but it sells you short. You're not just easy to work with. You're seeing possibilities for what a group could become that literally no one else in the room is seeing.",

  "howYouLearn": "It sticks when you learn it with people. The lecture you sat through alone is gone by the weekend, but the concept you wrestled through in a study group, explaining it back and forth until it clicked for everyone—that one stays. Solo flashcards feel hollow; the second you turn it into a conversation, your brain actually wakes up.\n\nYou want both the why and the how. The theory alone bores you, the steps alone feel pointless, but show you how knowing this lets you build something better with other people and you're locked in. \"How does this help us pull something off\" is the question running underneath everything you study.\n\nYou learn so you can immediately turn around and share it. Teaching a friend the thing you just figured out isn't a distraction from your learning—it's how the learning finishes. The study group where you become the one explaining it to everybody else? That's you retaining it harder than any of them.\n\nThe catch: you can quietly undervalue the stuff you can only learn alone. Some things just require you sitting by yourself, grinding through it, no group to lean on—the solo coding problem, the essay nobody can write for you. That mode doesn't come naturally, so you skip it. Make yourself sit in it anyway, even when it feels lonely.",

  "howYouCommunicate": "You talk in \"we\" automatically. \"What if we all just…\" \"We could totally…\" \"Okay so who's down?\" It's not a strategy to sound nice—it's genuinely how you see the situation. Everything lands in your head as a shared thing, so it comes out of your mouth as a shared thing.\n\nYou're the one who pulls quiet people into the conversation. You notice the friend who hasn't said anything in twenty minutes and ask what they think. You catch the two ideas floating past each other and go \"wait, those are kind of the same thing.\" People feel seen around you because you're actually tracking what they bring, not just waiting for your turn to talk.\n\nIn group projects and group chats you end up facilitating without anyone naming you the leader. You synthesize, you summarize, you say the thing everyone was circling. It's useful and it's also exhausting—you're doing real work that nobody assigned you and nobody's going to thank you for.\n\nThe thing you're worst at: speaking for yourself. You can rep the whole group's needs in a meeting flawlessly and then completely blank when someone asks what you personally want. \"I'm good with whatever\" is your default even when you're not. Practice saying \"I\" with the same ease you say \"we.\" Your own take is allowed to count too.",

  "phrase": "You don't just work well with others. You see what a bunch of \"others\" could become together. The team is always more obvious to you than your spot in it.",

  "secret": "Sometimes you don't really know who you are when there's no group around.\n\nWhen everyone's gone home and the chat goes quiet and there's no plan to coordinate, no friend to help, nothing to pull together—you can feel weirdly empty. Like, what do you even want when you're not tracking what everyone else wants? Who are you when you're not the one making the thing happen for other people?\n\nThose questions hit harder than you let on. Your whole sense of yourself has gotten tangled up in being the connector, the helper, the one who holds it together. You know exactly what you do for everyone else. You're way less sure who you are when nobody needs anything from you.\n\nThe deeper version: you've wondered if all this caring-about-the-group is secretly a way to avoid figuring out yourself. It's easier to ask what everyone wants than to admit what you want. Safer to help someone else chase their dream than to name your own and risk failing at it out loud. Being everyone's glue means you never have to just stand there as a whole separate person who wants things.\n\nIt doesn't mean any of it is fake—you really do love building stuff with people, that part is true. But underneath there's a question you keep dodging: what would you make if you weren't making it for someone else? You don't have to answer it tonight. But it's worth sitting with, alone, when there's no one around to orient toward.",

  "whatOthersGetWrong": "They think being collaborative means you're a pushover. They see you going with the group, caring about everyone being okay, and decide you must not have real opinions—that you'll just float along with whatever gets decided. They mistake \"cares about the team\" for \"has no spine.\"\n\nWhat they miss is that you usually have a very clear sense of what the group could pull off—you just hold it for the group instead of shoving it down everyone's throat. You can be stubborn about where things should go while staying flexible about your own little spot in it.\n\nThey think you're nice but not strategic. The warmth registers; the actual thinking underneath doesn't. They don't see you mapping who'd be good at what, tracking what each person needs, quietly designing the thing so it doesn't collapse. You're not just being friendly at the party—you're building something.\n\nSome assume that because you're into teamwork, you must want to be in charge, running people. But control isn't the thing for you—it's watching it click. You don't want to boss the group; you want to set it up so the group runs itself. That distinction is invisible to people who can only picture group stuff as somebody on top barking orders.\n\nAnd they think your big \"we could all\" energy is unrealistic, like you're dreaming about a team that'll never actually show up. They don't see that you're not imagining some impossible squad—you're seeing a real one that could exist, that everyone else just stopped looking for.",

  "hiddenSuperpower": "You can see the group that wants to form before it knows it wants to form.\n\nTeams don't just appear fully built. They start as a bunch of separate people who have no idea they fit together—chasing their own goals that could be one shared goal, sitting on skills that would be unstoppable combined, struggling alone with problems they could crush as a crew.\n\nMost people can't see a team until it already exists. You see it before it does. You clock the two people who should obviously be working together but haven't met. The classmate whose project is secretly the same as your friend's. The collab that's just sitting there waiting for someone to point it out.\n\nThat's the superpower. You make collaborations happen that genuinely wouldn't have otherwise—not because people didn't want to team up, but because they couldn't see who to team up with. You see the whole hidden network under what looks like a room full of strangers.\n\nWhen you introduce two people who should know each other, you're not just being social—you're building the wiring for something that doesn't exist yet. When you go \"wait, you both want the same thing,\" you're helping a team recognize itself. When you get unlikely people in the same room, you're surfacing potential nobody else could even see.\n\nThe futures you imagine—where scattered people become an actual crew, where a random group becomes a real thing—aren't fantasies. They're real possibilities sitting right in front of everyone, just waiting for someone like you to make them visible.",

  "blindSpot": "You don't always notice when being the collaborative one is getting you used.\n\nBecause you genuinely care about the group, you end up absorbing way more than your share—the planning, the chasing people down, the smoothing-over after a fight, the emotional cleanup—without clocking how lopsided it's gotten. You track everyone's needs, so you always notice when they need backup. You barely track your own, so you don't notice when you need it and nobody's offering.\n\nThis turns into a pattern where you're the one holding the whole thing together while everyone else just enjoys the thing. The group project where you do the coordinating and they put their names on it. The friend group where you're always the one who texts first, plans it, fixes it when it breaks. They let you, because why wouldn't they—you keep doing it.\n\nWatch for: the group efforts where you're somehow always doing the invisible work. The nights you leave the hangout drained while everyone else got recharged. The friendships where you're forever the initiator, the planner, the repair crew.\n\nAlso watch for your own part in it. Your whole orientation can make you complicit in your own burnout—you resist even admitting it's unfair, because admitting it means centering yourself, and that feels foreign and gross. It's genuinely easier to keep giving than to ask to receive.\n\nYour blind spot isn't the collaborating. It's the assumption that if the group's okay, you're automatically okay too. Sometimes you have to actually say \"I need something here\"—not because teamwork is bad, but because your specific role drifts straight toward self-neglect unless you fight it on purpose.",

  "frictionPatterns": "You grate against the friend who's only ever calculating what's in it for them. You're sitting there going \"if we combined this we could all win\" and they're going \"but what do I get.\" Their lone-wolf, mine-first energy hits your everyone-wins instinct like sandpaper, and neither of you fully gets why the other is like that.\n\nYou also clash with the people who want to dwell on how it went last time instead of building what's next. You're already imagining the new version; they're protecting the memory of the old one. Your \"let's just go\" can read as you blowing off history that matters to them, and their \"remember last time\" can read as them dragging on the brakes.\n\nThe hardest one is when you're hyped about something you could all build together and the group just… doesn't share it. You can see the whole thing—who'd do what, how good it could be—and they're shrugging. Pouring your connector energy into people who don't actually want to be connected is one of the most draining things there is.\n\nWhat you bring to all this is real: you create the conditions where a random group becomes an actual team, and you make people feel like they belong in it. The thing to watch is that not everyone is built to think in \"we,\" and that's not a flaw in them—some people really do work better solo, and not everything needs to be a group project. Your growth edge is letting the lone wolves be lone wolves without taking it personally.",

  "energyPatterns": "What drains you:\n- Group projects where it's secretly a competition and helping each other gets punished\n- Always being the one who plans it, with zero thanks and nobody planning back\n- Friend groups where you give and give and somehow never get held yourself\n- People who roll their eyes at the idea that a group could actually do something good\n- Long stretches with no one to build anything with, just you alone\n- Doing all the invisible coordinating that no one even notices got done\n\nWhat charges you:\n- Watching a group pull off something none of them could've done alone\n- Pulling a crew together that flat-out didn't exist before you\n- Being somewhere your behind-the-scenes work actually gets seen and valued\n- Connecting two people who didn't know they were a perfect match\n- Building toward something that's going to be good for more people than just you\n- The hangout that turns into a real plan because you connected the dots",

  "workEnvironments": "Where you thrive:\n- Places that care about what the team pulls off, not who out-competed who\n- Community work, organizing, anything where building partnerships is the actual job\n- Roles where you set people up to win instead of bossing them around\n- A crew small enough that your coordinating gets noticed and counts\n- Anywhere your job is literally to make a group work better together\n\nWhere you suffocate:\n- Cutthroat spots where it's every person for themselves\n- Places that lean on your coordinating but never acknowledge it exists\n- Working totally alone for long stretches with no one to build with\n- Rigid top-down setups where \"teamwork\" is just a buzzword on the wall\n- Cultures where collaborating is just a ladder for someone's personal climb",

  "topCareers": [
    {
      "title": "Community Org / Events Assistant",
      "description": "You think in \"we\"—you see the group that wants to form before it knows it wants to. Entry-level community organizing or event coordination is that instinct turned into a paycheck: scanning a room for who'd click, turning a bunch of separate people into one effort, building the thing that doesn't exist yet. You're probably already the one who organizes the whole friend group trip, finds everyone's strengths, and somehow makes the chaos into a plan. These roles pay you to be exactly that person, on purpose, full time."
    },
    {
      "title": "Team Lead / Shift Lead (Enablement)",
      "description": "You lead by setting people up, not by bossing them around—your win is the whole crew clicking, not you being the star. A first shift-lead or junior team-lead role rewards exactly that: getting the new person up to speed, smoothing the friction between two coworkers, making the team actually function. You see the potential scattered across people who don't see it in themselves yet, and you pull it together. The behind-the-scenes coordinating that goes unnoticed everywhere else is, here, literally the job you're being paid and promoted for."
    },
    {
      "title": "Onboarding / Community Manager",
      "description": "You walk into any room and instantly clock who could build with whom, and you can make that real instead of just imagining it. Junior community-manager or onboarding roles—running the Discord, welcoming new members, connecting people—pay for exactly that. You're energized by a group winning together in a way that solo grind-it-out jobs never gave you. The \"what could we all do together\" that's always running in your head becomes the actual day-to-day: turning a pile of strangers into a community that holds."
    }
  ],

  "blockIndicators": "Your Parser Profile suggests the following CBI block accessibility pattern:\n\nLikely High-Accessibility Blocks:\n- Social Signal Processing (continuous attention to others' needs and potential contributions)\n- Pattern Recognition (seeing coalition potential and alignment patterns)\n- Sequential Processing (coordinating complex collaborative logistics)\n\nLikely Moderate-Accessibility Blocks:\n- Spatial Relationships (mapping how people and groups relate)\n- Symbolic Manipulation (working with frameworks for collaboration)\n- Generative Creation (imagining collaborative futures)\n\nLikely Lower-Accessibility Blocks:\n- Self-Reference Processing (other-orientation may under-develop self-attention)\n- Perceptual Discrimination (present-moment sensory detail may be less attended than social-future perception)\n\nThis pattern suggests your cognitive architecture is optimized for collective vision and coalition-building, with room to grow in tracking your own needs, wants, and contributions with the same attention you give everyone else's. The most sustainable connectors are the ones who remember to include themselves in the group they're building.\n\nCOLLABORATIVE",

  "strengths": [
    {
      "title": "You See the Team Before It Exists",
      "description": "Where everyone else sees random people or rival groups, you see who could combine into something. You clock the people whose skills, needs, and goals would line up if someone connected them. Spotting that hidden potential before it's a thing is rare, and it's the whole start of anything getting built."
    },
    {
      "title": "You Know Who's Good at What",
      "description": "You naturally track what each person brings—who's reliable, who's creative, who handles the boring stuff, who's secretly great under pressure. So when something needs doing, you already know who to text. It makes you the person who can actually assemble a crew that works instead of one that looks good on paper."
    },
    {
      "title": "You Flex Between Hype and Logistics",
      "description": "You can hold the big inspiring vision and the boring spreadsheet at the same time. One minute you're getting everyone fired up about what it could be, the next you're figuring out who's bringing what and when. That range means you can hold a group together at both ends, not just one."
    },
    {
      "title": "You Make Everyone's Needs Fit",
      "description": "You're tracking multiple people's wants at once and looking for the version where they get met together instead of fighting over scraps. So you design plans that actually work for real humans—not by ignoring that people want different things, but by finding the setup where it all lines up."
    },
    {
      "title": "People Trust You With the Group",
      "description": "Because you're genuinely not in it for yourself, people sense you're not angling for personal credit—and that makes them trust you to run the thing. They'll let you coordinate, mediate, and lead because they can feel you actually want the whole group to win, not just you."
    },
    {
      "title": "You Play the Long Game on Relationships",
      "description": "You'll invest in people and connections that won't pay off for ages. You stay in touch, you keep the group warm through the slow patches, you build alliances that might only matter a year from now. That patience is exactly what anything real—a friendship, a project, a scene—actually needs to survive."
    }
  ],

  "challenges": [
    {
      "title": "You Disappear Into the Group",
      "challenge": "You're so locked onto what everyone else needs and could bring that your own needs go invisible—to them and to you. You'll organize a flawless group thing and somehow not actually be in it as a full person, just the one running it from the side.",
      "remedy": "Put yourself on the list. Whenever you're mapping out who needs what, deliberately add yourself as one of the people whose needs count. Literally ask: \"What do I want out of this? What am I getting?\" Treat yourself as someone in the group, not just the person tracking the group."
    },
    {
      "title": "You Assume Everyone Wants to Team Up",
      "challenge": "You figure other people are into building-together the way you are, and some just aren't. Some want to compete, some want to do their own thing, some will straight-up use a \"group\" for their own gain. Your faith in teamwork can blind you to the person who's about to take advantage of it.",
      "remedy": "Read the room before you go all in. Before you pour energy into pulling a crew together, check whether these people actually want to collaborate—look at what they've done, not just what's possible. Some people are never going to be team players no matter how good you are at it. Clocking that early saves you for the groups that could actually work."
    },
    {
      "title": "You Skip Over How It's Going Right Now",
      "challenge": "You're so focused on the better version that could exist that you miss what's actually happening in the group today—the simmering beef, the person who got steamrolled, the trust that quietly broke. You're imagining the good future while the present is on fire.",
      "remedy": "Check the temperature before you dream. Before you start planning the upgraded version, take an honest read: what's actually working, what's not, where's the tension, who's checked out. Your vision is great—grounding it in what's really going on right now is what makes it achievable instead of just a nice idea."
    },
    {
      "title": "You Get Stuck Waiting for Everyone to Agree",
      "challenge": "Because you want everyone on board, you can freeze the whole thing trying to get one last holdout aligned. The plan stalls because you won't move until literally everybody's in. Sometimes the group has to act before everyone agrees, and you struggle to let that happen.",
      "remedy": "Figure out what level of agreement the moment actually needs. Not every decision needs unanimous buy-in—most just need enough people on board to move. Learn to tell which is which, and let the thing roll forward when you've got enough, instead of holding it hostage waiting for the full set."
    },
    {
      "title": "You Undervalue the Solo Grind",
      "challenge": "You're so wired for group effort that you can dismiss the stuff people have to do alone. But not everything is a team thing—some work needs one person's solo vision, one person's quiet focus, the kind of thing a committee would just ruin.",
      "remedy": "Make room for the lone-wolf move inside your team brain. The best groups protect space for individuals to go off and do the thing only they can do. Sometimes serving the crew means letting someone disappear and work alone for a while. Teamwork isn't the only way people contribute—and that includes you."
    },
    {
      "title": "You Burn Out Coordinating Everything",
      "challenge": "Your reflex to organize means you end up holding every group together—tracking everyone's needs, running every plan, fixing every miscommunication—until you're completely fried and resentful and nobody even noticed you were carrying it.",
      "remedy": "Build groups that don't need you to function. Teach other people to run the chat, plan the thing, smooth the conflict. Set up little systems so it keeps going without you babysitting it. The real win is a group that holds together on its own—if it collapses the second you step back, it was never actually a team yet."
    }
  ]
};
