// COLLABORATIVE Profile
// Parser Profile™ © 2026 Cognition Blocks LLC
// Balanced • Future • Other

export const collaborativeProfile = {
  "name": "COLLABORATIVE",
  "code": "Balanced • Future • Other",
  "tagline": "The one who sees what we could build together",

  "overview": "You think in \"we.\" Not as a pleasantry—as your native frame. When you look at any situation, your mind naturally maps to collective possibility. What could this group accomplish if they worked together? What coalition could form here that hasn't yet? What's the combined potential that's currently fragmented?\n\nYou see the group that wants to form before it knows it wants to form. While others are calculating individual advantage or protecting personal territory, you're scanning for alignment—people whose separate efforts could become shared efforts, whose isolated goals could become collective goals. You perceive coalitions the way some people perceive color: automatically, without trying.\n\nYour thinking moves fluidly between practical and conceptual. When you imagine collaboration, you can hold the inspiring vision and also see the logistics. Who contributes what. How the pieces fit. What makes this partnership actually work. You're not lost in idealistic fantasy about working together—you can get concrete about how togetherness functions.\n\nYour attention orients toward futures. You're not focused on how groups have worked together in the past or even how they're functioning now. You're imagining how they could work together. The unrealized potential in teams, organizations, communities—this is what you perceive. The alliance that could emerge. The collective capacity that's currently scattered.\n\nYour reference point centers on others. You're not primarily tracking your own trajectory through collaborative spaces. You're tracking everyone's. What does each person need? What could each contribute? How could individual needs align with collective goals? You're running these calculations constantly, instinctively, mapping the social landscape for collaborative opportunity.\n\nPeople have called you a team player, a connector, a community builder. These descriptions capture something real but can flatten your architecture into simple agreeableness. You're not just pleasant to work with. You're seeing collaborative possibilities that others miss.",

  "howYouLearn": "Learning lands for you in collaborative contexts. Information that comes through group exploration, shared inquiry, or community engagement sticks better than what you absorb in isolation. The relational dimension of learning isn't peripheral for you—it's central to how you process and retain.\n\nYou need both the concept and the application. You want to understand the theory and see how it works in practice. Learning that offers both—especially learning that shows how knowledge enables better collaboration—engages your architecture most fully.\n\nFuture-orientation shapes your learning motivation. You're drawn to knowledge that serves future collaborative potential. Skills that will help you build better teams. Understanding that will let you design better coalitions. Wisdom that will make you more effective at facilitating collective effort. \"How does this help us work together better?\" is the filter you run learning through.\n\nYou may find that you learn particularly well when you can immediately share what you're learning with others. Teaching, discussing, collaboratively exploring new material—this reinforces your own learning while satisfying your other-orientation. Solitary study may feel incomplete until you've brought it into relationship.\n\nBe aware that your collaborative learning preference might cause you to undervalue what you could learn alone. Some knowledge requires individual wrestling, private reflection, or solo practice that can't be shortcut through group process. Make space for this even though it's not your preferred mode.",

  "howYouCommunicate": "You communicate with natural inclusion. You use \"we\" instinctively, frame situations in terms of collective stakes, and speak in ways that bring others into shared consideration. This inclusive framing isn't technique—it's how you actually think. You genuinely perceive situations through a collaborative lens.\n\nYour adaptability shows in how you communicate. You can handle concrete logistics—who does what, when, how—and you can hold conceptual space for shared vision and group purpose. You translate between people operating at different levels, bridging the practical and the aspirational.\n\nYou're probably skilled at drawing out others' contributions in conversation. Your other-orientation means you're attentive to what people have to offer, and you create conversational space for them to offer it. People may feel seen and valued in conversation with you because you're genuinely interested in what they bring.\n\nIn groups, you naturally facilitate without necessarily claiming the facilitator role. You notice who hasn't spoken. You synthesize different contributions. You name the emerging direction. This can be valuable and also exhausting—be aware of when you're doing collaborative labor that no one asked for or will recognize.\n\nYour communication challenge is advocacy for yourself. You can articulate collective needs, represent group interests, speak on behalf of coalitions. Speaking for yourself—your individual needs, your personal perspective, your distinct position—may feel less natural. Practice using \"I\" with the same fluency you use \"we.\"",

  "phrase": "You don't just work well with others. You see what 'others' could become together. The coalition is always more visible to you than your place in it.",

  "secret": "Sometimes you don't know who you are outside of collaborative contexts.\n\nYour other-orientation runs so deep that when you're alone—truly alone, with no collaboration to facilitate, no collective to serve, no coalition to build—you can feel strangely empty. Who are you when you're not helping groups function? What do you want when you're not tracking what everyone else wants? What's your vision when you're not synthesizing everyone else's visions?\n\nThese questions might haunt you more than you've admitted. Your identity has become so intertwined with your collaborative function that the person underneath the function is unclear—even to you. You know what you do for others, what you enable in groups, what you contribute to collective efforts. You're less certain who you are when no one else is around.\n\nDeeper: sometimes you've wondered if your orientation toward collaboration is actually avoidance of self. It's easier to focus on \"we\" than to clarify \"I.\" It's safer to facilitate others' visions than to articulate your own. Your collaborative gift might partly be a sophisticated way of never having to stand alone, want something for yourself, be a distinct self rather than a connector of selves.\n\nThis doesn't mean your collaborative capacity is false or merely defensive. You genuinely see coalition potential; you genuinely care about collective outcomes; you genuinely find meaning in building things with people. But underneath that genuine orientation may be questions you've avoided: What do you want? Who are you? What would you build if you weren't building for others?\n\nThese aren't questions that need answering today. But they're questions worth sitting with, in the quiet, when no one else is around to orient toward.",

  "whatOthersGetWrong": "They assume your collaborative orientation means you're a pushover. They see your focus on collective outcomes and your attention to others' needs, and they conclude you must not have strong views of your own—that you'll go along with whatever the group decides. They mistake your other-orientation for absence of spine.\n\nWhat they miss is that you often have clear vision for what collaboration could accomplish—you just hold that vision in service of the group rather than imposing it. You can be quite determined about collective direction while remaining flexible about your individual position within it.\n\nThey assume you're nice but not strategic. Your warmth and inclusion register, but they don't see the sophisticated thinking happening underneath—the coalition mapping, the contribution tracking, the strategic design of collaborative structures. You're not just being friendly; you're architecting collective capacity.\n\nSome assume that because you're other-oriented, you must want leadership positions that let you control groups. But control isn't your interest—emergence is. You don't want to direct collaboration; you want to create conditions where collaboration can direct itself. This distinction is lost on people who can only imagine collective work through hierarchical frames.\n\nAnd they assume your future-focus means you're impractical, lost in visions of collaboration that can't actually happen. They don't see how your future-orientation serves your practical work—you're not dreaming of impossible collectives but perceiving achievable coalitions that others have stopped looking for.",

  "hiddenSuperpower": "You can see the group that wants to form before it knows it wants to form.\n\nCoalitions don't spring into existence fully formed. They emerge from scattered individuals who don't yet realize their potential alignment—pursuing separate goals that could be shared goals, holding separate resources that could be combined resources, facing separate challenges that could be collective challenges.\n\nMost people can't see coalitions until they already exist. You see them before they do. You perceive the latent alignment between people who haven't met, the potential partnership between groups that see themselves as separate, the coalition that could form if someone just made the connections visible.\n\nThis perception is your superpower. It lets you catalyze collaborations that wouldn't happen otherwise—not because people didn't want to collaborate, but because they couldn't see who to collaborate with. You can see the network of potential relationship that underlies the apparent isolation of individuals and groups.\n\nWhen you introduce people who should know each other, you're not just being social—you're building infrastructure for collective action that doesn't exist yet. When you point out aligned interests, you're helping coalitions recognize themselves. When you convene conversations between unlikely partners, you're surfacing collaborative potential that would otherwise remain invisible.\n\nThe futures you see—where fragmented efforts become unified movements, where isolated individuals become powerful collectives—aren't fantasies. They're possibilities that exist in the present but require someone like you to make them visible.",

  "blindSpot": "You may not recognize when your collaborative orientation allows others to exploit your labor.\n\nBecause you're genuinely oriented toward collective outcomes, you might absorb more than your share of collaborative work—emotional labor, coordination labor, conflict-resolution labor—without recognizing the imbalance. You're tracking everyone's needs, so you notice when others need support. You're less attentive to your own needs, so you don't notice when you need support and aren't receiving it.\n\nThis can create patterns where you're the person holding collaborations together while others benefit from your effort without reciprocating. They learn that you'll do the coordination, manage the relationships, smooth the conflicts—and they let you, because why wouldn't they?\n\nWatch for: collaborations where you're consistently doing more invisible work than others. Patterns where you're exhausted by collective efforts while others seem refreshed. Relationships where you're always the one initiating, facilitating, or repairing.\n\nAlso watch for: your own collusion in these patterns. Your other-orientation can make you complicit in your own exploitation—you might resist acknowledging imbalance because doing so would require centering your own needs, which feels foreign. It's easier to keep giving than to demand receiving.\n\nYour blind spot isn't your collaborative gift. It's the assumption that collective well-being automatically includes your well-being. Sometimes you must explicitly advocate for yourself within collaborations—not because collaboration is bad, but because your particular role tends toward self-neglect unless you consciously counter it.",

  "frictionPatterns": "You'll clash with people anchored in concrete personal past while you're oriented toward collective futures. They're drawing from individual experience they've earned; you're imagining what groups could accomplish together. Their self-protective expertise meets your collective optimism—friction is almost inevitable.\n\nYou'll also struggle with heavily self-oriented profiles across any temporal dimension. They're centered on their own trajectory; you're centered on everyone's. What you experience as obvious collective benefit may feel to them like dilution of individual focus.\n\nAnd you'll find friction with past-oriented profiles who want to honor what was rather than build what could be. Your future-focus can seem dismissive of history that matters to them; their past-focus can seem like resistance to progress to you.\n\nYour gift in these frictions: Your genuine interest in others' contributions can create connection even across difference.\n\nYour growth edge: Recognizing that self-orientation and past-focus aren't deficits—they're different architectures with their own validity. Not everyone should think in coalitions; not everything should be collaborative.",

  "energyPatterns": "What drains you:\n- Competitive environments where collaboration is punished\n- Being expected to coordinate without recognition or reciprocity\n- Collaborations that exploit your labor without contributing to your well-being\n- Cynicism that dismisses collective possibility\n- Isolation from collaborative contexts for extended periods\n\nWhat charges you:\n- Witnessing collaborations that produce more than individuals could alone\n- Building coalitions that didn't exist before your involvement\n- Environments where your facilitation is recognized and valued\n- Finding alignment between people who didn't realize they were aligned\n- Contributing to futures that will benefit people beyond yourself",

  "workEnvironments": "Where you thrive:\n- Environments that value collective achievement over individual competition\n- Community organizing, partnership development, cooperative enterprises\n- Team leadership focused on enablement rather than control\n- Facilitation roles and any position where building collective capacity is the primary work\n\nWhere you suffocate:\n- Environments that reward individual competition over collective success\n- Cultures that don't recognize coordination labor\n- Isolation from collaborative relationship\n- Hierarchical structures where collaboration is merely instrumental to individual advancement",

  "blockIndicators": "Your Parser Profile suggests the following CBI block accessibility pattern:\n\nLikely High-Accessibility Blocks:\n- Social Signal Processing (continuous attention to others' needs and potential contributions)\n- Pattern Recognition (seeing coalition potential and alignment patterns)\n- Sequential Processing (coordinating complex collaborative logistics)\n\nLikely Moderate-Accessibility Blocks:\n- Spatial Relationships (mapping how people and groups relate)\n- Symbolic Manipulation (working with frameworks for collaboration)\n- Generative Creation (imagining collaborative futures)\n\nLikely Lower-Accessibility Blocks:\n- Self-Reference Processing (other-orientation may under-develop self-attention)\n- Perceptual Discrimination (present-moment sensory detail may be less attended than social-future perception)\n\nThis pattern suggests your cognitive architecture is optimized for collective vision and coalition-building. Your developmental opportunities lie in self-reference—building the capacity to track your own needs, wants, and contributions with the same attention you bring to tracking others'. The most sustainable collaborators are those who know how to include themselves in the collective they're building.\n\nCOLLABORATIVE",

  "strengths": [
    {
      "title": "Coalition Perception",
      "description": "You see potential alliances before they form. Where others see separate individuals or competing groups, you see possible coalitions—combinations of people whose skills, needs, and interests could align toward shared outcomes. This perception of collaborative potential is rare and valuable for any collective undertaking."
    },
    {
      "title": "Contribution Mapping",
      "description": "You naturally track what different people could offer to collective efforts. You perceive individual strengths, resources, and capacities, and you can see how these could combine. This makes you invaluable for assembling teams, designing collaborations, and ensuring that collective efforts actually leverage what participants bring."
    },
    {
      "title": "Flexible Facilitation",
      "description": "Your balanced processing lets you work at multiple levels of collaborative engagement. You can handle concrete logistics—who does what, when, how—and you can hold conceptual space for shared vision and group purpose. This flexibility means you can facilitate collaboration across its full range, from practical coordination to inspirational alignment."
    },
    {
      "title": "Needs Integration",
      "description": "Your other-orientation means you're tracking multiple people's needs simultaneously. Your future-focus means you're looking for how those needs could be met together rather than in competition. This combination lets you design collaborative structures that actually work for participants—not by ignoring differences but by finding configurations that address them."
    },
    {
      "title": "Trust Generation",
      "description": "Because your attention genuinely centers on collective benefit rather than personal advantage, people tend to trust you in collaborative contexts. They sense that you're not positioning for individual gain, which makes you credible as a coordinator, facilitator, or leader of collective efforts."
    },
    {
      "title": "Long-Term Collaboration Investment",
      "description": "Your future-orientation lets you invest in collaborative relationships that won't pay off immediately. You can build coalitions over time, nurture alliances that might matter later, and sustain collaborative effort through periods when outcomes aren't visible. This long-game capacity is essential for any significant collective achievement."
    }
  ],

  "challenges": [
    {
      "title": "Self-Disappearance",
      "challenge": "Your other-orientation can cause you to lose yourself in the collaborative field. You're so focused on what everyone else needs and could contribute that your own needs and contributions become invisible—to others and to yourself. You might facilitate beautiful collaborations that don't actually include you as a full participant.",
      "remedy": "Practice explicit self-inclusion. In any collaborative mapping you do, deliberately include yourself as one of the people whose needs matter and whose contributions count. Ask yourself: \"What do I need from this collaboration? What am I offering?\" Treat yourself as a stakeholder, not just the person tracking stakeholders."
    },
    {
      "title": "Collaboration Assumption",
      "challenge": "You may assume others share your orientation toward collective building when they don't. Not everyone values collaboration; some prefer competition, independence, or hierarchy. Your faith in collaborative potential can blind you to people who will exploit collaborative spaces for individual advantage.",
      "remedy": "Develop discernment about collaborative readiness. Before investing heavily in coalition-building, assess whether potential participants actually want to collaborate. Look for evidence, not just potential. Some people will never be collaborative partners regardless of how skillfully you facilitate—recognizing this saves your energy for coalitions that could actually form."
    },
    {
      "title": "Present-Functionality Neglect",
      "challenge": "Your focus on future collaborative potential can cause you to miss how collaboration is functioning (or not) right now. You might overlook current conflicts, power imbalances, or broken trust while imagining the better collaboration that could emerge.",
      "remedy": "Build in regular assessment of current collaborative reality. Before imagining better futures, take stock of what's actually happening: What's working? What's not? Where is trust strong and where is it broken? Your future-orientation is valuable; grounding it in accurate present perception makes your collaborative vision achievable rather than escapist."
    },
    {
      "title": "Consensus Trap",
      "challenge": "Your commitment to collective outcomes can create over-reliance on consensus. You might stall collaborative efforts while trying to get everyone aligned, unable to move forward while any participant remains uncommitted. Sometimes collaboration requires action without full agreement.",
      "remedy": "Distinguish between alignment that's necessary and alignment that's nice-to-have. Not every collaborative decision requires full consensus; some require only sufficient agreement. Learn to identify which level of alignment the situation actually needs, and be willing to move forward when that threshold is met rather than holding out for unanimity."
    },
    {
      "title": "Undervaluing Individual Contribution",
      "challenge": "Your orientation toward collective outcomes might cause you to undervalue what individuals do alone. Not everything is collaborative; some contributions require solo effort, individual vision, or work that can't be done by committee.",
      "remedy": "Expand your model of collective success to include individual contribution as a component. The best collaborations make space for individual excellence, not just group process. Sometimes serving the collective means protecting space for someone to work alone on something only they can do. Collaboration isn't the only form of valuable contribution."
    },
    {
      "title": "Burnout Through Over-Coordination",
      "challenge": "Your natural inclination to facilitate collaboration can lead you to take on coordination burdens that exhaust you. You might become the person holding every coalition together, tracking everyone's needs, managing every collaborative process—until you're depleted.",
      "remedy": "Build collaborative capacity that doesn't depend on you. Train others to facilitate. Create structures that coordinate without requiring your constant attention. The ultimate collaborative success is a collaboration that sustains itself—if you're the indispensable coordinator, the collaboration isn't truly collective yet."
    }
  ]
};
