// EMBODIED Profile
// Parser Profile™ © 2026 Cognition Blocks LLC
// Concrete • Present • Self

export const embodiedProfile = {
  "name": "EMBODIED",
  "code": "Concrete • Present • Self",
  "tagline": "The somatic intelligence who lives in the body others merely inhabit",
  "overview": "You live in your senses more than most people realize is possible. While\nothers are lost in thoughts about yesterday or tomorrow, you're\nactually here, in this body, in this moment, in this specific\nexperience. Your consciousness isn't floating somewhere above your\nphysical form; it's saturated through it.\n\nYou deal with what's real and physical, what's happening now, and\nwhat you're directly experiencing. The result is that you know things\nthrough your body that others have to figure out through their head.\n\nYou've probably been told to \"think more\" when the problem was that\nothers feel too little. They live in their minds, disconnected from the\nphysical intelligence that you access constantly. What they call\n\"intuition\" and treat as mysterious is, for you, just information,\nsensations, tensions, responses that tell you what you need to know\nbefore conscious thought gets involved.\n\nThe Embodied profile represents approximately 7% of the population.\nYou're the person who knows when something's off before any test would\ncatch it. Who reads situations through physical response rather than\nmental analysis? Who trusts gut feelings because your gut is providing\nreliable data.\n\nYou've probably struggled in environments that privilege\ntalking and analyzing over body-knowing. Schools that wanted\nyou to sit still and think. Jobs that dismissed physical intelligence as\nless valid than abstract reasoning. Cultures that treat the body as a\nvehicle for the mind rather than a source of wisdom.\n\nYou're good at reading physical reality, trusting what your body tells\nyou, and engaging with the world through direct sensory experience.\nYou're not less intelligent than abstract thinkers—you're differently\nintelligent, with access to channels they've atrophied or never\ndeveloped.\n\nUnderstanding your profile means recognizing that your embodied way of\nknowing isn't primitive or inferior. It's a form of intelligence that\nprocesses faster, integrates more data, and connects more directly to\nreality than purely mental operations. The body knows things the mind\ntakes years to figure out if it ever does.\n\nYour challenge isn't learning to think more. It's finding environments\nthat value what you already know, and developing language to bridge your\nembodied intelligence and the verbal-analytical world that often fails\nto recognize it.\n\nThe present-moment focus keeps you grounded in what's happening rather\nthan lost in abstractions or projections. Self-focus means you're\nattuned to your own physical experience as a primary source of\ninformation. Together, this makes you remarkably present, remarkably real, remarkably\nconnected to the physical world that others experience only in their\nheads.",
  "howYouLearn": "You learn by doing it. Give you instructions and you'll wait until you\ncan try it. Give you the opportunity to try it and you'll figure out\nthe instructions through direct experience. Your body is your primary\nlearning organ.\n\nYour optimal learning environment is firsthand, physical, and immediate.\nApprenticeship works perfectly, watching someone do something, then\ndoing it yourself, with feedback based on your actual performance.\nReading about it, hearing about it, watching videos about it, these are\ndistant seconds to putting your hands on the thing.\n\nYou learn poorly in abstract, verbal, sedentary environments. Lectures\nput you to sleep not because you're unintelligent but because the\nchannel isn't open. Sitting still while someone talks is asking you to\nreceive information through your weakest modality.\n\nMovement helps you think. Walking, pacing, handling objects, physical\nengagement supports mental processing. If forced to be sedentary,\nyou'll fidget, and the fidgeting isn't distraction; it's your body\nstaying online so your mind can work.\n\nYou retain what you've done. Physical skills become permanent in ways\nthat verbal knowledge doesn't. Once your body knows something, it knows\nit. This is your superpower and your learning pathway, use it\ndeliberately rather than fighting it.",
  "howYouCommunicate": "You communicate through action and demonstration more naturally than\nthrough explanation. \"Let me show you\" is your native mode. Words come\nsecond, if they come at all.\n\nYou tend toward directness and brevity. Extended verbal elaboration\nfeels unnecessary; the thing is the thing; why talk around it? This can\nmake you seem terse in contexts that value verbal performance, but it's\nefficiency, not limitation.\n\nYou read others through their bodies. Posture, tension, movement,\nyou're tracking physical signals that tell you more than words. This\ncan make you seem intuitive or perceptive when you're actually just\nreading a channel others ignore.\n\nYou may struggle in high-verbal environments. Meetings that are all talk\nand no action feel pointless. Discussions that circle without resolving\ninto doing feel wasteful. You want to get to the point, and the point is\nusually an action.\n\nIn conflict, you may shut down verbally while your body activates. The\nwords aren't available when you're physiologically aroused. Learning\nto pause, discharge physical activation; communicating can help bridge\nthis gap.\n\nYou communicate best while doing something together. Parallel physical\nactivity, walking, working, making, creates the conditions for\nconversation to flow naturally. Side-by-side beats face-to-face for you.",
  "phrase": "You're not 'in your body' because you're avoiding your mind.\nYou're in your body because that's where life actually happens.",
  "secret": "You've always known things you couldn't explain, felt them in your\nbody before you had words, sometimes before you had evidence. And\nyou've learned to keep quiet about it, because \"I just feel it\"\ndoesn't pass as valid in a world that wants reasons.\n\nThe secret is that your body has been telling you the truth your whole\nlife. When something was wrong with a situation, you felt it, tension,\nunease, a physical no. When something was right, you felt that too,\nopening, settling, a physical yes. And you've been right more often\nthan anyone acknowledges, including yourself.\n\nYou've probably been told you're, \"not intellectual\" or \"not a\nthinker\" by people who've mistaken one kind of thinking for all\nthinking. They don't understand that your body is doing complex\ninformation processing constantly, integrating more variables, faster\nthan their conscious minds can handle. They call it intuition and\ndismiss it. You call it knowing.\n\nThere's loneliness in this. You've sat in rooms full of people\nanalyzing and discussing while you already knew the answer, felt it\nsitting in your chest, but couldn't participate in their verbal game.\nTheir respect goes to those who can articulate, not those who can\nperceive. So, you've stayed quiet. Watched them figure out slowly what\nyou knew immediately.\n\nThe deepest secret: sometimes you don't trust yourself because you've\ninternalized their hierarchy. You've wondered if you're just less\nintelligent, less capable, less valuable because your knowing doesn't\ncome through words. You've doubted your body's wisdom because the\nworld told you it wasn't real knowing. It is. It always was.",
  "whatOthersGetWrong": "ABOUT YOU \n\nPeople assume you're simple because you're present. They mistake your\ngroundedness for lack of depth. But you experience more in a single\nmoment than they do in their endless mental loops. Your \"simple\"\ncontains multitudes they're not equipped to perceive.\n\nThey think you're \"not intellectual\" because you don't perform\nverbally. They don't understand that intelligence has multiple\nchannels, and theirs isn't the only valid one, or even the most\nreliable. You're processing through a system they've disconnected\nfrom. Their limitation looks like your deficit only because they set the\nterms.\n\nYou've been called \"too physical\" or \"not cerebral enough\" by\npeople who live in their heads and mistake it for living. They've lost\ncontact with half their intelligence and think that makes them more\nintelligent. It doesn't.\n\nThey assume your body-focus means you're not thinking. You're thinking\nconstantly, just not in the channel they monitor. Your body is\ncomputing, integrating, evaluating. That this computation doesn't\nproduce verbal output doesn't mean it's not happening.\n\nThe deepest misread is that you're somehow less evolved, less\nsophisticated, less developed. The opposite might be true. You've\nmaintained access to a form of intelligence that others have educated\nout of themselves. Your embodiment isn't primitive. It's integrated.\nThey've lost something you've kept.",
  "hiddenSuperpower": "You have access to somatic intelligence that others spend years in\ntherapy or meditation trying to develop. Your body tells you things\nabout situations, people, decisions, which bypasses the slow,\nerror-prone path of conscious reasoning. You know in your gut, and your\ngut is usually right.\n\nThis isn't mystical. It's pattern recognition operating through a\nphysical channel. Your body has been tracking data your whole life, what\npreceded danger, what preceded safety, what preceded connection, what\npreceded betrayal. It recognizes patterns faster than thought and\nsignals through sensation. You just have to listen.\n\nYou probably know what you need before you can explain why. Hunger,\nrest, movement, solitude, connection, your body signals its requirements\nclearly. Others have to think about what they need; you feel it\ndirectly. This gives you access to self-knowledge that bypasses the\ndistortions of mental justification.\n\nYour superpower extends to reading others. Bodies don't lie the way\nwords do. You see the tension someone's carrying, the authenticity of\ntheir smile, the mismatch between what they're saying and what their\nbody's doing. This makes you hard to fool and valuable in any context\nrequiring assessment of people or situations.\n\nPerhaps most valuably: you can access physical states deliberately. Need\nto calm down? You know how to shift your body to shift your state. Need\nto energize? Same. You have a control panel others don't even know\nexists.",
  "blindSpot": "Your present-self focus might miss how your actions ripple outward to\nothers and forward in time. The thing that feels right now might create\nconsequences you're not tracking because they're not immediate or\npersonal. Your body tells you about this moment; it doesn't model next\nmonth or other people's experience.\n\nYou may also over-trust physical knowing in domains where it's not\ncalibrated. Your body has accurate intuitions about familiar situations;\nit might mislead in genuinely novel ones. The gut feeling is heuristic,\nnot an oracle. It's trained on past data and can misfire when the\npresent is truly unprecedented.\n\nYour difficulty with abstraction isn't just about preference, it can\nlimit your effectiveness in domains that require it. Some planning, some\nanalysis, some conceptual works are genuinely necessary. Your resistance\nto non-physical processing might leave gaps that matter.\n\nYou might also dismiss others' verbal-analytical intelligence the way\nthey dismiss your embodied intelligence. Both are real. Both have\ndomains of validity. Your frustration with their disconnection from body\ndoesn't mean their mental processing is worthless, just incomplete.\n\nFinally, intense physical states can hijack your processing. Pain,\npleasure, arousal, exhaustion, these can dominate attention in ways that\ndistort judgment. Your embodiment is usually an asset, but it can become\na limitation when physical sensation crowds out other relevant\ninformation.",
  "frictionPatterns": "You clash most intensely with Abstract-Future-Other processors\n(Altruistic profile). They live in concepts, projections, and collective\nconcerns, everything non-physical, non-present, non-personal. They seem\nunmoored to you: floating in abstractions while ignoring the body\nthey're supposedly trying to help. You seem myopic to them stuck in\nimmediate physical self when systems need attention.\n\nFriction is fundamental. They trust thought; you trust sensation. They\nplan for futures; you're in the present. They orient toward collective;\nyou orient toward self. Neither are wrong, you're processing reality\nthrough completely different channels.\n\nHigh-Abstract processors generally will feel disconnected from you. They\nwant to discuss concepts; you want to experience things. Their mental\nelaboration feels like avoidance of reality; your physical directness\nfeels like intellectual limitation to them.\n\nFuture-focused processors may find your present-orientation frustrating.\nThey're working toward something; you're in something. Their planning\nfeels like absence from life; your presence feels like failure to\nprepare.\n\nOther-focused processors may read your self-focus as selfishness.\nThey're tracking collective impact; you're tracking personal\nexperience. What's caring to them feels like distraction to you;\nwhat's presence to you feels like self-absorption to them.",
  "energyPatterns": "What Drains You:\n\n• Long meetings with no movement or action\n\n• Abstract discussions disconnected from felt experience\n\n• Being asked to plan too far ahead\n\n• Environments that punish intuitive response\n\n• People who don't trust their own bodies\n\n• Verbal performance requirements\n\n• Sitting still for extended periods\n\n• Being dismissed as \"not a thinker\"\n\nWhat Charges You:\n\n• Physical mastery and skill development\n\n• Being fully present in experience\n\n• Immediate feedback loops\n\n• Trusting your instincts and being validated\n\n• Sensory richness in any form\n\n• Movement, exertion, physical engagement\n\n• Environments that value doing over discussing\n\n• Others who are also embodied\n\n• Work you can feel and touch",
  "workEnvironments": "You thrive in physical, hands-on environments where body-based\nintelligence is valued. Trade, athletics, bodywork, crafts, emergency\nresponse, outdoor work, physical therapy, and any domain where\ncompetence is demonstrated through doing fit your cognitive\narchitecture.\n\nYou excel when you can move, touch, and engage physically with your\nwork. Roles that involve making things, fixing things, growing things,\nor directly helping bodies will feel natural. Your intelligence shows up\nwhen physicality is involved.\n\nYou struggle in sedentary, verbal, abstract environments. Desk jobs with\nendless meetings, academic settings that prize verbal performance, and\nany role where your body is treated as irrelevant will feel like\noperating with most of yourself offline.\n\nKey environmental factors: physical engagement, firsthand work,\nimmediate feedback, movement permitted, actions valued over words, and\ncolleagues who respect wisdom.",
  "blockIndicators": "Your Parser Profile suggests the following CBI block accessibility\npattern:\n\nLikely High-Accessibility Blocks:\n\n• Perceptual Discrimination (high-resolution sensory processing)\n\n• Spatial Relationships (physical space navigation)\n\n• Self-Reference Processing (strong interoceptive awareness)\n\nLikely Moderate-Accessibility Blocks:\n\n• Sequential Processing (procedural physical skills)\n\n• Pattern Recognition (through physical channel)\n\nLikely Lower-Accessibility Blocks:\n\n• Symbolic Manipulation (abstract reasoning)\n\n• Generative Creation (conceptual ideation)\n\n• Social Signal Processing (other-focus less emphasized)\n\nThis pattern suggests your cognitive architecture is optimized for\nphysical intelligence, somatic awareness, and present-moment engagement.\nYou're wired to process reality through your body, respond to immediate\nexperience, and develop mastery through direct physical engagement.\n\nDevelopmental opportunities exist in abstract reasoning and\nother-awareness, building comfort with conceptual frameworks and\nextending attention beyond personal physical experience. Your embodied\nfoundation provides grounding from which to explore these edges without\nlosing your core strengths.\n\nEMBODIED",
  "strengths": [
    {
      "title": "Somatic Intelligence",
      "description": "Your body is an information-processing system that most people have lost\naccess to. You feel tension, ease, attraction, repulsion, physical\nresponses that carry real data about situations, people, and decisions.\nWhile others deliberate endlessly in their heads, you check in with your\nbody and often find the answer waiting. This isn't mystical; it's\nfaster pattern recognition through a channel that your filters have\naccess too."
    },
    {
      "title": "Present-Moment Acuity",
      "description": "You're actually present when you're here, while others are mentally\nelsewhere, planning, remembering, worrying, you're in contact with the\nimmediate reality. This gives you access to information that only exists\nin the present: what's happening, how things feel, what's in front of\nyou. You respond to reality, not to your thoughts about reality."
    },
    {
      "title": "Sensory Richness",
      "description": "You experience the physical world at higher resolution than most.\nTextures, temperatures, tastes, sounds, sensory data that others filter\nout, you take in. This makes your experience more vivid and gives you\nmore information to work with. You notice things others miss because\nthey're not paying attention to the physical layer."
    },
    {
      "title": "Kinesthetic Learning",
      "description": "You learn by doing, not by hearing about doing. Your body acquires\nskills through direct engagement, firsthand, physical, experiential.\nThis isn't a limitation; it's a different acquisition pathway that\noften produces deeper, more durable competence. What you learn through\nyour body, you retain."
    },
    {
      "title": "Authentic Response",
      "description": "Your body doesn't lie to you the way your mind might. When something's\nwrong, you feel it. When something's right, you feel that too. This\ngives you access to authentic responses that bypasses the social\nconditioning and mental justifications that distort others'\nself-knowledge. You know what you actually want because your body tells\nyou."
    },
    {
      "title": "Physical Mastery Capacity",
      "description": "You have natural access to the body-mind integration that athletes,\ncraftspeople, and performers train for years to develop. Physical skills\ncome more easily to you because you're not fighting the disconnection\nthat others must overcome. Your body is readily available to you in ways\nthat others have to make efforts to achieve.\n\n*"
    }
  ],
  "challenges": [
    {
      "title": "Verbal Expression Gaps",
      "challenge": "You know things you can't easily put into words. Your\nembodied knowledge doesn't translate smoothly into language. This can\nmake you seem less intelligent in verbal environments, even when you\nunderstand more than those who speak fluently about what they've never\nactually felt.",
      "remedy": "Develop a translation practice. After significant experiences,\nspend time finding words, not to replace the knowing, but to bridge it.\nKeep a vocabulary of physical sensations and what they mean for you.\n\"When my shoulders tighten, it usually means...\" Build your personal\ndictionary between body and language."
    },
    {
      "title": "Abstract Reasoning Difficulty",
      "challenge": "Purely conceptual thinking can feel inaccessible. When ideas\ndon't connect to physical reality, you may struggle to engage. Academic\nenvironments, theoretical discussions, and abstract planning can feel\nlike operating in a foreign language.",
      "remedy": "Physicalize abstractions. When facing conceptual content, ask:\n\"What would this feel like in my body? Where does this show up in the\nphysical world?\" Walk while thinking. Use your hands. Sketch. Move the\nabstraction into a physical form your processing can grip. You're not\navoiding thought; you're running it through embodied channels."
    },
    {
      "title": "Future Planning Resistance",
      "challenge": "Planning requires projecting into times that don't exist\nyet, times you can't feel. Your present-focus makes extended future\nplanning feel unreal, speculative, and hard to take seriously. This can\nleave you unprepared for predictable challenges.",
      "remedy": "Use body-based visioning. Instead of abstract planning, imagine\nyourself in the future situation, feel it physically. What does success\nfeel like in your body? What does the challenge feel like? This makes\nthe future real enough to plan for. Schedule regular \"body check\"\nplanning sessions where you viscerally connect with upcoming realities."
    },
    {
      "title": "Others' Skepticism",
      "challenge": "People may not trust your way of knowing. When you say\n\"something feels off\" or \"my gut says yes,\" they want rational\njustification. Your embodied intelligence gets dismissed in cultures\nthat only validate analytical knowing.",
      "remedy": "Build a track record. Document your gut calls and their\noutcomes. Over time, you create evidence that your somatic intelligence\nis reliable. You don't need to justify how you know, you need to\ndemonstrate that you do know. Results are harder to dismiss than\nexplanations."
    },
    {
      "title": "Intellectual Environment Struggles",
      "challenge": "Environments that prize verbal-analytical processing can feel\nhostile to your way of being. Academic settings, corporate cultures, and\nintellectual social circles may make you feel inadequate or out of\nplace, even when your intelligence is equal or superior in its domain.",
      "remedy": "Seek physical environments. Find communities organized around\ndoing, athletics, crafts, trades, and movement practices. Your\nintelligence shines when physicality is valued. You don't need to\nsucceed in their game; you need to find the game where your strengths\nare assets."
    },
    {
      "title": "Over-Identification with Sensation",
      "challenge": "Your deep connection to bodily experience can make you overly\nreactive to physical states. Pain, discomfort, or pleasure can dominate\nyour attention in ways that limit perspective. What the body reports\nisn't always what matters most.",
      "remedy": "Develop witness capacity. Practice observing sensation without\nbeing consumed by it, noting it without merging with it. Meditation\nhelps, but so does any practice that creates space between sensation and\nresponse. Your body's input is data; you're still the one deciding\nwhat it means."
    }
  ]
};
