// EMPATHETIC Profile — Young Adult (18–29)
// Parser Profile™ © 2026 Cognition Blocks LLC

export const empatheticyaProfile = {
  "name": "EMPATHETIC",
  "tagline": "The one who feels what everyone else is hiding",

  "overview": "You walk into a room and you already know. Before anyone's said a word, you've clocked who's having a bad day, who's pretending to be fine, who two people are quietly not okay with each other, where the weird tension is coming from. It's not you imagining things. You're picking up real stuff that everyone else just walks right past.\n\nYour read on people stays accurate because you're tracking what's happening right now, not the old version. You're not stuck on how your friend used to be or worried about who they'll become—you feel who they actually are in this exact moment. That's why you catch the shift the second their mood changes, even when their face is still doing the smile.\n\nYou can flex between getting practical and seeing the big picture. Friend needs you to actually help them fix something? You get concrete. Friend just needs someone to get why the whole situation feels impossible? You can zoom out to that too. You meet people wherever they are instead of forcing one mode.\n\nYou've been called \"sensitive\" your whole life like it's just a personality quirk and not an actual skill. People tell you that you \"care too much,\" like there's a dial you could just turn down. What they don't get is that you didn't choose to feel all this. It's not a choice you make. It's the instrument you got handed.",

  "howYouLearn": "You learn it better when there's a human in it. The professor you actually like, the study buddy whose stress you can feel, the group where you genuinely belong—that's where it sticks. Cold, faceless, sit-alone-and-grind learning slides right off you. The connection isn't a bonus; it's kind of the whole delivery system.\n\nYou want the concrete example and the bigger meaning. Pure theory with nothing to hook it to feels dead, and pure here's-the-steps with no understanding feels like a robot wrote it. Give you both and you're in.\n\nWhat's happening now lands way harder than someday. \"This'll matter for your career eventually\" does nothing for you. \"This changes how you can actually show up for people\" lights you up immediately.\n\nYou also half-learn the material by feeling how everyone around you is taking it. In a discussion you're not just tracking the ideas—you're tracking who's lost, who's bored, who's secretly really into it. The room's emotional weather is part of how you absorb anything.\n\nThe trap: you'll quietly put everyone else's learning ahead of your own. You'll spend the whole study session making sure your friend gets it and walk out not having studied. Keep a little attention on yourself as the one who also needs to actually learn the thing.",

  "howYouCommunicate": "You're reading how it's landing while you're still talking. You adjust mid-sentence based on the face in front of you—you catch the flicker of confusion before they admit it, feel the second you've hit something tender, sense when it's getting through and when it isn't. It's automatic.\n\nYou can talk in whatever mode the other person needs. Some friends need you to get real and practical—give them the actual steps. Some just need you to get the whole impossible weight of it—you can go there. You shift to fit them, not the other way around.\n\nYou're probably way better at listening than talking. Not because you've got nothing to say—because taking someone in comes more naturally than putting yourself out. You've been told you're a \"good listener\" so many times you've half-built your identity on it. People come to you to be heard, and you let them.\n\nIn group chats and group hangs you're tracking the emotional undercurrent as much as the actual words. You know when someone got talked over and is now quietly hurt. You know when the \"yeah totally, sounds good\" doesn't match how the room actually feels. You feel the gap between what people are saying and what's really going on.\n\nThe hard part for you is saying your own thing—especially when it might make someone uncomfortable. Speaking up for yourself goes against the whole grain of how you're built. You'll absorb a lot before you'll create a little tension. Learning to say the uncomfortable true thing is the work.",

  "phrase": "You don't just notice what people feel. You feel it with them. That's not a choice you're making—it's the instrument you were handed.",

  "secret": "Sometimes you low-key resent the exact thing everyone praises you for.\n\nThey call you caring, empathetic, sensitive, like these are sweet little gifts. They don't get that you can't switch it off. That a crowded party means absorbing forty people's emotional states whether you want to or not. That watching a friend struggle means feeling their struggle in your own body, not just seeing it. That being \"so good with people\" means you're doing exhausting work all the time that nobody even sees you doing.\n\nYou've genuinely wondered what it'd be like to just be oblivious. To walk past someone's pain and not register it. To have a normal conversation without your whole system scanning their insides. To just… not pick up on it for once.\n\nThe darker one: sometimes you've used it to hurt people, because you knew exactly how. Your read on people isn't just sweet—it's information. You know precisely where someone's tender, what would gut them, which sentence would cut the deepest. You've mostly chosen not to use that as a weapon. But you've been tempted, and that scares you because it doesn't match the soft image everyone has of you.\n\nHere's the thing: your sensitivity isn't good or bad on its own. It just shows you where people are vulnerable. What you do with that is a separate choice you get to make. You're not some saint. You're a person who happens to have unusual access to what's going on inside everyone else.",

  "whatOthersGetWrong": "They assume your empathy is bottomless. Because you can take in so much, they figure there's no limit—that you can keep receiving, keep holding space, keep absorbing forever without ever hitting full. They don't get that all this sensitivity has a cost, and that some days you're maxed out and have nothing left to give.\n\nThey assume that since you read everyone else so well, you must have yourself figured out too. The outward radar is obvious; the fact that you barely check in on your own insides is invisible to them.\n\nSome think you're fragile because you're sensitive. They mix up \"feels things deeply\" with \"can't handle things,\" like feeling a lot means you're weak. It's not weakness—it's perception. You can feel everything in the room and still be the steadiest person standing in it.\n\nOthers assume you want to be needed, like you're collecting people to feel important. Usually that's them projecting their own stuff onto you. You're not running a strategy—this is just how your attention works. You'd feel it whether or not it got you anything.\n\nAnd some think your empathy means you agree with them. Just because you can fully understand why someone did what they did doesn't mean you think it was okay. Getting it isn't the same as co-signing it.",

  "hiddenSuperpower": "You can stay with someone in the worst moment when everyone else has bailed.\n\nThere are places in life—real grief, deep shame, panic, the bottom—where most people physically cannot stay present. Their own discomfort makes them flee, or try to fix it fast, or go \"hey, it's not that bad.\" They leave the hurting person alone right when it's worst, because being there is unbearable for them.\n\nYou can stay.\n\nNot because it doesn't get to you—it gets to you completely. But your capacity to take someone's pain in and just hold it is bigger than most people's. You can sit with a friend in the dark without rushing to flip the lights on. You can witness someone falling apart without needing to immediately fix it. You can let the full weight of what they're going through just exist in the room without flinching away from it.\n\nThat's rarer than almost any skill there is. In a world that runs from pain, the fact that you stay is genuinely a big deal. People remember forever who didn't leave when everyone else did. A lot of the time, that's been you.",

  "blindSpot": "You might trust your read on people more than you should.\n\nYour radar is real—you genuinely pick up stuff other people miss. But picking up a signal isn't the same as understanding it perfectly. You're reading cues, making guesses, building a model of what's going on inside someone. Usually you're more accurate than most. But \"usually\" isn't \"always,\" and sometimes you're just wrong.\n\nSometimes you project. You feel your own thing and read it onto them. Sometimes your take on a person is shaped by your history with them rather than what's actually happening today. The story in your head gets mistaken for the facts.\n\nBecause your reads have been right so often, you may have never built the habit of just… checking. You act on the feeling without asking. Sometimes the fix is literally one question: \"hey, are you actually okay or am I making that up?\"\n\nAlso watch for when your \"empathy\" is actually just your anxiety. Sometimes what feels like sensing someone else's distress is really your own distress, leaking outward and landing on the nearest person. Learning to tell the difference between \"I'm picking up on them\" and \"I'm spiraling and blaming the room\" is a lifelong fine-tune of the gift.",

  "frictionPatterns": "You grind against the friend who's locked onto their own goals and just plows forward, not noticing anyone's feelings on the way. To you they seem kind of cold, almost callous. To them, your radar for how everyone's doing looks like you have no direction of your own. You're both kind of right and kind of missing each other.\n\nYou also clash with the very self-focused people who find your attentiveness too much—even invasive. What feels like care and connection to you can feel like you're getting in their space to them. You meant it as closeness; they experienced it as a spotlight they didn't ask for.\n\nAnd you butt heads with the future-and-plans people who want to skip past how everyone's actually feeling right now and get to the strategy. They think you're stuck in the current emotional mess; you think they're dodging it entirely. Neither of you is wrong, exactly—you're just pointed at different things.\n\nYour gift in all of it: even when you're clashing with someone, you can still feel where they're coming from. You get the person you're fighting with. Use that—it's the thing that lets you find your way back to connection when other people would just dig in.",

  "energyPatterns": "What drains you:\n- Places where feelings get shut down or treated as a weakness\n- Being everyone's free therapist and never getting any of it back\n- Crowded, loud, chaotic spaces with way too much emotional input at once\n- Being around someone who constantly waves off what you can clearly feel\n- Watching tension build that you can feel but aren't allowed to name\n- Holding everyone together at a party until you've got nothing left\n\nWhat charges you:\n- A real conversation where you both actually feel understood\n- People who treat reading emotions as an actual skill, not a quirk\n- A friendship that goes both ways—you witness them, they witness you\n- Using your radar to actually help someone, and watching it land\n- Quiet time alone to dump out all the emotional stuff you absorbed\n- One person who just gets you without you having to explain it",

  "workEnvironments": "Where you thrive:\n- Places that treat reading people as the real intelligence it is\n- Work where understanding humans is the actual point, not a soft add-on\n- Helping roles—support, care, coaching, teaching, anything people-facing\n- Spaces where responding to how someone's actually doing is the main skill\n- Teams that give back as much witnessing as you put in\n\nWhere you suffocate:\n- Places that treat people like numbers or resources to move around\n- Cultures where bringing up feelings gets you called unprofessional\n- Being told to ignore what you obviously sense for the sake of speed\n- Cold environments where only cold logic counts and the human stuff gets mocked\n- Roles with so much people-contact you never get to recharge alone",

  "topCareers": [
    {
      "title": "Peer Support / Crisis Line / Care Work",
      "description": "You live in other people's experience—you clock who's struggling and what's unspoken the second you walk in, not on purpose, just because that's where your attention goes. Peer support, a crisis line, or care work is that exact thing turned into a job: taking in what someone can't say and holding it without flinching or fleeing. You flex between practical help and just being with them. The emotional stuff other places call \"unprofessional\" is, in this work, the entire point of you being there."
    },
    {
      "title": "Coaching / HR / People Coordinator",
      "description": "You feel what people can't put into words, and you can name it gently enough that they don't get defensive. An entry-level people role—HR coordinator, junior recruiter, team coordinator—runs on that: sensing the human under the job title, the friction between two coworkers, what's actually driving someone's behavior. You treat emotional intelligence as real intelligence, because for you it always was. The thing efficiency-obsessed places asked you to switch off is exactly what makes people feel safe enough to be honest with you."
    },
    {
      "title": "Teaching Assistant / Youth & Community Work",
      "description": "When a kid or a group is talking past each other, you feel all sides at once and can hold them at the same time. Assisting in a classroom, mentoring younger people, or community work depends on exactly that—catching someone's unspoken fear or frustration and responding to the actual person, not just the surface problem. You can't reduce people to a roster or a stat, and that's the gift. The reading-and-responding that came so naturally you assumed everyone did it becomes the whole foundation of this work."
    }
  ],

  "blockIndicators": "Your Parser Profile suggests the following CBI block accessibility pattern:\n\nLikely High-Accessibility Blocks:\n- Social Signal Processing (continuous attunement to others)\n- Perceptual Discrimination (present-focus enables fine-grained social perception)\n- Pattern Recognition (reading emotional and relational patterns)\n\nLikely Moderate-Accessibility Blocks:\n- Sequential Processing (accessible when needed)\n- Symbolic Manipulation (available but not foregrounded)\n\nLikely Lower-Accessibility Blocks:\n- Self-Reference Processing (other-orientation may under-develop this)\n- Generative Creation (present-and-other focus may limit speculative self-expression)\n\nThis pattern suggests your cognitive architecture is optimized for understanding people and responding to what they actually feel, with room to grow in turning that same attention back onto yourself—your own needs, your own limits, your own inner weather.\n\nEMPATHETIC",

  "strengths": [
    {
      "title": "You Catch It in Real Time",
      "description": "You read someone's mood as it's happening, not three hours later. While everyone else realizes after the fact that your friend was upset, you knew in the first thirty seconds. That head start means you can actually respond to what someone needs right when they need it, before they even have to ask."
    },
    {
      "title": "You Hear the Unsaid Thing",
      "description": "You pick up what nobody's actually saying—the real meaning under the words, the feeling behind the joke, the thing they want but won't ask for. People can say \"I'm fine\" and you hear the whole truth underneath it. That's why people feel weirdly understood around you even when they didn't explain anything."
    },
    {
      "title": "You Meet People in Their Mode",
      "description": "You can flex to whatever someone needs in the moment. One friend wants you to actually help them fix the thing—you get concrete. Another just needs someone to get why it all feels impossible—you go there. You match people not just emotionally but in how their brain works, which makes you easy to open up to."
    },
    {
      "title": "Your Read Stays Current",
      "description": "Your empathy locks onto who someone actually is right now, not the old version of them or some version you're scared they'll become. So your read is trustworthy—you respond to the real present person. People can feel that you're seeing them as they are today, not as a story you already wrote about them."
    },
    {
      "title": "You Read the Whole Room",
      "description": "It's not just individuals—you feel the mood of a whole group or space. You know when a friend group is actually tight versus just performing it, when a party's secretly tense under the vibe, when the energy in a room just shifted and nobody's said why. You feel the climate, not just the people."
    },
    {
      "title": "People Trust You Fast",
      "description": "Folks open up to you quicker than they do with most people because they can feel you're actually receiving them. There's a quality of presence you bring that people recognize and relax into. You make people feel safe simply because you're genuinely, fully paying attention—and that's rarer than it sounds."
    }
  ],

  "challenges": [
    {
      "title": "Emotional Overload",
      "challenge": "You're constantly soaking up everyone's emotions around you. In a packed party, a chaotic group house, a tense family dinner, it floods in faster than you can process it. By the end you're fried and don't even fully know why—it's just that you absorbed forty people's stuff and never put it down.",
      "remedy": "Build in regular ways to discharge it—not just recovery after you're already wrecked, but release before. A walk, the gym, time outside, anything solo with no human emotional field to read. Drain the tank on purpose before it overflows, instead of waiting until you're underwater."
    },
    {
      "title": "Forgetting Yourself",
      "challenge": "You're so tuned to everyone else that your own needs, feelings, and limits turn into background static. You'll spend a whole night taking care of everyone and realize on the drive home you have no idea how you're actually doing or what you even wanted.",
      "remedy": "Schedule check-ins with yourself like they're non-negotiable. Set a recurring moment to literally ask: \"What am I feeling? What do I need right now?\" Reading others is automatic for you. Reading yourself takes you actually choosing to point the radar inward."
    },
    {
      "title": "Whose Feeling Is This",
      "challenge": "You're so permeable that the line between their feelings and yours blurs. You pick up emotions that aren't even yours, take on guilt for stuff you didn't cause, feel like you have to fix someone's pain just because you can feel it sitting there.",
      "remedy": "Practice this line in your head: \"I can feel this without carrying it.\" Being able to sense someone's pain doesn't mean you signed up to fix it or haul it around. Witnessing it is already a complete and real thing to do. You can put it down and still have been there for them."
    },
    {
      "title": "Dodging Every Conflict",
      "challenge": "Because tension physically hurts for you to be near, you'll avoid necessary conflict just to stop feeling it. You bite your tongue, skip the hard conversation, eat unfair treatment to keep things smooth—and the problem just quietly rots underneath.",
      "remedy": "Reframe conflict as care said out loud. Avoiding it usually just lets things fester worse. Your empathy is actually your best tool for hard conversations—it can guide you to have them with real gentleness and presence, instead of being the reason you keep running from them."
    },
    {
      "title": "Who Are You Without Them",
      "challenge": "With your attention always pointed at everyone else, you can lose track of who you are apart from your relationships. Your whole identity gets built around who you are to people—the listener, the supportive one—instead of just who you are.",
      "remedy": "Pick up something that's only about you—a creative thing, a sport, a class you take purely because you want to. Build an actual relationship with yourself that exists when no one else is in the room. You're allowed to be a whole person outside of who you are for other people."
    },
    {
      "title": "Getting Used",
      "challenge": "Your obvious empathy attracts people who want to be endlessly listened to and give nothing back. You become their full-time emotional support while they barely register that you have an inner life at all. You leave every hangout drained and somehow it's never your turn.",
      "remedy": "Track whether it goes both ways, on purpose. Your relationships should have you both giving and receiving real attention. When one keeps running one-direction, name it out loud. Your empathy is worth a lot—it shouldn't get poured into people who only ever take."
    }
  ]
};
