// EQUANIMOUS Profile — Young Adult (18–29)
// Parser Profile™ © 2026 Cognition Blocks LLC

export const equanimousyaProfile = {
  "name": "EQUANIMOUS",
  "tagline": "The one who stays steady when everyone else is losing it",

  "overview": "You sit in the middle without trying. While everyone around you is getting yanked to extremes—super hyped or super doomed, all in on the past or obsessed with the future, totally me-first or totally everyone-else—you just settle at center. Not because you're forcing yourself to be chill. It's actually how you're built.\n\nThis isn't being wishy-washy or having no personality. It's real balance. You can go to any extreme when you need to—get specific, get philosophical, pull from how things went before, plan ahead, focus on yourself, focus on others—you just don't live at any of those edges. Your default, the place you naturally rest, is the middle of all of it.\n\nPeople feel calmer around you and can't always say why. You're not pushing an agenda, not trying to drag the conversation toward your side, not making everything about your thing. You're just there, steady, present, easy to be around. In a group full of intensity, you're the one whose heart rate doesn't spike.\n\nIt can make you hard to read, though. The friends with strong opinions broadcast exactly what they want every five seconds. You don't send those signals. What you do depends way more on the situation than on some fixed preference—which makes you super adaptable but also a little unpredictable, even to the people closest to you.\n\nThe upside nobody mentions: you can understand almost anyone. Every type of person makes sense to you from the inside, because you've got access to all the modes yourself. You're the natural translator between people who can't understand each other, because no way of being feels totally foreign to you.",

  "howYouLearn": "You learn best when it comes at you from a few angles. Give you only the abstract concept and you'll want a real example. Give you only the example and you'll want the underlying point. You need both, because that's just how your brain processes—it doesn't lean hard one way, so the material shouldn't either.\n\nWhat's relevant now matters most. \"This will matter for your career someday\" or \"this is how it's always been done\" doesn't move you much. You want to get why it actually matters right now, in front of you.\n\nYou do best with teachers and material that don't lean too hard in one direction. The professor who's all dry concrete detail bores you to death; the one who's all floaty abstraction frustrates you. You need the balance because that's what matches what's going on inside your own head.\n\nTeaching yourself works well for you, honestly. Left to your own pace, you naturally adjust—you'll read some theory, then go try it, then circle back, switch between working solo and pulling in other people. You self-calibrate without even thinking about it, which a lot of people can't do.",

  "howYouCommunicate": "You shift to match whoever you're talking to. With the friend who's super literal, you get specific. With the friend who's all big ideas, you go abstract with them. You barely notice you're doing it, which is exactly why almost everyone finds you easy to talk to.\n\nBecause you live in the present, you tend to keep conversations grounded in what's actually going on. You're not the one spiraling into long stories about the past or wild speculation about the future—unless the moment genuinely calls for it, you stay with what's real and now.\n\nYou share your own take without steamrolling, and you take in other people's stuff without disappearing. You hold space for both. You're not the loudest in the group and you're not the doormat either—you're just balanced in the room.\n\nWhere you struggle is when someone wants you to pick a hard side. Because you can genuinely see why multiple takes are valid, picking one and arguing it hard feels kind of fake to you. You're way better at exploring something than debating it. \"Okay but here's the other angle\" is more your speed than \"no, I'm right.\"\n\nIn group stuff you often end up the unofficial translator—helping the literal friend and the big-idea friend actually get each other, bridging the one stuck on the past and the one racing toward the future. You're the one who goes \"wait, I think you're both kind of saying the same thing.\"",

  "phrase": "You're not empty. You're open. The space people read as \"nothing there\" is actually room for everything.",

  "secret": "Sometimes you fake having a preference just to seem normal.\n\nWhen the whole group knows exactly what they want—what to eat, what to watch, what to do with their life—and you genuinely could go any of five ways and be totally fine, you've learned to manufacture a decision. You pick something, say it with confidence you don't actually feel, and perform the having-an-opinion thing that seems to come so easily to everyone else.\n\nIt's not lying, exactly. It's that the real answer—\"honestly I'd be equally happy with any of these\"—sounds like you're being passive or dodging the question. So you've taught yourself to make up a preference on the spot, to have takes that are less discovered than just decided in the moment so people aren't annoyed.\n\nAnd then you lie awake wondering: is something wrong with me? Is there some basic human thing—wanting something really badly—that I'm just missing? Do other people actually feel the pull they seem to feel, or is everyone secretly faking it too?\n\nThe deeper one: sometimes you resent having to perform a certainty you don't have. It's weirdly exhausting being the one person who honestly doesn't mind, but having to pretend you do so everyone else feels comfortable around you.\n\nYou've even wondered if your calm is actually just you being checked out—like, is this real balance, or did I just go numb and dress it up as being chill? Here's the tell, though: if you're genuinely asking that question, you're probably not numb. Numb doesn't sit around wondering whether it's numb.",

  "whatOthersGetWrong": "They assume that because you don't react big, you must not feel big. They see calm and decide there's nothing deep happening. But you're feeling all of it—you just don't broadcast it the way other people use big reactions to announce what they're going through. Quiet on the outside isn't empty on the inside.\n\nThey assume you're lazy or have no ambition. In a world that worships people who are visibly obsessed with their goals, your steady, non-frantic version of going after stuff looks like you're not even trying. What they miss is that you can chase something without letting it consume your whole personality.\n\nSome think you must be bottling something up—that nobody's actually this calm, there's got to be a volcano under there. But your calm isn't suppression. It's just how you're built. There's no secret meltdown waiting to erupt; the steady surface goes all the way down.\n\nOthers read your flexibility as you being a pushover. They mistake genuine openness for weakness, like because you'll go along with things, you can be rolled. But chill isn't the same as spineless—when something actually matters, you'll plant your feet.\n\nThe one that stings most: people assume that because you can understand everyone's side, you don't have your own. Your ability to get all of it gets read as you being empty rather than having serious range. Being able to hold every perspective isn't the same as having none.",

  "hiddenSuperpower": "You're the room where people who can't stand each other can finally actually hear each other.\n\nIn a world where everyone's locked into their team—the literal people writing off the dreamers, the past-obsessed and the future-obsessed talking right past each other, the me-first and the everyone-else types constantly butting heads—you can hold space for all of them at once. Not because you're faking understanding. Because you genuinely get every side. Every mode is actually available to you.\n\nThat makes you an incredible mediator, translator, and bridge—not from learning some technique, but just from how you're wired. When two people who are fighting both feel actually understood, the defensiveness drops. When someone can finally say their piece and have it land fully, the whole thing can start to resolve.\n\nYou can sit in the middle of conversations that would otherwise just deadlock, because you're not secretly rooting for one side's way of thinking. You actually want everyone to understand each other, and because you mean it, people believe it.\n\nThe fights that don't happen because you were there are invisible. The understanding that shows up seems like it just naturally happened. It didn't. You made it possible by being the steady center that could hold every position without tipping into any of them.",

  "blindSpot": "Your calm might depend on things being low-stakes more than you realize.\n\nWhen the water's calm, your balance is effortless—it costs you nothing. But when the stakes spike—when something genuinely matters, when you might actually lose something, when you can't keep everyone happy at once—your steadiness might be shakier than you assume. You just haven't been tested the way the intense people get tested constantly.\n\nThe people who live at the extremes know their triggers because they trip them every single day. Your lack of extremes means fewer triggers—which also means you know yourself less well in those rare moments when you do snap. When the calm finally breaks, you might be way less ready for it than someone who's been melting down regularly their whole life.\n\nAlso watch for when \"balance\" is actually just avoidance. \"I can see all sides\" can sometimes really mean \"I don't want to take the stand this situation is clearly asking for.\" There are moments when staying neutral is wisdom and moments when it's just fear wearing a calm face. Learning to tell those two apart is your whole growth edge.",

  "frictionPatterns": "Your friction is kind of weird: you don't really have an opposite type to clash with. Instead, you clash with intensity itself.\n\nThe people who are super strongly anything—doesn't matter which direction—can grind on you. Not because of their specific take, but because of how fused they are with it, how they literally cannot access any other way of seeing it. From where you sit, that rigidity feels unnecessary, like, you could just consider the other angle for one second.\n\nAnd your calm can irritate them right back, specifically because you won't pick a side. When your friend is venting and wants you to be fully on their team, your \"well I can kind of see where the other person was coming from too\" can feel like a betrayal, even though you meant it as fairness.\n\nYour gift here: you show people that understanding someone doesn't mean agreeing with them, and that being present with someone doesn't require taking a position.\n\nYour growth edge: realizing that sometimes picking a side—even when you don't have to—is what someone actually needs from you. Sometimes loyalty matters more than balance, and reading which moment is which is the skill to build.",

  "energyPatterns": "What drains you:\n- Being pressured to have strong opinions you genuinely don't have\n- Constant drama and people stuck at the extremes about everything\n- Being forced to pick one side and argue it when you see truth in several\n- Friends who need you to be more intense or more defined to feel close to you\n- People endlessly questioning whether your calm is \"real\" or healthy\n- Group decisions where everyone wants you to just want something already\n\nWhat charges you:\n- Situations where your steadiness is actually the valuable thing—calming a fight, translating between people\n- Hangouts where nobody needs you to perform big feelings\n- People who genuinely appreciate that you're the chill one\n- Time in the present with no pressure to relive the past or panic about the future\n- Complicated stuff where you get to hold a bunch of angles at once\n- Being the steady one people instinctively gravitate toward when it all goes sideways",

  "workEnvironments": "Where you thrive:\n- Places that actually value fairness and seeing the whole picture\n- Mediation, support, coordination, anything needing a calm, even hand\n- Roles where staying steady under pressure is the point\n- Spaces where your calm presence is treated as a real asset\n- Complex situations that reward holding several angles at once\n\nWhere you suffocate:\n- Places that demand you pick a team and stay loyal no matter what\n- Cultures that reward whoever's the loudest and most extreme\n- Anywhere your balance gets read as you being weak or checked out\n- Cliquey, us-vs-them environments where \"not picking a side\" makes you suspect\n- Jobs that constantly pressure you into strong preferences you don't have",

  "topCareers": [
    {
      "title": "Mediation / Conflict Resolution Assistant",
      "description": "You rest at center—not by forcing it, just by how you're built—while everyone else gets yanked to the edges. Entry-level mediation, peer conflict resolution, or RA-type roles are made for exactly that: the person who can hold every side fairly because no side is where you actually live. You can access any angle when it's useful but default to none, which is why people trust you to not be secretly on the other person's team. The balance that gets called \"fence-sitting\" in cliquey rooms is, here, the entire qualification."
    },
    {
      "title": "Coordinator / Operations Assistant",
      "description": "You can get specific or zoom out, pull from the past or plan ahead, weigh yourself against everyone else—and not tip over. A coordinator or ops-assistant role rewards that even-keel: seeing the whole situation clearly without your own bias bending it. You hold the nuance where everyone else wants a quick hot take, and your read holds up because it isn't twisted toward the answer you wanted. The fairness that made cliquey groups suspicious of you becomes the foundation of judgment people can actually rely on at work."
    },
    {
      "title": "Support / Front Desk / Help Role",
      "description": "When everything's chaotic, you're the steady center that holds, and people calm down just being near you. Support work, a front desk, a help line—these pay for that steady-presence thing: staying clear and unbothered while someone else's panic runs hot. You don't get sucked into the drama; you hold the space around it. The calm that some friends read as \"not caring enough\" is, in this kind of work, exactly the value you bring to the table every single shift."
    }
  ],

  "blockIndicators": "Your Parser Profile suggests the following CBI block accessibility pattern:\n\nLikely High-Accessibility Blocks:\n- Pattern Recognition (balance lets you see patterns across all domains)\n- Perceptual Discrimination (present-focus enables fine-grained awareness)\n- Social Signal Processing (balanced reference gives access to interpersonal dynamics)\n\nLikely Moderate-Accessibility Blocks:\n- Sequential Processing (accessible when needed)\n- Symbolic Manipulation (available but not preferentially engaged)\n- Self-Reference Processing (balanced, not foregrounded)\n\nLikely Lower-Accessibility Blocks:\n- Generative Creation (balance may limit the drive that comes from tension and strong orientation)\n\nThis pattern suggests your cognitive architecture is optimized for understanding across difference, keeping perspective, and adapting to whatever the situation actually needs, with room to grow in taking a stand when a moment genuinely calls for one.\n\nEQUANIMOUS",

  "strengths": [
    {
      "title": "You Get Everyone From the Inside",
      "description": "You can genuinely understand every type of person, not fake it. The literal one and the dreamer, the past-stuck and the future-racing, the me-first and the everyone-else—none of them feel foreign to you. You can meet anybody in their own mode because all of those modes are sitting right there available to you."
    },
    {
      "title": "You Respond to What's Actually Needed",
      "description": "Without a strong default dragging you one way, you react to what a situation actually calls for instead of forcing your preference on it. You get specific when specific helps, big-picture when that's better. You're naturally fluid in a way the rigid people just can't be, and it makes you useful almost anywhere."
    },
    {
      "title": "You Don't Get Hooked",
      "description": "Your balance makes you genuinely hard to bait. The provocations that would set off someone strongly opinionated just slide off you, because you're not fused to any one side to defend. Where others get instantly defensive, you've got way less to protect, so you stay clear when everyone else is escalating."
    },
    {
      "title": "You Can Cool a Fight Down",
      "description": "When two people are clashing, you can hold space for both without secretly rooting for one. Your balance is real, so both sides trust you—you're not faking neutral, you actually are neutral. That makes you the person a fight needs in the room, the one who can lower the temperature instead of adding to it."
    },
    {
      "title": "You See It Clearly, Right Now",
      "description": "Your present-focus keeps you locked on what's actually happening, with way less distortion from old baggage or future panic. You read situations based on what's real in front of you, not the story your fears or your history are telling. That clarity is rarer than it sounds—most people are seeing through a filter."
    },
    {
      "title": "Your Calm Doesn't Run Out",
      "description": "Your steadiness isn't something you have to white-knuckle—it's just where you naturally rest. Other people have to work hard to find their center and then keep losing it. You just return to it on your own. That makes your calm sustainable in a way that forced, effortful calm never is."
    }
  ],

  "challenges": [
    {
      "title": "Nobody Knows What You Want",
      "challenge": "Because you don't have strong defaults, people can't tell what you actually want—and honestly, sometimes you can't either. Someone asks where you want to eat and you genuinely see five equally fine options. It frustrates the people who expect you to just have a preference like a normal person.",
      "remedy": "Practice tiny preferences. Even when the options feel exactly equal, just pick one and notice how it actually felt afterward. Over time you might find small real preferences hiding under the surface that you never noticed because you never made yourself choose and check."
    },
    {
      "title": "Feeling Like You're No One",
      "challenge": "Without strong leanings to build an identity on, you can feel undefined or kind of empty. \"Who even am I if I'm not strongly anything?\" Everyone else seems to build their whole self around their thing, and you don't have a thing, so you feel like you're missing the structure.",
      "remedy": "Get that balance itself is an identity. You're not \"nothing\"—you're centered, steady, the one who can hold it all. Let your calm become something you actually claim and identify with, instead of something you treat as a hole where a personality should be."
    },
    {
      "title": "Where's the Drive",
      "challenge": "Strong leanings create natural pull—the obsessed people get yanked toward their goals automatically. Your balance means there's less of that built-in pull in any direction, which can look like, and feel like, you just don't have any motivation or ambition.",
      "remedy": "Borrow the drive from the outside instead of waiting for it to bubble up inside. Attach yourself to projects, people, and goals that create their own pull. Use your flexibility as the asset it is—you can deliberately link up to meaningful directions and let them carry you, rather than expecting fire to spontaneously appear."
    },
    {
      "title": "Looking Like You Don't Care",
      "challenge": "Your non-reactive calm can read as you not caring. When everyone else is showing big reactions and you're just sitting there steady, it can come off as indifference. You're actually fully there and fully engaged—you just don't perform it the way people expect.",
      "remedy": "Say your engagement out loud when it matters. \"I'm actually really into this, even if I'm not showing it the way you might.\" Let people know you're with them even when your face and energy aren't broadcasting it. A few words can close the whole gap between what you feel and what they see."
    },
    {
      "title": "Getting Steamrolled",
      "challenge": "Your real flexibility can get taken advantage of by people with stronger agendas. Since you can genuinely go along with lots of options, the pushy personalities just default to getting their way with you every time—and it adds up into a pattern where you're always the one accommodating.",
      "remedy": "Watch for the people you keep bending toward. Notice if it's always the same friend getting their way. Then practice the occasional just-because assertion—picking your thing simply because it's yours, even when you honestly could go either way. Do it sometimes just to keep the muscle alive."
    },
    {
      "title": "Hard to Explain Yourself",
      "challenge": "When people ask why you did something or what you're feeling, you can struggle to answer. The strongly-oriented folks have a ready explanation built in; your balance means your reasons are genuinely mixed or depend on the situation, so a clean answer just isn't there.",
      "remedy": "Get comfortable with \"both/and\" answers. Your actual inner reality is genuinely multiple and situational—don't flatten it into a fake-clean reason just because people expect a tidy one. \"Honestly, a bit of both, it depended\" is a real and honest answer, even if it's not the neat one they wanted."
    }
  ]
};
