// FORESIGHTED Profile — Young Adult (18–29)
// Parser Profile™ © 2026 Cognition Blocks LLC

export const foresightedyaProfile = {
  "name": "FORESIGHTED",
  "tagline": "The one who already sees where this is headed",

  "overview": "You see where things are going before they get there. Not in some psychic way—you just clock the pattern and follow it forward. While everyone's reacting to what's happening right now, you're already watching what it's turning into. The friendship that's going to blow up in three months. The group plan that's obviously going to fall apart. The trend everyone's going to be on in a year. You see the shape of it before it finishes forming.\n\nYour brain runs on patterns and possibilities way more than on the concrete details right in front of you. You're tracking trajectories—where the line is pointing, what forces are pushing it, where it most likely lands. It feels less like guessing and more like just reading the obvious continuation that nobody else seems to be reading.\n\nThis isn't you being optimistic or pessimistic. You see the good futures and the bad futures with the same clarity, which is exactly why your read is worth something—you're not just projecting your hopes or your fears onto it. You're tracking the actual pattern, wherever it goes.\n\nYou're watching your own path and everyone else's at the same time—where you're heading, where your friends are heading, how it all weaves together. That wide view gives you a kind of strategic sense that people locked onto just one thing can't really access. Your gift is seeing what's coming. Your challenge is patience with everyone who can't see it yet—and the fact that seeing it doesn't mean you can make anyone listen.",

  "howYouLearn": "It clicks when it connects to where things are going. Why does this matter for what's coming? How does this hook into the bigger direction? Static facts that just sit there do nothing for you—but show you how this knowledge sets up what's next, and you're locked in. You learn forward.\n\nYou want learning that links now to later. Not just what something is, but what it's becoming, where the whole field is heading, how today's version is going to evolve. Anything that preps you for what's coming feels genuinely urgent in a way that \"memorize this for the test\" never will.\n\nYou struggle with pure history or pure here's-how-it-is-right-now with no future to it. \"This is how it used to work\" bores you unless it explains how it shaped what's coming. You also check out when stuff gets chopped into disconnected little pieces with no sense of how they add up to something bigger.\n\nFrameworks that show how things develop over time work great for you. Case studies of how something evolved pull you right in. The teacher who connects today's material to where it's all heading matches your brain way better than the one who treats knowledge like a frozen list of facts.",

  "howYouCommunicate": "You talk in directions and what-ifs. Where everyone else describes what is, you describe what it's turning into. Your sentences are full of \"this is heading toward,\" \"if this keeps going,\" \"watch, in a few months…\" You can't help framing the now in terms of the later.\n\nThis can throw off the people who live in the present. They feel like you're not even addressing what's actually happening, or that you're catastrophizing, or just making stuff up. They don't have the pattern-read that makes your future-talk feel completely grounded to you—so to them it can sound like anxiety or fantasy.\n\nYou'll often need to anchor your read in something they can actually see. \"Here's what's happening right now, and here's what it tells me is coming\" bridges the gap way better than just announcing the future. Show your work and people can follow you there.\n\nYou click best with the other people who think ahead, or with the ones who've watched you be right enough times that they've learned to trust your read even when they can't see it yourself.",

  "phrase": "You're not anxious about the future—you're informed about it. What other people experience as worry, you experience as pattern recognition showing up early.",

  "secret": "You've always seen it coming. As a kid you'd watch something play out exactly the way you knew it would, while the adults acted shocked by an ending that felt completely obvious to you. You learned early not to say \"I knew that would happen\" because it sounded smug—but you did know. You almost always know.\n\nIt started as feeling a little ahead of everyone, then turned into frustration at how nobody else seemed to see it, and eventually settled into this quiet, lonely acceptance. You see where things are going. Most people don't. Explaining it barely helps. So you've learned to just watch stuff unfold without always trying to stop it, because your seeing it almost never turns into them doing anything about it.\n\nThe secret you carry is that seeing ahead is isolating. You're basically living in a slightly different time zone than everyone around you—already in a future they haven't even imagined yet. That gap puts distance between you and people. You're trying to talk about what's coming while they're fully absorbed in what is.\n\nAnd you've carried the weight of watching bad things come that you couldn't stop. The relationship clearly headed for a wreck. The friend making a decision you could see was going to hurt them. You saw it. You sometimes tried to warn them. It usually didn't land. And then you had to sit there and watch it arrive—having already grieved it months ago, alone, while everyone else was just starting to get it.",

  "whatOthersGetWrong": "They think you're anxious when you're actually just informed. Your future-focus looks like worry to people who can't see what you see. They read your trajectory-tracking as catastrophizing instead of recognizing it's just pattern recognition running on a different clock than theirs.\n\nThey think you're not present when you're actually clocking what the present means for later. Your attention being on where things are heading doesn't mean you're missing what's happening now—it means you're processing what now turns into. You're not zoned out. You're ahead.\n\nThey think your calls are lucky guesses instead of pattern reads. When you're right, which is a lot, they chalk it up to chance. When you're wrong the one time, they use it to wave off everything you've ever predicted. They don't get that you're working with probabilities, not magic—you were never claiming certainty, just the most likely line.\n\nThey think you're a pessimist when you flag a bad trajectory, or naive when you get excited about a good one. Your read gets treated like an emotional mood you're in rather than information you're actually picking up. It's not that you're down or hyped—it's just what the pattern is showing.",

  "hiddenSuperpower": "You can help people get ready for futures they can't see yet. Your read on where things are going isn't just for you—it translates. When you slow down and actually explain what you're seeing and why, other people can start to catch patterns they'd have completely missed on their own.\n\nThat makes you genuinely valuable anytime something needs to be set up in advance. You see what has to happen now for a future that isn't obvious yet. Which choice is going to matter way more than it looks like it does. Which thing to start early. Which risk is bigger than people think. You're the friend who says \"start applying now, not in spring\" and turns out dead right.\n\nYou also see possibility, not just probability—not only where things are likely heading, but where they could head if something changed. What could open up if a certain move got made. What might become real if someone invested in it now. That positive version of the read lets you spot opportunities other people walk right past because they can't picture them yet.\n\nAnd because you're tracking both your own path and the people around you, you can apply all this to your own life and to the group at the same time—a kind of two-track strategic sense that people locked onto just one of those can't reach.",

  "blindSpot": "You can undervalue right now because it's already turning into later in your head. But what's here now has worth beyond where it's going—the actual experience, the connection, the moment that matters on its own whether or not it leads anywhere. Your future-focus can quietly rob the present of the weight it deserves, and you end up half-missing your own life as it happens.\n\nYou can also over-trust your read. You're right a lot, but not always, and being right so often can make you skip the healthy uncertainty. Some futures genuinely can't be predicted from the current pattern—random stuff happens, things blindside everyone. The confidence that comes from usually nailing it can blind you to the times the pattern just doesn't hold.\n\nTracking both your own path and everyone else's can also turn into a way to dodge commitment. By keeping one eye on yourself and one on the group, you can avoid ever answering which one actually matters more in a given moment. Holding all the options open forever isn't the same as choosing.\n\nAnd you can struggle with people running on a different clock. Your future-focus feels so obviously correct to you that you forget the present-focused and past-focused people aren't failing to see—they're just seeing differently. Living in the now isn't a defect. It's a whole valid way of being that you sometimes treat like they're just behind.",

  "frictionPatterns": "You clash with the people anchored hard in their own past experience—the ones who go \"that's not how it's gone before\" and shut it down. They think you're just speculating with nothing real behind it. You think they're trapped in what already happened instead of seeing what's becoming. You're both reading reality, just from opposite ends of the timeline.\n\nYou also grind against the heavy present-focused people, who feel like your future-talk drags you both out of the shared real moment. They want to deal with what is; you keep pulling toward what's coming. To them you're never just here, and to you they're never looking up the road.\n\nThe past-focused ones can even find your read kind of threatening—your whole future-orientation implies that history isn't the final word, that what was doesn't lock in what'll be. That can feel like you're dismissing the thing they trust most.\n\nYour gift in all of it: your read can help the grounded people get ready while there's still time to do something. You're the early-warning system.\n\nYour growth edge: getting that present-focus and past-focus aren't failures to see the future—they're just different ways of being pointed at time, each with their own real value. You don't have a monopoly on reality just because you're looking ahead.",

  "energyPatterns": "What drains you:\n- Getting waved off as \"anxious\" or \"overthinking it\" when you're just reading the pattern\n- Watching something you clearly called arrive because nobody listened\n- Present-only environments that treat thinking ahead as a distraction\n- Having to pretend you don't see what you obviously see\n- Feeling urgent about something nobody else feels urgent about, because they can't see it\n- Being trapped in pure react-mode where nothing ever gets planned\n\nWhat charges you:\n- Reading where something's headed clearly and getting ready for it early\n- Helping someone see what's coming in time to actually do something about it\n- Places that treat thinking ahead as a real, valued skill\n- Watching your call get proven right over time\n- Planning that connects what you do now to what you want later\n- Spotting an opportunity early that nobody else has noticed yet",

  "workEnvironments": "Where you thrive:\n- Places where seeing ahead is literally the job\n- Strategy, planning, research, trend-spotting, anything forward-looking\n- Roles where catching what's coming actually creates value\n- Spaces that want your read on where things are headed, not just today's fire\n- Teams that pair your vision with people who handle the details\n\nWhere you suffocate:\n- Pure react-mode places where nobody ever plans anything\n- Cultures that treat thinking ahead as a waste of time\n- Spots where putting out today's fire eats every ounce of attention\n- Anywhere your future-read gets treated like anxiety to be managed instead of info to use\n- Rigid places stuck on \"how it's always been done\" with no eye on what's coming",

  "topCareers": [
    {
      "title": "Junior Analyst / Research Assistant",
      "description": "You see the future bleeding into the present—pattern recognition pointed at where things are heading, which other people experience as you somehow predicting stuff. An entry-level analyst or research role is exactly that turned into work: tracking what's becoming while everyone else is fixed on what is. You catch the shape of things before they finish forming and turn it into something people can act on. The future-read that got managed as \"you're overthinking it\" becomes, in this field, literally the product you're paid for."
    },
    {
      "title": "Planning / Operations / Project Coordinator",
      "description": "You're already living in the consequence of today's decision before anyone else has felt it. A planning or project-coordinator role rewards exactly that—seeing what needs to happen now for a deadline or outcome that isn't obvious yet, and getting ahead of the thing before it becomes a crisis. You're the one who flags the problem in week two that everyone else hits in week six. The \"why are you worrying about that already\" energy that reactive friends gave you is, here, the entire discipline they hire you for."
    },
    {
      "title": "Trend / Social / Content Strategist",
      "description": "You catch the signal of where things are heading before it's obvious—the shift that's about to become everyone's thing. An entry-level strategy, social, or content role pays for that early read: seeing the trajectory and naming it while there's still time to be early instead of late. You track where the audience and the culture are going, not just where they are. The \"you're getting ahead of yourself\" that present-focused people said becomes, in this work, precisely the point of you."
    }
  ],

  "blockIndicators": "Your Parser Profile suggests the following CBI block accessibility pattern:\n\nLikely High-Accessibility Blocks:\n- Pattern Recognition (trajectory and trend detection)\n- Symbolic Manipulation (abstract processing of future implications)\n- Generative Creation (perceiving possible futures, not just probable ones)\n\nLikely Moderate-Accessibility Blocks:\n- Self-Reference Processing (through balanced attention that includes self)\n- Social Signal Processing (through balanced attention that includes other)\n- Sequential Processing (tracking how futures unfold from presents)\n\nLikely Lower-Accessibility Blocks:\n- Perceptual Discrimination (abstract orientation may de-emphasize concrete present-moment detail)\n- Spatial Relationships (temporal processing emphasized over spatial)\n\nThis pattern suggests your cognitive architecture is optimized for thinking ahead and reading where things are going, with room to grow in actually valuing what's here right now—not just what it's about to become.\n\nFORESIGHTED",

  "strengths": [
    {
      "title": "You Read Where It's Going",
      "description": "You see where things are heading, not just where they are. Trends, momentum, how a situation is progressing—you track it automatically and run the line forward into what's probably coming. It's not a wild guess; it's pattern recognition aimed at the future. You're the one who calls it months before it's obvious to everyone else."
    },
    {
      "title": "You See More Than One Future",
      "description": "Because you're tracking your own path and everyone else's at once, you see several futures at the same time—where you're heading, where the group's heading, how your choices ripple out to other people. That wide view keeps you out of the tunnel-vision trap that gets people who only watch one single thing."
    },
    {
      "title": "You Catch the Turn Early",
      "description": "You notice when a trajectory shifts before the shift is obvious to anybody else. The friendship starting to cool, the problem just beginning to form, the opportunity opening up—you catch it at the turning point instead of after it's already happened. That gives you response time nobody else in the room has."
    },
    {
      "title": "You See the Whole Tree of Outcomes",
      "description": "You naturally trace where today's choice leads down the line. Where everyone else just sees a decision, you see the whole branching set of outcomes it sets off. So you can weigh options by where they actually end up, not just by which one looks best in the moment—which is why your advice ages well."
    },
    {
      "title": "You Prep for What's Actually Likely",
      "description": "Your future-focus turns into preparation that matches the real odds, instead of either panicking about everything or pretending nothing's coming. You get ready for what's genuinely likely because you can actually see what's likely. It looks like you're always weirdly prepared—you're just reading the probabilities clearly."
    },
    {
      "title": "You Can Translate the Future",
      "description": "You can explain what's coming in terms people can grasp right now—connecting today's action to tomorrow's outcome so it lands. That translation makes you valuable for helping people see what's actually at stake in a choice they were about to make casually, without thinking past tonight."
    }
  ],

  "challenges": [
    {
      "title": "Missing Right Now",
      "challenge": "Your future-focus can pull you right out of the present. You're so busy tracking where everything's headed that you half-miss what's actually happening—the night out, the conversation, the moment in front of you feels less real than the possibilities running ahead in your head. People feel you're not really there.",
      "remedy": "Practice being present on purpose, like a skill you have to work at, not something that just happens. What's here now is real too, not only what's coming. Block off time where you deliberately stop tracking trajectories and just experience the thing you're actually in—the meal, the friend, the moment."
    },
    {
      "title": "Nobody Believes You Yet",
      "challenge": "You see it coming and people just don't believe you. Your warning about the bad trajectory or your hype about the good one lands on ears that can't hear it. You're not wrong—you're early. But early feels exactly like wrong right up until time finally proves you right, and that gap is lonely.",
      "remedy": "Write your calls down with the date. When you turn out right, the receipts help people actually take you seriously next time, instead of forgetting you ever said it. It also sharpens your own read—you learn from your track record where your pattern recognition is solid and where it runs hot."
    },
    {
      "title": "You're Urgent and They're Not",
      "challenge": "What feels urgent to you—because you can see where it's headed—doesn't feel urgent at all to the people still living in the now. That mismatch causes friction: you want to act immediately, they don't get what the rush is, and you come off as anxious or pushy.",
      "remedy": "Tune your pitch to their clock, not yours. What do they actually care about regarding the future? Start there, not with what's bugging you. Build the bridge from their timeline to yours instead of expecting them to leap to where you already are. Make the future they care about the reason to move now."
    },
    {
      "title": "Frozen by Too Many Futures",
      "challenge": "Seeing all the possible outcomes can make actually choosing feel impossible. Every option has consequences you can clearly see, every path branches into more paths. The same clarity that lets you see so well can lock you up so you can't move—stuck analyzing every version forever.",
      "remedy": "Set yourself a hard deadline to decide, before you've mapped everything. Perfect foresight isn't on the menu—good-enough foresight you actually act on beats perfect foresight you never use. Sometimes you just have to move with the read you've got and adjust as the real thing unfolds."
    },
    {
      "title": "Half-Here in Relationships",
      "challenge": "Your future-focus can make a partner or friend feel like you're not all the way with them. You're here, but you're also already ahead—tracking where this relationship is heading. That split attention can feel like absence to someone who just wants you fully present with them, right now.",
      "remedy": "Say which mode you're in out loud. Let people know when you're future-tracking versus when you're fully here, instead of leaving them to guess and feel shut out. And carve out present-only time on purpose—where you deliberately set the trajectory-reading aside and just be with them in the now."
    },
    {
      "title": "The Details Trip You Up",
      "challenge": "Your big-picture, pattern brain can skip right over the concrete specifics that actually matter. You see the whole trajectory crystal clear but fumble the actual little steps of getting there—the paperwork, the logistics, the boring details the plan dies on.",
      "remedy": "Team up with the detail people who can turn your read into actual steps. Your vision genuinely needs their execution—it's not a weakness, it's just a different skill. Pairing your \"here's where this is going\" with someone's \"here's exactly how we do it\" covers the part your brain alone keeps dropping."
    }
  ]
};
