// FORESIGHTED Profile
// Parser Profile™ © 2026 Cognition Blocks LLC
// Abstract • Future • Balanced

export const foresightedProfile = {
  "name": "FORESIGHTED",
  "code": "Abstract • Future • Balanced",
  "tagline": "The trajectory tracker who sees where things are heading",
  "overview": "You see the future bleeding into the present. Not through prophecy or\nmysticism, but through pattern recognition applied to trajectories, you\nperceive where current conditions are heading with a clarity that others\nexperience as prediction. While they're focused on what is, you're\ntracking what's becoming. You see the shape of things before they fully\nform.\n\nYour cognitive architecture prioritizes abstract patterns over concrete\ndetails, future possibilities over present or past, and maintains\nbalanced attention between self and other. The result is a consciousness\noriented toward emergence, perceiving not just the direction of travel\nbut the landscape it's traveling through, the forces at work, the\nprobable destination.\n\nThis isn't optimism or pessimism. It's trajectory perception. You see\npositive and negative futures with equal clarity, which is precisely why\nyou're valuable: you're not projecting wishes or fears onto what's\ncoming. You're perceiving the actual patterns that will shape what\narrives. When you say \"this is heading somewhere,\" you're usually\nright.\n\nThe Foresighted profile represents approximately 3% of the population.\nYour rarity comes from the specific configuration: abstract processing\n(pattern over detail), future orientation (what's coming over what is\nor was), and balanced reference (neither predominantly self nor other).\nMost future-oriented processors have a directional bias, they're\ntracking their own trajectory or collective outcomes. You track both,\nwhich gives you a more complete picture of where things are heading.\n\nYour gift is anticipatory intelligence that serves whoever needs it.\nYour challenge is patience with those who can't see what you see and\nurgency that may outpace others' readiness. You perceive what's\ncoming, but perception isn't persuasion, and seeing the future doesn't\nmean you can make others see it too.\n\nUnderstanding your profile means recognizing that your\nfuture-orientation isn't anxiety or fantasy, it's pattern recognition\noperating on a different temporal axis than most minds access.",
  "howYouLearn": "You learn by understanding where knowledge is heading, why this matters\nfor what's coming, how this connects to future developments, what\nimplications this creates. Static information that has no temporal\ntrajectory engages you less than dynamic understanding that's going\nsomewhere.\n\nYour optimal learning environment connects present learning to future\napplication. You want to know not just what something is but what it's\nbecoming, where the field is heading, how current knowledge will evolve.\nYou're motivated by relevance to futures you can perceive, learning\nthat prepares you for what's coming feels urgent; learning that\naddresses only what is feels optional.\n\nYou struggle with learning that's purely historical or present-focused\nwithout future application. \"This is how it was\" interests you less\nthan \"this is how it shaped what's coming.\" You also struggle with\nlearning environments that fragment into disconnected pieces without\nshowing how the pieces connect to emerging wholes.\n\nFrameworks work well for you, especially frameworks that show\ndevelopment over time. Case studies of how things evolved engage you\nmore than snapshots of how things are. Teachers who can connect current\ncontent to future developments match your processing better than those\nwho treat knowledge as static.",
  "howYouCommunicate": "You communicate in terms of direction, trajectory, and implication.\nWhere others describe what is, you describe what's becoming. Your\nlanguage is full of temporal markers: \"this is heading toward,\" \"if\nthis continues,\" \"the trajectory suggests.\" You naturally frame\npresent situations in terms of their future states.\n\nThis can be disorienting for present-focused listeners. They may feel\nlike you're not addressing what's actually happening, or that you're\ncatastrophizing (if the trajectory is negative) or fantasizing (if it's\npositive). They don't have access to the pattern recognition that makes\nyour future-talk feel grounded to you.\n\nYou may need to consciously anchor your future-perception in present\nevidence. \"Here's what I'm seeing now, and here's what it suggests\nis coming\" bridges the gap between your perception and others' access.\nWithout this bridging, your communication can feel unmoored from reality\nthat others can verify.\n\nYou communicate best with those who share future-orientation or who have\nlearned to trust your trajectory perception. You communicate least\neffectively with heavy present-focused processors who experience your\nfuture-talk as leaving the conversation, or with past-focused processors\nwho want to discuss history while you want to discuss destination.",
  "phrase": "You're not anxious about the future, you're informed about it. What\nothers experience as worry, you experience as pattern recognition\narriving early.",
  "secret": "You've always seen what was coming. As a child, you watched situations\nunfold exactly as you'd perceived they would, while adults seemed\nsurprised by outcomes that felt obvious to you. You learned not to say\n\"I knew this would happen\" because it sounded arrogant, but you did\nknow. You almost always know.\n\nThis knowing started as a feeling of being ahead of everyone else, then\nbecame a frustration at others' apparent blindness, then settled into a\nkind of lonely acceptance. You see where things are heading. Others\ndon't. Explaining rarely helps. So you've learned to watch\ntrajectories unfold without always trying to redirect them, knowing that\nyour perception often can't become their action.\n\nThe secret you've carried is that foresight is isolating. You live in a\ndifferent temporal zone than most people, already in futures they\nhaven't conceived yet. This displacement creates distance. You're\nhaving conversations about what's coming while others are having\nconversations about what is. You're tracking implications while\nthey're still processing events. The gap is constant, and constantly\nlonely.\n\nYou've also carried the weight of seeing negative trajectories you\ncouldn't prevent. Relationships heading for destruction, organizations\nmaking decisions that would prove disastrous, individuals walking paths\nthat would lead to pain. You saw. You sometimes tried to warn. It rarely\nworked. And you've had to watch what you foresaw arrive, knowing you'd\nalready grieved it while others were just beginning to understand what\nhappened.",
  "whatOthersGetWrong": "About You\n\nThey think you're anxious when you're actually informed. Your\nfuture-focus looks like worry to those who can't see what you see. They\ninterpret your trajectory perception as catastrophizing rather than\nrecognizing it as pattern recognition operating on a different timeline.\nThey want to calm you down when you don't need calming, you need to be\nheard.\n\nThey think you're not present when you're actually perceiving the\npresent's implications. Your attention on future trajectory doesn't\nmean you're missing what's happening now, it means you're processing\nwhat now means for later. You're not absent; you're ahead. But\n\"ahead\" looks like \"absent\" to those who can only see \"here.\"\n\nThey think your predictions are lucky guesses rather than pattern\nrecognition. When you're right, which is often, they attribute it to\nchance rather than perception. When you're wrong, which happens, they\nuse it to dismiss all your future-perception. They don't understand\nthat you're working with probabilities, not prophecies, and that high\naccuracy doesn't require perfection.\n\nThey think you're pessimistic when you see negative trajectories or\nnaive when you see positive ones. Your perception is treated as\nemotional bias rather than pattern recognition. They project optimism or\npessimism onto your trajectory-tracking without understanding that\nyou're perceiving direction, not choosing attitude.",
  "hiddenSuperpower": "You can help others prepare for futures they can't yet see. Your\ntrajectory perception isn't just for you, it's translatable. When you\ntake time to explain what you're seeing and why, others can begin to\nperceive patterns they would have missed entirely. You expand their\ntemporal horizon by lending them your perception.\n\nThis makes you invaluable in any context requiring strategic\npreparation. You see what needs to happen now for futures that aren't\nobvious yet. You perceive which decisions will matter more than they\nappear to, which investments will pay off, which risks are larger than\nthey look. This foresight, shared effectively, becomes collective\nadvantage.\n\nYou also perceive possibility, not just probable futures but potential\nfutures. You see what could become if certain conditions changed, what\nmight emerge if certain investments were made. This positive trajectory\nperception is equally valuable, allowing you to identify opportunities\nthat others would miss because they can't see past current conditions.\n\nYour balanced reference means you can apply this foresight to both\npersonal and collective contexts. You're not just tracking where\nyou're heading or where the group is heading, you're tracking both,\nwhich gives you integrated strategic intelligence that single-focus\nprocessors can't access.",
  "blindSpot": "You may undervalue the present moment because it's already transforming\ninto future. What's here now has value beyond its trajectory,\nexperience, connection, reality that matters independently of where\nit's heading. Your future-focus can rob the present of significance it\ndeserves on its own terms.\n\nYou may also overweight your trajectory perception. You're usually\nright, but not always, and the confidence that comes from frequent\naccuracy can prevent appropriate uncertainty. Some futures genuinely\naren't predictable from current patterns. Black swans exist. Your model\nof what's coming is excellent, but it's still a model, and all models\nhave limits.\n\nYour balanced reference might become a way of avoiding commitment. By\ntracking both personal and collective trajectories, you may evade the\nquestion of which matters more in specific situations. Balance is wisdom\nuntil it becomes refusal to prioritize when prioritization is required.\n\nAnd you may struggle with those who operate on different timelines. Your\nfuture-focus feels obviously correct to you, how could anyone not want\nto know where things are heading? But present-focused and past-focused\nprocessors aren't failing to perceive; they're perceiving differently.\nTheir temporal orientations have value your future-focus might dismiss.",
  "frictionPatterns": "You clash most with Concrete • Past • Balanced (Seasoned) processors.\nThey're anchored in specific historical experience that's proven\nreliable; you're perceiving abstract future patterns that haven't been\nvalidated yet. They think you're speculating without foundation. You\nthink they're trapped in what was instead of perceiving what's\nbecoming. The conflict is Concrete vs. Abstract, Past vs. Future, two\ndimensions of opposition.\n\nYou also experience friction with heavy present-focused processors who\nexperience your future-talk as leaving the shared reality of now. They\nwant to address what is; you want to address what's coming. The\ntemporal mismatch creates conversations that never quite meet.\n\nPast-focused processors may find your trajectory perception threatening.\nYour future-orientation implicitly suggests that history isn't\nsufficient, that what was doesn't determine what will be. This can feel\ndismissive to those whose identity and confidence come from\nunderstanding what came before.",
  "energyPatterns": "What Energizes You:\n\n• Perceiving trajectories clearly and preparing accordingly\n\n• Helping others see what's coming in time to respond\n\n• Environments that value strategic foresight\n\n• Watching your perceptions validate over time\n\n• Planning that connects present action to future outcome\n\nWhat Drains You:\n\n• Being dismissed as anxious or speculative\n\n• Watching preventable futures arrive because no one listened\n\n• Present-focused environments that treat future-talk as distraction\n\n• Having to pretend you don't see what you clearly see\n\n• Urgency that others can't feel because they can't see",
  "workEnvironments": "You thrive in environments where foresight is the job, strategy,\nplanning, forecasting, risk assessment, trend analysis, futures\nresearch, any role where perceiving what's coming creates value. You\nalso thrive as strategic advisor, translating your trajectory perception\ninto actionable guidance for leaders or organizations.\n\nYou struggle in environments that are purely reactive, where no one\nplans, where strategy is considered overhead, where putting out today's\nfires consumes all attention. You also struggle where your\nfuture-perception is treated as anxiety to be managed rather than\nintelligence to be leveraged.\n\nIdeal factors: valued strategic thinking, decision-makers who want to\nsee further, planning horizons that match your perception, colleagues\nwho respect foresight even when they don't share it. Avoid: purely\nreactive cultures, dismissal of future-perception, environments where\nraising concerns about trajectory is treated as negativity.",
  "blockIndicators": "Your Parser Profile suggests the following CBI block accessibility\npattern:\n\nLikely High-Accessibility Blocks:\n\n• Pattern Recognition (trajectory and trend detection)\n\n• Symbolic Manipulation (abstract processing of future implications)\n\n• Generative Creation (perceiving possible futures, not just probable\nones)\n\nLikely Moderate-Accessibility Blocks:\n\n• Self-Reference Processing (through balanced attention that includes\nself)\n\n• Social Signal Processing (through balanced attention that includes\nother)\n\n• Sequential Processing (tracking how futures unfold from presents)\n\nLikely Lower-Accessibility Blocks:\n\n• Perceptual Discrimination (abstract orientation may de-emphasize\nconcrete present-moment detail)\n\n• Spatial Relationships (temporal processing emphasized over spatial)\n\nThis pattern suggests your cognitive architecture is optimized for\nstrategic intelligence and anticipatory perception. Your developmental\nopportunities lie in present-moment engagement, building capacity to\nvalue what's here now, not just what it's becoming, and in concrete\ngrounding when abstract trajectory perception needs anchoring in\nspecific observable data. The most mature version of your architecture\nperceives futures while remaining fully available to the present\nthey're emerging from.",
  "strengths": [
    {
      "title": "Trajectory Recognition You perceive where things are heading, not",
      "description": "just where they are. Trends, developments, progressions, you track these\nautomatically, extrapolating current patterns into probable futures.\nThis isn't guessing; it's pattern recognition applied temporally. You\nsee the path before others see there is a path."
    },
    {
      "title": "Balanced Anticipation Your dual attention to self and other means",
      "description": "you perceive multiple futures simultaneously, personal trajectory and\ncollective direction, individual implications and systemic outcomes.\nThis comprehensive anticipation prevents the tunnel vision that\nsingle-focus future processors often develop."
    },
    {
      "title": "Early Warning Perception You notice when trajectories shift before",
      "description": "the shift becomes obvious. Changes in direction, emerging problems, new\npossibilities, you perceive these at the inflection point rather than\nafter the new course is established. This early perception creates\nresponse time that others don't have."
    },
    {
      "title": "Implication Mapping You naturally trace the implications of current",
      "description": "decisions into their future consequences. Where others see a choice, you\nsee a branching tree of outcomes. This doesn't paralyze you, it informs\nyou, letting you weigh options against their probable results rather\nthan just their immediate appeal."
    },
    {
      "title": "Pattern-Based Preparation Your future-focus translates into",
      "description": "preparation that's proportional to probability rather than driven by\nanxiety or denial. You prepare for what's likely because you can see\nwhat's likely. Others may see this as either paranoid or prescient\ndepending on whether they share your perception."
    },
    {
      "title": "Temporal Translation You can communicate across time horizons,",
      "description": "explaining future implications in present terms, connecting current\nactions to future outcomes. This translation capacity makes you valuable\nfor helping others see what's at stake in decisions they might\notherwise make casually."
    }
  ],
  "challenges": [
    {
      "title": "Present-Moment Absence Your future-focus can evacuate you from the",
      "challenge": "present. You may be so busy tracking where things are heading that you\nmiss what's actually happening. Relationships, experiences,\nopportunities that exist now may feel less compelling than the\npossibilities you're perceiving ahead. Practice deliberate\npresent-focus as a discipline rather than a natural state. What's here\nnow is also real, not just what's coming.",
      "remedy": ""
    },
    {
      "title": "Cassandra Frustration You see what's coming and others don't",
      "challenge": "believe you. Your warnings about negative trajectories or excitement\nabout positive ones lands on ears that can't hear it. You're not\nwrong, you're early. But early can feel exactly like wrong until time\nproves otherwise. Document your perceptions with timestamps. When\nyou're validated, the record helps establish credibility for next time.\nPattern recognition improves when you can study your own track record.",
      "remedy": ""
    },
    {
      "title": "Urgency Mismatch What feels urgent to you, because you can see where",
      "challenge": "things are heading, doesn't feel urgent to those still focused on the\npresent. This mismatch creates friction: you want action now, they\ndon't see why. Your timeline isn't their timeline. Calibrate your\ncommunication to others' temporal perception. What matters to them\nabout the future? Start there, not with what matters to you.",
      "remedy": ""
    },
    {
      "title": "Analysis Paralysis Seeing multiple possible futures can make",
      "challenge": "choosing between them feel impossible. Every option has visible\nconsequences; every path has traceable implications. The clarity that\nhelps you see can become the complexity that prevents you from acting.\nSet decision deadlines that force action before analysis is complete.\nPerfect foresight isn't available; good-enough foresight must be acted\non.",
      "remedy": ""
    },
    {
      "title": "Relationship Strain Your future-focus can make partners and friends",
      "challenge": "feel like you're not fully with them. You're here but you're also\nalready ahead, tracking where this relationship is going, what this\nperson is becoming. This divided attention can feel like absence to\nthose who want full presence. Name when you're future-tracking and when\nyou're present-focused. Let others know which mode you're in rather\nthan leaving them to guess.",
      "remedy": ""
    },
    {
      "title": "Overlooked Details Your abstract processing may miss concrete",
      "challenge": "specifics that matter. You see the trajectory clearly but may stumble on\nthe details of navigating it. The path is visible; the individual steps\nless so. Partner with detail-oriented processors who can translate your\ntrajectory perception into actionable specifics. Your vision needs their\nexecution intelligence.",
      "remedy": ""
    }
  ]
};
