// GROUNDED Profile
// Parser Profile™ © 2026 Cognition Blocks LLC
// Concrete • Present • Balanced

export const groundedProfile = {
  "name": "GROUNDED",
  "code": "Concrete • Present • Balanced",
  "tagline": "The reality-anchor who keeps both feet planted",
  "overview": "You see what's actually in front of you, not what was there yesterday,\nnot what might be there tomorrow, just what is. And often, that's\nenough. More than enough. While others spin elaborate theories or worry\nabout distant possibilities, you're dealing with reality as it actually\npresents itself. This isn't limitation. It's clarity.\n\nYou deal with what's in front of you. Not theories about it. Not\nworries about what it might become. Just the thing itself. And you give\nfair weight to your own needs and others'—not swinging to extremes in\neither direction. The result is that you're the steady one, the person\npeople look to when everything else feels chaotic.\n\nYou've probably frustrated people who wanted you to \"think bigger\" or\n\"consider the implications.\" What they didn't understand is that you\nwere already considering the only implications that mattered, the\nimmediate, practical ones. You weren't missing the bigger picture; you\nwere correctly identifying that most of the \"bigger picture\" was\nnoise.\n\nThe Grounded profile represents approximately 6% of the population.\nYou're rare, and you're essential. Every team, every family, every\norganization needs someone who can cut through complexity to the\nactionable core. That's you. When others are paralyzed by analysis or\ndistracted by speculation, you're the one asking, \"but what are we\nactually doing right now?\"\n\nYou're good at solving problems in real-time, cutting through noise to\nwhat matters, and staying calm when things get tense. You're not easily\nrattled because you're not tracking all the catastrophes that might\nhappen—you're dealing with what's actually happening. This makes you\ninvaluable in crisis situations, hands-on roles, and any context\nrequiring steady competence under pressure.\n\nUnderstanding your profile means recognizing that your simplicity is a\nsuperpower, not a deficiency. You see clearly because you're not adding\nunnecessary layers.",
  "howYouLearn": "You learn by handling things, literally and figuratively. Give you the\ntheory and you'll ask for the practical application. Give you the\npractical application and you'll build the theory yourself through\ndirect experience. Abstraction without tangibility doesn't stick;\nlearning through doing becomes permanent.\n\nYour optimal learning environment is hands-on, immediate, and\nresults-oriented. You want to see the connection between what you're\nlearning and what you'll do with it, not in some hypothetical future,\nbut now. Apprenticeship models work well; abstract coursework less so.\n\nYou learn poorly from theoretical instruction disconnected from\napplication. Long lectures about concepts that might someday be useful\nfeel like time theft. You learn powerfully from immediate application\nwith tight feedback loops, do something, see the result, adjust, repeat.\n\nCase studies work only if they connect to immediate relevance.\nHistorical examples or future projections engage you less than \"here's\nwhat's happening now and here's how to handle it.\" Your learning is\noptimized for the practical, the present, and the actionable.",
  "howYouCommunicate": "You communicate directly, concretely, and efficiently. You say what you\nmean without excessive hedging or abstract framing. Others know where\nthey stand with you because you don't speak in codes or implications,\nyou say it straight.\n\nYou can be perceived as blunt or even dismissive when you cut through\nwhat you see as unnecessary complexity. What feels clarifying to you can\nfeel reductive to others who think in bigger concepts or longer\ntime horizons. The gap is real and bridging it requires\nrecognizing that others' complexity isn't always avoidable.\n\nIn meetings, you're the one who asks, \"what are we actually deciding\nhere?\" In conversations, you prefer clear topics and concrete outcomes\nover open-ended exploration. In conflict, you want to identify the\nactual problem and solve it rather than analyzing how everyone feels\nabout the problem.\n\nYou communicate best in situations requiring practical coordination,\nworking together on tangible tasks where clear communication has\nimmediate value. You communicate less effectively in contexts requiring\ntheoretical exploration, emotional processing, or long-term planning\ndiscussion.",
  "phrase": "You're not missing the bigger picture; you're focused on the part of\nthe picture that actually matters right now.",
  "secret": "You've watched people spin themselves into exhaustion over problems\nthat weren't actual problems. You've sat in meetings that took two\nhours to decide something obvious. You've listened to elaborate\ntheories about situations that just needed someone to do the thing. And\nyou've wondered, quietly, because saying it out-loud sounds arrogant,\nwhy everyone makes everything so complicated.\n\nThe secret is that you see through the noise. Not because you're\nsmarter, but because you don't add layers that aren't there. You see\nwhat's in front of you. You deal with what's happening. And usually\nthat's enough. More than enough.\n\nYou've probably solved problems in five minutes that others spent weeks\noverthinking. Not because you found a clever solution, because you found\nthe obvious one that everyone else was too busy theorizing to see. The\nanswer was right there. You just... saw it. And then you did it. While\neveryone else was still discussing frameworks.\n\nThere's a loneliness in this clarity. People don't always appreciate\nhaving their complexity cut through. They're attached to their\nelaborate analyses, their sophisticated concerns, their\nimportant-sounding deliberations. When you point out that something is\nsimple, it can feel dismissive to them, even when you're right.\nEspecially when you're right.\n\nYou've learned to stay quiet sometimes. To let people finish their\ncomplicated thoughts before you offer the simple path. To pretend you\nneeded to think about it longer than you did. It's a social tax you pay\nfor seeing clearly. The alternative, being seen as simplistic or\nunsophisticated, is worse. So you've carried this secret: that most\nthings aren't as hard as people make them, and you've always known\nthat.",
  "whatOthersGetWrong": "ABOUT YOU \n\nPeople confuse your simplicity with simple-mindedness. They assume that\nbecause you don't engage with elaborate theoretical frameworks, you\ncan't. They mistake your preference for directness as inability to\nhandle complexity. The opposite is true: you handle complexity by not\nadding to it unnecessarily.\n\nThey call you \"not a big-picture thinker\" when you're actually a\nclear-picture thinker. You see the picture fine. You just don't see the\npoint of adding pixels that aren't there. Their \"big picture\" often\nincludes projections, anxieties, and abstractions that obscure rather\nthan clarify. Your picture is accurate. Theirs is decorated.\n\nYou've been told to \"think bigger\" by people drowning in thoughts\nthat don't lead anywhere. You've been labeled \"too tactical\" by\nstrategists whose strategies never ship. You've been dismissed as \"not\nvisionary\" by visionaries who can't execute their way out of a paper\nbag.\n\nThe deepest misread is that you lack depth because you operate at\nsurface level. But the surface is where reality lives. The surface is\nwhere things happen. Your comfort at surface level isn't avoidance of\ndepth, it's recognition that depth without surface application is just\nintellectual entertainment.\n\nThey also assume that because you consider both sides, you don't have\nstrong opinions. You do. You just don't see the point of fighting about\nopinions when you could be solving problems. Your balance isn't\nweakness, it's efficiency. Why add conflict when collaboration gets to\nthe outcome faster?",
  "hiddenSuperpower": "**\n\nYou can stabilize any situation. When others are spiraling into\nabstraction, catastrophizing about futures, or lost in interpersonal\ncomplexity, you're the one who asks the question that brings everyone\nback: \"What are we actually doing right now?\" That question is more\npowerful than it sounds. It cuts through everything.\n\nYour superpower is presence—real presence, not performed mindfulness.\nYou're actually here, dealing with what's happening. This makes you\nthe calm center that others orbit when they start spinning out.\nYou don't have to try to be grounding. You just are.\n\nYou can see through false complexity to real simplicity. Where others\nsee ten interrelated problems, you see one problem wearing costumes.\nWhere others see impossible tradeoffs, you see obvious priorities\nthey've obscured with analysis. You read what's actually happening\nrather than reading interpretations of interpretations.\n\nYou're also genuinely versatile. Because you weigh both your own needs\nand others' fairly, you can work with people across the spectrum.\nYou don't have the",
  "blindSpot": "Your groundedness can become a ceiling. Some problems genuinely require\nabstract thinking, and your concrete orientation might dismiss\nconceptual approaches that would actually help. When someone says, \"we\nneed to think about this differently,\" your instinct to focus on\nwhat's tangible might close off perspectives you need.\n\nYou may also undervalue planning and future-orientation. Your\npresent-focus keeps you effective now, but \"now\" is always becoming\n\"later.\" The person worrying about next quarter isn't necessarily\nanxious, they might be appropriately preparing. Your comfort in the\npresent can become negligence about the future if you're not careful.\n\nYour tendency to consider both sides, while generally an asset, can\nbecome avoidance of necessary commitment. Sometimes situations require you to\nprioritize yourself strongly, or to prioritize others strongly. Your\ninstinct toward balance might keep you in a moderate position when an\nextreme position is actually correct. Not every situation calls for\nbalance; some call for advocacy.\n\nYou may also frustrate people who need more engagement with complexity\nthan you naturally provide. When they bring you something genuinely\ncomplicated and you offer a simple solution, they might feel unheard,\neven if your solution is right. The process of being understood matters\nto people, and your efficiency can skip steps they need.\n\nFinally, your clarity about what's real can become dismissiveness of\nwhat's felt. Emotions, intuitions, and concerns that don't map to\nconcrete present reality are still real to the people experiencing them.\n\"That's not actually a problem\" might be true and still be the wrong\nthing to say.",
  "frictionPatterns": "You clash with anyone who seems to be making things harder than they\nneed to be—which, from your perspective, is most people most of the\ntime. But the most intense friction comes with big-picture future\nthinkers who want to explore possibilities before committing to action.\n\nThey experience your groundedness as premature closure. You experience\ntheir abstraction as avoidance of reality. They want to think more; you\nwant to do it already. Neither is wrong—you're just operating at\ndifferent levels.\n\nDeep-past thinkers also challenge you. Their need to understand\nhistory before acting, to trace patterns, and to build theories feels\nlike unnecessary delay when the path forward is obvious. \"Why are we\nstill talking about this?\" is a question you ask internally more than\nyou should probably admit.\n\nYou may also frustrate people at either extreme of self-focus or\nother-focus. Very self-focused people find your balance wishy-washy;\nvery other-focused people find it insufficiently committed to the group.\nYour centered position looks like fence-sitting to people who've chosen\nsides. They want you to care more about yourself or about others, and\nyour steadiness reads as apathy.",
  "energyPatterns": "What Drains You:\n\n-   Theoretical debates that never resolve into action\n\n-   People who catastrophize about distant or unlikely futures\n\n-   Unnecessary process and bureaucracy\n\n-   Drama that could be avoided with simple directness\n\n-   Abstract frameworks applied to concrete problems\n\n-   Meetings about meetings\n\n-   Having to justify obvious decisions\n\n-   Complexity that serves no purpose\n\nWhat Charges You:\n\n-   Solving real problems in real-time\n\n-   Clarity and directness in communication\n\n-   Competence recognized and utilized\n\n-   Stripping away the unnecessary to reveal the essential\n\n-   Things that work the first time\n\n-   Collaborative action without excessive deliberation\n\n-   Environments where doing matters more than discussing\n\n-   The satisfaction of completion\n\n-   People who say what they mean and do what they say",
  "workEnvironments": "You thrive in environments with clear tasks, tangible outputs, and\nimmediate feedback. Operations, project management, skilled trades,\nemergency response—any role where competent execution is valued over\ntheoretical sophistication fits how you work.\n\nYou struggle in environments dominated by abstraction, speculation, or\nlong planning horizons. Strategy consulting, academic research, and\nroles requiring extensive work with concepts that never become concrete\nwill feel frustrating and misaligned.\n\nKey environmental factors: clear objectives, tangible deliverables,\naction orientation, minimal theoretical overhead, and colleagues who\nvalue practical competence over intellectual performance.",
  "blockIndicators": "Your Parser Profile suggests the following CBI block accessibility\npattern:\n\nLikely High-Accessibility Blocks:\n\n-   Perceptual Discrimination (concrete present focus)\n\n-   Sequential Processing (practical task execution)\n\n-   Social Signal Processing (balanced reference enables social reading)\n\nLikely Moderate-Accessibility Blocks:\n\n-   Spatial Relationships (practical, hands-on)\n\n-   Self-Reference Processing (balanced, accessible)\n\nLikely Lower-Accessibility Blocks:\n\n-   Pattern Recognition (across time; present-focus limits)\n\n-   Generative Creation (abstract ideation)\n\n-   Symbolic Manipulation (theoretical reasoning)\n\nThis pattern suggests you're naturally wired for practical\nproblem-solving and steady execution, with room to grow in abstract\nreasoning and recognizing longer-term patterns.\n\nGROUNDED",
  "strengths": [
    {
      "title": "Clarity Under Pressure When others are overwhelmed by complexity,",
      "description": "you maintain focus on what matters now. Crisis situations don't rattle\nyou because you're not projecting into worst-case futures, you're\nsolving the present problem. This makes you invaluable when things go\nwrong."
    },
    {
      "title": "Practical Simplification You have a gift for cutting through",
      "description": "noise to signal. Complex situations that paralyze others become\nmanageable when you identify the essential action. You're not\nsimplistic, you correctly distinguish between complexity that matters\nand complexity that doesn't."
    },
    {
      "title": "Consistent Performance You deliver steady, reliable results",
      "description": "because you're not distracted by what-ifs. Your output doesn't swing\nwith mood, speculation, or anxiety about the future. You show up and do\nthe work, day after day, without the variability that plagues more\nvolatile processors."
    },
    {
      "title": "Balanced Perspective Your balanced reference processing means you",
      "description": "naturally consider both personal and collective implications without\nextreme bias toward either. You can advocate for yourself while\nconsidering others, a combination that creates social effectiveness."
    },
    {
      "title": "Grounding Influence Your presence tends to stabilize others. When",
      "description": "you remain calm and focused, it gives others permission to do the same.\nYou're a natural anchor for teams, families, and any group that needs\nsomeone who isn't going to spin out."
    },
    {
      "title": "Efficient Decision-Making You make decisions with the information",
      "description": "available rather than waiting for perfect information that never\narrives. This prevents analysis paralysis and keeps things moving. Your\ndecisions may not be optimal, but they're usually good enough, and\nthey're made."
    }
  ],
  "challenges": [
    {
      "title": "Strategic Blindness*",
      "challenge": "Your present-focus can cause you to miss longer-term\nimplications of current actions. You solve today's problem without\nfully considering how that solution creates tomorrow's problem.\nStrategic thinking requires temporal extension that doesn't come\nnaturally.",
      "remedy": "Build in a \"then what?\" check. After solving the immediate\nproblem, force one question: \"What does this create six months from\nnow?\" You don't need to live in the future, just visit briefly. One\ndeliberate projection per decision catches most strategic blind spots\nwithout pulling you out of your effective present-focus."
    },
    {
      "title": "Abstract Reasoning Gaps",
      "challenge": "Purely theoretical or conceptual challenges can frustrate\nyou. When there's no concrete handle to grab, you may struggle to\nengage. This can limit your effectiveness in domains that require\nworking with abstractions.",
      "remedy": "Demand examples. When facing abstract content, ask: \"What\ndoes this look like in practice?\" Translate theory into scenarios you\ncan visualize. You're not failing to understand; you're requiring\ninformation in a format your architecture processes. Most abstractions\nhave concrete manifestations; insist on seeing them."
    },
    {
      "title": "Over-Simplification",
      "challenge": "Sometimes situations genuinely are complex and simplifying\nthem loses important information. Your gift for cutting through can\nbecome a liability when the \"noise\" you're cutting is actually\nsignal.",
      "remedy": "Test your simplification. Before acting on your streamlined\nversion, check: \"What am I leaving out? Would someone who sees this\ndifferently think that matters?\" Run your simple solution past someone\nwho processes with more complexity, not to adopt their complexity, but\nto verify you haven't cut something essential."
    },
    {
      "title": "Patience with Process",
      "challenge": "You can become frustrated with discussions, planning, and\nprocesses that don't seem to lead to immediate action. This impatience,\nwhile often justified, can cause you to overlook the value in\npreparation and deliberation.",
      "remedy": "Reframe process as reconnaissance. Deliberation surfaces\nobstacles you'd otherwise hit during execution. Questions reveal gaps.\nDisagreements flag implementation risks. The discussion isn't delaying\naction; it's making action more effective. Ask yourself: \"What might I\nlearn here that prevents rework later?\""
    },
    {
      "title": "Emotional Depth Access",
      "challenge": "Your practical focus can make it hard to engage with\nemotional complexity, your own or others'. When feelings don't\ntranslate into actionable problems, you may struggle to know what to do\nwith them.",
      "remedy": "Treat emotions as data, not problems. You don't need to solve\nfeelings, just acknowledge them. Practice naming emotions (yours and\nothers') without immediately moving to action. Sometimes presence is\nthe action. \"That sounds frustrating\" is doing something, even if it\ndoesn't feel productive to you."
    },
    {
      "title": "Innovation Resistance",
      "challenge": "Your present-concrete focus may make you skeptical of new\napproaches that don't have immediate, tangible benefits. You might miss\nvaluable innovations because they require investment in abstract\npotential.",
      "remedy": "Create an innovation sandbox. Designate small, low-risk spaces\nwhere you try new approaches just to gather data. Not commitment,\nexperimentation. Your skepticism is warranted, but it should follow\nevidence, not precede it. Let small tests generate the concrete results\nyou need to evaluate fairly.\n\n*"
    }
  ]
};
