// HARMONIOUS Profile — Young Adult (18–29)
// Parser Profile™ © 2026 Cognition Blocks LLC

export const harmoniousyaProfile = {
  "name": "HARMONIOUS",
  "tagline": "The one who sees how everyone could actually win",

  "overview": "Two friends are fighting and they've both already texted you separately, sure the other one is the problem. Everyone's picked a side. The group chat's split. And you're sitting there seeing the thing neither of them can see right now: there's a version of this where they both get heard and nobody has to be the bad guy. Not because you're naive. Because you can actually picture it.\n\nWhere everyone else sees somebody-wins-somebody-loses, you see a fit that just hasn't been found yet. The roommate who wants quiet and the one who wants people over. The job that pays versus the one you'd love. To everyone else those are dead ends. To you they're puzzles with an answer nobody's landed on. You're the person still asking \"wait, what if we could do both?\" after the room already gave up.\n\nYour head moves easily between the dream and the steps. You can hold the picture of how it could all work and also get specific about how you'd actually pull it off. You're not floating in pure idealism, and you're not stuck in \"that's just not realistic.\" You can do the vision and the to-do list.\n\nYou look forward more than back. Not anxiously—curiously. What's coming? What could this turn into? How could these pieces line up better than they do now? Right now matters to you mostly as raw material for what's next.\n\nPeople have called you the optimist, the peacemaker, the one who keeps the group together. That's all real, but it misses what's underneath. You're not hopeful because you ignore the problems. You're hopeful because you can see the way through that other people can't.",

  "howYouLearn": "Learning sticks for you when it clicks into a bigger picture. A random fact with nothing attached to it just slides off. But show you how this piece connects to that piece, how it feeds into something larger you're building toward, and you soak it up.\n\nYou need the idea and the real-world version of it. Give you only the theory and you immediately want to know how it actually plays out. Give you only the how-to and you want the why underneath. You learn best when a class or a job gives you both—the concept and the thing it turns into. The stuff that connects different subjects, that shows how it all fits, lights you up most.\n\nFuture-payoff keeps you going. You'll grind through something that doesn't matter yet if you can feel how it serves the thing you're heading toward. \"This'll matter eventually\" actually works on you, as long as you can feel the line to that eventually—which is not true for everybody.\n\nWatch for one thing, though: your eagerness to get to the big connected picture can make you rush past the boring foundations. Sometimes you have to actually learn the parts before you can do the cool synthesis of the whole. Sitting with the basic stuff a little longer pays off later in a richer version of exactly the connections you love.",

  "howYouCommunicate": "You talk in a way that connects things. You naturally link people's ideas, frame a situation so it includes more than one side, point at a future where the competing wants don't have to compete. People often feel like you just said the thing that pulled it all together.\n\nYou adapt to who you're talking to. You can get concrete with the friend who needs specifics and stay big-picture with the one who likes frameworks—because you've got access to both modes yourself, so you translate between them without thinking about it.\n\nYou tend to talk in possibilities. \"What if we could...\" and \"I can kind of see how this might...\" are just how you frame things. It inspires people and it also sometimes frustrates them—they want you to just pick a side already, and you're still exploring the both-and.\n\nIn a conflict you move toward fixing it—sometimes too fast. The thing to practice is staying in the awkward unresolved part a little longer. Sometimes a friend needs to feel fully heard before they can even get to the compromise, and your rush to smooth it over can cut that off before they've said the whole thing.",

  "phrase": "You're not naive. You're seeing the option everyone else stopped looking for. Your optimism isn't you missing the problem—it's you seeing wider than the room.",

  "secret": "Sometimes the whole \"how can everyone win\" thing is a way of dodging a messier truth: you don't actually know what you want.\n\nBeing the balanced one feels like a gift—you can hold everyone's side, find the fit that works for all of them. But underneath it is a question you sometimes can't answer: what do you want? Not what compromise keeps the peace. Not what works for the group. What do you, just you, separate from everyone else, actually want for yourself?\n\nWhen you're always busy figuring out how everyone can be okay, you can skip the harder, scarier work of knowing what okay looks like for you specifically. Keeping the peace becomes a place to hide from your own opinion. \"I'm happy with whatever works for everyone\" sounds generous, and sometimes it's quietly covering \"I have no idea what I actually want.\"\n\nDeeper than that: imagining a future where nobody has to choose lets you avoid choosing right now. If you can picture a version where you get to keep both the major and the dream and the relationship and the move, you don't have to grieve giving one of them up. Your hope about it all working out is sometimes really just fear of losing something.\n\nAnd deepest: you sometimes worry that always being the flexible one leaves you kind of shapeless. The friends with strong opinions and a clear direction seem more solid than you feel. They know what they want. They'll fight for it. They have edges. Your in-between-ness sometimes feels like having no edges at all.\n\nNone of this makes your gift fake. It just means it's doing two jobs at once—part of it real, part of it protecting you. Telling those apart is your work.",

  "whatOthersGetWrong": "They think your optimism is naive. They see you reaching for the version where it all works out and decide you must not get how hard things actually are. They figure you've got rose-colored glasses on, missing the real conflict they see so clearly.\n\nWhat they miss is that you see the hard part too—you're just not stopping there. Your hope isn't you pretending the problem isn't real; it's you not letting the problem be the end of the story. You know the obstacles. You just refuse to call them the final answer.\n\nThey think because you see every side, you don't actually believe in anything. Your refusal to instantly pick a team reads to them like you have no opinion, like you're just sitting on the fence. They don't get that holding multiple sides at once is its own position—and a harder one than just picking one and digging in.\n\nSome people think because you want peace, you're scared of conflict. Sometimes they're right. But often they're wrong—you're not avoiding the fight, you're looking past it to the part where it actually gets resolved, which takes more nerve than just yelling from your corner.\n\nAnd they think your future-focus means you're checked out of right now. They don't see how picturing where it could go is exactly what helps you deal with the messy present—because you can see where this all might actually lead.",

  "hiddenSuperpower": "You can hold two opposite things being true without it breaking you.\n\nMost people need everything to line up. When they hit two truths that genuinely clash—your friend was wrong AND also got hurt, you love the city AND need to leave it—they fix the discomfort by just picking one. They flatten it into a clean side. They make it simple so they can stop feeling the tension.\n\nYou don't have to do that. Your wiring lets you sit with \"this is true and the opposite thing is also true\" without your brain demanding you choose. You can stand in the ambiguity that makes other people rush to slam a door.\n\nThat's worth a lot, because most of the real situations in your twenties are exactly this—two real wants that both matter, two people who are both kind of right, a choice with no clean answer. Being the one who can stay in that long enough for an actual third option to show up is rare.\n\nYour superpower isn't finding the easy answer. It's staying with the hard question long enough for a real answer to appear. While everyone else is defending their take, you're still in the space looking. Sometimes there's no fit to find—but way more often than people think, there is one. And you're the one who finds it, because you didn't quit looking when everyone else did.",

  "blindSpot": "You might not notice when keeping everyone happy quietly costs you.\n\nYou do consider yourself in the mix—you're not a total pushover. But when the compromise needs someone to give ground, you're often the one who volunteers. \"I'm easy, I'll go with whatever\" slowly turns into \"I'll be the one who eats the cost again.\" Do that enough and you end up drained, a little resentful, and honestly unsure what you even wanted in the first place.\n\nWatch for it: the situations where you're always the one who adjusts. The plans that somehow always bend around your schedule, your money, your comfort, more than anyone else's. The slow feeling that your needs are just the ones that quietly yield so things stay smooth.\n\nAlso watch for this: getting attached to being the peacekeeper. If \"I'm the one who keeps everyone together\" is central to who you think you are, you'll resist the times when the actually-healthy move is to hold your ground and let someone else bend for once. Sometimes the most harmonious thing you can do is just clearly say what you want and let everyone else adjust around it—but that doesn't feel like \"you.\"\n\nYour blind spot isn't the gift itself. It's the assumption that you always have to be the one who flexes. Sometimes the group needs your clarity way more than your flexibility.",

  "frictionPatterns": "You'll bump up against the very concrete, been-there-done-that people while you're looking at how it could be. Their \"this is just how it actually works\" hits your \"yeah, but here's how it could work better.\" Their certainty from experience meets your hope built on possibility, and you talk right past each other.\n\nYou'll also struggle with the super present-focused friend who just wants to deal with what's real right now instead of what could be. Your eyes-on-the-future thing can feel like avoidance to them; their stay-in-the-now thing can feel like a ceiling to you.\n\nAnd the people who are all-the-way on one side—all about themselves, or all about the group—can read your balance as you not being committed, while you read their hard stance as them limiting themselves for no reason.\n\nWhat you bring to all that: you can almost always find the real, fair point inside the other person's position, and that's the door that lets a stuck thing open back up.\n\nYour growth edge: noticing that sometimes holding your own line firmly actually serves the peace better than scrambling for a compromise. Your flexibility is genuinely valuable—it just shouldn't be automatic, or it stops being a choice.",

  "energyPatterns": "What drains you:\n- Situations where it's genuinely somebody-loses and there's no fit to find\n- Being forced to pick a side when you can see both are kind of right\n- Short-term thinking that blocks building anything better\n- People writing off your hope as you just being naive\n- Being the one who always bends, then having it taken for granted\n- Conflict that just loops and never actually resolves\n\nWhat charges you:\n- Finding the fit everyone swore was impossible\n- Groups and jobs where your knack for connecting things is actually wanted\n- Longer projects building toward a future that includes everybody\n- Conversations that explore what could be instead of defending positions\n- Being the one who introduces people and watches something click\n- Watching two people who were stuck actually find their way back to each other",

  "workEnvironments": "Where you thrive:\n- Places that value bringing people together and thinking longer-term\n- Coordinating, facilitating, planning, anything with lots of moving people\n- Roles where you have to balance what different people need\n- Work where holding multiple perspectives at once is the actual skill\n- Teams that reward finding the third option instead of just picking a side\n\nWhere you suffocate:\n- Rigid this-or-that thinking with no room for both\n- Constant drama that never resolves\n- Cliquey or political spots where who-you-know beats solving the problem\n- Pressure to commit to a position before you've explored the options\n- Any place that punishes nuance and wants a quick, simple side picked",

  "topCareers": [
    {
      "title": "Coordinator / Program Assistant",
      "description": "Where everyone else accepted the tradeoff and picked a side, you're still seeing the setup that works for more people than they thought possible—not naively, but because you can actually see it. Coordinating and program work rewards exactly that: holding a bunch of competing needs as a puzzle with an unfound answer instead of a dead end. You keep the project moving toward something better without flattening anyone's stake in it. The \"what if we could do both\" that frustrated either/or rooms becomes, in this work, the whole point of the job."
    },
    {
      "title": "Community / People Operations Roles",
      "description": "You hold a lot of perspectives at once and build toward something that fits more of them than people expected. Entry-level community and people-ops work pays for exactly that connecting move—getting a roommate-level standoff scaled up to a whole team or group to a place none of them had found alone. You're the one still looking for the fit after everyone else stopped. The nuance that rigid places punish becomes, here, the thing that unsticks the stuck situation everyone else gave up on."
    },
    {
      "title": "Mediation / Conflict Resolution Track",
      "description": "You see how it could all fit together, across sides and across time, and you don't accept somebody-has-to-lose as the final word. Entry-level mediation and conflict-resolution work is built for that balancer's mind—honoring what each side actually needs while building toward something better for everyone. You hold a bunch of viewpoints without collapsing into one, which is exactly why people who disagree end up trusting where you're steering things. The refusal to instantly pick a winner that got read as indecision is the precise thing that lets you broker the deal nobody else could."
    }
  ],

  "blockIndicators": "Your Parser Profile suggests the following CBI block accessibility pattern:\n\nLikely High-Accessibility Blocks:\n- Pattern Recognition (seeing integrative patterns across people and situations)\n- Spatial Relationships (mapping how the pieces could fit together later)\n- Social Signal Processing (balanced reference gives access to group dynamics)\n\nLikely Moderate-Accessibility Blocks:\n- Sequential Processing (accessible for actually planning the steps)\n- Symbolic Manipulation (working with frameworks and ideas)\n- Self-Reference Processing (available but balanced with attention to others)\n- Generative Creation (imagining how it could all come together)\n\nLikely Lower-Accessibility Blocks:\n- Perceptual Discrimination (the right-now sensory detail gets less attention than the future picture)\n\nThis pattern suggests your cognitive architecture is optimized for connecting people and ideas and finding the fit others gave up on. Your room to grow is in present-moment grounding—getting comfortable with what is before reaching for what could be—and in getting clear on what you actually want when the harmonious move is to hold your ground instead of bend.\n\nHARMONIOUS",

  "strengths": [
    {
      "title": "Seeing the Both-And",
      "description": "You can see how two wants everyone called incompatible could actually fit. Where the group sees somebody-wins-somebody-loses, you see a setup that honors more than one side at once. That's rare, and it's worth a lot in basically any messy situation."
    },
    {
      "title": "Holding Everyone's Side",
      "description": "Your balanced wiring lets you genuinely hold what different people need, want, and fear all at once without collapsing into any single one. You can sit with all of it and look for the version that addresses the whole range. That makes you the one people trust to mediate when it gets tense."
    },
    {
      "title": "Vision Plus the Steps",
      "description": "You can work at the level of the dream and the level of the actual to-do list. You're not stuck in pure idealism or grinding pragmatism—you move between them. That lets you turn a big fuzzy goal into concrete steps that actually move toward it."
    },
    {
      "title": "Hope That Isn't Naive",
      "description": "Your eyes-forward thing plus your knack for connecting creates real optimism that isn't fake. You're not hopeful because you ignore the problems—you're hopeful because you can see the fixes other people miss. That energy carries you, and it lifts the people around you too."
    },
    {
      "title": "Playing the Long Game",
      "description": "Because you're looking ahead, you can put up with things not being perfect right now. You get that the thing you're building takes time to come together. That patience lets you keep going through the stretches where nothing's showing yet and everyone else has quit."
    },
    {
      "title": "Connecting People and Ideas",
      "description": "You naturally link people, ideas, and possibilities that others keep in separate boxes. You speak a few different cognitive languages, and you're always looking for how things could connect. You're the bridge—the one who introduces, translates, and pulls a scattered group together."
    }
  ],

  "challenges": [
    {
      "title": "Smoothing It Over Too Fast",
      "challenge": "Your drive to fix it can push you to resolve a fight before it's even been fully said out loud. You might smooth over a conflict that actually needed to surface, or jump to the compromise before either friend felt heard.",
      "remedy": "Practice staying in the tension longer than feels okay. Before you offer the fix, make sure each side has actually been said and genuinely heard. A compromise that skips the real argument isn't peace—it's avoidance. The fit you find after truly hearing everyone holds up way better."
    },
    {
      "title": "Skipping Over Right Now",
      "challenge": "Your eyes-forward thing can make you breeze past what's actually happening now in favor of what could be. You might shrug off a present problem because you're focused on the future fix, or miss what's genuinely good now because you're already seeing how it could be better.",
      "remedy": "Deliberately schedule being present. Block time where you're not optimizing or planning or connecting anything—just experiencing what is. Looking ahead is a strength; setting it down sometimes keeps it from quietly disconnecting you from your actual life as it's happening."
    },
    {
      "title": "Can't Just Pick",
      "challenge": "Because you genuinely see something valid in every option, choosing can feel like betrayal. You might put off a decision forever—the major, the apartment, the relationship—still hunting for the version where you don't have to give anything up at all.",
      "remedy": "Accept that some choices are genuinely either/or, and making one doesn't mean you failed at finding the fit. Not everything has a both-and. Sometimes you have to choose, and choosing doesn't mean the other option was worthless. Build the muscle of deciding even while you can still see the good in what you didn't pick."
    },
    {
      "title": "Peacekeeping as Hiding",
      "challenge": "Your whole how-can-everyone-win thing can quietly become a fancy way of avoiding conflict. If you're always finding the compromise, you might be unable to handle the times someone has to lose—including the times that someone should be you standing up for yourself.",
      "remedy": "Look honestly at your relationship with conflict. Are you finding the compromise because it's genuinely there, or because you can't stand the discomfort of just disagreeing? Sometimes the actually-healthy move is to hold your ground and let there be friction that leads to a real repair instead of a fake, smoothed-over peace."
    },
    {
      "title": "Some Things Are Just Win-Lose",
      "challenge": "Some situations really are somebody-wins-somebody-loses. The money's finite, the two plans genuinely can't both happen, one person's yes is another's no. Your hope can blind you to that and keep you searching for a fit that isn't actually there.",
      "remedy": "Build the radar for which situations can actually integrate and which can't. Ask: \"Is there genuinely a version that works for everyone here, or am I just hoping for one so I don't have to face a hard tradeoff?\" Your gift works best aimed at the situations where a real fit is actually possible."
    },
    {
      "title": "All Vision, No Follow-Through",
      "challenge": "You can see the harmonious version super clearly—but seeing it and building it are different jobs. Building it means grinding through the unglamorous present-moment execution, and that's the part that's easy for you to let slide.",
      "remedy": "Team up with people who finish things, or build that finishing muscle yourself. The fit you can see isn't real until it's actually built, and building takes different skills than seeing. Either develop those on purpose or partner with someone who already has them."
    }
  ]
};
