// HARMONIOUS Profile
// Parser Profile™ © 2026 Cognition Blocks LLC
// Balanced • Future • Balanced

export const harmoniousProfile = {
  "name": "HARMONIOUS",
  "code": "Balanced • Future • Balanced",
  "tagline": "The one who sees how everything could fit together",

  "overview": "You see the integration that others have stopped looking for. When they've accepted the tradeoff, declared the conflict irreconcilable, chosen sides—you're still holding space for a configuration that honors everyone. Not because you're naive. Because you can actually see it.\n\nWhere others perceive zero-sum, you perceive synthesis waiting to be discovered. The competing needs, the opposing values, the irreconcilable differences—these register to you as puzzles with solutions that haven't been found yet, not permanent limitations. You're the person in the room still asking \"what if we could have both?\" when everyone else has moved on.\n\nYour thinking flows naturally between practical and conceptual. When you imagine how things could work together, you can hold the vision and also see the concrete steps. You're not lost in idealistic abstraction—you can get specific about implementation. And you're not trapped in pragmatic limitation—you can see possibilities beyond current constraints.\n\nYour attention orients toward futures. Not anxiously—curiously. What's coming? What could be? How might all these pieces align differently than they do now? The present matters to you as raw material for what's next, and you're constantly scanning for the configurations that could emerge.\n\nYour reference point balances self and other. You're not sacrificing yourself for collective outcomes or ignoring everyone else to pursue personal goals. You're looking for futures where your needs and their needs aren't in competition—where individual flourishing and collective flourishing align. You believe these configurations exist because you can see them.\n\nPeople have called you an optimist, a peacemaker, a big-picture thinker. These descriptions capture something real, but they miss the cognitive architecture underneath. You're not optimistic because you ignore problems. You're optimistic because you see integrative solutions that others can't perceive.",

  "howYouLearn": "Learning lands for you when it fits into a larger integrated picture. Isolated facts without connection to broader frameworks struggle to engage you. But show you how a piece connects to other pieces, how it contributes to something larger, and you'll absorb it readily.\n\nYou need both the theory and the application. Give you only concepts and you'll want to know how it works in practice. Give you only technique and you'll want the underlying principle. You integrate best when learning includes both—understanding that bridges the abstract and concrete.\n\nFuture-relevance motivates you. You're willing to learn things that won't apply immediately if you can see how they serve something you're building toward. \"This will matter eventually\" works for you in ways it doesn't for present-focused learners, as long as you can feel the connection to that eventual mattering.\n\nYou may find that you learn particularly well when you can see how different domains connect. Interdisciplinary content, systems thinking, anything that shows relationships between fields—this engages your integrative architecture. You're not seeking mastery of a single domain; you're seeking understanding of how domains relate.\n\nBe aware that your future-focus might cause you to rush past foundational learning in your eagerness to get to integration. Sometimes you need to master the parts before you can synthesize the whole. Patience with component learning pays off in richer eventual integration.",

  "howYouCommunicate": "You communicate in ways that connect and integrate. You naturally link ideas, perspectives, and possibilities in your speech. Others may experience this as synthesizing—you draw connections they hadn't seen, frame situations in ways that include multiple viewpoints, point toward futures that accommodate different needs.\n\nYour adaptability shows in how you speak. You can get concrete with people who need specifics and stay conceptual with those who prefer frameworks. You translate between cognitive styles because you have access to multiple styles yourself.\n\nYou probably speak in terms of possibility. \"What if we could...\" and \"I can see how this might...\" are natural framings. This can inspire and also frustrate—others may want you to commit to positions rather than perpetually explore integrations.\n\nYou share your perspective and attend to others' perspectives. You're not dominating conversations with your vision or disappearing into pure listening. You hold space for both, which creates a sense of mutuality in your communication.\n\nIn conflict, you naturally move toward resolution—sometimes too quickly. Practice staying in the dissonance of unresolved disagreement rather than rushing to propose synthesis. Others sometimes need their position fully heard before they can move toward integration; your eagerness to harmonize can short-circuit that process.",

  "phrase": "You're not naive. You're seeing possibilities that others have stopped looking for. Your optimism isn't blindness—it's wider vision.",

  "secret": "Sometimes your vision of harmony is a way of avoiding the messier truth that you don't know whose side you're on.\n\nYour balanced reference feels like a gift—you can hold multiple perspectives, see validity everywhere, find integration that honors all needs. But underneath that gift is sometimes a question you can't answer: What do you actually want? Not what synthesis works for everyone. Not what integration satisfies all parties. What do you, yourself, independent of everyone else's needs, actually desire?\n\nWhen you're always looking for how everyone can win, you may be avoiding the confronting work of knowing what winning means for you specifically. Harmony becomes a hiding place from the clarity of your own position. \"I want what works for everyone\" sounds noble but can mask \"I don't know what I want for myself.\"\n\nDeeper: sometimes your vision of integrated futures is fantasy specifically because it lets you avoid present choices. If you can imagine a future where you don't have to choose between competing goods, you don't have to make the sacrifice that choosing would require. Your optimism about synthesis might be motivated by fear of loss.\n\nAnd deeper still: you may suspect that your harmonious orientation makes you somewhat shapeless. People with clear positions, strong preferences, and definite directions seem more real than you feel. They know what they want. They're willing to fight for it. They have edges. Your integration sometimes feels like absence of edges—valuable for bridging, but leaving you without clear definition.\n\nThis doesn't mean your integrative capacity is false. It means it may be serving multiple functions—some generative, some protective. Knowing the difference is your growth work.",

  "whatOthersGetWrong": "They assume your optimism is naive. They see your orientation toward positive futures and integrative solutions and conclude you must not understand how hard things really are. They think you're wearing rose-colored glasses, missing the genuine conflicts and real constraints that they see so clearly.\n\nWhat they miss is that you see the difficulties too—you're just not stopping there. Your optimism isn't denial of problems; it's continued search past problems toward solutions. You understand the obstacles. You're just not letting them be the end of the story.\n\nThey assume your balanced perspective means you lack conviction. Because you can see validity in multiple positions, they think you must not really believe anything yourself. Your integration looks like indecision, your bridge-building looks like fence-sitting. They don't understand that holding multiple perspectives is itself a position—and a demanding one.\n\nSome assume that because you seek harmony, you're afraid of conflict. They think your orientation toward integration is avoidance dressed as wisdom. And sometimes they're right. But often they're wrong—you're not avoiding conflict, you're looking past it toward resolution. The path through conflict toward integration requires more courage than simply fighting from an entrenched position.\n\nAnd they assume your future-focus means you're disconnected from present reality. They think you're lost in possibility, unable to deal with what is. They don't see how your vision of future integration actually helps you engage more effectively with present complexity—because you can see where it might lead.",

  "hiddenSuperpower": "You can hold contradictions that break other people.\n\nMost people need coherence. When they encounter genuinely conflicting truths—values that oppose, needs that compete, goods that exclude each other—they resolve the tension by choosing sides. They collapse the paradox into a position. They simplify complexity into manageability.\n\nYou don't have to do that. Your balanced architecture lets you hold multiple truths simultaneously without forcing premature resolution. You can say \"this is true AND this opposing thing is also true\" without your cognitive system demanding that you pick one. You can tolerate the ambiguity that drives others to hasty closure.\n\nThis capacity is extraordinarily valuable in a complex world. Most important situations involve competing goods, legitimate opposing needs, irreconcilable values that must somehow be honored together. Leaders who can hold this complexity without collapsing it, who can stay in the paradox long enough for creative response to emerge, are rare and essential.\n\nYour superpower isn't finding easy answers. It's staying with hard questions long enough for genuine answers to emerge. While others are defending positions, you're still exploring the space. While they've stopped looking for integration, you're still searching. Sometimes there's no integration to find, but sometimes there is—and you find it because you didn't stop looking when others did.\n\nThe futures you imagine, where competing needs find mutual satisfaction, aren't always possible. But they're possible more often than most people assume. And you're the one who finds them because you're the one who's still looking.",

  "blindSpot": "You may not recognize when your pursuit of harmony serves others at your own expense.\n\nYour balanced reference frame includes self-consideration—you're not purely self-sacrificing. But when integration requires someone to give ground, you may habitually volunteer yourself. \"I can be flexible\" becomes code for \"I'll absorb the cost of this compromise.\" Over time, this pattern can leave you depleted, resentful, and unclear about your own needs.\n\nWatch for: recurring situations where you're the one who accommodates. Integrations that somehow always require your flexibility more than others'. A pattern of feeling that your needs are systematically the ones that yield to make harmony possible.\n\nAlso watch for: attachment to your identity as the integrator. If being the bridge-builder is central to how you see yourself, you might resist situations where the harmonious move is to hold your ground and let others do the bridging. Sometimes the most integrative thing you can do is clearly assert your own position and let the system integrate around it—but that doesn't feel like \"you.\"\n\nYour blind spot isn't your integrative capacity itself. It's the assumption that integration must be led by you or shaped by your flexibility. Sometimes harmony requires you to be the immovable point around which others adjust. Sometimes the system needs your clarity more than your flexibility.",

  "frictionPatterns": "You'll clash with people anchored in concrete past experience while you're oriented toward integrated futures. Their \"this is how it actually works\" meets your \"but here's how it could work better.\" Their experience-based certainty meets your possibility-based optimism.\n\nYou'll also struggle with heavily present-focused profiles who want to deal with what is rather than what could be. Your future-orientation may feel like avoidance to them; their present-focus may feel like limitation to you.\n\nAnd you'll find friction with those heavily positioned on either self or other dimensions—they may see your balance as lack of commitment, while you see their positioning as unnecessary limitation.\n\nYour gift in these frictions: You can usually find genuine validity in the other position, which opens doors for connection.\n\nYour growth edge: Recognizing that sometimes holding your own position firmly serves integration better than searching for compromise. Your flexibility is valuable; it shouldn't be automatic.",

  "energyPatterns": "What drains you:\n- Chronic zero-sum environments where integration is genuinely impossible\n- Being forced to choose sides when you see validity in both\n- Short-term thinking that prevents investment in better futures\n- Cynicism that dismisses your optimism as naive\n- Situations where your bridge-building is exploited rather than honored\n\nWhat charges you:\n- Finding integrations that others said were impossible\n- Environments where your synthesizing capacity is valued\n- Long-term projects building toward futures that include everyone\n- Conversations that explore possibility rather than defend positions\n- Witnessing genuine resolution of what seemed irreconcilable",

  "workEnvironments": "Where you thrive:\n- Environments that value integration and long-term thinking\n- Strategy, facilitation, organizational development, diplomacy, mediation\n- Roles requiring multi-stakeholder consideration and complex synthesis\n- Systems design and any role holding multiple perspectives while building toward better futures\n\nWhere you suffocate:\n- Rigid either/or thinking and short-term orientation\n- Chronic conflict that can't resolve\n- Political environments where positioning matters more than problem-solving\n- Any context that punishes nuanced thinking",

  "topCareers": [
    {
      "title": "Strategy / Systems Designer",
      "description": "Where others have accepted the tradeoff and chosen sides, you're still seeing the configuration that honors everyone—not naively, but because you can actually see it. Strategy and systems design reward that: holding competing needs as a puzzle with an unfound solution rather than a permanent limitation. You synthesize toward a better future without flattening anyone's stake in it. The \"what if we could have both\" that frustrated either/or rooms is, in this work, the entire creative act."
    },
    {
      "title": "Organizational Development / Facilitation",
      "description": "You hold multiple perspectives at once and build toward a future that fits more of them than people thought possible. Organizational development and facilitation pay for exactly that integrative move—getting stakeholders who'd declared the conflict irreconcilable to a configuration none of them had found. You're the one still looking for synthesis after everyone else stopped. The nuance that rigid environments punished becomes, here, the thing that unlocks the stuck system."
    },
    {
      "title": "Diplomat / Mediator",
      "description": "You see how everything could fit together, across sides and across time, and you don't accept zero-sum as the final word. Diplomacy and mediation are built for that balancer's mind—honoring competing values while building toward something better for all of them. You hold many viewpoints without collapsing into one, which is why opposed parties trust where you're steering. The refusal to pick a winner that read as indecision is exactly what lets you broker the thing nobody else could."
    }
  ],

  "blockIndicators": "Your Parser Profile suggests the following CBI block accessibility pattern:\n\nLikely High-Accessibility Blocks:\n- Pattern Recognition (seeing integrative patterns across domains and stakeholders)\n- Spatial Relationships (mapping how pieces fit together in future configurations)\n- Social Signal Processing (balanced reference gives access to interpersonal dynamics)\n\nLikely Moderate-Accessibility Blocks:\n- Sequential Processing (accessible for implementation planning)\n- Symbolic Manipulation (working with frameworks for integration)\n- Self-Reference Processing (available but balanced with other-reference)\n- Generative Creation (imagining integrative futures)\n\nLikely Lower-Accessibility Blocks:\n- Perceptual Discrimination (present-moment sensory detail may be less attended than future-oriented perception)\n\nThis pattern suggests your cognitive architecture is optimized for integrative strategy and multi-stakeholder synthesis. Your developmental opportunities lie in present-moment grounding—building comfort with what is before reaching for what could be—and in clarity about your own distinct position when integration requires you to hold ground rather than bridge differences.\n\nHARMONIOUS",

  "strengths": [
    {
      "title": "Integrative Vision",
      "description": "You can see how apparently competing needs could be reconciled. Where others see zero-sum conflict—my interests versus yours, this priority versus that one—you see potential configurations that could honor multiple values simultaneously. This integrative capacity is rare and valuable in any complex situation."
    },
    {
      "title": "Multi-Stakeholder Thinking",
      "description": "Your balanced reference frame lets you hold multiple perspectives without collapsing into any single one. You can genuinely consider what different people need, want, and fear, then search for futures that address the full range. This makes you valuable in negotiation, strategy, and any context requiring consideration of diverse interests."
    },
    {
      "title": "Flexible Implementation",
      "description": "Your balanced processing means you can work at the level of vision and the level of action. You're not stuck in abstract idealism or grinding pragmatism—you can move between them. This lets you translate big-picture synthesis into concrete steps that actually move toward it."
    },
    {
      "title": "Constructive Optimism",
      "description": "Your future-orientation paired with integrative thinking creates genuine optimism that isn't naive. You're not optimistic because you ignore problems—you're optimistic because you can see solutions that others miss. This constructive optimism energizes you and often inspires others."
    },
    {
      "title": "Long-Game Patience",
      "description": "Because you're oriented toward future integration, you can tolerate present imperfection. You understand that the synthesis you're working toward takes time to construct. This patience lets you sustain effort through periods when the vision isn't manifesting, when progress is invisible, when others have given up."
    },
    {
      "title": "Bridge-Building Capacity",
      "description": "You naturally connect people, ideas, and possibilities that others keep separate. Your balanced processing lets you speak multiple cognitive languages; your future-focus keeps you looking for how things could connect. You're a natural translator and connector across differences."
    }
  ],

  "challenges": [
    {
      "title": "Premature Harmony",
      "challenge": "Your drive toward integration can push you to resolve tensions before they've been fully understood or expressed. You might smooth over conflict that needs to surface, propose synthesis before positions have been clearly articulated, or rush to \"both/and\" before either side has been honored.",
      "remedy": "Practice staying in tension longer than is comfortable. Before offering integration, make sure each position has been fully expressed and genuinely understood. Synthesis that skips the thesis and antithesis isn't harmony—it's avoidance. The integration you find after truly hearing all sides will be more robust than premature resolution."
    },
    {
      "title": "Present-Moment Bypass",
      "challenge": "Your future-orientation can cause you to skip over current reality in favor of imagined possibility. You might minimize present problems because you're focused on future solutions, or fail to appreciate what's working now because you're already seeing how it could be better.",
      "remedy": "Schedule deliberate present-focus. Build in time where you're not working toward anything, not optimizing, not integrating—just experiencing what is. Your future-orientation is a strength; occasionally setting it aside prevents it from becoming a compulsion that disconnects you from life as it's actually happening."
    },
    {
      "title": "Decision Paralysis",
      "challenge": "Your balanced perspective means you can genuinely see validity in multiple positions. This is a gift for understanding, but it can become a trap for deciding. When you see merit everywhere, choosing feels like betrayal. You might defer decisions endlessly while searching for the integration that lets you avoid choosing at all.",
      "remedy": "Accept that some decisions are genuinely zero-sum, and making them doesn't make you a bad integrator. Not every situation has a synthesis; sometimes you must choose, and choosing doesn't mean the unchosen option lacked merit. Build the muscle of deciding despite seeing validity on all sides."
    },
    {
      "title": "Harmony as Avoidance",
      "challenge": "Your orientation toward integration can become sophisticated conflict avoidance. If you're always looking for how everyone can win, you might be unable to tolerate situations where someone must lose—including situations where you should advocate for yourself against others' interests.",
      "remedy": "Examine your relationship with conflict. Are you seeking integration because it's genuinely possible, or because you can't tolerate the discomfort of opposition? Sometimes the harmonious move is to hold your ground, create friction, or allow a rupture that leads to genuine repair rather than smoothed-over pseudo-peace."
    },
    {
      "title": "Overlooking Zero-Sum Reality",
      "challenge": "Some situations are genuinely win-lose. Resources are finite, positions are incompatible, someone's gain requires someone's loss. Your integrative optimism can blind you to these realities, causing you to keep searching for synthesis where none exists.",
      "remedy": "Develop discernment about which situations are actually integrable and which aren't. Ask: \"Is there genuinely a configuration that honors all needs here, or am I hoping for one to avoid difficult tradeoffs?\" Your integration superpower works best when deployed in situations where integration is possible."
    },
    {
      "title": "Inspiration Without Execution",
      "challenge": "Your strength in vision and integration may not be matched by follow-through. You can see the harmonious future clearly, but building it requires sustained attention to present-moment execution—the less glamorous work of implementation.",
      "remedy": "Partner with executors or develop execution as a skill. Recognize that vision without implementation is just daydreaming. The integration you see isn't real until it's built, and building requires different capacities than seeing. Either develop those capacities deliberately or collaborate with people who have them naturally."
    }
  ]
};
