// IDEALIZED Profile — Young Adult (18–29)
// Parser Profile™ © 2026 Cognition Blocks LLC

export const idealizedyaProfile = {
  "name": "IDEALIZED",
  "tagline": "The one who remembers what we said we'd be",

  "overview": "You remember what things were supposed to mean. Not just what happened—anybody can remember the party, the trip, the group that used to be tight. You remember what it stood for. The friend group that swore it'd never turn into this. The relationship that promised something it stopped delivering. The version of everyone that showed up when it actually mattered. You carry that, and you hold right now up against it.\n\nYour head goes to the meaning under the thing more than the thing itself. You're not really tracking exactly what got said at the party—you're tracking what it meant that nobody checked on her after. The specific words fade; the significance stays. You'll forget the details of a fight and remember exactly what it revealed about where you stand with someone.\n\nYour attention drifts backward, to what's already happened. But you're not just scrolling old memories—you're sorting them, finding the moments when people were at their best, when the friend group was actually the thing it claimed to be, when someone lived up to what they promised. Those become the bar you measure everything against now.\n\nAnd it's not mostly about you. You're holding the group's standard—what we said we were, what this was supposed to be. What did this friendship promise? What did we used to stand for before it got weird? You end up being the one who remembers the best version of the group, from the times it was actually real, and you notice hard when it falls short of that now.\n\nIt makes you a kind of memory-keeper for whatever you're part of. You remember what we said we cared about. You remember when we actually lived it. You remember the bar we set in our best moments, and you feel it when we drop below it.",

  "howYouLearn": "Learning lands for you when it connects to something that actually matters—values, meaning, what's really at stake. A class that just makes you memorize facts with no point behind them struggles to hold you. But a class that gets at why something matters, what it means, what it says about people—that one you're locked into.\n\nBecause you're tuned to the group and to meaning, you learn best from collective stories—history, documentaries, how a movement rose or fell apart, how a band or a friend group or a company drifted from what it started as. How did this group keep its soul? How did that one sell out? What happened when those people compromised the thing they swore they'd never compromise?\n\nYou learn by comparing—now versus then, what is versus what it was supposed to be. That's just how you process new stuff: where does this fit, does it live up to the standard, is this real or has it drifted?\n\nOrigin stories pull you in. You want to know how a thing started, what it was for at the beginning, what the founders actually intended. That's not you living in the past—it's you building the library of ideals you'll measure everything else against.\n\nOne thing to watch: your learning can get filtered through judgment before curiosity. Practice just taking the information in before you grade it. Let yourself learn what something is before you measure it against what it should be.",

  "howYouCommunicate": "You talk with a kind of moral clarity and a memory for what was promised. You bring up the standard, the thing that was said before. \"That's not what we agreed to, though.\" \"Remember when we said we'd always...?\" \"That's not the whole point of this.\" Your way of talking naturally ties what's happening now back to what got committed to earlier.\n\nYou talk in terms of what it means more than the play-by-play. You'll skip past the exact details to get at the significance underneath. What does this actually mean? What does it say about us? What's really at stake here?\n\nYou say \"we\" a lot, and you're tracking what things mean for the group—the friendship, the crew, the family—not just for one person.\n\nYou can come across as preachy, especially to people who don't want to be measured against an ideal right now. It helps to notice that, and when it matters, just name what you're actually doing: \"I'm not trying to judge you—I'm trying to remember together what we said we'd be.\"",

  "phrase": "You're not stuck in the past—you're holding it accountable. Somebody has to remember what we promised, and you can't unknow it.",

  "secret": "Sometimes you use the ideal to punish what's real, because you're angry at it.\n\nBeing the one who remembers the standard feels noble, and a lot of the time it is. But underneath the principled stuff, there's sometimes something less clean: disappointment that hardened into judgment, hurt that dressed itself up as being right. The ideal becomes a weapon against a present that let you down.\n\nYou remember what it was supposed to be. And when it fell short—when the friend bailed, when the relationship turned into something it promised it wouldn't, when the people you trusted didn't show up—you held onto the ideal precisely because it makes the letdown undeniable. There's a satisfaction in that clarity, in being able to point at exactly how far it fell. And that satisfaction isn't purely about values.\n\nThe deeper secret: you might be more attached to the gap between how it should be and how it is than to either one by itself. The gap is where you live—in the permanent disappointment, the endless measuring, the grief that something fell short. If reality ever actually matched the ideal, you'd lose the one solid ground you've got.\n\nAnd deeper still: you might idealize the past exactly because it can't hurt you again. It already happened. It's safe. You can perfect it in your memory in a way the risky, unfinished now never lets you.\n\nThese shadows don't make your memory false. They just show you where it got wounded.",

  "whatOthersGetWrong": "They think you're rigid and can't handle change. They see you holding onto how things were and decide you must just hate anything new. They don't get that you're not against change—you're against drift, against things quietly turning into something else while everyone pretends nothing's different and nobody names what got left behind.\n\nThey think your standards are you being self-righteous, like you enjoy judging people just to feel above them. They don't see that you're usually hardest on yourself, that you live inside the exact same gap between ideal and actual that you point out in everyone else.\n\nSome people figure that because you focus on the group, you don't have your own needs or your own hurt. They see you talking about \"us\" and miss the personal wound sitting right underneath it.\n\nAnd people assume the idealized past you remember actually happened exactly the way you remember it. They take your memory as straight history instead of curated meaning. They don't realize you're remembering what it meant, not the literal facts, and that your golden version might be part real memory, part something you built.\n\nMaybe the one that stings most: people think you can't see what's good right now because you're always comparing to back then. Usually you do see it—you just also see how much further it could go if everyone remembered who we said we'd be.",

  "hiddenSuperpower": "You can call a group back to itself.\n\nEvery group drifts—the friend crew, the team, the relationship, all of it. When it does, it needs someone who remembers the original direction. Not a hater standing outside throwing rocks, but a member standing inside holding up a mirror. \"This is who we said we'd be. This is what we were actually about. This is the thing that brought us together in the first place.\"\n\nYou can do that because you genuinely remember. Your idealized version isn't a fantasy—it's built on real moments when the group actually was the thing it claimed to be, when people actually showed up, when it was real. You have the receipts. You were there.\n\nThat calling-back is essential for anything that wants to keep its soul over time. Without it, a friend group slowly turns into something nobody chose. A relationship erodes without anyone noticing. The thing that made it special fades until no one even remembers why you all started.\n\nYour superpower is that you notice the drift before it's too far gone to fix. You name the gap while it's still close enough to close. You hold the memory that makes turning it around even possible.\n\nAnd when a group does come back to itself—remembers what it was about, recommits—you're often the reason it happened.",

  "blindSpot": "You might not notice when the idealized past you're holding onto is more built than remembered.\n\nYour head pulls the meaning out of things, and meaning is always a little bit interpretation. The perfect version of the friend group or the relationship you're measuring now against might be a clean edit you made—the good feeling without the messy parts, the loyalty without the times it also let you down. Your memory is selective, and you might not see the selecting happening.\n\nWatch for this: other people who were also there remembering it really differently. If the friends who lived the same thing don't recognize your version of it, maybe you idealized it more than you realized.\n\nAlso watch for: an ideal that fits your current disappointment a little too perfectly. If the past you remember makes right now look as bad as possible, you might be building the comparison rather than honestly finding it.\n\nAnd watch for: not being able to admit when now is actually better than then. If every comparison somehow comes out favoring back-in-the-day, that's a tell. Sometimes the present genuinely beats the past.\n\nYour blind spot isn't the memory itself. It's assuming the memory is just accurate, when it's actually something you're actively building.",

  "frictionPatterns": "You'll clash with the people heads-down building their own future—chasing their own goals, moving toward what they personally want. Their \"I'm just trying to build my life\" hits your \"but we're abandoning what we had.\" You can look stuck and judgy to them; they can look selfish and rootless to you.\n\nYou'll also struggle with the super future-focused friend who finds your looking-backward thing frustrating. They want to talk about where we're going; you want to talk about where we came from and what we promised on the way.\n\nAnd the people who are all about themselves can find your group-focus kind of irrelevant. They're not invested in \"what we said we'd be\"—they're invested in what they want, right now, for them.\n\nWhat you bring to that friction: you can remind the future-chasers that where they're going was shaped by where they came from, and that you can't just delete the past without losing something.\n\nYour growth edge: getting that future-focus isn't betrayal and being self-focused isn't automatically selfish. Not everyone is built to carry the group's memory the way you are, and that's allowed.",

  "energyPatterns": "What drains you:\n- Friends or groups that act like the past just doesn't matter\n- Getting called judgmental when you're honestly just trying to remember together\n- A crew that abandoned what it stood for and doesn't want to hear about it\n- Being told to \"just move on\" from a standard that still matters to you\n- Watching something good quietly get traded for something cheaper\n- Being the only one still holding a memory everyone else let go of\n\nWhat charges you:\n- A group that actually wants to remember and recommit to what it was about\n- Real conversations about meaning, values, what things were supposed to be\n- Being seen as the one who keeps the important memory alive\n- A friend living up to the best version of themselves you've seen\n- Watching a friend group or a person actually come back to who they said they'd be\n- Digging into history—origin stories, how things started and what they were for",

  "workEnvironments": "Where you thrive:\n- Places that actually care about history, principle, and staying true to a mission\n- Mission-driven nonprofits, causes, communities built around shared values\n- Roles focused on culture, integrity, or keeping a place honest to its purpose\n- Work where standing for something over time is the actual point\n- Teams that want to be reminded what they started this for\n\nWhere you suffocate:\n- Places that treat the past as totally irrelevant\n- Cultures that worship \"disruption\" without honoring anything they're tearing up\n- Spots where convenience quietly wins over the thing you signed up for\n- Cynical rooms that treat caring about values as a joke\n- Relentlessly move-fast spots with zero interest in why anything started",

  "topCareers": [
    {
      "title": "Mission-Driven Nonprofit / Advocacy Roles",
      "description": "You remember what things were supposed to mean—the promise under the thing, what was actually at stake. Entry-level nonprofit and advocacy work is exactly that: holding the work accountable to the cause it claims to serve. You track the values an organization says it's about, and you notice fast when it starts drifting toward convenience. The \"why are you so hung up on what we said\" that impatient rooms throw at you is, here, basically the whole job. People who carry the mission like it's personal are the ones these places run on."
    },
    {
      "title": "Community / Culture Roles",
      "description": "You carry a picture of how a group should be at its best, built from the times it actually was, and you hold people to it. Entry-level community-building and culture work rewards that: helping a team or a space stay true to what it was founded on instead of letting it quietly erode. You see the values under the day-to-day where other people just see logistics. The idealism that got called impractical becomes the exact thing a values-driven community most needs someone to keep alive."
    },
    {
      "title": "Ethics / Integrity / Standards Track",
      "description": "You know what the original promise pointed toward, and you won't let it quietly disappear. Entry-level work on ethics, standards, or institutional integrity is built for that—keeping the meaning and the principle of a place alive over time, not just its paperwork. You honor what's worth honoring and you name it out loud when something better is getting traded for something cheaper. The loyalty to ideals that frustrated disruption-for-its-own-sake cultures is precisely what these roles exist to protect."
    }
  ],

  "blockIndicators": "Your Parser Profile suggests the following CBI block accessibility pattern:\n\nLikely High-Accessibility Blocks:\n- Pattern Recognition (seeing value patterns and drift across time)\n- Social Signal Processing (other-oriented attention to group dynamics)\n- Symbolic Manipulation (working with abstract meaning and values)\n\nLikely Moderate-Accessibility Blocks:\n- Self-Reference Processing (accessible when your attention turns inward)\n- Sequential Processing (organizing the story of how things went)\n- Generative Creation (putting ideals and what they mean into words)\n\nLikely Lower-Accessibility Blocks:\n- Perceptual Discrimination (right-now sensory detail gets less attention than meaning)\n- Spatial Relationships (concrete spatial stuff less emphasized)\n\nThis pattern suggests your cognitive architecture is optimized for holding meaning and calling a group back to its values. Your room to grow is in appreciating what's good right now and in noticing your own wounds inside your principled stance—seeing the present clearly and seeing yourself in it.\n\nIDEALIZED",

  "strengths": [
    {
      "title": "Keeping What Mattered",
      "description": "You remember what things were supposed to mean when everyone else conveniently forgot. The thing the group said it was about, the promise the relationship made, why you all started this—you carry it even after people moved on and let it slide. That keeping is what lets a group stay connected to its roots instead of just becoming whatever's easy."
    },
    {
      "title": "Naming the Gap",
      "description": "Because you remember the standard, you can name the distance between who we said we'd be and who we're actually being. It's not criticism for fun—it's the clarity that makes real change possible. You see the gap that everyone else stopped measuring because it got uncomfortable to look at."
    },
    {
      "title": "Spotting the Pattern",
      "description": "You notice when the same drift is happening in different places—the same little compromise showing up across the friend group, the job, the relationship. That pattern-radar helps you catch a real slow slide instead of writing it off as one isolated weird moment."
    },
    {
      "title": "Holding the Story",
      "description": "You keep the story of what things meant, so the group's memory doesn't just fragment into everyone's separate version. You can remind people where you all came from, what you intended, why this even started—which matters most exactly when everyone's forgotten."
    },
    {
      "title": "Standards Bigger Than You",
      "description": "Your bar isn't just personal taste—it's about what the group actually committed to. You're not saying \"I don't like this,\" you're saying \"this isn't what we agreed to.\" That makes your standard land harder and feel more legit than someone just complaining about their own preference."
    },
    {
      "title": "Proof It's Possible",
      "description": "By remembering the best version of how things were, you keep the hope of it alive. You prove it's possible because you watched it happen. Your idealized memory isn't a fantasy—it's evidence that people are capable of more than the watered-down thing they're settling for right now."
    }
  ],

  "challenges": [
    {
      "title": "The Edited Memory",
      "challenge": "Your head holds onto the meaning and quietly drops the messy reality that came with it. You might be idealizing a past that wasn't as solid or as good as you remember. The \"golden era\" of the friend group you're comparing now to might never have actually been that golden.",
      "remedy": "Make yourself recall the hard parts alongside the good. When you bring up the past as the standard, ask: \"What was also rough about that time? What wasn't working back then?\" Putting the shadow back into the memory makes your version of it way more accurate."
    },
    {
      "title": "Judgment With No Grace",
      "challenge": "Your clear sense of how things should be can curdle into harsh judgment of how they are. You might hold a friend to a standard with zero compassion, measuring them against the ideal without accounting for whatever they're actually dealing with.",
      "remedy": "Pair the accountability with curiosity. Before you judge the gap, ask: \"What might explain this? What's this person actually going through right now?\" Understanding doesn't mean dropping the standard—it just means actually being interested in why reality fell short before you swing."
    },
    {
      "title": "When It's Growth, Not Betrayal",
      "challenge": "Your loyalty to how things were can turn into resisting change that's actually good. Not all change is drift—some of it is people growing up. But you might treat any move away from the original as a betrayal, even when it's just someone becoming who they're supposed to be.",
      "remedy": "Separate the core thing you value from the old specific form it used to take. The deepest values can show up in brand new ways and still be true. Ask: \"Is this change abandoning what I actually care about, or is it just a new way of honoring it?\""
    },
    {
      "title": "Wearing People Out",
      "challenge": "Your constant memory of the standard can exhaust people who just need room to be imperfect. If you're always measuring, always remembering how it's supposed to be, your friends can start to feel like they can never just relax around you.",
      "remedy": "Make clear spaces of grace on purpose. Let people know when you're not measuring—when you're just hanging out, just present, standards set aside for the night. Being the one who remembers is valuable. It just can't be the only mode they ever get from you."
    },
    {
      "title": "Missing What's Good Now",
      "challenge": "Your eyes-on-the-past idealism can cut you off from what's actually good right now. You might be so busy comparing today to the perfect version of back-then that you miss what's genuinely working, what's growing, who's actually showing up for you in this moment.",
      "remedy": "Practice naming present good, not just past ideal. Ask: \"What is this moment doing that the old version couldn't? What new good thing is showing up here?\" Right now isn't only a downgraded version of back then—sometimes it's quietly better."
    },
    {
      "title": "Holding People to a Promise They Never Made",
      "challenge": "Your group-focused ideals might hold someone to a standard they personally never signed up for. Just because the friend group said something once doesn't mean every single person in it actually agreed to it or even meant it.",
      "remedy": "Check for the actual buy-in before you apply the shared standard. Not everyone signed the same thing. When you invoke what \"we\" agreed to, make sure this specific person actually did—and didn't just go along with it in the moment."
    }
  ]
};
