// INTEGRATED Profile
// Parser Profile™ © 2026 Cognition Blocks LLC
// Balanced • Past • Self

export const integratedProfile = {
  "name": "INTEGRATED",
  "code": "Balanced • Past • Self",
  "tagline": "The one who knows themselves because they've done the work",

  "overview": "You know who you are because you know where you've been. Your sense of self isn't invented or hoped for—it's built from examined evidence. You've looked back at what you've lived, made sense of it, and integrated it into something you can stand on.\n\nYou've probably spent more time than most people making sense of your own story. Not ruminating—integrating. Understanding why you did what you did. What patterns repeat. What you've learned. Who you've become through what you've experienced. This isn't navel-gazing; it's construction. You're building a self that's grounded in evidence.\n\nYour thinking moves fluidly between the specific and the conceptual. You can recall particular moments with clarity and also see the themes they reveal. This gives you access to both concrete memories and abstract meanings—what happened and what it meant.\n\nYour attention naturally turns toward what's already occurred. Not with regret or nostalgia, but as resource. Your history is data. Your experiences are evidence. Your reflection is how you make sense of the data.\n\nYour reference point is internal. You're primarily integrating your own experience rather than tracking others'. This isn't indifference—it's scope. You understand that you can only truly know one interior: yours. So that's where you do your deepest work.\n\nPeople have probably called you introspective, self-aware, sometimes \"too much in your own head.\" They see the internal focus and assume it's excessive. What they don't see is the structure you've built—a coherent identity grounded in examined experience, tested against actual behavior, refined through honest reflection.",

  "howYouLearn": "Learning lands for you when it connects to personal experience. Abstract concepts that link to something you've lived become permanent; information without experiential anchor fades. Your learning is autobiographical—you remember what connects to your story.\n\nYou need reflective space to process. Rushed instruction that doesn't allow for personal connection doesn't stick. You learn by testing new ideas against your own history. Give you a model for understanding behavior, and you'll immediately check it against what you've experienced.\n\nYou're willing to learn things slowly if they're learned thoroughly. Surface coverage without integration feels incomplete. You want understanding that becomes part of your self-knowledge, not just information that floats without anchor.\n\nYou learn well from examined experience—journaling, therapy, reflective practice, memoir. Anything that supports making sense of what you've lived supports your learning. You're not just acquiring information; you're integrating it into coherent self-understanding.\n\nBe aware that your self-referential learning style might undervalue knowledge that doesn't obviously connect to your experience. Some learning serves the collective, serves others, serves purposes beyond personal integration. Don't let your filter screen out knowledge that could expand your contribution.",

  "howYouCommunicate": "You communicate through personal narrative. Stories from your experience are your natural medium—not to make everything about you, but because that's where your knowledge lives. Your examples are autobiographical; your evidence is experiential.\n\nYou tend toward depth over breadth. You'd rather explore one topic thoroughly than skip across many surfaces. Small talk is tolerable but not nourishing; real conversation goes deeper.\n\nYou're good at articulating your own experience with nuance and precision. You've done the work of understanding yourself, so you can communicate that understanding clearly. Others may find your self-knowledge impressive or intimidating, depending on their own relationship with self-examination.\n\nYou may struggle with communication that requires leaving your experience aside. Pure abstraction without personal grounding, or discussion of others' experiences without connecting to your own, can feel foreign. You process through the personal.\n\nYou communicate best in intimate, reflective contexts—one-on-one or small groups where depth is possible and personal sharing is valued.",

  "phrase": "You're not stuck in the past. You're rooted in it. There's a difference between being trapped by your history and being built by it.",

  "secret": "You've spent more time understanding yourself than most people spend understanding anything. While others rush forward unexamined, you've been doing the slow work of integration—making sense of what you've lived, building a self that's grounded in actual history rather than wishful thinking.\n\nThe secret is that this work has been lonely. You can't really share it—the nuances of your own self-discovery don't translate into casual conversation. You've had insights about yourself that felt profound, and no one to tell who would understand why they mattered.\n\nYou've probably been told you're \"too introspective\" or \"too focused on the past\" by people who've never looked closely at themselves. They're running on unexamined defaults and calling it living. You've done the work of actually knowing yourself, and somehow that's the problem.\n\nThere's a part of you that wonders if all this reflection has been worth it. Others seem to function fine without it. They make decisions without examining, act without integrating, move forward without understanding where they've been. Sometimes their carelessness looks like freedom. Sometimes your depth feels like weight.\n\nBut you can't go back to not knowing. The examined life isn't reversible. Once you've seen your own patterns, you can't unsee them. You're committed to self-knowledge now, even when it's heavy.\n\nThe deeper truth: you're still not done. Integration is never complete. You're still making sense of things that happened years ago, still finding new patterns in old experiences, still building a self that's never quite finished.",

  "whatOthersGetWrong": "They think you're self-absorbed when you're actually self-aware. There's a difference. Self-absorbed people think about themselves without seeing clearly. You think about yourself because you're committed to seeing clearly. The introspection isn't vanity; it's integrity.\n\nThey call you \"stuck in the past\" when you're actually grounded in it. They don't understand that your past-focus isn't regret or nostalgia—it's foundation. You're building on examined experience, not drifting on unexamined assumption.\n\nYou've been told to \"stop overthinking\" by people who would benefit from thinking at all. They've mistaken depth for dysfunction. Your examined life isn't a disorder; it's a discipline.\n\nThey assume your self-focus means you don't care about others. You do. You've just learned that you can't understand others clearly until you understand yourself clearly. Your self-examination is foundation for connection, not substitute for it.\n\nThe deepest misread is that your reflection is passive. It isn't. Integration is active work. Making sense of experience takes effort. Building coherent identity from scattered history requires construction. You're not sitting with your past; you're working with it.",

  "hiddenSuperpower": "You actually know yourself. Not the marketing version, not the aspirational version, not the defensive version—the actual version, built from examined evidence. This is rarer than it should be.\n\nMost people operate on unexamined self-concepts that don't survive contact with their actual behavior. You've tested yours. When life shakes, you know what you're standing on. When choices arise, you know what matters to you—because you've checked.\n\nYour pattern recognition extends into prediction. Because you know how you've responded before, you can anticipate how you'll respond again. You're not surprised by yourself the way others are. This predictive self-knowledge lets you position for success and avoid setups for failure.\n\nYou can also spot inauthenticity—in yourself and others. You know what examined self-knowledge looks like, so you can tell when someone's operating from unexamined assumption. This isn't judgment; it's perception.\n\nPerhaps most valuably: you can grow deliberately. Because you understand your patterns, you can change them. Self-knowledge is leverage for development. You're not just living your history; you're learning from it in ways that make your future different from your past.",

  "blindSpot": "Your examined past can become an over-fitted model. You know yourself so well in familiar contexts that you might not recognize yourself in unfamiliar ones. Your self-knowledge is historically grounded, but you're not only your history. The person you could become in new circumstances might surprise you—if you let new circumstances occur.\n\nYour self-focus can leave you less calibrated to others. While you're integrating your experience, you might miss how your experience intersects with, affects, or differs from others'. Self-knowledge in isolation is incomplete; it needs relational context to be fully accurate.\n\nYou might also over-trust your self-interpretation. Just because you've reflected doesn't mean you've reflected accurately. Your narrative about yourself is still a narrative—a construction that could be incomplete or biased.\n\nYour past orientation might make you undervalue present novelty and future possibility. Some experiences don't fit your patterns because they're genuinely new. Some opportunities require becoming someone your history doesn't predict.\n\nFinally, integration can become endless deferral. There's always more to understand, more to process, more history to examine. At some point, you know enough to act, and continuing to examine becomes avoidance of action, not preparation for it.",

  "frictionPatterns": "You'll clash with people focused on external deliverables and future commitments while you're doing internal work with past experience. They're tracking what needs to happen for others going forward; you're making sense of what's already happened inside yourself. Neither is wrong—you're optimizing for completely different dimensions.\n\nFuture-focused profiles may frustrate you. They're always looking ahead while you're making sense of what's behind. Their forward motion feels like escape from self-understanding; your backward gaze feels like failure to progress to them.\n\nOther-focused profiles may find your self-focus difficult. They're tracking collective needs; you're integrating personal experience. Your introspection looks like abandonment of relationship to them; their external focus looks like avoidance of self-knowledge to you.\n\nYour gift in these frictions: Your grounded self-knowledge can help others start their own examination.\n\nYour growth edge: Recognizing that future-focus and other-focus aren't failures to do the work you've done—they're different work with its own validity.",

  "energyPatterns": "What drains you:\n- Environments that don't allow reflection time\n- Pressure to act before understanding\n- Having your introspection dismissed as self-absorption\n- Surface interactions without depth\n- Being rushed past integration\n- People who don't know themselves and don't want to\n\nWhat charges you:\n- Time for deep reflection\n- New frameworks that illuminate your experience\n- Conversations that reach personal depth\n- Insights about your own patterns\n- Integration breakthroughs—when something finally makes sense\n- Others who value examined living\n- Writing, journaling, reflective practices\n- The stability that comes from knowing yourself",

  "workEnvironments": "Where you thrive:\n- Environments that value self-awareness and allow reflection\n- Psychology, counseling, writing, research, coaching, spiritual direction\n- Any domain where self-knowledge is an asset\n- Roles where knowing yourself deeply translates into effectiveness\n\nWhere you suffocate:\n- Environments that only value external production\n- Cultures that dismiss introspection as indulgence\n- Fast-paced contexts with no space for reflection\n- Organizations that see self-examination as weakness",

  "blockIndicators": "Your Parser Profile suggests the following CBI block accessibility pattern:\n\nLikely High-Accessibility Blocks:\n- Self-Reference Processing (strong interoceptive and autobiographical awareness)\n- Pattern Recognition (personal pattern detection)\n- Sequential Processing (narrative construction)\n\nLikely Moderate-Accessibility Blocks:\n- Symbolic Manipulation (meaning-making from experience)\n- Perceptual Discrimination (specific memory access)\n- Generative Creation (narrative construction)\n\nLikely Lower-Accessibility Blocks:\n- Social Signal Processing (self-focus may reduce other-awareness)\n- Spatial Relationships (less emphasized)\n\nThis pattern suggests your cognitive architecture is optimized for self-understanding, personal integration, and narrative identity construction. Your developmental opportunities lie in other-awareness and future-orientation—extending your integration to include relational patterns and forward projection.\n\nINTEGRATED",

  "strengths": [
    {
      "title": "Personal Pattern Recognition",
      "description": "You see patterns in your own history that others miss in theirs. Why you keep making certain choices, what triggers certain responses, how your past shapes your present—these connections are visible to you because you've looked. This self-pattern recognition gives you leverage for change that people with less self-knowledge don't have."
    },
    {
      "title": "Narrative Coherence",
      "description": "Your life story makes sense to you. Not because you've invented a flattering fiction, but because you've done the work of integration—connecting events, extracting meaning, building a coherent account of how you became who you are. This narrative gives you stability that people with fragmented self-understanding lack."
    },
    {
      "title": "Examined Identity",
      "description": "You know who you are because you've checked. Not assumed, not hoped, not performed—checked against evidence. When you say \"I'm someone who...\" you can point to the history that supports the claim. Your identity is grounded, which makes it resilient."
    },
    {
      "title": "Learning From Experience",
      "description": "You actually learn from your past, not just live it. You extract lessons, identify mistakes, recognize what worked. This reflective processing means your history becomes wisdom rather than just memory. You're building on experience rather than just accumulating it."
    },
    {
      "title": "Self-Continuity",
      "description": "You have a clear sense of how your current self connects to your past selves. The thread of identity is visible to you across time. This continuity provides psychological stability—you know where you come from, which helps you know where you stand."
    },
    {
      "title": "Authentic Self-Knowledge",
      "description": "Your self-understanding is earned, not assumed. You've questioned your own stories, tested your self-concepts, refined your understanding through honest examination. This authenticity makes your self-knowledge more reliable than most people's unexamined self-images."
    }
  ],

  "challenges": [
    {
      "title": "Reflection Becoming Rumination",
      "challenge": "The line between productive reflection and unproductive rumination can blur. You might process the same experiences repeatedly without generating new insight, stuck in loops that feel like work but don't produce integration.",
      "remedy": "Set reflection boundaries. Ask: \"What new understanding am I generating?\" If the answer is none, you're ruminating, not integrating. Shift to action, external focus, or new input. Reflection needs material to work with; recycling old material without new perspective isn't integration—it's repetition."
    },
    {
      "title": "Past as Prison",
      "challenge": "Your past-focus can become deterministic—believing you are only what you've been, that history constrains rather than informs. When identity becomes too fixed in the past, growth feels like betrayal of self.",
      "remedy": "Hold identity loosely. Your past informs who you are; it doesn't determine who you must remain. Integration includes integrating change—acknowledging that who you're becoming is as real as who you've been. The self is a process, not a monument."
    },
    {
      "title": "Self-Focus Isolation",
      "challenge": "Your orientation toward your own experience can leave you less attuned to others'. While you're examining your history, you might miss how your history connects to others' histories, or how your current self-focus affects current relationships.",
      "remedy": "Extend integration outward. Your story intersects with others' stories. Examine those intersections. How have others shaped your history? How has your history affected others? Self-knowledge that includes relational context is more complete than self-knowledge in isolation."
    },
    {
      "title": "Over-Identification with History",
      "challenge": "You might become so identified with your history that present experience gets interpreted only through past patterns. Everything becomes a repeat of something that happened before, even when it isn't. Pattern recognition becomes pattern imposition.",
      "remedy": "Test for novelty. When you recognize a pattern, ask: \"Is this actually the same, or am I forcing fit?\" Some situations are genuinely new. Your past is a lens, not a template. Be willing to see what's actually in front of you, not just what resembles something behind you."
    },
    {
      "title": "Future Neglect",
      "challenge": "Your past orientation can leave future planning underdeveloped. You're so focused on understanding where you've been that where you're going gets less attention. The examined life can become the backward-looking life.",
      "remedy": "Use integration for projection. Your self-knowledge is a resource for the future, not just an understanding of the past. Ask: \"Given who I've learned I am, what do I want to build? Where does this history point?\" Integration serves forward motion, not just backward understanding."
    },
    {
      "title": "Analysis Paralysis",
      "challenge": "The drive to fully understand before acting can delay action indefinitely. There's always more to examine, more to integrate, more self-knowledge to develop. Meanwhile, life is happening and decisions need making.",
      "remedy": "Accept incomplete integration. You'll never fully understand yourself—you're still happening. Make decisions from current understanding, then integrate the results. Action generates new material for reflection; waiting for complete self-knowledge before acting means waiting forever."
    }
  ]
};
