// INTENTIONAL Profile
// Parser Profile™ © 2026 Cognition Blocks LLC
// Concrete • Future • Self

export const intentionalProfile = {
  "name": "INTENTIONAL",
  "code": "Concrete • Future • Self",
  "tagline": "The self-architect who engineers their own becoming",
  "overview": "You see your future self clearly, and you're constantly building the\nbridge to get there. While others drift through life waiting for things\nto happen, you're engineering outcomes. Not hoping. Not wishing.\nArchitecting. Every choice is a brick in a structure you've already\nvisualized.\n\nYour cognitive architecture prioritizes concrete reality over abstract\nconcepts, future possibilities over present or past circumstances, and\npersonal outcomes over collective concerns. The result is a mind that\nnaturally plans, prepares, and executes toward defined personal goals,\nsomeone who treats their own life as a project to be deliberately\nconstructed.\n\nYou've probably achieved things that others thought were lucky. They\ndidn't see the work that started years before the outcome became\nvisible. They saw the result and called it fortune. You know it was\narchitecture, thousands of small, intentional choices accumulating into\nwhat looked like sudden success.\n\nThe Intentional profile represents approximately 6% of the population.\nYou're the person who has a plan when others have wishes. Who's\nalready working on next year while others are reacting to last week. Who\ntreats time as a resource to be invested, not a current to be carried\nby.\n\nYou've probably frustrated people who wanted you to \"relax\" and \"go\nwith the flow.\" They don't understand that flow, for you, leads\nnowhere. You're not anxious about the future, you're building it. The\ndifference is invisible to people who've never taken control of their\nown trajectory.\n\nYour cognitive architecture excels at goal-setting, reverse-engineering\nsuccess paths, and executing consistently over time. You're a natural\nproject manager of your own life, not because you're controlling, but\nbecause you're intentional. You know that futures don't happen to you;\nyou happen to them.\n\nUnderstanding your profile means recognizing that your relationship with\nthe future isn't obsession, it's orientation. You're not fleeing the\npresent or fearing uncertainty. You're simply wired to see time as a\ndimension you can shape, and you refuse to leave that shaping to chance.\n\nThe concrete focus keeps your planning grounded in actionable steps\nrather than abstract aspirations. The self-focus means you're primarily\nengineering your own outcomes rather than diffusing energy across\ncollective goals. Together with future orientation, this creates a\nconsciousness that's remarkably effective at personal achievement,\nturning visions of who you could become into the reality of who you are.\n\nYour challenge isn't motivation or discipline, those come naturally.\nYour challenge is knowing when to release the plan, when to let present\nmoments matter for their own sake, and when goals for yourself need to\naccount for their impact on others.",
  "howYouLearn": "You learn what serves your goals. Information connected to your\nobjectives sticks; information without clear application fades. This\nisn't intellectual limitation, it's prioritization. You're running a\nrelevance filter that keeps you focused.\n\nYour optimal learning environment connects knowledge to outcomes. You\nwant to know why this matters, how it fits into what you're building.\nGive you the application first, then the theory. Show you where this\nleads, then how to get there. Purpose drives your acquisition.\n\nYou learn well from people who've achieved what you're pursuing. Their\npath is a map; their mistakes are warnings; their insights are\nshortcuts. Mentors, case studies, and documented journeys all serve your\nlearning because they connect to demonstrated outcomes.\n\nYou learn poorly from abstract knowledge disconnected from application.\nTheoretical understanding without practical purpose doesn't engage your\nprocessing. \"Interesting\" isn't enough; you need \"useful.\" This can\nlimit breadth, but it creates depth in domains that matter to you.\n\nSelf-directed learning works well for you, you're motivated enough to\nstructure your own development. Formal education works when it aligns\nwith your goals; it feels like obstacle when it doesn't. You'll learn\nanything if you can see how it serves what you're building.",
  "howYouCommunicate": "You communicate with purpose. Conversation is rarely idle for you, it's\neither relationship-building, information-gathering, or goal-advancing.\nThis efficiency can make you seem intense or transactional to people who\nprocess socially rather than instrumentally.\n\nYou tend toward directness. You say what you need, ask for what you\nwant, and move conversation toward resolution. Small talk is tolerable\nbut not natural; you're waiting for the point, or you're making one.\n\nYou're good at articulating goals, plans, and progress. You can\ndescribe where you're going and how you're getting there with clarity\nthat inspires some and alienates others. People either find your clarity\nmotivating or exhausting depending on their own orientation.\n\nYou may struggle with conversations that aren't going anywhere.\nProcessing out loud, venting without resolution, socializing without\npurpose, these can feel like time-waste even when they serve relational\npurposes you're not tracking. Learning to value process-less connection\nis developmental work for you.\n\nIn groups, you orient toward decisions and next steps. You're the one\nasking, \"so what are we doing?\" when discussion extends past its\nuseful life. This can be invaluable or annoying depending on whether the\ngroup needs action or needs to process.\n\nYou communicate best when purpose is clear meetings with agendas,\nconversations with objectives, relationships with mutual understanding\nof what you're building together.",
  "phrase": "You're not obsessed with control, you're just unwilling to leave\nyour future to chance when preparation is an option.",
  "secret": "You see your future-self more clearly than you see your present self.\nThat person you're becoming feels more real than the person you\ncurrently are, closer, more vivid, more essentially you. You're not\nliving in the present; you're living toward the future, using now as\nmaterial for then.\n\nThe secret is that this has cost you. Moments you should have savored,\npassed through in transit. Relationships you should have nurtured,\nneglected because they didn't fit the timeline. Rest you should have\ntaken, deferred because there was more to build. You've been so focused\non becoming that you've sometimes forgotten to be.\n\nYou've probably achieved things that impressed others while feeling\nhollow yourself. The goal reached wasn't the point, the next goal was\nalready in focus. The celebration felt performative because you'd\nalready moved on internally. Arrival is less satisfying than pursuit,\nand you've never figured out how to make it otherwise.\n\nThere's a fear underneath all this building that you've rarely\nexamined. What happens if you stop? What are you without the trajectory?\nThe constant forward motion isn't just strategy, it's also avoidance.\nStillness might reveal something you're not ready to face that the\nfuture you're chasing might not satisfy any more than the futures\nyou've already reached.\n\nThe deepest secret: you've sometimes wondered if you're capable of\nbeing happy now, or if you're wired only for the pursuit of happiness\nlater. If the destination will always recede as you approach. If you're\nbuilding a life you'll never actually inhabit because your always\nbuilding the next one.",
  "whatOthersGetWrong": "ABOUT YOU \n\nPeople think you're controlling when you're actually prepared. They\ncall you \"obsessed with goals\" like it's a personality flaw rather\nthan a functional advantage. They don't understand that your planning\nisn't rigidity; it's freedom through foresight. You're not anxious\nabout the future, you're building it.\n\nThey assume your future-focus means you're not present. But you are\npresent, present to the full temporal dimension of now, which includes\nits trajectory. You see the present more completely than they do because\nyou see where it leads. Their \"presence\" is just temporal myopia.\n\nYou've been told to \"relax\" and \"go with the flow\" by people who\nare constantly dealing with preventable crises. They've confused\npassivity with peace. You have peace, the peace of knowing you're on a\npath, making progress, building something real. Their chaos is not your\ngoal.\n\nThey think your self-focus means you don't care about others. You do.\nYou've just learned that you can't serve others from a position of\npersonal chaos. Building yourself is often prerequisite to helping\nothers effectively. Your self-investment isn't selfishness; it's\nfoundation.\n\nThe deepest misread is that you're never satisfied. You are satisfied\nby progress. The goal isn't the point; the trajectory is. They want you\nto arrive and stop; you know that arriving is just the beginning of the\nnext journey. That's not dissatisfaction. That's understanding how\ngrowth works.",
  "hiddenSuperpower": "You can reverse-engineer any personal goal into concrete steps and\nactually execute them. While others dream vaguely about \"someday,\"\nyou've got the timeline, the milestones, and the daily actions mapped\nout. You turn abstract desires into reality through sheer systematic\nintention.\n\nThis isn't common. Most people have goals they'll never achieve\nbecause they've never broken them down into actionable sequences. You\ndo this automatically. The gap between wanting and having is, for you,\njust a project management problem, and you're a natural project\nmanager.\n\nYour superpower extends into discipline without force. What looks like\nwillpower to others is actually alignment for you. You're not fighting\nyourself to execute; you're doing what obviously makes sense given\nwhere you're going. The resistance others feel, you've bypassed\nthrough clarity.\n\nYou've probably accomplished things that seemed impossible to others\nbecause they didn't see the work you put in before it became visible.\nYears of preparation compressed into what looks like overnight success.\nThey see the iceberg tip; you built the whole thing.\n\nPerhaps most valuable: the ability to maintain a trajectory toward a\ngoal, even when facing obstacles that traditionally stop others.\nSetbacks are data, not verdicts. Delays are just revised timelines.\nFailures are learning opportunities for the next attempt. Your\norientation toward the future makes present obstacles feel temporary,\nbecause they are.",
  "blindSpot": "Your self-future focus might miss how your plans affect others or ignore\npresent needs for future optimization. You might climb the ladder\nefficiently while neglecting the people who matter, arriving at success\nonly to find you're alone there. The future you're building might not\nbe worth living in if you build it without paying attention to what\nmakes life meaningful now.\n\nYou may also defer happiness to a perpetually receding horizon. \"I'll\nrelax when...\" but that when keeps moving. \"I'll enjoy life\nafter...\" but after never comes. Your architecture can trap you in\npermanent preparation for a satisfaction that exists only in\nanticipation.\n\nYour concrete-future processing might struggle with present uncertainty.\nWhen the path forward isn't clear, when goals need to change, when the\nfuture becomes genuinely unpredictable, your advantage becomes\nlimitation. You're optimized for building toward; you're less equipped\nfor being with.\n\nYou might also dismiss people whose orientation is different.\nPresent-focused processors seem unambitious. Past-focused processors\nseem stuck. Other-focused processors seem diffuse. But they have access\nto things you don't, presence, wisdom, connection. Your way isn't the\nonly valid way; it's one architecture among many.\n\nFinally, your goal clarity can blind you to emerging opportunities that\ndon't fit your plan. The best thing for you might be something you\nhaven't imagined yet, but you won't see it if you're only looking\nwhere you've decided to look.",
  "frictionPatterns": "You clash most intensely with Abstract-Past-Other processors (Idealized\nprofile). They're focused on collective history and inherited\nprinciples, looking backward and outward while you're looking forward\nand inward. They seem stuck in tradition to you; you seem to ignore\nwisdom to them.\n\nThe friction is structural. They trust what's been proven collectively;\nyou trust what you're building personally. They want to preserve; you\nwant to progress. Neither is wrong, you're optimizing for different\ntemporal horizons with different reference frames.\n\nPresent-focused processors of any type may frustrate you. They're\ncontent with now; you're building toward then. Their presence feels\nlike stagnation to you; your future-focus feels like absence to them.\nYou want them to plan; they want you to arrive.\n\nOther-focused processors may experience your self-focus as selfish.\nThey're tracking collective impact while you're engineering personal\noutcomes. What's purpose to them feels like distraction to you; what's\nfocused to you feels narrow to them.\n\nPast-focused processors will challenge your forward orientation. They\nwant to know what's worked before; you want to know what could work\nnext. They see your innovation as recklessness; you see their precedent\nas limitation.",
  "energyPatterns": "What Drains You:\n\n• Environments with no clear advancement path\n\n• Being dependent on others' timelines\n\n• Wasted time that could be invested\n\n• People who don't take their own goals seriously\n\n• Having to slow down for group process\n\n• Waiting without progress\n\n• Unpredictable environments that defeat planning\n\n• Goals blocked by factors outside your control\n\nWhat Charges You:\n\n• Progress toward defined objectives\n\n• Personal development that compounds\n\n• Autonomy over your own trajectory\n\n• Milestones met and exceeded\n\n• The discipline of delayed gratification paying off\n\n• Clear path from here to there\n\n• Control over your own schedule\n\n• Seeing your plans materialize\n\n• Investment in yourself yielding returns",
  "workEnvironments": "You thrive in environments that reward individual achievement and offer\nclear advancement paths. Entrepreneurship, sales, professional\ndevelopment, skilled specialization, and any domain where your effort\ndirectly determines your outcomes fit your cognitive architecture.\n\nYou excel when you control your trajectory, when what you do determines\nwhere you go. Meritocratic environments where results matter more than\npolitics, tenure, or relationships play to your strengths. You'll\noutwork and out-plan competition when the game rewards that.\n\nYou struggle in environments where advancement is opaque, political, or\ndisconnected from individual effort. Bureaucracies that promote by\nseniority, organizations where success depends on factors you can't\ncontrol, and any role that caps your growth will feel suffocating.\n\nKey environmental factors: clear success metrics, individual\naccountability, advancement opportunity, autonomy over method, and\nvisible connection between effort and outcome.",
  "blockIndicators": "Your Parser Profile suggests the following CBI block accessibility\npattern:\n\nLikely High-Accessibility Blocks:\n\n• Sequential Processing (planning and execution)\n\n• Self-Reference Processing (strong personal goal orientation)\n\n• Pattern Recognition (reverse-engineering success paths)\n\nLikely Moderate-Accessibility Blocks:\n\n• Perceptual Discrimination (concrete detail tracking)\n\n• Spatial Relationships (practical, hands-on)\n\n• Generative Creation (ideation in service of goals)\n\nLikely Lower-Accessibility Blocks:\n\n• Social Signal Processing (other-focus less emphasized)\n\n• Symbolic Manipulation (abstract reasoning without concrete\napplication)\n\nThis pattern suggests your cognitive architecture is optimized for\npersonal achievement, goal execution, and deliberate self-development.\nYou're wired to see your future clearly, reverse-engineer paths to get\nthere, and execute consistently over time.\n\nDevelopmental opportunities exist in present-moment awareness and\nother-focus, building capacity to inhabit now without always building\ntoward later and expanding attention to include impact on others. Your\nachievement orientation provides drive from which to explore these\ndimensions without losing your core engine.\n\nINTENTIONAL",
  "strengths": [
    {
      "title": "Reverse-Engineering Mastery",
      "description": "You can take any personal goal and work backward to identify the\nconcrete steps required to achieve it. Where others see distant\noutcomes, you see project plans. Where they feel overwhelmed by the gap\nbetween here and there, you're already mapping the path. This isn't\njust planning, it's translation of vision into sequence."
    },
    {
      "title": "Delayed Gratification Capacity",
      "description": "You can invest now for returns later without losing motivation. The\nfuture reward is real enough to you that present sacrifice doesn't feel\nlike deprivation, it feels like investment. This capacity to defer is a\ngenuine competitive advantage; most people can't hold the future real\nenough to trade present pleasure for it."
    },
    {
      "title": "Consistent Execution",
      "description": "You don't just plan; you do. Day after day, brick after brick, you\nexecute against your objectives with a consistency that accumulates into\nsignificant achievement. This isn't willpower as others experience it,\nwhite-knuckling against resistance. It's alignment. You're doing what\nmakes sense given where you're going."
    },
    {
      "title": "Milestone Thinking",
      "description": "You naturally break large objectives into measurable checkpoints. This\nmakes enormous goals manageable and provides regular feedback on\nprogress. While others are overwhelmed by the mountain, you're focused\non the next camp. Each milestone reached reinforces the path."
    },
    {
      "title": "Resource Optimization",
      "description": "You treat time, energy, money, and attention as resources to be\nallocated strategically toward your goals. Waste bothers you.\nInefficiency frustrates you. You're constantly optimizing, not from\nanxiety, but from clarity about what you're building and what that\nbuilding requires."
    },
    {
      "title": "Self-Investment Orientation",
      "description": "You prioritize personal development because you understand compound\nreturns. Skills built today pay dividends for decades. Knowledge\nacquired now becomes foundation for future capability. You invest in\nyourself the way smart investors invest in assets, for long-term\nappreciation."
    }
  ],
  "challenges": [
    {
      "title": "Present-Moment Sacrifice",
      "challenge": "Your future-focus can cause you to defer joy, connection, and\nrest because they don't advance your goals. The present becomes merely\na construction zone for the future. You might arrive at your destination\nhaving missed the journey entirely.",
      "remedy": "Schedule presence deliberately. Block time for experiences that\nhave no goal except being experienced. Treat present-moment living as\nits own investment, in relationships, in memories, in the capacity for\nenjoyment that makes achievement meaningful. The future you're building\nneeds a self that can inhabit it fully."
    },
    {
      "title": "Relationship as Obstacle",
      "challenge": "People can feel like friction in your trajectory, slowing you\ndown, diverting resources, complicating your clean plans. You might\ndeprioritize relationships or optimize them instrumentally, losing\nconnection that can't be scheduled.",
      "remedy": "Reframe relationship as infrastructure. The people who matter\naren't obstacles to your goals, they're part of what makes goals worth\nachieving. Invest in relationships the way you invest in skills:\ndeliberately, consistently, for long-term returns. Isolation at the top\nof your mountain isn't success."
    },
    {
      "title": "Rigidity Under Disruption",
      "challenge": "When circumstances disrupt your plans, you might struggle\nmore than present-focused processors. Your architecture depends on a\nrelatively predictable future. When that future shifts fundamentally,\nyou can feel unmoored in ways others don't.",
      "remedy": "Build adaptive capacity into your planning. Include\ncontingencies. Practice pivoting on small disruptions so you're\nprepared for large ones. Your planning strength doesn't require a fixed\ndestination; it can apply to navigating changing terrain. Flexibility is\na skill you can intentionally develop."
    },
    {
      "title": "Others' Timelines",
      "challenge": "You're operating on a longer timeline than most people\naround you. This can create friction; they want results now; you're\nbuilding for later. They may see your investment phase as delay, your\npreparation as procrastination, your patience as passivity.",
      "remedy": "Communicate your timeline explicitly. Help others see the\nstructure you're building so your current actions make sense. When\ntimelines genuinely conflict, negotiate, but don't abandon your longer\nhorizon to match their shorter one. Your architecture is valid; it just\nneeds translation."
    },
    {
      "title": "Goal Attachment",
      "challenge": "You can become so identified with specific goals that missing\nthem feels like identity failure, not just outcome failure. The goal\nbecomes who you are rather than what you're doing. This makes pivoting\npainful and failure devastating.",
      "remedy": "Separate identity from objectives. You're not your goals;\nyou're someone capable of setting and pursuing goals. That capacity\npersists regardless of specific outcomes. Practice releasing goals that\nno longer serve, and notice: you're still you. The builder is more\nfundamental than any building."
    },
    {
      "title": "Comparative Measurement",
      "challenge": "Your clear goals create clear metrics, which invite\ncomparison. You might measure yourself against others' progress, or\nmeasure your reality against an idealized timeline, generating\ndissatisfaction that undermines the very pursuit you care about.",
      "remedy": "Measure against your own baseline, not others' outcomes.\nProgress is personal. Someone else's faster timeline might reflect\ndifferent starting points, different resources, different goals. Your\nonly valid comparison is yesterday's you versus todays you. That's the\ndata that matters."
    }
  ]
};
