// INTROSPECTIVE Profile — Young Adult (18–29)
// Parser Profile™ © 2026 Cognition Blocks LLC

export const introspectiveyaProfile = {
  "name": "INTROSPECTIVE",
  "tagline": "The one who's always watching their own mind work",

  "overview": "You're walking back from class, earbuds in but no music playing, and you're already three layers deep into your own head—noticing the thought, then noticing yourself noticing it, then wondering why that's where your brain went. This isn't something you turned on. It's just where you live. Everyone else seems to be on the surface of their own mind; you've always been somewhere lower down.\n\nPeople have told you that you \"think too much\" since you were a kid. The roommate who can fall asleep in two minutes. The friend who shrugs off the thing that's been looping in your chest for three days. You used to believe them, that something was wrong with how much you turned inward. Then you realized half of them barely check in with themselves at all.\n\nIt's not anxiety, even though people lump it in with that. It's more like there's a quiet channel always running, watching how you actually felt about that text, why you said yes when you meant no, where the real reason underneath the surface reason is hiding.\n\nThey call it overthinking. You've sat with that word a lot, turning it over. And what you keep landing on is: you're not overthinking, you're just thinking at a depth that makes other people uncomfortable, because it shows them how little they look at themselves.",

  "howYouLearn": "You learn by sitting with something until it actually means something to you. A professor can lecture for an hour and it slides right off, but give you one real question to chew on during a long walk and you'll come back with more than the slides ever held. The stuff that sticks isn't what you memorized—it's what you reconstructed in your own head until it clicked.\n\nGroup study sessions kind of wreck you. Everyone's talking fast, staying on the surface, and you can feel yourself getting pulled up out of the deep end where you actually do your best thinking. You need to go off alone, read it slow, let it settle. A psych chapter or a philosophy thread online will hook you for hours; a how-to-fill-out-this-form tutorial loses you in two minutes.\n\nThe honest catch is that not everything deserves the depth you bring to it. Some classes are just procedural, some tasks just need doing, and you can burn a whole afternoon trying to find meaning in something that was always meant to be shallow. You'll go looking for the deeper layer in stuff that doesn't have one.\n\nSo the thing that makes you good—needing to understand it all the way down before you trust it—is also the thing that makes the boring-but-necessary parts of being a student or a new hire feel almost impossible. You're not lazy. You just can't make yourself care about something your mind can't get underneath.",

  "howYouCommunicate": "You can put words to inner stuff that most people your age can't even locate. The exact difference between feeling lonely and feeling alone. The specific flavor of dread before a hard conversation versus before a deadline. You name the things other people just feel as a vague bad mood, and when you get it right out loud, it can stop someone in their tracks.\n\nSmall talk, though, is almost physically hard for you. The \"how was your weekend, good, you?\" loop feels like a waste of the one tool you actually have. At parties you sometimes just go quiet, not because you're shy, but because engaging at that level feels like running an engine in neutral. People read the silence as you being stuck-up or awkward.\n\nWhere you come alive is the 2am conversation, the one friend who'll actually go all the way down with you. You ask the question nobody else thought to ask, you notice the thing under the thing they said, and those talks can genuinely change how someone sees their own life. You'd trade a hundred surface hangouts for one of those.\n\nThe hard part is reading when someone actually wants that and when they were just making conversation. You've watched people's eyes glaze over mid-sentence enough times that now you sometimes give a flatter, easier version of yourself just to fit the moment—and then feel a little fake for doing it.",

  "phrase": "You're not overthinking. You're thinking at a depth that scares people, because it shows them how rarely they look at themselves at all.",

  "secret": "There's a loneliness in this that's hard to explain to anyone, because explaining it requires the exact depth that loses them.\n\nYou understand things about yourself that some people won't reach in their whole lives, if ever. You've caught your own patterns mid-spiral. You've traced why you do the thing you keep promising to stop doing. You've watched yourself get defensive in real time and known exactly what nerve got hit. You've done the work people pay therapists years to even approach—and you did it alone, in your head, walking around campus.\n\nBut none of it translates. You try to tell a friend what's actually going on inside you and you can watch them reach for their phone, or change the subject, or say \"you're so deep\" in a way that ends the conversation instead of opening it. The thing that feels like real connection to you—sharing the actual texture of what's happening in your mind—reads as \"a lot\" to almost everyone.\n\nThe deepest part, the part you've turned over at 3am: sometimes you wonder if all this watching is just a really sophisticated way of not living. If you're examining your life so closely because it's easier than going out and having one. You don't think that's it. But you've thought about thinking about it more than you'd ever say out loud.",

  "whatOthersGetWrong": "They think you're checked out or lost in your head when you're actually taking in more of the moment than they are, just on a channel they can't see. Your quiet isn't absence. You're tracking dimensions of the room they filtered out the second they walked in.\n\n\"You overthink everything\" gets thrown at you like a diagnosis. But under-thinking isn't some healthier state—it's just a different way of getting things wrong. People who never examine themselves aren't more well-adjusted; they're just more surprised by their own behavior. Your depth isn't a malfunction. It's the whole engine.\n\nYou've been told to \"get out of your head\" by people who would genuinely benefit from spending five minutes in theirs. You've been called intense by people who treat their own mind like a hallway they sprint through. And you've been called self-absorbed when what you actually are is self-aware, and those are not even close to the same thing.\n\nThe biggest miss is the assumption that because you turn inward, you can't connect. You connect harder than most people—you just do it through depth instead of width. One conversation that reaches the bottom beats a hundred that skate the surface, and you've quietly known that since high school.",

  "hiddenSuperpower": "You can watch your own mind while it's running. Most people get carried off by a thought before they even notice it started; you can see the thought form, clock the bias steering it, and step in before it drives. You catch yourself about to send the regrettable text. You notice the jealousy as jealousy instead of acting it out. You debug yourself in real time, where everyone else only figures it out in hindsight, if at all.\n\nThat's what makes you able to actually change. Most people try to fix themselves with willpower, swinging a hammer at a problem they can't quite see. You can see exactly where the wiring is—so you can change it with a precision tool. You know the precise moment you start self-sabotaging, which means you know precisely where to interrupt it.\n\nYou also have an inner compass that doesn't need anyone's approval to point. When the whole group is hyped about something that feels off to you, you can check it against your own examined sense of things instead of just going along. You know what you know because you've actually looked at it, not because everyone around you agreed.\n\nAnd maybe the most underrated part: you're genuinely okay alone. While people your age are terrified of an empty Friday night, of being left with just their own thoughts, your own company is rich. Your relationship with yourself is real and built. That's rarer at your age than anyone admits.",

  "blindSpot": "Sometimes the thinking stops yielding anything and just spins. Thinking about the feeling, then thinking about why you're thinking about the feeling, then analyzing the analysis—and somewhere back there it quit producing insight and started producing fog. The hard part is you can't always feel the moment it crossed from useful into a loop, because it all feels like the same deep work.\n\nYou can also mistake your map of yourself for the actual you. You've got such a detailed self-image that when something doesn't fit it—someone points out a pattern you don't recognize, you act in a way that's off-script—you can wave it off because it contradicts the story. The map is incredible. It's still just a map.\n\nBecause you live so far inside, the outside can get neglected without you noticing. The friend you meant to text back, the thing future-you needed present-you to handle, the relationship that needed actual tending and not just understanding—those quietly slide while you're spelunking. You give yourself the deep attention; the world outside you can starve.\n\nAnd the closest one to catch: you can turn a feeling into a thing to analyze instead of a thing to feel. You'll map your own heartbreak in stunning detail and somehow never actually let yourself cry. Understanding your anger isn't the same as being angry. Sometimes the most honest thing is to drop the observer and just be in it.",

  "frictionPatterns": "You grate against the people who measure everything by output—the roommate who thinks a day spent thinking is a day wasted, the group-project partner who reads your need to actually process before acting as you dragging your feet. They do for others, they stay busy, they keep moving; you go inward first. To them you look impractical and self-involved. To them, you're navel-gazing while real life happens.\n\nThe honest version is that neither of you is fully wrong. They genuinely do process by doing, by staying in motion and serving the thing in front of them. You genuinely do process by going still and turning it over. They think your introspection is a way of dodging responsibility. You think their nonstop activity is a way of dodging ever looking at themselves. There's truth in both, and that's what makes it sting.\n\nThe concrete, just-give-me-the-steps people struggle with you too. You're off in abstract territory they don't value or can't even see, and your inner world is so vivid to you and so invisible to them that you each kind of suspect the other is missing the point.\n\nWhat you actually bring to all this is real: your depth can help someone reach a part of themselves they've been avoiding for years. The growth edge is admitting that being focused outward, and on the future, isn't a failure of self-awareness—it's just a different orientation, with its own kind of intelligence you don't naturally respect.",

  "energyPatterns": "What drains you:\n- Settings that treat thinking time like slacking off\n- Being pushed to act before you've actually processed anything\n- Getting called self-absorbed when you were just being self-aware\n- Someone flattening a complicated inner thing into a dumb hot take\n- Small talk that stays small the whole night\n- A long social stretch where you have to perform surface-level energy\n\nWhat charges you:\n- A long stretch of uninterrupted time inside your own head\n- Understanding yourself reaching a layer you hadn't reached before\n- Catching a pattern in your own mind as it actually happens\n- A conversation that goes all the way to the bottom\n- The one friend who can actually match you in the deep end\n- Solitude that feels like company instead of being lonely",

  "workEnvironments": "Where you thrive:\n- Work that rewards going deep instead of just going fast\n- Anything close to psychology, writing, counseling, ideas, meaning\n- Roles that give you real reflection time instead of constant pings\n- A small, quiet team that doesn't treat thinking as a luxury\n- Places that judge the quality of your thought, not your visible busyness\n\nWhere you suffocate:\n- All speed, all output, zero space to actually process\n- A job that's just reacting to whatever blew up in the last five minutes\n- Open-plan chaos with no door and no quiet anywhere\n- Cultures that treat looking busy as the same thing as being good\n- Surface-level work that never asks for anything underneath",

  "topCareers": [
    {
      "title": "Peer Counselor / Mental Health Support Role",
      "description": "You already understand your own inner world at a level most people never reach, and that's exactly what lets you sit with someone in theirs. Entry roles like peer counseling, a crisis text line, or a mental-health support job run on that—being able to dive instead of skim, to stay with someone's hard stuff without flinching. You're the friend people already come to at 2am when everything's falling apart. The intensity of self-watching that made you feel like too much in a dorm becomes the actual skill the work is built on, and it pays you to keep getting better at it."
    },
    {
      "title": "Writer / Content Creator on Depth Topics",
      "description": "You can put words to inner experience that most people only feel as a fog, and there's a real audience hungry for exactly that. Starting a newsletter, a blog, a video channel, or just writing essays about how minds actually work rewards your depth instead of punishing it. You get to stay with a question past the point where everyone else needs a tidy answer. The thing that made small talk painful—you only come alive below the surface—is the entire foundation of writing that people actually save and send to a friend."
    },
    {
      "title": "Research / Analyst Track (Psychology, Philosophy, UX)",
      "description": "You learn by reconstructing something in your own head until it truly clicks, and you can hold sustained attention on abstract stuff that makes other people bail. Entry research jobs, lab assistant roles, or junior analyst work in human-focused fields reward that patient, go-all-the-way-down processing. You see the layer under the obvious one. The depth-over-breadth wiring that made fast group projects miserable is the exact thing that makes you genuinely good here over time, where being thorough and reflective is the point, not a bottleneck."
    }
  ],

  "blockIndicators": "Your Parser Profile suggests the following CBI block accessibility pattern:\n\nLikely High-Accessibility Blocks:\n- Self-Reference Processing (your native mode)\n- Pattern Recognition (abstract internal patterns)\n- Symbolic Manipulation (philosophical reasoning)\n\nLikely Moderate-Accessibility Blocks:\n- Generative Creation (internal ideation)\n- Spatial Relationships (abstract conceptual space)\n\nLikely Lower-Accessibility Blocks:\n- Sequential Processing (external task execution)\n- Perceptual Discrimination (concrete external details)\n- Social Signal Processing (other-focus may be underdeveloped)\n\nThis pattern suggests your cognitive architecture is optimized for contemplative depth and going all the way down on the questions that matter, with room to grow in turning some of that attention outward—toward other people and the future—before your inner world quietly absorbs all of it.\n\nINTROSPECTIVE",

  "strengths": [
    {
      "title": "You Can Watch Your Own Mind",
      "description": "You catch your own thoughts while they're still forming—the bias steering you, the spiral starting up, the about-to-be-regretted decision. Most people only see it in hindsight. You can step in mid-thought and change course, which means you can actually fix things in yourself instead of just being surprised by them later."
    },
    {
      "title": "Present-Moment Depth",
      "description": "When you're actually in a moment, you're all the way in it—not at the surface, but down where it actually means something. While everyone else is half-here, half-scrolling, you're reading the real texture of what's happening. It's why a quiet moment can hit you with more weight than a whole loud night hits other people."
    },
    {
      "title": "Your Own Compass",
      "description": "You don't need the group to approve something for you to trust your read on it. You can hold your own experience up against your own examined standards instead of just social consensus, which makes you weirdly hard to peer-pressure or sell. When everyone's hyped about something off, you can still feel your own no."
    },
    {
      "title": "The Big Questions Don't Scare You",
      "description": "The stuff that makes other people anxious or bored—what's the point, who am I really, what does any of this mean—is genuinely interesting to you, not a panic spiral. You can sit in those questions like they're a place to explore, not a problem to flee. That's rare, and it ages well."
    },
    {
      "title": "You Actually Know Yourself",
      "description": "You've mapped territory in yourself that most people don't even know is there. Your patterns, your defenses, your real reasons under the surface ones—you've looked at all of it. That self-knowledge is the foundation everything else gets built on, and it means you grow when other people just repeat themselves."
    },
    {
      "title": "Built for Solitude",
      "description": "An empty weekend doesn't scare you the way it terrifies your friends. Your own company is rich—your inner world genuinely keeps you company. While people your age panic at being alone with their thoughts, you've already built a real relationship with yourself, and that steadiness shows up everywhere else in your life."
    }
  ],

  "challenges": [
    {
      "title": "The Spiral That Stops Going Anywhere",
      "challenge": "Sometimes the thinking quits producing anything new and just loops—you're analyzing the analysis, three layers past where any insight was, and it all still feels like deep work so you don't notice you're just spinning in fog at 2am.",
      "remedy": "Build an exit. Ask yourself: have I actually learned anything new in the last ten minutes, or am I just circling? When it's circling, force it out of your head—write the one sentence down, text it to someone, or just go do a dish. Externalizing it breaks the loop."
    },
    {
      "title": "Mistaking Your Self-Image for Yourself",
      "challenge": "You've got such a detailed story of who you are that when someone points out a pattern you don't recognize—or you act in a way that's off-script—you wave it off because it doesn't fit the map. The map is incredible. It's still not the actual territory.",
      "remedy": "Go get outside data. Ask two or three people you trust: \"what do you see in me that I might be missing?\" Their view isn't more true than yours, but it's positioned differently. Triangulate. Your self-knowledge is powerful and still incomplete on its own."
    },
    {
      "title": "The Outside World Quietly Starving",
      "challenge": "You live so far inside that the unanswered texts pile up, the friend you meant to check on drifts, and future-you keeps inheriting things present-you was too deep to handle. Your inner life gets all your attention while everything external slowly goes neglected.",
      "remedy": "Schedule the outward stuff so it isn't optional. Put a standing hangout on the calendar. Block twenty minutes a week to handle future-facing tasks—signups, money, plans. You won't naturally point your attention outward, so build a system that does it for you."
    },
    {
      "title": "Analyzing the Feeling Instead of Feeling It",
      "challenge": "You'll map your own heartbreak in beautiful detail and somehow never actually cry. Your mind turns the emotion into a thing to study, which puts a pane of glass between you and it. Understanding your grief is not the same as grieving it.",
      "remedy": "Practice dropping the observer. When something hits, try just feeling it with zero commentary—no analyzing, no narrating. Pick moments where you deliberately turn the watching off. The examined life has to include the part where you stop examining and just live it."
    },
    {
      "title": "When Nobody Can Receive the Real You",
      "challenge": "You open up at your actual depth and watch their eyes glaze, or they change the subject, or they call you \"so deep\" in a way that closes the door. What feels like connection to you keeps landing as \"too much\" to them.",
      "remedy": "Read the room before you dive. Share in layers—start at the surface, go deeper only when they actually invite it. And put real effort into finding your few: the rare people who can match your depth. With them you don't have to perform a shallower version of yourself."
    },
    {
      "title": "When Being Alone Becomes Hiding",
      "challenge": "Your comfort with solitude is a gift, but it can quietly turn into avoidance—pulling inward to think when what the moment actually needed was you showing up for something or someone outside your own head.",
      "remedy": "Check the motive. Ask: am I alone because it's feeding me, or because I'm dodging something? Real solitude feels nourishing; avoidant solitude feels like hiding, and the difference is subtle but real. When you catch the hiding, push toward one external thing before you retreat back in."
    }
  ]
};
