// INTUITIVE Profile
// Parser Profile™ © 2026 Cognition Blocks LLC
// Abstract • Present • Other

export const intuitiveProfile = {
  "name": "INTUITIVE",
  "code": "Abstract • Present • Other",
  "tagline": "The social reader who knows before being told",
  "overview": "You know things about people that you have no business knowing. Not\nthrough investigation or deduction, through perception so immediate it\nfeels like receiving rather than analyzing. You walk into a room and\nunderstand the relational landscape: who trusts whom, who's pretending,\nwhere the real alliances lie beneath the official ones. This knowing\narrives whole, wordless, and almost always accurate.\n\nYour cognitive architecture prioritizes abstract patterns over concrete\ndetails, present experience over past or future, and the experience of\nothers over your own internal states. The result is a consciousness that\noperates like a social radar, continuously scanning for interpersonal\nsignals, processing them at a conceptual level, and generating\nunderstanding that feels more like intuition than analysis.\n\nThis isn't empathy in the conventional sense. Empathy suggests feeling\nwhat others feel. You're doing something different: perceiving the\npatterns of feeling, the shapes of relationship, the dynamics beneath\nthe surface. You see the system of social reality, not just its\nindividual nodes. This is why you often understand relationships better\nthan the people inside them.\n\nThe Intuitive profile represents approximately 4% of the population.\nYour rarity comes from the specific combination: abstract processing\n(pattern over detail), present focus (what's happening now), and\nother-orientation (attention directed outward). Most social processors\nare more concrete, tracking specific behaviors rather than relational\npatterns. Most pattern recognizers are more self-referential. You occupy\nan unusual perceptual position.\n\nYour gift is social sight that operates in real time. Your challenge is\nthat you may know more about others than is comfortable, for them or for\nyou. And because your attention naturally flows outward, you may remain\na mystery to yourself while understanding everyone else clearly.\n\nUnderstanding your profile means recognizing that your social perception\nisn't intuition in the mystical sense, it's pattern recognition\napplied to interpersonal data at a resolution others don't access.\nYou're not psychic. You're perceptive in ways that can feel like the\nsame thing.",
  "howYouLearn": "You learn through observing people in action. Theories about human\nbehavior interest you, but they become real only when you can watch them\noperate in actual interactions. You extract principles from observation\nrather than applying principles to observation.\n\nYour optimal learning environment puts you in proximity to human\ndynamics, mentorship relationships where you can watch experts navigate\ncomplexity, group settings where you can observe how different people\nhandle the same situation, any context that provides rich interpersonal\ndata for your processing to work with.\n\nYou struggle with learning that's purely abstract or decontextualized\nfrom human application. Theories without people bore you. You also\nstruggle when learning requires extensive self-reference, tracking your\nown process, analyzing your own reactions. Your attention naturally\nflows outward; turning it inward takes deliberate effort.\n\nCase studies work well. Live observation works better. Apprenticeship to\nsomeone with relational mastery works best. You learn by watching how\nit's done, extracting the patterns, and integrating them into your own\nrepertoire. Explanations about what works matter less than\ndemonstrations of working.",
  "howYouCommunicate": "You communicate with embedded social awareness. You're not just\nconveying information, you're tracking how it's landing, adjusting in\nreal time, responding to reactions before they're verbalized. This\nmakes you an adaptive communicator who can meet people where they are,\noften without them realizing you've adjusted.\n\nYou may struggle to communicate your social perceptions directly. What\nyou know arrives as pattern recognition, not verbal proposition.\nTranslating \"I can see the whole relational system\" into sentences\nthat make sense to others is effortful and often incomplete. You may\nsettle for vague gestures toward what you perceive, \"something's\noff,\" \"be careful with her\", that don't convey the richness of your\nunderstanding.\n\nIn groups, you often function as an implicit facilitator, reading\ndynamics and subtly steering toward better outcomes without taking\nobvious leadership. You might not realize how much you're doing until\nyou're not there to do it and things fall apart.\n\nYou communicate best in contexts where social intelligence is valued and\nwhere your implicit knowledge can be trusted even when it can't be\nfully explained. You communicate least effectively in environments that\ndemand explicit justification for everything, where knowing without\nevidence is treated as suspicious rather than valuable.",
  "phrase": "You're not imagining things, you're perceiving things others miss.\nYour knowing isn't paranoia; it's pattern recognition operating faster\nthan language.",
  "secret": "You've always seen behind the curtain. As a child, you watched adults\nperform for each other and understood it was performance. You saw the\npolitics in your family before you had words for politics. You knew when\nyour parents' friends didn't actually like each other, when teachers\nplayed favorites while claiming fairness, when official stories were\ncovers for messier truths.\n\nThis seeing started before you could explain it or even understand that\nothers didn't share it. You assumed everyone saw what you saw. When you\nacted on your seeing, avoiding someone who seemed unsafe, questioning an\narrangement that looked wrong, adults often treated you as difficult or\nsuspicious. You learned to stop explaining why you knew things.\n\nThe secret you've carried is that people are more transparent to you\nthan they realize, and this transparency is isolating. You see their\nfears, their strategies, their hidden loyalties, and you often wish you\ndidn't. Seeing clearly doesn't mean seeing kindly. You perceive\npeople's limitations alongside their gifts, their manipulations\nalongside their generosities. This full picture can make simple\nconnection feel impossible.\n\nYou've also carried the loneliness of being perpetually the one who\nunderstands. Others feel known by you without ever knowing you back.\nYou've been the keeper of other people's secrets, the reader of rooms\nthat couldn't read you. And you've wondered if something is wrong with\nyou, if your way of seeing is a gift or a curse, a capacity or a problem\nto be solved.",
  "whatOthersGetWrong": "About You\n\nThey think you're judging them because you see them clearly. Your\nperception feels like scrutiny, and people project negative evaluation\nonto your attention. They don't understand that seeing clearly isn't\nthe same as judging harshly, that you can perceive someone's\nlimitations and still value them, that transparency doesn't mean\ncondemnation.\n\nThey think you're manipulative because you read social situations so\nwell. Skill at perceiving dynamics looks like skill at exploiting them.\nThey confuse your capacity with your intention, assuming that because\nyou could manipulate, you are manipulating. They don't understand that\nperception isn't predation.\n\nThey think you're cold because you see patterns rather than getting\nswept into emotion. Your abstract processing creates slight distance\nfrom the raw affect others might express. You care deeply, you just\nprocess caring through pattern recognition rather than emotional\ncontagion. Others mistake this for detachment.\n\nThey think your knowing is a party trick rather than a way of being.\nThey want you to perform it on command, \"read that person,\" \"tell me\nwhat's going on\", without understanding that your perception is\nconstant, not summoned. You don't turn it on; you can barely turn it\noff. Their requests miss that this is how you exist, not something you\ndo.",
  "hiddenSuperpower": "You can perceive relational systems that others experience only as\nconfusion or pain. When someone is caught in a dysfunctional dynamic, a\ntoxic workplace, a troubled family, a manipulative relationship, they\nusually can't see it clearly because they're inside it. You can see\nthe whole pattern from outside, even while standing next to them.\n\nThis systemic perception makes you invaluable for helping people\nunderstand what they're caught in. Not by analyzing them, but by\ndescribing what you see: \"Here's the pattern. Here's how it operates.\nHere's why it feels the way it feels.\" When you name the system\naccurately, people often experience profound relief, finally, someone\nsees what they've been unable to articulate.\n\nYou also perceive potential, not just current relational reality but\npossible relational reality. You see what connections could become, how\ngroups could function, what relationships could offer if certain\npatterns shifted. This vision of relational possibility lets you\nfacilitate growth that neither party could have imagined alone.\n\nYour perception isn't just diagnostic. It's generative. By seeing\nclearly, you help others see more clearly too. Your attention creates\nconditions for relational reality to become more visible to everyone,\nnot just you.",
  "blindSpot": "You may trust your social perception so completely that you miss when\nit's wrong. Pattern recognition is probabilistic, not certain, and your\nconfidence in your reading can prevent you from noticing exceptions,\nupdating on new data, or accepting that someone has changed. Your\nperception is excellent but not infallible.\n\nYou may also neglect yourself to the point of crisis. Your attention\nflows so naturally outward that you can ignore your own needs until they\nbecome emergencies. You track others' wellbeing while losing track of\nyour own. By the time you notice you're depleted, you may be too\ndepleted to recover easily.\n\nYour other-focus can become a way of hiding. By making yourself the one\nwho understands rather than the one who is understood, you stay safe\nfrom the vulnerability of being truly seen. Your social perception is\nreal, but it may also serve a protective function, keeping you in the\nobserver position where you can't be hurt the way you could be if you\nwere fully inside relationship.\n\nAnd you may undervalue information that requires self-reference. Your\nown history, your own patterns, your own contributions to dynamics\nyou're perceiving, these can be harder for you to see than others'\npatterns. The most complete relational picture includes you, but your\narchitecture makes it easier to see everyone else.",
  "frictionPatterns": "You clash most with Concrete • Past • Self (Sharp) processors. They're\nanchored in specific personal experience from their own history; you're\nperceiving abstract relational patterns in others right now. They think\nyou're projecting or imagining things. You think they're trapped in\ntheir own perspective without seeing the larger system. The conflict is\nConcrete vs. Abstract, Past vs. Present, Self vs. Other, opposition on\nall three dimensions.\n\nYou also experience friction with those who demand explicit\njustification for every assessment. Your knowing arrives as pattern\nrecognition, not evidence chains. Environments that treat \"I can't\nexplain how I know\" as disqualifying rather than as a different way of\nknowing will frustrate and dismiss you.\n\nHeavy self-focused processors may feel invaded by your attention. Your\nother-orientation means you're naturally tracking them; their\nself-focus means they're naturally tracking themselves. Your perception\ncan feel like intrusion to those who aren't used to being seen from\noutside their own perspective.",
  "energyPatterns": "What Energizes You:\n\n• Relational complexity you can perceive and understand\n\n• Helping others see the systems they're caught in\n\n• Environments where social intelligence is valued\n\n• Connection with others who can read you back\n\n• Witnessing relational repair and growth\n\nWhat Drains You:\n\n• Environments dense with irrelevant social data\n\n• Having your perception dismissed or pathologized\n\n• Relationships where you always understand more than you're understood\n\n• Pretending not to see what you clearly see\n\n• Neglecting yourself while tracking everyone else",
  "workEnvironments": "You thrive in environments where social perception is the job, coaching,\ntherapy, organizational consulting, mediation, diplomacy, human-centered\ndesign, any role requiring understanding of how people work together or\nfail to. You also thrive as the relational intelligence behind leaders\nwho lack it, translating social dynamics into strategic understanding.\n\nYou struggle in environments that deny the validity of interpersonal\nperception, highly technical cultures that dismiss \"soft skills,\"\norganizations that pretend politics don't exist, any context where your\nseeing is treated as distraction rather than value. You also struggle in\nenvironments so chaotic with interpersonal information that you can't\nfilter or recover.\n\nIdeal factors: valued social intelligence, complex human dynamics to\nunderstand, colleagues who respect perception they don't share, space\nfor recovery after high-information environments. Avoid: denial of\nrelational reality, demand for explicit justification of implicit\nknowing, environments that saturate your processing without recovery\nopportunity.",
  "blockIndicators": "Your Parser Profile suggests the following CBI block accessibility\npattern:\n\nLikely High-Accessibility Blocks:\n\n• Social Signal Processing (your native mode)\n\n• Pattern Recognition (abstract relational patterns)\n\n• Perceptual Discrimination (social signals and cues)\n\nLikely Moderate-Accessibility Blocks:\n\n• Generative Creation (perceiving relational possibility)\n\n• Symbolic Manipulation (conceptual processing of social data)\n\n• Sequential Processing (tracking how dynamics unfold)\n\nLikely Lower-Accessibility Blocks:\n\n• Self-Reference Processing (attention flows outward, not inward)\n\n• Spatial Relationships (abstract orientation de-emphasizes concrete\nspatial processing)\n\nThis pattern suggests your cognitive architecture is optimized for\nsocial intelligence and relational systems perception. Your\ndevelopmental opportunities lie in self-reference, building capacity to\nturn inward with the same quality of attention you naturally give\nothers, and in concrete grounding when abstract social pattern\nrecognition needs anchoring in specific evidence. The most mature\nversion of your architecture includes yourself in the relational picture\nyou perceive so clearly.",
  "strengths": [
    {
      "title": "Real-Time Relational Perception You perceive social dynamics as they",
      "description": "unfold, not retroactively. While others reconstruct what happened in a\nconversation after it ends, you're tracking the shifts as they occur,\nthe moment trust forms or fractures, the instant someone decides\nsomething they haven't announced. This real-time processing gives you\nsocial information others never access."
    },
    {
      "title": "Pattern Recognition Across People You see how people relate not just",
      "description": "to you but to each other and to groups. You perceive the system, not\njust the individuals. This lets you understand dynamics that make no\nsense when you look at any single person, why certain combinations work\nor fail, how information flows, where influence actually lives."
    },
    {
      "title": "Unspoken Communication Fluency You read what isn't said as clearly",
      "description": "as what is. Tone, timing, gesture, what's avoided, what's emphasized,\nyou process these signals automatically and weight them appropriately\nagainst verbal content. When words and signals conflict, you trust your\nsignal-reading. You're usually right."
    },
    {
      "title": "Anticipatory Social Understanding Because you're tracking patterns",
      "description": "in real time, you often know where interactions are heading before they\narrive. You sense the question before it's asked, the objection before\nit's raised, the need before it's expressed. This anticipation lets\nyou respond to what's emerging rather than what's already surfaced."
    },
    {
      "title": "Group Dynamic Perception You perceive how individuals change in",
      "description": "different group configurations, who becomes more themselves with certain\npeople, who disappears, who dominates, who withdraws. You track these\ncontextual shifts that most people don't notice because they're\nfocused on individuals rather than relational systems."
    },
    {
      "title": "Implicit Trust Calibration You know who to trust and how much, often",
      "description": "without being able to explain why. Your processing generates trust\nassessments based on pattern data you may not consciously access. These\nassessments aren't paranoid or naively optimistic, they're calibrated\nto reality others miss."
    }
  ],
  "challenges": [
    {
      "title": "Self-Opacity Your attention flows so naturally outward that you may",
      "challenge": "be a stranger to yourself. You understand others' motivations, fears,\nand needs while remaining unclear about your own. The radar points\neverywhere except inward. Schedule deliberate self-attention as you\nwould attention to any important person. You're worth the same quality\nof perception you give others.",
      "remedy": ""
    },
    {
      "title": "Knowing Without Warrant You often know things you can't justify",
      "challenge": "knowing. This creates social awkwardness, you respond to what someone\nhasn't said, you avoid people you have no official reason to distrust,\nyou act on information you can't source. Others may find this\nunsettling or presume you're making things up. When your knowing\nmatters, find the concrete evidence that supports what you already\nperceive. Translate pattern recognition into shareable data.",
      "remedy": ""
    },
    {
      "title": "Boundary Confusion Your other-orientation can blur where you end and",
      "challenge": "others begin. You may take on others' emotional states without\nrealizing it, or prioritize their needs so automatically that your own\ndisappear. This isn't generosity, it's architecture without\nboundaries. Practice noticing what you want before asking what others\nwant. Your needs exist even when your attention doesn't naturally find\nthem.",
      "remedy": ""
    },
    {
      "title": "Cassandra Syndrome You see relational disasters coming that others",
      "challenge": "walk into blindly. Warning them rarely works, they don't have access to\nthe pattern data you're processing, so your warnings seem baseless or\nparanoid. You watch preventable problems unfold, knowing you couldn't\nhave prevented them. Accept that perception isn't persuasion. Your role\nmay be to understand, not to save. Witnessing accurately is its own\ncontribution.",
      "remedy": ""
    },
    {
      "title": "Intimacy Asymmetry You understand others far more than they",
      "challenge": "understand you. This creates lopsided relationships where you're\nperpetually the one who sees. Others may feel known without ever really\nknowing you in return. The intimacy is real but asymmetrical. Offer\ninformation about yourself even when others don't ask the right\nquestions. They can't read you like you read them, help them out.",
      "remedy": ""
    },
    {
      "title": "Sensory Overwhelm Your constant social processing requires",
      "challenge": "significant cognitive resources. Environments dense with interpersonal\ninformation, parties, complex group dynamics, high-conflict situations,\ncan saturate your processing capacity quickly. You see everything, which\nmeans you can't filter. Protect recovery time as infrastructure, not\nindulgence. Your perception has costs that require restoration.",
      "remedy": ""
    }
  ]
};
