// INTUITIVE Profile — Young Adult (18–29)
// Parser Profile™ © 2026 Cognition Blocks LLC

export const intuitiveyaProfile = {
  "name": "INTUITIVE",
  "tagline": "The one who already knows before anyone says it",

  "overview": "You walk into the party and within thirty seconds you know the whole map. Who's actually into whom. Which two of them are quietly not okay right now. Who's performing being fine and who really is. You didn't analyze it or piece it together—it just arrived, whole and wordless, the second you stepped in. And you're almost always right.\n\nThis has been happening your entire life. You knew which teachers played favorites while swearing they were fair. You knew when a friend group was about to split before anyone said a word. You read the text and clocked exactly what they really meant under the polite version. Your brain runs a kind of social radar you can't switch off, scanning the room and handing you the answer before you ask the question.\n\nIt isn't the same thing as being super empathetic, even though people mix those up. You're not soaking up what everyone feels—you're seeing the shape of it. The pattern. The system underneath the surface. That's why you'll sometimes understand a friend's relationship better than the two people actually in it.\n\nPeople have called it paranoia, or said you're reading into things, or told you to mind your business. You're not imagining it. You're picking up signals they filtered out, running faster than words can keep up with. The hard part isn't the seeing. It's that you often know more about people than is comfortable—for them, and for you.",

  "howYouLearn": "You learn by watching people actually do the thing. A textbook chapter on how teams work or how persuasion functions is fine, but it stays flat until you can watch it play out in a real room with real people. You pull the principle out of the moment, not the other way around. Sit you in front of a live dynamic and you'll extract more than any lecture could hand you.\n\nThat's why a good mentor beats a good syllabus for you. The manager at your first job who navigates a tense customer like it's nothing, the older student who knows exactly how to handle the group when it's about to fall apart—watching them work teaches you more than a stack of how-to videos. You learn by apprenticeship, by being close to someone who's good at the human part.\n\nWhere you stall is anything purely abstract with no people attached. Theory floating in a vacuum bores you fast. You also struggle when learning asks you to track your own process—analyze your own reactions, journal about yourself—because your attention naturally points outward. Turning it inward takes real, deliberate effort that doesn't come for free.\n\nSo case studies work, live observation works better, and shadowing someone who's genuinely good with people works best of all. You watch how it's done, you catch the pattern, and then it's quietly yours.",

  "howYouCommunicate": "You communicate with the social tracking already built in. You're not just saying the thing—you're watching how it's landing in real time, adjusting before the other person even reacts, reading the micro-flinch and changing course mid-sentence. It makes you the person who can meet someone exactly where they are, which is why people feel weirdly understood by you fast.\n\nThe frustrating part is putting your reads into words. What you know shows up as a whole pattern, not a sentence. Trying to explain \"I can just tell the vibe between them is off\" to someone who needs receipts comes out vague and incomplete, and you end up sounding like you're guessing when you're not.\n\nIn group chats and group hangs, you tend to quietly steer things—smoothing the tension nobody named, nudging the conversation off the landmine, reading the room and gently redirecting it—usually without anyone noticing you did it. You might not even realize how much of that you're doing until you're not there and it all gets messier.\n\nYou communicate best around people who trust your read even when you can't fully explain it. The friend who's learned that when you say \"I've got a bad feeling about that guy,\" it's worth listening to—that's where you can actually be yourself instead of constantly translating.",

  "phrase": "You're not reading into it. You're reading it. Your knowing isn't paranoia—it's pattern recognition running faster than anyone can put into words.",

  "secret": "You've always seen behind the curtain. As a kid you watched adults perform for each other and knew it was a performance. You clocked which of your parents' friends didn't actually like each other. You saw the politics in your own family before you had a word for politics. It started before you understood that not everyone saw what you saw—you just assumed they did.\n\nAnd when you acted on it—pulling away from someone who felt off, questioning a setup that looked wrong—grown-ups treated you like you were being difficult or suspicious. So you learned, early, to stop explaining how you knew things. You just quietly knew them and kept it to yourself.\n\nThe secret you carry is that people are way more transparent to you than they think, and that transparency is lonely. You see their fears, their little strategies, who they're really loyal to under the friendly surface. And seeing clearly is not the same as seeing kindly—you catch people's limitations right next to their best parts, the small manipulations next to the genuine warmth. The full picture can make simple, easy connection feel almost impossible.\n\nThe deepest part: you're forever the one who understands. People feel known by you and never quite know you back. And some nights you've genuinely wondered if this way of seeing is a gift or a curse, and whether something's wrong with you for having it.",

  "whatOthersGetWrong": "They think you're judging them because you see them clearly. Your attention feels like scrutiny, so people project a verdict onto it that isn't there. Seeing someone accurately and condemning them are completely different things, but from the outside they can look the same, and people brace like you've already decided something about them.\n\nThey think you're manipulative because you read situations so well. Being able to perceive a dynamic looks, to a nervous person, like being able to exploit it—they mix up your capacity with your intention. You usually just want to understand the room, not work it.\n\nThey think you're cold because you see the pattern instead of getting swept into the feeling. Your read runs a little above the raw emotion, so people assume you don't care. You care a lot. You just process the caring through recognition instead of getting drowned in it like they do.\n\nAnd they treat your knowing like a party trick—\"do me, what am I thinking\"—without getting that it's not something you switch on for fun. The radar is always running. You can't really turn it off any more than you can choose not to hear. It isn't a performance; it's just the channel you're permanently tuned to.",

  "hiddenSuperpower": "You can see whole relationship systems that other people only feel as confusion or pain. When a friend is stuck in something toxic—a using friendship, a controlling relationship, a messed-up family pattern—they usually can't see it, because they're inside it. You're standing outside, watching the entire shape of it, and you can hand it back to them in a way that finally makes their own life make sense.\n\nThat systems-read is exactly what makes you the friend people come to when they're drowning and can't name why. You don't analyze them; you just describe what you see: here's the pattern, here's how it runs, here's why it feels the way it feels. When you name it accurately, people get this huge wave of relief—because someone finally put words to the thing they've been stuck in for months.\n\nYou also see potential, not just the current mess. You catch what a friendship could turn into, how a group could actually work if one dynamic shifted, what someone could be to each other if they stopped doing the one thing wrecking it. You're not just reading what is—you're reading what could be.\n\nSo your seeing isn't only diagnostic, it's generative. By reading a situation clearly and saying it out loud, you help everyone around you see more clearly too. You're the person who makes the invisible thing visible, and that changes what people are able to do about it.",
  "blindSpot": "You can trust your read so completely that you miss the times it's wrong. Pattern recognition is a probability, not a certainty—and your confidence in your gut can stop you from noticing the exception, or from letting someone actually change. You decided who someone was in the first thirty seconds, and then quietly stopped collecting new data on them.\n\nYou can also neglect yourself all the way to a breaking point. Your attention flows outward so naturally that you'll track everyone else's wellbeing while completely losing the thread on your own, until your own needs aren't a quiet signal anymore—they're an emergency you should've caught weeks ago.\n\nAnd being the one who always understands can quietly become a place to hide. As long as you're the one reading everyone else, you never have to be the one who's seen. Understanding people keeps you safe from the scarier thing—actually being known, which means being vulnerable, which is the one move your radar can't do for you.\n\nThe other one: you undervalue the stuff that requires looking at yourself. Your own history, your own patterns, the part you played in a dynamic you're busy diagnosing—those are genuinely harder for you to see than anyone else's, because the radar points everywhere except inward.",

  "frictionPatterns": "You grind against the people who only trust their own narrow, personal experience and wave off anything bigger. They think you're projecting or making things up when you describe the larger pattern. You think they're trapped inside their own perspective, unable to see the system they're standing in the middle of. It's not a small disagreement—it's two different ways of knowing that barely translate to each other.\n\nYou also rub hard against anyone who demands an explicit, step-by-step justification for every read you have. Your knowing arrives as a whole pattern, not a chain of evidence, so a person or a setting that treats \"I can't fully explain how I know, I just do\" as automatically disqualifying will frustrate you and dismiss you at the same time.\n\nThe specific loneliness is being the friend who saw the breakup, the falling-out, the bad roommate situation coming—and getting ignored, then watching it happen exactly the way you said. They couldn't access the pattern you were reading, so your warning sounded baseless, and being right after the fact doesn't feel like winning.\n\nWhat you bring to all of it is that you can usually understand their side better than they understand yours, which means you can be the bridge. Your growth edge is learning to translate what you see into words other people can actually take in—and staying honest that your read, while usually right, is not actually infallible.",

  "energyPatterns": "What drains you:\n- A loud, crowded room flooding you with social signals you can't filter\n- Having a clear read dismissed as \"you're overthinking it\"\n- Relationships where you always understand more than you're understood\n- Pretending you don't see the thing you obviously see\n- Tracking everyone else so hard you forget you exist\n- Being asked to perform your reads like a party trick\n\nWhat charges you:\n- A tangled situation you can actually perceive and make sense of\n- Helping a friend finally see the pattern they're stuck inside\n- Being somewhere that treats reading people as a real skill\n- The rare person who can read you back for once\n- Watching two people actually repair something that was broken\n- A mentor who's genuinely good with people and lets you watch up close",

  "workEnvironments": "Where you thrive:\n- Work where reading people accurately is basically the whole job\n- Coaching, support, HR, community, mediation, anything human-centered\n- Roles where your read gets trusted even when you can't fully prove it\n- Sitting next to a leader who's clueless about people and translating it for them\n- Teams small enough that the dynamics are real and worth tracking\n\nWhere you suffocate:\n- Cultures that flat-out deny that reading people is a real thing\n- Hyper-technical rooms that sneer at \"soft skills\" as fluff\n- Places that pretend office politics and group dynamics don't exist\n- An environment so chaotic with people-signals you can never recover\n- Roles where you're punished for naming what's obviously happening",

  "topCareers": [
    {
      "title": "Coaching / Peer Support / Community Role",
      "description": "You know things about people immediately, by reading rather than reasoning, and you're almost always right. Entry roles in coaching, peer support, residential life, or community work run on exactly that—catching what's really going on under what someone's presenting and meeting it head-on. You're already the friend people come to when their life is tangled. The \"soft skill\" a technical crowd would dismiss is, in this work, the entire hard skill, and it pays you to keep sharpening it."
    },
    {
      "title": "HR / People Operations / Recruiting",
      "description": "You read the alliances under the official ones and feel where the real tension sits before anyone admits it's there. Entry HR, people-ops, and recruiting work rewards that—understanding how people actually function together, who'll mesh and who'll quietly clash, who's about to leave before they say so. You can't switch the radar off anyway, so you may as well get paid for it. The interpersonal sense that overwhelms you in chaotic, denial-based rooms becomes, here, the core instrument of the job."
    },
    {
      "title": "Mediation / Conflict Resolution / Client-Facing Roles",
      "description": "You walk into a room and understand the relational landscape—who trusts whom, who's pretending, where it's really tense—whole and wordless. Entry-level mediation, customer success, account management, or front-of-house client work pays for that immediate read: understanding how people work together so you can move them toward each other instead of apart. The knowing that arrives without any investigation, the thing you \"have no business\" knowing, becomes your most valuable professional read."
    }
  ],

  "blockIndicators": "Your Parser Profile suggests the following CBI block accessibility pattern:\n\nLikely High-Accessibility Blocks:\n- Social Signal Processing (your native mode)\n- Pattern Recognition (abstract relational patterns)\n- Perceptual Discrimination (social signals and cues)\n\nLikely Moderate-Accessibility Blocks:\n- Generative Creation (perceiving relational possibility)\n- Symbolic Manipulation (conceptual processing of social data)\n- Sequential Processing (tracking how dynamics unfold)\n\nLikely Lower-Accessibility Blocks:\n- Self-Reference Processing (attention flows outward, not inward)\n- Spatial Relationships (abstract orientation de-emphasizes concrete spatial processing)\n\nThis pattern suggests your cognitive architecture is optimized for reading people and seeing whole relational systems in real time, with room to grow in turning that same quality of attention inward—onto your own needs and patterns—instead of pointing it permanently at everyone else.\n\nINTUITIVE",

  "strengths": [
    {
      "title": "You Read the Room as It Happens",
      "description": "You catch social shifts live, not after the fact. While everyone else reconstructs what happened on the walk home—wait, was she mad?—you felt the exact moment trust formed or cracked, the instant someone decided something they never announced. You're tracking the room in real time while it's still moving."
    },
    {
      "title": "You See the Whole System, Not Just People",
      "description": "You don't just clock how someone relates to you—you see how everyone relates to each other and to the group. You perceive the whole web, which is why you understand dynamics that make no sense one person at a time: why this combo of friends always implodes, where the real influence actually sits, who's quietly running things."
    },
    {
      "title": "You Hear What Isn't Said",
      "description": "You read tone, timing, the pause, the thing they pointedly avoided, as clearly as the actual words. You process all of it automatically and weight it right—so when someone's words say fine but their whole body says not fine, you trust the signal, not the sentence. People can't really hide from you in person."
    },
    {
      "title": "You See It Coming",
      "description": "Because you're tracking the pattern live, you usually know where a situation is heading before it arrives. You feel the question before it's asked, the objection before it's raised, the falling-out before it happens. It can feel almost like a sixth sense, but it's really just your radar finishing the pattern early."
    },
    {
      "title": "You Track How People Shift by Group",
      "description": "You notice how the same person becomes different in different rooms—who gets more themselves around certain friends, who disappears, who suddenly dominates, who shrinks. Those contextual shifts that everyone else misses, you catch automatically, and it tells you who someone actually is versus who they perform being."
    },
    {
      "title": "You Know Who to Trust",
      "description": "You can usually tell who's safe and how much, often without being able to explain why. Your gut is running on pattern data you barely notice consciously, and it calibrates trust to a reality other people walk right past. When your read on someone is off, you feel it long before they give you a reason."
    }
  ],

  "challenges": [
    {
      "title": "A Stranger to Yourself",
      "challenge": "Your attention points outward so hard that you can be a mystery to your own self. You understand everyone else's fears and motives and needs cold, while staying genuinely fuzzy on your own. The radar points everywhere except inward, so your own life can blur while everyone else's is crystal clear.",
      "remedy": "Schedule attention on yourself the way you'd give it to anyone important. Once a week, actually ask: what do I want, what am I feeling, what's off with me right now? Turn the same quality of read you give your friends onto your own life. You're worth that attention too."
    },
    {
      "title": "Knowing Without Receipts",
      "challenge": "You know things you can't justify knowing, so you respond to what someone hasn't said, avoid a person you have no official reason to distrust, act on a read you can't source. It can come off as unsettling, and people who need proof brush it off as you being weird or dramatic.",
      "remedy": "When a read actually matters, go find the concrete evidence that backs what you already feel. Translate the pattern into something shareable—a specific thing they said, a behavior you can point to. Not to prove you're right, but to build a bridge for the people who genuinely need the explicit version."
    },
    {
      "title": "Where You End and They Begin",
      "challenge": "Your outward focus can smear the line between you and everyone else. You'll absorb a friend's mood without noticing it's not yours, or prioritize what they need so automatically that what you need just quietly vanishes off the list entirely.",
      "remedy": "Practice noticing what you want before you ask what they want. Even just a beat—what do I actually need here?—before you default to managing them. Your needs exist even when your attention doesn't naturally find them. That's not being selfish; that's just being a whole person."
    },
    {
      "title": "Nobody Listens to the Warning",
      "challenge": "You see the breakup, the bad roommate, the friendship blowup coming, and warning people almost never works—they don't have the pattern you're reading, so it sounds baseless. Then you stand there watching the preventable thing happen exactly the way you called it.",
      "remedy": "Accept that perceiving something isn't the same as being able to persuade someone of it. Sometimes your role is to understand, not to save—and to be the steady person there after it falls apart, which can matter more than the warning they couldn't hear. Save your energy for when they're actually ready to listen."
    },
    {
      "title": "Known Without Being Known",
      "challenge": "You understand people far more than they understand you, which builds lopsided friendships where you're always the one who sees. Others feel deeply known by you and never quite manage to know you back, and after a while that asymmetry gets lonely.",
      "remedy": "Offer real things about yourself even when nobody asks the right question. They can't read you the way you read them—so help them out, hand them the information instead of waiting to be perceived. Real closeness needs you to reveal, not just to perceive everyone else."
    },
    {
      "title": "Too Much Signal, No Off Switch",
      "challenge": "Your constant people-reading burns real energy, and a loud, packed, drama-heavy environment can max out your processing fast. You see everything, which means in a flood you can't filter down to anything useful—you just get fried and overstimulated.",
      "remedy": "Treat recovery time like actual maintenance, not a luxury. Your radar has a real cost and needs you to restore it. Build in quiet, low-stimulation time on purpose—solo walks, a calm room, a night in—and protect it as non-negotiable, the same way you'd protect anything your body needs."
    }
  ]
};
