// LEGACY Profile — Young Adult (18–29)
// Parser Profile™ © 2026 Cognition Blocks LLC

export const legacyyaProfile = {
  "name": "LEGACY",
  "tagline": "The one already thinking about what they'll leave behind",

  "overview": "Your friends are figuring out the weekend. You're quietly thinking about something bigger—what actually lasts, what you want your life to add up to, whether the thing you're pouring time into now will still mean anything in ten years. Nobody asked you to think that way this early. You just always have. While everyone's living for the next night out, part of you is already standing at the end, looking back, asking if any of this mattered.\n\nThis isn't you being morbid or old before your time, even though people read it that way. It's that meaning matters to you in a way it doesn't seem to for everyone else yet. You want to build something. You remember who taught you the things you know and you feel like you owe them something. You notice when a tradition gets tossed out and nobody even asks why it existed, and it bothers you more than it seems to bother anyone else.\n\nPeople call you intense, or an old soul, or they tease you for caring so much about stuff that's \"not that deep.\" To you it's all deep. The job isn't just a paycheck—it's where your time goes, and your time is the one thing you don't get back. The friendships aren't just fun—they're what you'll have built when this whole chapter is over.\n\nThey think caring about legacy is something you do when you're old. You already feel the weight of it. If you don't build something that means something, what was any of it for?",

  "howYouLearn": "The story behind the thing matters to you more than the thing itself. Hand you a rule with no reason and it stays hollow—you want to know what failure it was written in response to, who got burned that made someone write it down. \"This is just how we do it\" makes you itch. You need to know how it became how we do it, and at whose expense, before it'll actually stick.\n\nYou learn best from people who've actually lived it. The manager at your first job who tells you why the shortcut everyone takes always blows up. The older student or coach or relative who hands you the lesson with the scar still attached. Their war stories teach you more than any orientation packet, because they come with the names and the cost still in them, not the cleaned-up version.\n\nA polished success story with the struggle edited out is useless to you—it's missing the exact thing your brain reaches for. You want to know how it actually got built: the dead ends, the near-disasters, the part where it almost didn't work. The monument bores you. The story of building it is what you keep.\n\nAnd knowledge with no lineage doesn't stick at all. A random fact with no chain of people behind it has nowhere to attach in you. But show you the line of hands a piece of knowledge passed through to reach you, and it becomes permanent, because now it's part of a story worth carrying forward.",

  "howYouCommunicate": "You open with the backstory. \"Okay but the reason this works is—.\" \"This reminds me of when my old boss tried—.\" \"You have to understand why we even started doing it this way.\" To you, the present thing is meaningless without the history that made it, so you hand people context they didn't ask for, because you can tell they need it whether they know it or not.\n\nThere's real generosity in that, and it doesn't always land as generosity. Sometimes your friend just wanted the quick answer and you gave them the whole origin story instead. Sometimes that's exactly what saves them from a dumb mistake, and sometimes it's just more than they had patience for right then. You're slowly learning to offer the context in a size people can actually hold.\n\nWhen things blow up in a group, you're the one who brings the long view—\"we've literally been here before, here's how it went last time\"—and you watch the room either settle or stiffen depending on whether they're ready to hear it. You can feel which one it's going to be before you even finish the sentence.\n\nAnd you're the one who names the people everyone else forgot. When credit gets handed out and the person who actually did the work gets skipped, you're the voice that says their name. Nobody else seems to think to. You genuinely can't not do it—it would feel like a kind of theft to stay quiet.",

  "phrase": "You're not stuck in the past or weirdly obsessed with the end. You're just already building like it counts, because you figured out early that it does.",

  "secret": "You carry weight your friends haven't picked up yet. You think about what your life will add up to, what you'll have built, who'll remember what when this is all over—and most people your age aren't there. Not because they're shallow. Because they haven't felt it yet. You have.\n\nYou've watched people your age treat everything as disposable—jobs, friendships, the place that raised them, the people who got them here—and tear through it all like it'll just regenerate. And you feel something close to grief watching it, not for the past exactly, but for the disrespect. For how casually people throw away things that took someone real effort to build.\n\nYou've probably already been the one who made sure something got remembered. Kept the group chat alive when everyone drifted. Held a tradition together that would've died otherwise. Said the name nobody else said. Thankless stuff, mostly, and the people who'd benefit most from it are usually the least interested in why it matters.\n\nThe deepest part: it's lonely being this serious about building something this young. Sometimes you wish you could just live like everyone else, light and disposable and unbothered. But you can't unfeel the weight. You already know your time is finite and you already want it to mean something, and carrying that at twenty-two when no one around you does can feel less like a gift and more like being alone.",

  "whatOthersGetWrong": "They call you an old soul like it's a cute little label, when really you just figured out early that your time is the one thing you don't get back. Someone has to think about what lasts or the whole thing just drifts, and you've quietly been that person since before you could explain it. \"Why are you so serious\" usually means you cared about something they decided didn't deserve caring about.\n\n\"You're overthinking your whole life\" is the easy read, and it's exactly backwards—you're not overthinking it, you're refusing to sleepwalk through it. While everyone treats their twenties like a throwaway warmup round, you're treating them like part of the actual thing you're building, because they are. The years count even when you're young. Especially then.\n\nThey assume that because you care about roots—where you came from, who built what, what you owe—you must be scared of the new. You're not. You adapt constantly. You just build on the foundation instead of dynamiting it and pretending you started from nothing. Change that keeps faith with where it came from isn't slower. It's the kind that lasts.\n\nAnd they think caring this much makes you easy to push around, because you care about the group over yourself. That's the worst miss of all. You'll fight harder than anyone for the thing you're protecting—the friend who's getting forgotten, the standard that's getting dropped—because to you it was never just about you. It belongs to people who aren't in the room, and you're the one who stayed to defend it for them.",

  "hiddenSuperpower": "You carry the why behind things that no one wrote down. Why this group has the unspoken rule it has. Why that friend doesn't get brought up. Why the team does the thing this specific way. You don't just know the rule exists—you know what it's protecting, what went wrong before it, what it quietly prevents. That kind of memory is irreplaceable, and usually nobody notices it's holding everything together until you're gone and it all starts breaking.\n\nYou see the whole story when other people only see the highlight reel. You know who actually did the work before the narrative got rewritten. Whose contribution got quietly absorbed by someone louder. Which foundation got laid by a person nobody credits anymore. You hold the real version.\n\nYou can also spot decay early. You notice when a friend group is starting to rot, when a place is losing the thing that made it good, when a standard is slipping—because you know what healthy looked like, and you've watched this slide before. You catch the early signs everyone else misses until it's too late.\n\nAnd you can pass it on. You don't just remember—you transmit. When someone's actually ready to learn, you can hand them in an afternoon what took you years to understand. You're a living archive, and the rare friend who lets you teach them gets a head start on a whole bunch of expensive lessons.",

  "blindSpot": "Sometimes the thing genuinely doesn't matter anymore—and you defend it anyway, because defending it has become a reflex. That's the shadow side of caring this much. The same loyalty that saves the valuable stuff from getting carelessly trashed can keep you guarding something long after its actual point has died, and from inside the loyalty you can't always tell which is which.\n\n\"We tried that already\" is the line that gets you in trouble. It's true—and it's also where you miss the most. The plan that flopped for your friend group last year might work now, because the people and the situation have shifted in ways your memory doesn't automatically update for. Your recall of how it went is an asset right up until you treat it as a final verdict on how it has to go.\n\nYou also carry the group's stuff so completely that you can lose yourself somewhere inside it. Always the one holding the friendships together, always the one remembering everyone's hard days—and somewhere in there you stop checking what you actually need, because you're too busy carrying what everyone else set down. The caring that makes you essential can quietly erase you.\n\nAnd the hardest one to catch: protecting something can slowly curdle into controlling it—deciding who's worthy of the thing you're keeping, gatekeeping the group or the tradition or the standard instead of guarding it. And the grief you carry for what's been lost, if you never set any of it down, stops being wisdom and just becomes weight you haul around.",

  "frictionPatterns": "You grind hardest against the person who treats history like dead weight—the friend who wants to ditch everything and \"start fresh,\" the new hire who looks at how things are done and assumes it's all just outdated noise to clear out of the way. They want to build from scratch, like scratch is a real place you can stand on, instead of a foundation other people poured before they showed up. To them the past is baggage; to you it's the ground holding the whole thing up.\n\nThe \"move fast and break things\" energy turns your stomach in a specific way, because you're usually the one who knows exactly what breaking costs and who ends up holding the pieces. Everyone's racing ahead, hyped about what could be, and you're standing there with the full memory of what this took to build and what it'll take to lose.\n\nThe people who act like the job, the school, the group owes them strike you as having it backwards. You were raised on the opposite math—that you owe something to what you inherited, to the people who made the thing you walked into. That flip doesn't feel like a difference of opinion to you. It feels like a forgetting.\n\nWhat you bring to that friction is roots—you keep the bold new plan tethered to what's actually been learned, so the future gets built on something instead of on a wish. Your growth edge is remembering that the forward-rushers and the dreamers aren't trashing anything on purpose. They just can't see the history you're carrying, and not seeing it isn't the same as disrespecting it.",

  "energyPatterns": "What drains you:\n- People tearing into something without ever asking why it existed\n- Being the only one who seems to remember or care\n- Having to defend the basic idea that some things are worth keeping\n- Watching the same avoidable mistake cycle back on schedule\n- Credit going to the loud person instead of the one who did it\n- The friend group or place forgetting what made it good\n\nWhat charges you:\n- Teaching something to someone who actually wants to learn it\n- Seeing a tradition adapted thoughtfully instead of trashed\n- Someone finally getting recognized for what they really did\n- A group that grows without forgetting where it came from\n- Building something meant to outlast this whole chapter\n- A younger friend who asks \"wait, why do we even do it this way?\"",

  "workEnvironments": "Where you thrive:\n- Places that actually value their own history and people\n- Roles where remembering and passing things on is the point\n- Organizations playing a long game, not just chasing the quarter\n- Teams that respect why things are the way they are\n- Work where your memory and continuity are treated as an asset\n\nWhere you suffocate:\n- \"Move fast and break things\" with no respect for what came before\n- Places where nobody knows or cares about the backstory\n- Cultures that prize disruption purely for its own sake\n- Settings where institutional knowledge is treated like a roadblock\n- Roles where your long view gets written off as just being resistant",

  "topCareers": [
    {
      "title": "Archives / Museum / Records Assistant",
      "description": "You remember what everyone else forgot—the people who built the thing, the reason the rule exists, the sacrifice that didn't make the highlight reel. Entry roles in archives, museums, libraries, or records work make a craft of exactly that: preserving not just the object but the why behind it. You don't romanticize the past; you witness it and keep the names that got erased. The memory you carried because someone had to becomes the literal thing an institution trusts you, even young, to hold."
    },
    {
      "title": "Teaching / Mentoring / Coaching",
      "description": "You know why we stopped doing it the old way, and you can hand that knowing to someone who never lived it. Starting out as a tutor, assistant teacher, youth coach, or program mentor is built for the tradition-keeper—passing on the context and the reason behind the rule so a community keeps its own memory. You make the past usable instead of sacred. The role you already played for free, holding the backstory when it lived nowhere else, becomes the actual job you're there to do."
    },
    {
      "title": "Nonprofit / Community / Heritage Organizing",
      "description": "When people want to tear something down and start over, you're the one asking if they know what they're standing on. Entry roles in nonprofits, community organizing, or heritage and preservation work are that instinct made into a job—keeping the record of how a place got here so the next group doesn't pay full price to relearn it. You build things meant to outlast you, which is what you've quietly wanted to do this whole time. People will lean on your memory for years before it ever shows up in your title."
    }
  ],

  "blockIndicators": "Your Parser Profile suggests the following CBI block accessibility pattern:\n\nLikely High-Accessibility Blocks:\n- Sequential Processing (historical narrative tracking)\n- Social Signal Processing (collective awareness)\n- Self-Reference Processing (through community identity)\n\nLikely Moderate-Accessibility Blocks:\n- Pattern Recognition (historical patterns)\n- Perceptual Discrimination (concrete details)\n\nLikely Lower-Accessibility Blocks:\n- Generative Creation (preference for preservation over innovation)\n- Symbolic Manipulation (abstract reasoning without concrete grounding)\n- Spatial Relationships (may be less emphasized)\n\nThis pattern suggests your cognitive architecture is optimized for holding the story, honoring what came before, and building things meant to last, with room to grow in giving genuinely new ideas a clean shot before your memory of how it went last time decides it for you.\n\nLEGACY",

  "strengths": [
    {
      "title": "You Hold the Why",
      "description": "You remember the stuff that never got written down—the context, the reasoning, who was actually involved, why things ended up the way they are. You know how it all came to be, not just that it is. That knowledge is irreplaceable, and usually nobody realizes you were holding it together until you're not around and things start quietly falling apart."
    },
    {
      "title": "You Keep the Real Story",
      "description": "You hold the stories that would otherwise just vanish. Who actually built the thing, who quietly contributed, who sacrificed something and never got named for it. When the narrative gets simplified down to whoever was loudest, you're the one who makes sure the full version survives—and that matters more than people realize."
    },
    {
      "title": "You Connect Across Time",
      "description": "You link the thing happening now to what came before it—this situation to its precedent, this decision to the one that already played out, this person to the ones who came first. Without someone doing that, a group just drifts randomly. You're the reason it develops with some kind of coherence instead of repeating itself blindly."
    },
    {
      "title": "You Stop Careless Destruction",
      "description": "When people want to throw out something they don't even understand, you're the one who makes them at least understand it first. You've probably already saved a friendship, a group, or a plan from getting trashed for no reason—talked someone down from torching the thing before they knew what it was holding up. You've protected more than anyone will ever know."
    },
    {
      "title": "You Build Belonging",
      "description": "Your focus on people and on history makes you a natural at holding a group together. You remember the relationships, you honor what people contributed, and you create belonging by tying people back to a shared story. You're the reason a friend group or a team feels like an actual thing and not just a pile of strangers who happen to overlap."
    },
    {
      "title": "You Pass It On",
      "description": "You don't just remember—you teach. You hand the lesson forward so the next person doesn't have to pay the same tuition you did. That transmission is the whole difference between a group that learns and one that just repeats its mistakes on a loop, and you do it without even being asked."
    }
  ],

  "challenges": [
    {
      "title": "Guarding Something That's Already Dead",
      "challenge": "You protected it because it mattered. But the situation changed and it quietly stopped serving its purpose, and your loyalty kept you defending it anyway. The thing you saved became the thing holding everyone back, and from inside the loyalty you couldn't quite see the switch.",
      "remedy": "Separate form from function. Ask: what was this actually for? Is there a newer version that serves the same purpose better? The people you look up to adapted too. Sometimes keeping faith with something means updating it, not just preserving it exactly as it was."
    },
    {
      "title": "Carrying It All Alone",
      "challenge": "Nobody else seems to remember. Nobody else seems to care that much. You're holding a story everyone else set down, and it's genuinely heavy—the specific loneliness of being the only one who didn't forget, while everyone around you moved on like it was nothing.",
      "remedy": "Find your witnesses. The one or two people who see what you see—an older mentor, a friend who also cares this way. You don't need everyone to carry it with you; you need someone. And write it down. Putting what you remember somewhere real is an act of preservation, even if nobody reads it yet."
    },
    {
      "title": "\"We Already Tried That\"",
      "challenge": "It's true—you did. But the conditions shifted. The thing that flopped a year ago might actually work now, with different people and a different moment around it. Your memory is an asset, but treating it like a guaranteed outcome closes off stuff that genuinely deserves another shot.",
      "remedy": "Map what's different. When something looks like a past failure, force yourself to name out loud what's changed now—who's involved, what the situation is, what you know that you didn't. Your experience is a great starting point for thinking it through, not the final verdict on it."
    },
    {
      "title": "Disappearing Into Everyone Else",
      "challenge": "You've given so much to the group, the friendships, the thing you're building that you've lost track of your own needs. The caring turned into self-neglect. The whole thing needs you healthy to keep going, but you stopped checking on yourself a while ago.",
      "remedy": "Remember that the person who holds everything also needs holding. Block out time that's just for you—not the group, not the legacy, you. Your own upkeep isn't a betrayal of the mission. It's what keeps you able to do the mission at all."
    },
    {
      "title": "Expecting Them to Know What They Couldn't",
      "challenge": "They don't know what you know. They weren't there for the part that taught you. Your frustration with how clueless they seem is fair—but it's also just structural. They literally can't know a thing they weren't present for, and resenting them for it doesn't move anything.",
      "remedy": "Teach without the resentment. They're not disrespecting a thing they don't even know exists. Your job isn't to judge the gap between what you know and what they don't—it's to bridge it, if they're willing to learn. Lead with the story, not with the disappointment."
    },
    {
      "title": "Grief That Turned Into Weight",
      "challenge": "You remember what got lost—the people who left, the things that ended, the way it used to be. Grief stacks up when you're the one who never forgets, and after a while it stops being meaningful and just becomes heavy, something you drag around without noticing.",
      "remedy": "Make space to actually mark the losses. Grief that's honored and then released turns into wisdom; grief you just hold forever turns into dead weight. Find some way to acknowledge what's gone—talk about it, write it, mark the day—so you can keep remembering without bleeding from it."
    }
  ]
};
