// LEGACY Profile
// Parser Profile™ © 2026 Cognition Blocks LLC
// Concrete • Past • Other

export const legacyProfile = {
  "name": "LEGACY",
  "code": "Concrete • Past • Other",
  "tagline": "The tradition-keeper who carries forward what matters",
  "overview": "You remember what was sacrificed to build what others take for granted.\nWhile people casually propose tearing it down and starting over, you\nfeel the weight of every decision, every contribution, every struggle\nthat created what exists now. This isn't nostalgia, it's witness.\nIt's honoring what was given.\n\nYour cognitive architecture prioritizes concrete reality over\nabstraction, historical evidence over future speculation, and collective\nexperience over personal preference. The result is a consciousness that\nserves as institutional memory, holding the full story when others have\nonly the convenient summary.\n\nYou've probably been called \"traditional\" or \"stuck in the past\" by\npeople who don't understand what they're dismissing. They haven't\npaid the costs; they don't know the history. They see constraints where\nyou see hard-won wisdom. They see obstacles where you see guardrails\nbuilt after someone got hurt.\n\nThe Legacy profile represents approximately 6% of the population.\nYou're the cultural connective tissue that prevents every generation\nfrom relearning every lesson. Without people like you, organizations\nlose their memory, families lose their stories, and societies lose their\ncontinuity. Someone has to remember, and that someone is you.\n\nYour cognitive architecture excels at preserving institutional\nknowledge, honoring collective sacrifice, and providing continuity\nacross time. You're the one who knows why the rule exists, not because\nyou're attached to it, but because you remember what happened before it\ndid.\n\nUnderstanding your profile means recognizing that your relationship with\nthe past isn't resistance to the future, it's protection of what's\nworth carrying forward.",
  "howYouLearn": "You learn through story and context. Information presented without\nhistorical grounding or human connection tends to feel arbitrary and\nforgettable. The same information embedded in narrative, who did what,\nwhy, and what happened, becomes permanent.\n\nYour optimal learning environment connects new knowledge to existing\nhistory, provides human context for abstract principles, and\nacknowledges what came before. You need to know the lineage of ideas,\nthe genealogy of practices, the history of the domain.\n\nYou learn poorly from decontextualized instruction that treats knowledge\nas existing without origin. \"Best practices\" presented without\nhistorical development, theories without intellectual heritage, and\nskills without traditional grounding may not engage your processing.\n\nApprenticeship and mentorship work well, learning from someone who\ncarries knowledge from previous generations. Historical case studies\nengage you. Learning that honors the past while building toward the\nfuture aligns with your architecture.",
  "howYouCommunicate": "You communicate through story, context, and historical reference. You\nsituate current events in larger narratives, connect present people to\npast contributions, and provide the \"why behind the why\" through\nhistorical explanation. Your communication carries temporal depth.\n\nYou may struggle with audiences who want only the immediate, actionable\nsummary. Your instinct is to provide context they don't think they\nwant, and sometimes they're right that they don't need it, but\nsometimes they're missing essential understanding.\n\nIn meetings, you're the one who says \"this reminds me of when we\ntried...\" or \"the reason we do it this way is because...\" In\nconflicts, you bring historical perspective that can either illuminate\nor frustrate depending on relevance.\n\nYou communicate best in contexts that value history, honor precedent,\nand have patience for narrative. You communicate less effectively in\ncontexts that prize only the new, the fast, and the action-oriented.",
  "phrase": "You're not living in the past; you're protecting the future from\npeople who don't know what it cost to get here.",
  "secret": "You remember what was sacrificed to build what others take for granted.\nWhile people casually propose burning it down and starting over, you\nfeel the weight of every decision, every contribution, every struggle\nthat created what exists now. You know the names they've forgotten. You\nknow the costs they never learned.\n\nThe secret is that you're a witness. Not just to events, but to the\nfull story behind them, the parts that didn't make it into the official\nnarrative, the people who were erased from the simplified version, the\nreasons behind rules that now seem arbitrary. You carry this because\nsomeone has to. Because if you don't, it's gone.\n\nYou've watched people dismiss things they don't understand, call\ntraditions \"outdated\" without asking why they existed, tear down\nstructures without knowing what they were holding up. And you've felt\nit like a physical pain, not nostalgia, but grief. Grief for disrespect.\nGrief for what's about to be lost. Grief for the people who built it,\nwho won't even get a thank-you before their work is demolished.\n\nYou've probably been the one who made sure the full story got told, at\nleast somewhere, at least once. The one who kept the records when no one\nelse cared. The one who named the contributors when everyone else had\nmoved on. It's thankless work. The people who need to hear it most are\nusually the ones least interested in listening.\n\nThe deepest secret: you're tired of being the only one who remembers.\nTired of carrying institutional memories for people who treat history as\nirrelevant. Tired of watching the same mistakes cycle back because no\none bothered to learn what happened last time. You remember. You always\nremember. And sometimes that feels like a curse.",
  "whatOthersGetWrong": "ABOUT YOU \n\nPeople call you \"traditional\" or \"conservative\" like those are\ninsults, not realizing that someone has to maintain continuity or\neverything falls apart. Innovation is cheap. Anyone can propose tearing\nthings down. Stewardship is rare. Building things that last, preserving\nwhat deserves to survive, honoring what came before, that takes\nsomething most people don't have.\n\nThey assume you're afraid of change. You're not. You're aware of\ncosts that others ignore. Change isn't free. It spends accumulated\ncapital that took generations to build. You're not resisting change;\nyou're insisting that change acknowledge what it's spending. That's\nnot fear. That's accounting.\n\nYou've been dismissed as \"stuck in the past\" when you were protecting\nthe future. You've been told to \"let it go\" by people who benefit\nfrom forgetting. You've been labeled \"not innovative\" by people whose\ninnovations will fail because they ignored the lessons you tried to\nteach them.\n\nThe deepest misread is that your past-focus means you can't adapt. You\nadapt constantly; you just adapt by building on foundations rather than\nabandoning them. You evolve traditions rather than destroying them. You\nintegrate new information into existing structures rather than\npretending structures don't matter.\n\nThey also assume your other-focus makes you a pushover. It doesn't.\nYou'll fight harder than anyone for the things you're protecting. Your\nloyalty to the group, the institution, the legacy, it's not passive.\nIt's fierce. You're not a doormat. You're a guardian.",
  "hiddenSuperpower": "You carry institutional memory that no documentation captures. You know\nwhy the rule exists, not just that it exists. You know what happened\nbefore it did, what problem it solved, what failure it prevented. This\nknowledge is irreplaceable, and it's usually invisible until you're\ngone and everything starts breaking for reasons no one understands.\n\nYou can see the full story when others see only fragments. You know who\nthe real builders were, before the narrative got revised by people who\nshowed up late. You know which contributions were stolen, which\nsacrifices were erased, which foundations were laid by people who never\ngot credit. You hold the complete picture.\n\nYour superpower extends into protection. You can spot threats to what\nyou're guarding before they become critical. You recognize the patterns\nof institutional decay, the early signs of erosion that others miss\nbecause they don't know what healthy looks like. You've seen it\nbefore. You know what comes next.\n\nYou also provide continuity that enables coherent development rather\nthan random drift. Without people like you, every generation rediscovers\nthe same lessons, makes the same mistakes, loses the same knowledge.\nYou're the connective tissue across time. You're why institutions can\nbe wiser than individuals, because you hold what individuals forget.\n\nPerhaps most valuable: you can transmit. You don't just remember, you\ncan pass it on. When someone is ready to learn, you can give them\ndecades of accumulated wisdom in hours. You're a living library, and\nfor those who value it, you're priceless.",
  "blindSpot": "Your devotion to what worked can become resistance to what's needed.\nSometimes the old ways genuinely no longer serve. Conditions change.\nContexts shift. What was adaptive becomes maladaptive. Your loyalty to\nproven approaches can prevent you from seeing when those approaches have\nexpired. Preservation can become obstacle when the thing being preserved\nhas outlived its function.\n\nYou may also give too much weight to the past in your pattern-matching.\n\"We tried that before and it failed\" might be true, but conditions\nmight be different enough now that it could succeed. Your historical\ndatabase is an asset but treating it as deterministic rather than\nprobabilistic can close off possibilities that deserve testing.\n\nYour other-focus can mean you carry group burdens so completely that you\nlose yourself within them. You become so identified with the\ninstitution, the family, the tradition that your individual needs\ndisappear. You sacrifice your own wellbeing for continuity that might\nnot actually require that sacrifice. Your loyalty can become\nself-erasure.\n\nYou might also hold others to standards from a past they didn't live\nthrough. Younger people haven't earned the wisdom you're offering;\nthey haven't had time. Your frustration with their ignorance might be\nfair, but it's also structural. They can't know what they weren't\nthere for. Teaching requires patience with that gap, not resentment of\nit.\n\nFinally, your guardianship can become gatekeeping. Protecting something\ncan slide into controlling access to it. Your knowledge gives you power,\nand power can be hoarded even with good intentions.",
  "frictionPatterns": "You clash most intensely with Abstract-Future-Self processors (Visionary\nprofile). They treat history as irrelevant data, institutions as\nobstacles to innovation, and collective legacy as constraint on personal\nvision. They see liberation where you see destruction. You see wisdom\nwhere they see dead weight. Mutual incomprehension is profound.\n\nThey want to build from scratch. You know that scratch is a fantasy,\neverything builds on something. Their dismissal of the past feels like\ndisrespect for the people who built what they're standing on. Your\ninsistence on continuity feels like refusal to let them create.\n\nYou'll also clash with high-Self processors across configurations. Your\nother-focus, your orientation toward collective memory and group\ncontinuity, conflicts with their individual orientation. They see your\ndevotion to institutions as self-suppression. You see their self-focus\nas abandonment of responsibility.\n\nFuture-focused processors generally may frustrate you. They're always\nlooking ahead, treating the present as a transition zone and the past as\nirrelevant. You know that the future they're building will be someone\nelse's past, someone else's legacy. They don't seem to think about\nwhat they'll leave behind. You can't stop thinking about it.",
  "energyPatterns": "What Drains You:\n\n-   \"Move fast and break things\" cultures\n\n-   People who don't acknowledge what came before\n\n-   Having to defend the basic value of continuity\n\n-   Watching preventable mistakes repeat on schedule\n\n-   Being the only one who remembers\n\n-   Credit going to the wrong people, again\n\n-   Institutions forgetting their own foundations\n\n-   Disrespect dressed up as innovation\n\nWhat Charges You:\n\n-   Passing knowledge to the next generation\n\n-   Seeing traditions adapted meaningfully rather than abandoned\n    carelessly\n\n-   Recognition of contribution over time\n\n-   Communities that honor their history while growing\n\n-   Building things meant to outlast you\n\n-   Others finally understanding why the rule existed\n\n-   Being sought as a source of institutional memory\n\n-   Young people who actually want to learn what came before",
  "workEnvironments": "You thrive in environments that value institutional knowledge, honor\ntradition, and maintain continuity. Archives, heritage organizations,\nfamily businesses, established institutions, and any role focused on\npreservation and transmission fit your cognitive architecture.\n\nYou struggle in environments that prize disruption, dismiss history, and\nreward constant reinvention. Fast-moving startups, \"move fast and break\nthings\" cultures, and organizations without respect for precedent will\nfeel both frustrating and morally wrong.\n\nKey environmental factors: institutional stability, valued history,\nrespected precedent, transmission opportunities, and colleagues who\nunderstand the weight of what came before.",
  "blockIndicators": "Your Parser Profile suggests the following CBI block accessibility\npattern:\n\nLikely High-Accessibility Blocks:\n\n-   Sequential Processing (historical narrative tracking)\n\n-   Social Signal Processing (collective awareness)\n\n-   Self-Reference Processing (through community identity)\n\nLikely Moderate-Accessibility Blocks:\n\n-   Pattern Recognition (historical patterns)\n\n-   Perceptual Discrimination (concrete details)\n\nLikely Lower-Accessibility Blocks:\n\n-   Generative Creation (preference for preservation over innovation)\n\n-   Symbolic Manipulation (abstract reasoning without concrete\n    grounding)\n\n-   Spatial Relationships (may be less emphasized)\n\nThis pattern suggests your cognitive architecture is optimized for\ncultural transmission and institutional stewardship, with potential\ndevelopmental opportunities in abstract reasoning and future-oriented\nthinking.\n\nLEGACY",
  "strengths": [
    {
      "title": "Institutional Memory You remember what documentation doesn't",
      "description": "capture, the context, the reasoning, the people involved. You know why\nthings are the way they are because you remember how they came to be.\nThis knowledge is irreplaceable and often invisible until you're gone."
    },
    {
      "title": "Collective Witness You hold stories that would otherwise be lost.",
      "description": "Who built what, who contributed what, who sacrificed what, you carry\nthis knowledge when others have moved on. You ensure that the full story\nsurvives, not just the simplified version."
    },
    {
      "title": "Continuity Provision You bridge time. You connect current",
      "description": "situations to their precedents, current people to their predecessors,\ncurrent decisions to their historical context. This continuity is\nessential for coherent development rather than random drift."
    },
    {
      "title": "Protection Instinct You prevent the careless destruction of",
      "description": "hard-won progress. When others want to throw out what they don't\nunderstand, you make sure they at least understand what they're\nthrowing out. You've saved more than anyone will ever know."
    },
    {
      "title": "Community Building Your other-focus and historical awareness",
      "description": "combine to make you a natural community builder. You remember\nrelationships, honor contributions, and create belonging by connecting\npeople to shared history."
    },
    {
      "title": "Wisdom Transmission You don't just remember, you teach. You pass",
      "description": "on what was learned so that subsequent generations don't have to pay\nthe same tuition. This transmission function is essential for cultural\nevolution rather than repetition."
    }
  ],
  "challenges": [
    {
      "title": "Change Resistance*",
      "challenge": "Your protective instinct can become excessive resistance.\nSometimes things genuinely need to change, and your devotion to what\nwas, can prevent necessary evolution. Distinguishing between valuable\npreservation and unnecessary attachment is an ongoing challenge.",
      "remedy": "Distinguish form from function. Ask: \"What was this tradition\nserving? Is there a new form that serves the same function better?\"\nYou're not betraying the past by evolving it, you're honoring the\nunderlying purpose. The ancestors adapted too. Stewardship sometimes\nmeans updating, not just maintaining."
    },
    {
      "title": "Burden of Memory",
      "challenge": "You carry weight that others have set down. The sacrifices,\nthe losses, the struggles, you remember them when others have moved on.\nThis can be isolating and exhausting, especially when others seem\noblivious to what you're holding.",
      "remedy": "Find your witnesses. Seek others who see what you see, fellow\nLegacy processors, elders, historians. You don't need everyone to mourn\nwith you; you need someone. Also: document. Write down what you\nremember. Recording the story is an act of preservation, even if no one\nreads it now. Your witness has value whether or not it's shared."
    },
    {
      "title": "Innovation Skepticism",
      "challenge": "Your historical focus may make you dismissive of genuinely\nnew approaches. You might miss valuable innovations because they don't\nmatch historical patterns, even when those patterns no longer apply.",
      "remedy": "Map the delta. When something resembles a past failure,\nexplicitly identify what's different now. New technology? Different\npeople? Changed context? Your experience is a starting point for\nanalysis, not a final verdict. The question isn't \"did this fail\nbefore?\" but \"would it fail under current conditions?\""
    },
    {
      "title": "Self-Neglect Through Other-Focus",
      "challenge": "Your orientation toward collective memory and group welfare\ncan cause you to neglect your own needs. You may sacrifice personal\ninterests for institutional or community ones to an unsustainable\ndegree.",
      "remedy": "Remember that stewards need sustenance. You can't protect\nwhat you love if you're depleted. Schedule time that's for you, not\nthe group, not the legacy, just yourself. This isn't betrayal; it's\nmaintenance. The tradition needs you healthy. Your self-care serves your\nmission."
    },
    {
      "title": "Abstract Processing Difficulty",
      "challenge": "Your concrete-historical focus may struggle with\ntheoretical or future-oriented thinking. Strategic planning that\nrequires projection into unknown futures can feel groundless and\nuncomfortable.",
      "remedy": "Anchor future-thinking in historical analogy. When facing the\nabstract future, ask: \"What past situation is this most like? What did\nwe learn then?\" You're not avoiding the future; you're approaching it\nthrough your strongest channel. Your history-based projection is valid\nstrategic thinking, use it deliberately."
    },
    {
      "title": "Grief Accumulation",
      "challenge": "As the one who remembers, you also remember what was lost.\nAccumulated grief for departed people, abandoned traditions, and changed\ncircumstances can become a heavy emotional burden.",
      "remedy": "Create rituals of release. Grief held indefinitely becomes\nweight; grief honored and released becomes wisdom. Find ways to mark\nlosses, privately or with others who understand. Carrying memory\ndoesn't require carrying pain forever. You can remember without\nbleeding.\n\n*"
    }
  ]
};
