// MINDFUL Profile — Young Adult (18–29)
// Parser Profile™ © 2026 Cognition Blocks LLC

export const mindfulyaProfile = {
  "name": "MINDFUL",
  "tagline": "The one who's actually here while everyone else is somewhere else",

  "overview": "You're at the table with everyone, and you can feel it—the exact second the conversation goes from real to performance, the quality of the quiet between two people who used to be close, the difference between a friend who's present and one who's just physically sitting there. You're not trying to notice this. You just do. You pick up the texture of the moment while everyone else is half-here, replaying this morning or pre-living tomorrow.\n\nThis isn't something you learned from a meditation app. It's just how your attention is built. You've always caught what other people filter out—the shift in someone's voice that doesn't match their words, the heaviness in a room before anyone names it, the way a hangout can be loud and still feel empty. What people work hard to access on a retreat is just your default Tuesday.\n\nYour read isn't only on other people, and it isn't only on yourself—it's balanced, taking in both at once. So you can tell when a group goes from a pile of people to an actual connection, and you can tell when you yourself have checked out, all at the same time.\n\nPeople call you chill, or spacey, or ask why you're so quiet. They mistake \"fully present\" for \"not much going on.\" They don't get that your quiet is full, not empty—that you're more in the moment than anyone at the table, just without the noise they expect that to come with.",

  "howYouLearn": "You learn by watching the real thing happen, not by reading the description of it. A framework can interest you on paper, but it doesn't become real until you can see it actually operating in front of you, live. Give you access to the thing itself and you'll pull the pattern out yourself—you don't need it pre-chewed.\n\nYou need rich stuff to actually perceive, not a tidy summary of it. You'd rather watch the process unfold than read about its five neat stages. That's why a demo lands and a lecture slides off—one points you at the real thing, the other substitutes someone else's understanding for your own perception. The best teachers you've had didn't over-explain; they just directed your attention and let you see it.\n\nWhere you struggle is anything purely symbolic or all about some far-off future. \"This'll matter later\" does almost nothing for you, while \"notice what's happening right now\" lights you up. And you fall apart in fragmented, chaotic learning settings—a dozen tabs, constant pings, everyone talking over each other—because that splits the exact quality of attention your brain needs to actually work.\n\nSo immersion beats abstraction, observation beats instruction, and watching beats being told. Drop you into the actual experience with room to be present in it, and you'll extract more than any neat explanation could ever hand you.",

  "howYouCommunicate": "You name the precise thing. Where other people speak in vague generalities, you point at the exact quality of what's happening—\"something just shifted,\" \"that's a different kind of quiet than a second ago,\" \"you're here in a different way than you were this morning.\" You put words on the texture of the moment that most people don't even register is there.\n\nThat precision can low-key unsettle people. They don't always know what you're pointing at, or they suddenly feel watched, self-conscious that you clocked something they thought was invisible. You're not judging them—you just see at a higher resolution than they're used to being seen at.\n\nYou tend toward fewer words, not more. You're not filling silence to be polite, not performing that you're engaged. When you do speak, it's because something got clear enough to actually say. The quiet in between isn't you being checked out—it's you taking it in.\n\nYou communicate best where there's room to breathe—where a pause is allowed, where a conversation can grow out of two people actually paying attention instead of getting manufactured to avoid awkward silence. Drop you into fast, loud, everyone-talking-over-each-other energy and the thing you're best at gets drowned out.",

  "phrase": "You're not detached from your life. You're more attached to it than people lost in last week or next year. Your quiet isn't absence—it's the realest kind of presence there is.",

  "secret": "You figured out young that most people aren't actually here. They're rehearsing what they'll say next, replaying an old fight, pre-stressing something that hasn't happened. You've watched entire conversations where nobody was listening. You've sat in a packed room and felt completely alone, because you were the only one who actually showed up.\n\nThis started early. You noticed adults saying one thing and meaning another. You noticed that real attention was rare and usually came with a catch. You noticed how much of everything was performance instead of presence. You didn't judge it—you just saw it. And seeing it gave you this feeling of watching life through a pane of glass while everyone else was on the other side, not noticing the glass at all.\n\nThe secret you carry is that your awareness can isolate you. The exact thing that lets you perceive more clearly also separates you from people who don't. You see the texture they're missing, and seeing it puts distance between you and them. You've genuinely wondered if you should learn to see less, to dull it down on purpose, so you could just belong easily like everyone else seems to.\n\nBut you can't unsee it. And you've never found a way to explain it that doesn't come out sounding arrogant or detached or like you think you're better. So you mostly stay quiet—present to moments other people walk right past, holding an awareness that doesn't have anywhere to go.",

  "whatOthersGetWrong": "They think you're passive because you're not constantly doing something. They don't get that taking it in is its own kind of engagement—that your watching is active, that your silence is full and not empty. They measure being present by output, so when you're not visibly producing, they read it as you being absent, when you're actually more here than they are.\n\nThey think you're aloof because you don't get swept into the drama. Your not reacting looks like not caring, but it's actually caring without the distortion. You're not above the situation—you're more in it than they are, just without all the spinning out they assume caring has to come with.\n\nThey think you're judging them, because you see so clearly. Your attention lands like scrutiny even when it's just attention. Most people aren't used to being seen that closely, so they brace for a verdict that was never coming.\n\nAnd they think your awareness is some practice you do—that you must meditate for an hour every morning or work really hard at being present. They don't understand that this is just how you process reality. There's no effort behind it. It's not a routine you keep. It's the only way your attention knows how to run.",

  "hiddenSuperpower": "You can stay fully present to stuff that overwhelms everyone else. When someone's falling apart—crying, panicking, getting hit with hard news—most people flinch, fix, or flee. You can stay. You perceive the whole intensity of it without getting wrecked by it, because you can be with something without merging into it. You give the hard moment a place to actually land.\n\nThat makes you the person people want around when it matters most. When everyone else is reacting or fleeing or making it about themselves, you're still there—still seeing, still present. You're the one who can sit with a friend at 3am and not need them to be okay yet, just be with them while they're not.\n\nYou also catch when presence is happening in other people. You notice the exact moment someone drops the act and gets real, when a conversation turns from small talk into something true, when a group shifts from a bunch of separate people into an actual connection. You track those transitions everyone else misses entirely.\n\nAnd your presence is contagious in a good way. By being genuinely here, you make it easier for other people to be here too. You're not just reading the quality of attention in a room—you're raising it, just by the quality of your own. People calm down around you and don't always know why.",

  "blindSpot": "You can undervalue stuff that lives in the past or the future. Your lock on the present is a strength right up until it turns into tunnel vision—missing context that needed you to remember how something went last time, or to plan for something coming. The present moment is rich, but it isn't the whole picture, and you can act like it is.\n\nYou can also turn presence itself into a concept to think about instead of a thing to actually live. Your mind can get abstract about it—perceiving yourself perceiving, narrating your own awareness—and that adds a quiet layer of distance between you and the moment you were trying to be in.\n\nYour balanced attention can quietly become a way of never committing. By weighing yourself and everyone else equally, all the time, you can dodge the actual question of what you want or what you're going to do. Balance is wisdom until it turns into a permanent excuse not to choose anything.\n\nAnd you can assume other people could see what you see if they just tried harder. Your awareness feels so normal to you that you genuinely underestimate how rare it is—so you get quietly frustrated with people for missing things they were never built to catch in the first place.",

  "frictionPatterns": "You clash with people locked onto the past—the ones replaying old history, hung up on what already happened, making every conversation about back then. They think you're ungrounded, like you don't respect what came before. You think they're trapped in old content that's blocking their view of what's actually happening right now, in front of them.\n\nYou also rub against the relentlessly action-oriented types—the ones who measure everything by output, who think if you're not visibly doing, you're not engaged. Your receptive, taking-it-in mode reads as laziness to people who can only recognize caring when it looks like busyness. To them, sitting with something instead of fixing it looks like doing nothing.\n\nThe always-future people frustrate you in their own way—forever leaving the present for the next plan, the next goal, the next projection. You're trying to perceive what's here, and they're already three steps down a road that doesn't exist yet, missing the actual moment to chase a hypothetical one.\n\nWhat you bring to all that friction is your non-reactivity—you create space for other people to move from a knee-jerk reaction into an actual response. Your growth edge is remembering that being past-focused or future-focused isn't a failure of presence. They're just different orientations with their own real value, even if you don't naturally live there.",

  "energyPatterns": "What drains you:\n- Constant interruptions and notifications fracturing your attention\n- Faking engagement when there's no room to actually be present\n- Explaining what you perceive to someone who can't receive it\n- Loud, shallow, overstimulating environments with nonstop noise\n- Being pushed to do something when just witnessing was what was needed\n- A whole night where everyone's half-here and nobody actually shows up\n\nWhat charges you:\n- A setting where being present is actually possible and valued\n- A conversation that grows out of two people really paying attention\n- Watching someone drop the act and get real\n- Spacious, unfragmented time with nothing pulling at you\n- Being around people who are actually here, not half-elsewhere\n- A long, slow stretch of quiet that lets you actually settle in",

  "workEnvironments": "Where you thrive:\n- Places where the quality of your attention actually matters\n- Counseling, facilitation, care work, contemplative or healing settings\n- Roles that involve holding space for other people\n- Work that needs a careful read on what's happening in the room right now\n- Anything where simply being present is itself the contribution\n\nWhere you suffocate:\n- Environments that fracture your attention nonstop\n- Roles that are all rapid task-switching with no room to be present\n- Cultures that treat looking busy as the same thing as doing good work\n- Loud, high-noise, low-signal places where you can't find a clear thread\n- Settings that need you reacting fast instead of actually present",

  "topCareers": [
    {
      "title": "Mindfulness / Wellness / Mental Health Support Role",
      "description": "You live in the present at a resolution most people never reach—the quality of attention in a room, the shift under the surface. Entry roles in wellness, mindfulness coaching, or peer mental-health support are that perception made into a job: helping other people access the texture of now that you live in natively. You hold balanced attention on yourself and others without losing either one. The presence that fragmented, busy environments couldn't value becomes, here, the entire offering—and it pays you to deepen it."
    },
    {
      "title": "Care Work / Hospice / Companion Roles",
      "description": "You can hold space without needing to fill it, perceiving what's actually going on under what's being said. Entry roles in caregiving, hospice support, or companion work depend on exactly that—presence itself as the contribution, attention as the gift. You don't rush a hard moment or run from its weight; you stay, at full resolution, when most people flinch. The capacity to just be fully present that high-noise settings wasted is precisely what this kind of work asks for, and it's rarer than the field can usually find."
    },
    {
      "title": "Facilitation / Group Support / Hospitality",
      "description": "You perceive the felt sense of a room and catch the meaningful shift before anyone names it. Entry-level facilitation, group support, residential life, or thoughtful hospitality reward that quality of attention—holding a space with enough presence that the real thing can actually surface. You read present dynamics without tipping into self or other. The attentiveness that busyness-equals-value cultures couldn't count becomes the skill the whole role quietly rests on."
    }
  ],

  "blockIndicators": "Your Parser Profile suggests the following CBI block accessibility pattern:\n\nLikely High-Accessibility Blocks:\n- Pattern Recognition (perceiving patterns as they form)\n- Self-Reference Processing (through balanced attention that includes self)\n- Social Signal Processing (through balanced attention that includes other)\n\nLikely Moderate-Accessibility Blocks:\n- Perceptual Discrimination (abstract rather than concrete, but still perceptive)\n- Symbolic Manipulation (conceptual processing of present-moment data)\n- Generative Creation (witnessing as active, not merely passive)\n\nLikely Lower-Accessibility Blocks:\n- Sequential Processing (present-focus may resist temporal sequencing)\n- Spatial Relationships (abstract orientation may de-emphasize concrete spatial processing)\n\nThis pattern suggests your cognitive architecture is optimized for present-moment awareness and reading the quality of right now, with room to grow in stretching that same attention across time—tracking what came before and what's coming—without losing your hold on the present.\n\nMINDFUL",

  "strengths": [
    {
      "title": "You Catch the Pattern as It Forms",
      "description": "You read shifts as they're happening, not after the fact. Where everyone else reconstructs it later—wait, when did the night turn?—you felt the shape of it while it was still unfolding. It gives you an almost predictive thing, where you sense where a moment is heading before it actually gets there, just from being present enough to feel it move."
    },
    {
      "title": "You Tell Real From Fake Instantly",
      "description": "You separate surface from substance automatically. Genuine engagement versus performance, real presence versus polished absence, a conversation that's actually alive versus one that's just going through the motions—those distinctions land for you immediately. You can't be fooled by the polished version of something hollow, even when everyone else buys it."
    },
    {
      "title": "You See Yourself and Others at Once",
      "description": "Your attention holds both directions—you're neither lost in your own head nor completely absorbed in reading everyone else. That balance lets you perceive dynamics that one-directional people miss. You can track how you're doing and how the room is doing in the same breath, which keeps you grounded in situations that throw other people off."
    },
    {
      "title": "You Stay Clear in Chaos",
      "description": "Because you're reading the pattern instead of getting swept into the content, you keep your clarity when everyone else's gets muddied. The emotional intensity in a room doesn't hijack you—you can see it clearly while staying separate from it. That's why people get calmer around you when things get heavy. You're the steady one."
    },
    {
      "title": "You Read Things in Context",
      "description": "You catch how the same thing means totally different things depending on the moment around it. A word, a look, a silence—you read it in its full situational meaning instead of flattening it into one fixed thing. You understand that ripping something out of its context distorts what it actually meant, so you keep the whole picture."
    },
    {
      "title": "Your Attention Is the Tool",
      "description": "Your presence itself is how you understand things. By being fully here, you pick up information that divided, half-here attention just can't receive. Other people gather the facts; you perceive what those facts are actually saying right now. It's a quiet superpower that doesn't look like much from outside but changes everything about what you catch."
    }
  ],

  "challenges": [
    {
      "title": "Frozen by Seeing Too Much",
      "challenge": "Perceiving the full complexity of a moment can make any actual choice feel impossibly crude—like picking one option collapses this whole rich field you're seeing into one flat, reductive trajectory. So you stall, because moving feels like losing the picture.",
      "remedy": "Remember that acting is its own kind of perceiving—you learn things by doing that you literally can't learn by just watching. Let action be another lens, not a betrayal of seeing. Pick the move, and trust that doing it will show you the part observing never could."
    },
    {
      "title": "Worn Out by Translating",
      "challenge": "What you perceive instantly, other people need explained at length, and the gap between knowing something directly and getting it across drains you. It's not that explaining is hard—it's that so much of what you see gets lost the second you try to put it into words.",
      "remedy": "Accept that translation is always lossy. Share the 70% that can actually travel, and hold the other 30% as private perception instead of treating it as failed communication. Not everything you see has to be passed on. Some of it is just yours to notice."
    },
    {
      "title": "Looking Like You Don't Care",
      "challenge": "Your receptive, witnessing mode can read as you being disengaged or not bothered. People read it as not caring, when you're actually caring at a deeper level than their busy, action-focused attention even knows how to recognize.",
      "remedy": "Make your engagement visible sometimes through small actions. Your attention is real, but attention alone is invisible to people who only count caring when it looks like doing. Drop the occasional small, concrete gesture so the people who need proof can actually see that you're in it."
    },
    {
      "title": "Drowning in Noise",
      "challenge": "Environments flooded with low-quality stimulation—constant interruption, shallow back-and-forth, a dozen things pulling at your attention—degrade how you process, fast. You can't filter down to a useful signal when the whole channel is just noise, and it fries you quicker than it fries other people.",
      "remedy": "Protect your environment like it's actual infrastructure, not a preference. Quiet isn't a luxury for you—it's an operational requirement. Speak up for the conditions your attention needs: a calmer space, fewer pings, real breaks. Building that in isn't being precious; it's just maintenance."
    },
    {
      "title": "Out of Sync in Time",
      "challenge": "Your lock on the present can disconnect you from people living in the past or the future. They're deep in a conversation about what happened or what's coming, and you're tracking what's happening right now—and that mismatch creates a quiet, specific kind of loneliness.",
      "remedy": "Practice briefly visiting their time frame—just acknowledging that the past and the future are real even when you don't naturally hang out there. It's not abandoning the present; it's stretching your presence across time so you can actually meet people where they are and connect."
    },
    {
      "title": "Coming Across as Critical",
      "challenge": "Your awareness includes noticing where things fall short of what they could be. To you that's not criticism—it's just pattern recognition—but other people experience it as you judging them, because you keep clocking the gap between what is and what could be.",
      "remedy": "Name the good patterns you see as openly as you name the gaps. Your perception is complete, but your reporting probably skews toward what's missing, because that's what catches your eye. Balance how you talk about it—say the thing that's working out loud, not just the thing that's off."
    }
  ]
};
