// MINDFUL Profile
// Parser Profile™ © 2026 Cognition Blocks LLC
// Abstract • Present • Balanced

export const mindfulProfile = {
  "name": "MINDFUL",
  "code": "Abstract • Present • Balanced",
  "tagline": "The awareness keeper who sees the texture of now",
  "overview": "You inhabit the present moment at a resolution most people never access.\nWhile others skim the surface of their experience, half-attending,\nhalf-elsewhere, you're perceiving the full texture of what's actually\nhappening: the quality of attention in a room, the felt sense of a\nconversation, the subtle shifts that signal something meaningful\noccurring beneath the obvious.\n\nYour cognitive architecture prioritizes abstract patterns over concrete\ndetails, present experience over past or future, and maintains balanced\nattention between self and other. The result is a consciousness uniquely\nsuited to perceiving the how of the present moment, not just what's\nhappening, but the quality with which it's happening.\n\nThis isn't meditation you practiced or awareness you cultivated. It's\nyour native operating system. You've always noticed things others\nfilter out: the precise moment a conversation shifts from genuine to\nperformative, the quality of silence between words, the difference\nbetween presence and proximity. What others must work to achieve, being\nhere now, is your default state.\n\nThe Mindful profile represents approximately 3% of the population.\nYou're rare because this configuration requires three relatively\nunusual settings: abstract processing (pattern over detail), present\nfocus (now over then or later), and balanced reference (neither\npredominantly self nor other). Most people land somewhere more concrete,\nmore temporally displaced, or more directionally focused.\n\nYour gift is perceiving what's actually present when most minds are\nelsewhere. Your challenge is translating that perception into forms\nothers can receive. You see the quality of the moment clearly, but that\nclarity doesn't automatically communicate itself to those operating at\ndifferent temporal and conceptual altitudes.\n\nUnderstanding your profile means recognizing that your present-moment\nawareness isn't a practice to maintain but an architecture to leverage.\nYou're not trying to be mindful, you're perceiving reality through a\nfilter that others must deliberately construct.",
  "howYouLearn": "You learn through direct perception and pattern extraction from live\nexperience. Abstract frameworks engage you intellectually, but they\nbecome real-only when you can observe them operating in present-moment\nreality.\n\nYour optimal learning environment provides rich phenomena to perceive\nrather than pre-digested explanations. You want to see the thing itself,\nnot descriptions of the thing. You want to watch the process unfold, not\nread about its stages. Give you access to experience and you'll extract\nthe patterns yourself, often more accurately than secondhand frameworks\nprovide.\n\nYou struggle with learning that's purely symbolic or entirely\nfuture-referenced. \"This will matter later\" doesn't motivate you the\nway \"notice what's happening now\" does. You also struggle with\nlearning environments that fragment attention, multiple competing inputs\nprevent the quality of presence your processing requires.\n\nDemonstrations work better than explanations. Observation works better\nthan instruction. Immersion works better than abstraction. You learn by\nbeing present to phenomena, not by being told about them. The most\neffective teachers for you are those who can point rather than explain,\nwho can direct your attention rather than substitute their understanding\nfor your perception.",
  "howYouCommunicate": "You communicate through precise description of present-moment\nperception. Where others speak in generalities, you name specifics, not\nconcrete details necessarily, but the exact quality of what you're\nperceiving. \"Something shifted just now.\" \"That's not the same kind\nof silence.\" \"You're present in a different way than you were.\"\n\nThis precision can be disorienting for those who aren't tracking at\nyour resolution. They may not know what you're referring to or may feel\nobserved in ways that make them self-conscious. Your perception, shared\ndirectly, can feel like exposure.\n\nYou tend toward fewer words rather than more, you're not performing\nunderstanding or filling silence. When you speak, it's because\nsomething became clear enough to articulate. Others may experience this\nas withholding or judgment when it's actually just waiting for\nperception to crystallize into language.\n\nYou communicate most effectively in contexts that allow spaciousness,\nwhere silence is acceptable, where conversation can emerge from shared\nattention rather than needing to be manufactured. You communicate least\neffectively in rapid-fire exchanges that prioritize speed over presence,\nor in environments where verbal output is equated with engagement.",
  "phrase": "You're not detached from reality, you're more attached to it than\npeople who are lost in past or future. Your awareness isn't absence;\nit's the deepest form of presence.",
  "secret": "You've always known that most people aren't actually here. They're\nrehearsing, replaying, projecting, defending, but they're not present.\nYou've watched conversations happen where no one was listening. You've\nsat in rooms full of people and felt entirely alone because you were the\nonly one who showed up.\n\nThis awareness started young. You noticed that adults said one thing and\nmeant another, that attention was rare and usually conditional, that\nmost interaction was performance rather than presence. You didn't judge\nthis, you just saw it. And seeing it made you feel like you were\nwatching from behind glass.\n\nThe secret you've carried is that your awareness isolates you. The very\nthing that lets you perceive more clearly also separates you from those\nwho don't. You see the texture they're missing, and that seeing\ncreates distance. You've wondered if you're doing something wrong, if\nsomehow your awareness is the problem, if you should learn to see less\nclearly so you could belong more easily.\n\nBut you can't unsee what you see. And you've never found a way to\nexplain it that doesn't make you sound arrogant or detached or somehow\nsuperior. So you've stayed quiet, present to moments that others miss,\nholding awareness that has nowhere to go.",
  "whatOthersGetWrong": "About You\n\nThey think you're passive because you're not constantly acting. They\ndon't understand that reception is its own form of engagement, that\nyour witnessing is active, that your silence is full rather than empty.\nThey equate presence with output and mistake your attention for absence.\n\nThey think you're aloof because you don't get swept up in reactions.\nYour non-reactivity looks like not caring when it's actually caring\nwithout distortion. You're not above the situation, you're in it more\nfully than they are, just without the drama they expect caring to\ninclude.\n\nThey think you're judging them because you see so clearly. Your\nperception feels like scrutiny even when it's just attention. They're\nnot used to being seen that closely, and closeness without familiar\nemotional signals makes them nervous about what you might be thinking.\n\nThey think your awareness is a practice you do rather than the way you\nare. They imagine you meditate extensively or study Buddhism or work\nhard to be present. They don't understand that this is just how you\nprocess reality, that presence isn't something you achieve but\nsomething you can't escape.",
  "hiddenSuperpower": "You can be fully present to experiences that overwhelm others. Your\nabstract processing combined with present-focus and balanced reference\ncreates a unique capacity to witness intensity without being destroyed\nby it. You can sit with dying people, hold space for grief, accompany\nothers through crisis, not because you're numb but because you can\nperceive without merging.\n\nThis capacity makes you invaluable in moments that matter most. When\neveryone else is reacting, defending, fleeing, you're still there,\nstill perceiving, still present. Your lived experiences become a\ncontainer of experiences waiting to be shared with someone in need. You\ngive reality a place to land.\n\nYou also perceive when presence is happening in others. You notice when\nsomeone shifts from performance to authenticity, when a conversation\nbecomes real, when a group moves from collection to connection. You\ntrack these transitions that others miss entirely, and your tracking\nsomehow supports them happening more often.\n\nYour awareness is generative, not just receptive. By being fully\npresent, you create conditions for others to become more present too.\nYou're not just observing the quality of attention in a room, you're\ninfluencing it by the quality of your own attention.",
  "blindSpot": "You may undervalue information that exists in past patterns or future\nprojections. Your present-focus is a strength until it becomes temporal\nmyopia, missing context that requires historical perspective or\nstrategic foresight. The present moment is rich, but it's not complete;\nsome patterns only reveal themselves across time.\n\nYou may also intellectualize presence rather than inhabiting it. Your\nabstract processing can turn awareness itself into a concept to think\nabout rather than an experience to have. You might perceive yourself,\nperceiving in ways that add a layer of distance to what could be a\ndirect experience.\n\nYour balanced reference can become a way of avoiding commitment. By\nattending equally to self and others, you may evade the question of what\nyou want or what serves others. Balance is wisdom until it becomes a way\nof never having to choose.\n\nAnd you may assume others could perceive what you perceive if they just\npaid attention. Your awareness feels natural to you; you may not fully\ngrasp how rare it is or how much effort it would take for others to see\nwhat you see. This assumption can lead to frustration when others miss\nwhat seems obvious, and to communication that doesn't bridge the\nperceptual gap.",
  "frictionPatterns": "You clash most with Concrete • Past • Other (Legacy) processors.\nThey're anchored in specific historical facts serving collective\nmemory; you're perceiving abstract present-moment patterns with\nbalanced attention. They think you're ungrounded and dismissive of\nhistory. You think they're trapped in content that obscures present\nreality. The conflict is Concrete vs. Abstract, Past vs. Present, two\ndimensions of opposition.\n\nYou also experience friction with heavily action-oriented profiles,\nthose who measure engagement by output and presence by productivity.\nYour receptive mode reads as laziness or disengagement to those who can\nonly recognize caring in visible doing.\n\nHigh-future processors may frustrate you by constantly leaving the\npresent for projections and plans. You're trying to perceive what's\nhere; they're already somewhere else. The temporal mismatch creates\nconversations where it seems you're, but never quite in the same\nmoment.",
  "energyPatterns": "What Energizes You:\n\n• Environments where presence is possible and valued\n\n• Conversations that emerge from shared attention rather than\nmanufactured connection\n\n• Witnessing authenticity in others\n\n• Spacious time without fragmentation\n\n• Being with people who are mentally and emotionally present\n\nWhat Drains You:\n\n• Constant interruption and attention-fragmenting environments\n\n• Performing engagement when presence isn't possible\n\n• Explaining your perception to those who can't receive it\n\n• Environments saturated with noise and shallow stimuli\n\n• Pressure to act when witnessing is what's needed",
  "workEnvironments": "You thrive in environments where quality of attention matters,\ncontemplative settings, therapeutic contexts, roles involving holding\nspace for others, work requiring nuanced perception of present dynamics.\nFacilitation, counseling, certain artistic practices, meditation\ninstruction, hospice care, any role where presence itself is the\ncontribution.\n\nYou struggle in environments that fragment attention relentlessly open\noffices with constant interruption, roles requiring rapid\ntask-switching, cultures that equate busyness with value. High-noise,\nlow-signal environments degrade your processing faster than you can\nrestore it.\n\nIdeal factors: protected attention, valued presence, spacious pace,\nmeaningful witnessing, colleagues who are mentally present. Avoid:\nattention fragmentation, performance metrics divorced from quality,\ncultures where doing is the only recognized form of caring.",
  "blockIndicators": "Your Parser Profile suggests the following CBI block accessibility\npattern:\n\nLikely High-Accessibility Blocks:\n\n• Pattern Recognition (perceiving patterns as they form)\n\n• Self-Reference Processing (through balanced attention that includes\nself)\n\n• Social Signal Processing (through balanced attention that includes\nother)\n\nLikely Moderate-Accessibility Blocks:\n\n• Perceptual Discrimination (abstract rather than concrete, but still\nperceptive)\n\n• Symbolic Manipulation (conceptual processing of present-moment data)\n\n• Generative Creation (witnessing as active, not merely passive)\n\nLikely Lower-Accessibility Blocks:\n\n• Sequential Processing (present-focus may resist temporal sequencing)\n\n• Spatial Relationships (abstract orientation may de-emphasize concrete\nspatial processing)\n\nThis pattern suggests your cognitive architecture is optimized for\npresent-moment awareness and nuanced perception of quality. Your\ndevelopmental opportunities lie in temporal extension, learning to track\npatterns across time without abandoning present-focus, and in concrete\ngrounding when abstraction needs anchoring. The most mature version of\nyour architecture perceives the present in full temporal context without\nlosing presence.",
  "strengths": [
    {
      "title": "Real-Time Pattern Perception You detect patterns as they emerge, not",
      "description": "retroactively. Where others reconstruct what happened after the fact,\nyou're perceiving the shape of events while they're unfolding. This\ngives you an almost predictive quality, you sense shifts before they\ncomplete because you're tracking the pattern's formation, not waiting\nfor its conclusion."
    },
    {
      "title": "Quality Discernment You distinguish between surface and substance",
      "description": "automatically. The difference between genuine engagement and\nperformance, between authentic presence and polished absence, between\nalive conversation and dead ritual, these distinctions are immediately\napparent to you while others might not notice them at all."
    },
    {
      "title": "Balanced Witnessing Your dual attention to self and other creates a",
      "description": "uniquely comprehensive perspective on situations. You're neither lost\nin your own experience nor absorbed entirely in reading others. This\nbalance lets you perceive dynamics that single-directional processors\nmiss entirely."
    },
    {
      "title": "Non-Reactive Clarity Because you're perceiving patterns rather than",
      "description": "being swept into content, you maintain clarity under conditions that\nmuddy most people's perception. Emotional intensity in a room doesn't\nhijack your awareness, you can observe it while remaining distinct from\nit."
    },
    {
      "title": "Contextual Sensitivity You perceive how the same content means",
      "description": "different things in different contexts. A word, a gesture, a silence,\nyou read these in their full situational meaning, understanding that\nabstraction from context distorts understanding. Others mistake the\nfinger for the moon; you track both."
    },
    {
      "title": "Presence as Perception Your attention itself becomes a tool of",
      "description": "understanding. By being fully present, you access information that\ndivided attention cannot receive. Others gather facts; you perceive what\nthe facts are actually saying right now."
    }
  ],
  "challenges": [
    {
      "title": "Action Paralysis Perceiving present-moment complexity in full detail",
      "challenge": "can make action feel impossibly reductive. Any choice collapses the rich\nfield of possibility you're perceiving into a single crude trajectory.\nThe remedy isn't less perception but understanding that action is\nitself a form of perception, you learn things by doing that you cannot\nlearn by observing. Let action be another lens, not a departure from\nseeing.",
      "remedy": ""
    },
    {
      "title": "Translation Exhaustion What you perceive directly, others need",
      "challenge": "extensively explained. The gap between immediate knowing and\ncommunicable knowledge drains you, not because explaining is hard, but\nbecause so much is lost in translation. Accept that translation is\nalways lossy. Share the 70% that can travel; hold the 30% as private\nperception rather than failed communication.",
      "remedy": ""
    },
    {
      "title": "Apparent Passivity Your receptive, witnessing mode can read as",
      "challenge": "disengagement or indifference. Others may perceive you as not caring\nwhen you're actually caring at a deeper level than their action-focused\nattention can recognize. Make your engagement visible periodically\nthrough small actions. Your attention is real, but attention alone is\ninvisible to those who equate caring with doing.",
      "remedy": ""
    },
    {
      "title": "Overwhelm in Noise Environments saturated with low-quality stimuli,",
      "challenge": "constant interruption, shallow interaction, attention-fragmenting\ndemands, degrade your processing quickly. You can't filter to a useful\nsignal when the channel is all noise. Protect your perceptual\nenvironment as non-negotiable infrastructure. Quiet isn't preference;\nit's operational requirement.",
      "remedy": ""
    },
    {
      "title": "Temporal Isolation Your present-focus can disconnect you from those",
      "challenge": "oriented to past or future. They're having conversations about what was\nor will be; you're tracking what's happening right now. The temporal\nmismatch creates subtle loneliness. Learn to briefly visit their\ntemporal frames, acknowledging past and future exist even when you\ndon't naturally dwell there. It's not abandoning the present; it's\nextending presence across time.",
      "remedy": ""
    },
    {
      "title": "Judgment as Failure Your awareness includes perceiving where things",
      "challenge": "fall short of what they could be. This isn't criticism, it's just\npattern recognition, but others may experience your perception as\nnegative judgment. Name the positive patterns you perceive as explicitly\nas you notice gaps. Your perception is complete; your reporting may be\nskewed toward what's missing.",
      "remedy": ""
    }
  ]
};
