// RESILIENT Profile — Young Adult (18–29)
// Parser Profile™ © 2026 Cognition Blocks LLC

export const resilientyaProfile = {
  "name": "RESILIENT",
  "tagline": "The one who already saw it coming and packed for it",

  "overview": "You see around corners. While everyone else gets blindsided by the thing that was honestly pretty predictable—the group trip that falls apart because nobody booked anything, the project that tanks because nobody read the assignment—you'd already run it in your head, spotted the weak point, and quietly got ready. This isn't you being anxious. It's just your brain pointed at what could go wrong, on purpose.\n\nThey call it being a pessimist. You call it being awake.\n\nYou've been the person who \"just happened\" to have the charger, the cash, the backup plan when it all went sideways. The one who asked the uncomfortable question before everyone signed the lease. The one who said \"okay but what if this doesn't work\" and got ignored until the exact moment it didn't work. Your prep looks like negativity right up until it looks like you saving the whole thing.\n\nYou don't lie awake worrying about the future. You get ready for it—and those are not the same thing, even though the people who confuse them are usually the ones caught completely off guard when reality doesn't match the hype. You've learned to prepare quietly, because the credit only ever comes in hindsight, once the disaster you called is the one everyone's finally dealing with. And by then you're already thinking about the next thing that could break.",

  "howYouLearn": "The case studies that include the disasters teach you more than any success story. A clean win with all the failures edited out is missing the exact part your brain reaches for—you want to know where it broke, what they didn't see coming, where the bodies are buried. A breakdown of how a startup died or a plan fell apart lights you up, because it's basically a map of failure modes you can carry into your own next thing.\n\nYou trust the people with scars way more than the people with confidence. The friend who actually went through the bad year can tell you what the advice column leaves out—how the plan met reality and bent, and what they grabbed for when it did. A motivational speech from someone who's never face-planted lands flat for you. You want to learn from the survivor, not the cheerleader.\n\nTheory that's never been stress-tested doesn't stick. An idea nobody's ever pushed until it breaks feels unfinished to you—you don't really believe you've learned something until you've seen where its edges are. You learn way more from actually trying it and watching it fail in a low-stakes way than from being told how it's supposed to go.\n\nYou need the full picture, including the part where it goes wrong, before you feel like you actually know the thing. The all-upside version registers to you as half a lesson. Show you both sides, run it until it breaks, and now you've got something you can actually lean on when the real day comes.",

  "howYouCommunicate": "\"What if this doesn't work?\" isn't you trying to kill the plan—it's you trying to finish it. You ask the question that closes the gap nobody else wanted to look at, because a plan with no answer to that question isn't done, it's just hopeful. To you the downside isn't being negative. It's the other half of a complete picture.\n\nYou tend to walk people through the scenarios, not just hand them the conclusion. Where someone else gives a flat \"it'll be fine,\" you lay out the branches—if this, then that; if that falls through, here's the backup. It makes your thinking easy to follow, and to a group that just wanted the hype, it can sound like you're raising problems instead of solving them.\n\nWhen things actually go wrong, people turn to you, and they're always surprised how calm you are. You're calm because you already ran this exact scenario in your head two weeks ago—you did the freaking-out in advance, so while everyone's in shock you're already in fix-it mode with half the backup plan built.\n\nWhere it gets harder is the crowd that only wants good vibes. They hear your completeness as pessimism, your \"wait, have we thought about—\" as a wet blanket on the whole thing. You do your best work with people who already value being ready—anyone who's organized an event, run a trip, managed a budget—where the question that gets you called negative everywhere else is exactly the one they actually needed asked.",

  "phrase": "You're not negative. You're complete. They see the upside and call it realism. You see both sides and they call you a downer.",

  "secret": "You've spent your life seeing what could go wrong while everyone around you stared only at what could go right. And you learned to keep most of it to yourself, because people don't want to hear it. They want the hype, the optimistic plan, the good vibes only.\n\nBut you're not actually pessimistic. You're prepared. And honestly you've got more peace than the optimists, because you're not betting everything on the best case. You ran the scenarios. You know the backups. You can hope it goes great precisely because you got ready for it not to.\n\nYou've saved things nobody knows you saved. Trips that would've fallen apart. Nights that would've gone bad. Friendships that would've fractured. The disaster that doesn't happen leaves no trace—your prep is invisible exactly when it works, which is most of the time.\n\nThe deepest part: you're tired of being the one who sees the risk. Tired of holding the backup plan alone. Tired of getting called a downer right up until the moment you're the most needed person in the room. You'd love to just relax into the optimism like everyone else. You've just seen too much. You know better.",

  "whatOthersGetWrong": "They think you're worried when you're actually ready. From the outside the two look identical—both involve thinking about what could go wrong—but anxiety just spins without landing anywhere, and your scenario-running lands on an actual plan. You're not fretting. You're building the response, and once it's built you're calmer than the optimists, because you're not depending on everything going perfectly.\n\n\"Negative,\" they call you, when all you did was name the downside they preferred not to look at. But looking away from a risk doesn't shrink it—it just guarantees nobody's ready for it. \"You always expect the worst,\" they say, and it's the same people who later quietly needed the backup you built while they were rolling their eyes.\n\nThey think your habit of weighing both sides means you have no conviction. You've got conviction. It's just about something they don't want to hear—that good outcomes come from prep, not from hope alone. Holding the upside and the downside at the same time isn't fence-sitting. It's refusing to pretend half the picture isn't there.\n\nAnd they think you can't enjoy anything because you see what could go wrong. The opposite, actually. You enjoy stuff with your eyes open, which makes your fun sturdy—it's not riding on nothing breaking. Theirs is the fragile kind that shatters the second reality doesn't cooperate. Yours already accounted for the weather.",

  "hiddenSuperpower": "You're calm when everyone else panics because you already processed the scenario they're just walking into. While they're in shock, you're in response mode. The crisis that flattens them is basically a Tuesday for you—not because you're cold, but because you did the emotional work of bracing for it ahead of time, weeks ago, when nobody was watching.\n\nYou don't just see problems coming—you build the response. When something breaks, you know how to get it working again because you already thought through the fix. Your backups aren't just \"if X, then panic\"—they're \"if X, then specifically do Y.\" That's the difference between you and someone who's just nervous.\n\nYou catch fragility other people miss. The plan everyone thinks is solid, you see as one bad break from collapse. So you strengthen it before it fails, flag the problem early, and end up positioned for things to go wrong while everyone else is only positioned for things to go right.\n\nAnd you can hold hope and realism at the same time. You're not picking between optimist and pessimist—you're running both at once, which is rarer and way more useful than either one alone.",

  "blindSpot": "You over-prepare for futures that never show up. Your brain is so good at generating scenarios that it generates way more than the situation actually calls for, and you can pour real time and energy into bracing for something that was never going to happen. The same ability that saves the day when the rare disaster lands also quietly taxes every normal day that turns out completely fine.\n\nBeing aware of risk can tip into amplifying it. Not every scenario your brain produces deserves equal weight, but they can all arrive feeling equally vivid and urgent, and without a filter you'll treat a one-in-a-thousand thing like a coin flip. And the worry doesn't always stay in your head—you can dump a load of \"here's everything that could go wrong\" onto a friend who's not built to carry it, and now they're anxious without being any more ready.\n\nBecause your attention scans forward, you can miss what's behind you. The pattern from last time that would totally predict this risk slips past, because you're modeling the future from scratch instead of checking whether you've literally seen this exact failure before. Your forward-lean is a strength with a blind spot directly behind it.\n\nAnd the hard one: weighing both sides so evenly can lock you up when your own interest and everyone else's actually conflict. You end up advocating for neither, frozen at the exact moment a call needed to get made. Prep is how you buy a sense of control—and in the situations that are genuinely uncontrollable, the preparing itself becomes the thing stressing you out, a grip tightening on something that was never going to hold still.",

  "frictionPatterns": "You rub up hardest against the pure optimist—the one who wants to believe in the upside and never once glance at the downside, who hears your backup plan as you betraying the vision. To them, naming what could break is basically wishing for it to break. To you, refusing to name it is how you guarantee nobody's ready. You're both staring at the same plan; one of you is checking the half the other one skipped.\n\nThe people who love floating in ideas with no connection to actual reality wear on you too. You want to know how the idea behaves when it meets a real Tuesday and something goes sideways; they're happy just admiring the concept. And the person who's never learned a single thing from failing, trying to teach you about success—that lands badly. You trust the survivor's scars over the cheerleader's confidence every time.\n\nThere's a specific grind in the group that treats having a backup plan as being a downer—where doing the responsible thing gets you read as the buzzkill, and everyone would rather feel good now than be ready later.\n\nWhat you bring to that friction is the missing half: you keep the bold plan honest about what it'll cost and ready for what it'll actually run into. Your growth edge is remembering the optimists aren't fools and the look-back people aren't stuck. Their faith can carry a room through the part where your caution would freeze it, and the history you skip past sometimes holds the exact pattern you're trying to predict.",

  "energyPatterns": "What drains you:\n- Groups that treat being aware of risk as just being negative\n- Being the only one who actually prepares for anything\n- Plans with zero backup and pure hope\n- \"It'll be fine\" energy built on denial instead of any prep\n- Warnings you raised getting ignored until they come true\n- Getting called a pessimist when you were just being real\n\nWhat charges you:\n- Your prep actually paying off when things go wrong\n- Building a backup into a plan and watching it hold\n- People actually valuing that you see the risks\n- A contingency that quietly prevents a disaster\n- A group that shares the prepping instead of dumping it on you\n- Calling a risk right and having reality back you up",

  "workEnvironments": "Where you thrive:\n- Places where seeing risk is valued, not waved off\n- Emergency and safety work, operations, healthcare, security\n- Teams that have actually learned from things going wrong\n- Where having a backup plan is just standard, not paranoia\n- People who appreciate a realistic read instead of only hype\n\nWhere you suffocate:\n- Toxic-positivity crowds that punish you for naming any risk\n- Cultures where \"negative thinking\" gets you side-eyed\n- Places that treat failure as unthinkable instead of something to prep for\n- Groups that read a backup plan as you not believing in them\n- Rooms where only the cheerleaders get ahead",

  "topCareers": [
    {
      "title": "Operations / Logistics Coordinator",
      "description": "You see around corners—you already ran the scenarios and got the backup ready nobody wanted until they suddenly needed it. Operations and logistics work is that instinct turned into a job: spotting what could go wrong before it does and building the plan that turns a disaster into a Tuesday. The question you ask before launch instead of after the crash is the whole value here. Coordinator and ops-assistant roles are real entry points in your twenties, and the prep that read as pessimism in hype-only rooms finally lands somewhere it reads as foresight."
    },
    {
      "title": "Emergency Services / Safety Roles",
      "description": "You're the one who \"just happened\" to have what was needed when it all went wrong—because you saw it coming and quietly got ready. Emergency services and safety work is built around exactly that: a realistic read of how things fail, plans for the bad day, and the calm that comes from having already braced for it. You don't catastrophize; you prepare. EMT training, dispatch, safety coordinator, and lifeguard-type roles take people on young, and the uncomfortable foresight that made your friends wince becomes the discipline these fields literally can't run without."
    },
    {
      "title": "Risk / Quality Assurance Support",
      "description": "While everyone assumes it'll be fine, you've already mapped how it breaks and what you'd do about it. Risk and quality-assurance work pays for precisely that vigilance—treating failure as something to prepare for instead of something unthinkable. You hold realism without panic, the steady middle that plans for the worst while still functioning in the present. QA tester, junior risk analyst, and compliance-support roles are real entry points, and the risk-radar that read as you being a downer becomes the entire reason you're the one people trust."
    }
  ],

  "blockIndicators": "Your Parser Profile suggests the following CBI block accessibility pattern:\n\nLikely High-Accessibility Blocks:\n- Sequential Processing (scenario and contingency planning)\n- Pattern Recognition (spotting risk patterns)\n- Perceptual Discrimination (tracking concrete detail)\n\nLikely Moderate-Accessibility Blocks:\n- Self-Reference Processing (balanced, accessible)\n- Social Signal Processing (balanced awareness of others)\n\nLikely Lower-Accessibility Blocks:\n- Generative Creation (focus on prep over inventing new stuff)\n- Symbolic Manipulation (abstract reasoning without concrete grounding)\n\nThis pattern suggests your cognitive architecture is optimized for seeing what's coming, getting ready for it, and staying functional when it actually hits. Your room to grow is in trusting that not every scenario deserves equal prep, and in checking the past for patterns instead of always modeling the future from scratch.\n\nRESILIENT",

  "strengths": [
    {
      "title": "Running the What-Ifs",
      "description": "You naturally play out \"what if\"—not anxiously, but systematically. What could go wrong? What would we actually do about it? That mental rehearsal means you've often solved the problem before it even happens, just because you already imagined it once on the walk to class."
    },
    {
      "title": "Calling Risk Accurately",
      "description": "You don't panic about everything—you evaluate the specific thing. What's the actual chance this goes wrong? How bad would it actually be? Your concerns are worth taking seriously because you're not crying wolf about every little thing. When you flag something, it's usually a real wolf."
    },
    {
      "title": "Always Has a Plan B",
      "description": "Plan A is never the only plan you've got. You had B and C ready before A even launched. Your backups have quietly saved trips, projects, and friendships—usually without any credit, because the disaster just never happened and nobody knew how close it came."
    },
    {
      "title": "Pivots Without Falling Apart",
      "description": "Because you already imagined a few different ways it could go, you can switch gears when things change. You're not locked into one path that shatters the second reality moves. That flexibility makes you resilient in the literal sense—you absorb the hit and keep functioning while others freeze."
    },
    {
      "title": "Calm When It Hits",
      "description": "A crisis feels way more manageable to you because it's not a total surprise. You already ran this scenario. You already know the response. While everyone else is still processing the shock, you're quietly already doing the thing that fixes it."
    },
    {
      "title": "Thinks About Everyone",
      "description": "Your prep accounts for more than just you. You're thinking about how the thing going wrong hits you and how it hits everyone else in it. Your backup plans tend to cover the whole group, not just your own spot in it, which is why people end up relying on you."
    }
  ],

  "challenges": [
    {
      "title": "Prep That Never Ends",
      "challenge": "Every scenario feels worth preparing for, and the prep never feels finished. You're ready for everything except how tired you are. Your ability to see risk runs way ahead of your ability to actually handle all of it, and the list just keeps growing.",
      "remedy": "Weight by probability. Not every scenario deserves equal prep. Rank them by how likely and how bad—prep hard for the likely stuff, lightly for the long-shot stuff, and let the rest go. Accept that you genuinely cannot prepare for everything, and trying is its own kind of crash."
    },
    {
      "title": "Missing the Actual Present",
      "challenge": "Living in prep mode turned right now into staging ground for some future scenario. The fun and the rest keep getting pushed because there's always more to get ready for. The secure future you're chasing never actually arrives, because you're always already securing the next one.",
      "remedy": "Schedule unprepared time. Block off stretches where prepping is straight-up off-limits—a night out, a day where you don't plan anything. Treat being present as its own form of resilience, the kind that comes from rest and people, not from one more contingency."
    },
    {
      "title": "The Warning Nobody Listened To",
      "challenge": "You saw the risk, you said it out loud, and they didn't listen. Then it happened. And the pattern just repeats—warn, get waved off, get proven right, repeat. It breeds a real frustration and a creeping cynicism. You're tired of being the one who called it and got ignored.",
      "remedy": "Work on how you say it, not just whether you see it. Lead with a fix, not just the doom. Acknowledge what they're excited about first, then frame the backup as protecting that excitement. You can't control whether they listen, but you can stack the odds way better."
    },
    {
      "title": "Gripping the Uncontrollable",
      "challenge": "Prep is how you create a feeling of control, but some things are genuinely out of anyone's hands. Your attempts to prepare for those turned into their own source of stress—you're white-knuckling something that was never going to sit still no matter what you did.",
      "remedy": "Sort the controllable from the uncontrollable. For what you can actually influence, prep away. For what you can't, practice letting it be—genuinely. Build up a tolerance for not knowing in the areas where prepping does literally nothing but stress you out."
    },
    {
      "title": "Getting Called the Downer",
      "challenge": "Your realistic read on risk gets heard as negativity by people who'd rather not look at the downside at all. You're actually balanced, but the \"pessimist\" label sticks anyway—usually slapped on by the same people who later quietly needed the realism you brought.",
      "remedy": "Lead with the positive. Before you bring up the risk, name the goal and what could go right. \"Here's how we make sure this works even if X happens\" lands a hundred times better than \"what if X happens?\" Same exact content, totally different reception."
    },
    {
      "title": "Carrying It All Alone",
      "challenge": "Other people don't prep like you do, so you end up carrying all of it solo. That centralizes the whole group's resilience in just you—which wears you out and leaves everyone else never building the skill themselves.",
      "remedy": "Teach the thinking instead of just doing it. Show people how to run their own what-ifs rather than always running them yourself. Your prep is worth way more as something you multiply across a group than as a thing you do alone. The group's only as ready as its least-ready person."
    }
  ]
};
