// SEASONED Profile — Young Adult (18–29)
// Parser Profile™ © 2026 Cognition Blocks LLC

export const seasonedyaProfile = {
  "name": "SEASONED",
  "tagline": "The one who's already paid the tuition",

  "overview": "You're 22 and somehow the one everyone in the friend group comes to when their thing falls apart. The breakup, the lease drama, the job that ghosted them after the third interview—they show up at your door like you've got a manual nobody handed you. And kind of, you do. You've just already been through enough of it to know how it goes.\n\nPeople your age call you an old soul, and they don't always mean it as a compliment. You've watched a roommate \"find their own way\" with money and end up exactly where you quietly knew they'd end up. You're not trying to control anyone. You're just efficient. You already ran that experiment and found the wall they're about to walk into.\n\nWhen you tell someone how to do something—change the tire, handle the boss, set up the spreadsheet, talk to the landlord—you're not being bossy. You're handing over something that cost you. You learned it the slow, expensive way so you wouldn't forget it, and now it's just yours.\n\nThey call it \"set in your ways\" like you're 60. You'd call it figured out. There's a real difference between being stuck in what you've been through and being built by it—and you can feel which one you are.",

  "howYouLearn": "You learn by getting your hands on it and doing it badly first. Reading the syllabus, watching the how-to video, listening to someone explain it—that's the table of contents, not the book. The actual learning starts the second you've tried it, messed it up, and felt exactly where it broke. \"Okay but how does this actually work in real life\" is the first thing out of your mouth in every class.\n\nThe abstract stuff slides right off. A principle with no real situation attached to it has nowhere to land in your head. But the same lesson baked into something you actually did—the shift you worked, the project you ran, the time it all went sideways on you—that one's permanent. It's stored in the doing, not the words about the doing.\n\nYour favorite teacher was never the one with the cleanest slides. It was the person at your first job who'd actually done it for years and told you about the time everything went wrong. You'd learn more in one shift next to them than in a whole semester of theory, because you're after the hard-won stuff—the dead ends they already mapped so you don't have to fall in all of them yourself.\n\nWhat doesn't work for you is dabbling. Touching ten subjects for a week each leaves you with nothing solid to stand on. You're a depth person. Going deep on one thing over and over is what builds the pattern library that eventually lets you see a problem coming before anyone's done explaining it.",

  "howYouCommunicate": "Your credibility comes from having actually done the thing, not from a title or a grade. When you say something with that flat certainty, it's because you've been there—run the shift, made the mistake, found the fix—and people can hear the difference between that and someone repeating a TikTok. You're direct. You say what works and what doesn't without a lot of cushioning, because the truth cost you something and softening it into a maybe feels like a waste.\n\nWhen you're showing someone how to do something, you're naturally organized about it, and you never studied how to be. You just remember the order it had to come in for you—the part that makes no sense until the earlier part is solid. You teach in the sequence that actually makes someone good fastest, not the sequence that sounds smartest.\n\n\"Just do it this way and you'll see\" is your default, and it's usually right. The understanding tends to show up in the doing, after the action, not before. You'd rather put someone's hands on it than walk them through the theory of it, because you know where the real learning actually lives.\n\nYou're at your best in rooms where being good at the thing is what counts. Around people who respect what's been proven, your plainness reads as exactly what it is—earned. In rooms full of people who reward clever talk over actually-can-they-do-it, that same plainness can land as blunt, and you've learned to clock which kind of room you're in before you decide how much to say.",

  "phrase": "You're not stuck in the past—you're standing on it. There's a difference between being trapped by what you've been through and being built by it.",

  "secret": "You've figured out ways of doing things that actually work, and watching people wave them off to \"do it their own way\" is quietly painful in a way you don't talk about. You're not trying to run their life. You're efficient. You already paid the tuition on that exact mistake and you're trying to give them the receipt for free.\n\nYou've quietly become the person who keeps things running—the group chat logistics, the shift that goes smooth because you set it up right, the system your roommates use without ever clocking that you built it. Your fingerprints are on stuff that just works, and nobody credits you for it because you made it look obvious.\n\nYou've had people twice your age and people your own age tell you to \"loosen up\" and \"be more open\"—usually people who haven't actually done anything yet. You've watched confident newcomers blow off your way of doing it, fail right on schedule, and then quietly start doing it your way without ever saying so. And then it happens again with the next person.\n\nThe deepest part: you're not sure any of it carries. You've built real competence young, and some nights you wonder if anyone your age even values that kind of thing, or if they'll just keep relearning everything the hard way while what you know sits there unused. The thought of it going nowhere gets under your skin more than you let on.",

  "whatOthersGetWrong": "They call you rigid when the real word is optimized. You didn't land on your way of doing things out of habit—you got there through trying, failing, and adjusting until something actually delivered. What looks like stubbornness from outside is the leftover of everything you already tested and ruled out. \"You're so resistant to change,\" they say, when what you're actually resistant to is going backward—someone repackaging a worse way as a fresh idea.\n\n\"You're not creative\" usually comes from people whose great new idea won't survive its first real Monday. You've watched a lot of shiny plans break on the exact rocks your method was built to avoid, so your skepticism isn't a closed mind. It's pattern recognition with a track record behind it, even if that track record is only a few hard years long.\n\nThey assume that because you trust what's already worked, you can't adapt. You adapt constantly. You just do it by building on what works instead of torching it and starting from zero—because you actually know what starting from zero costs in time, money, and sanity. Tweaking the thing is still change. It's just change that keeps the wins instead of paying for them twice.\n\nThe one that stings: they think you guard your way of doing things out of ego. It's not pride. You're not protecting the method, you're protecting the result it reliably gets you. They see someone being difficult. What's actually there is someone refusing to trade something that works for something that just sounds better.",

  "hiddenSuperpower": "You can train anyone. Because you learned everything by doing it in order, you know exactly what a new person needs to learn, when, and through which mistakes. You've walked the whole path, so you can map it for someone else. You know the pitfalls because you fell in them. You know the shortcuts because you earned them.\n\nYou've probably got systems for stuff other people handle in pure chaos—your money, your week, the way you prep before a shift or a deadline—and your systems actually hold. Not because they're clever, but because you ran them until the parts that break got fixed.\n\nWhen something goes wrong, you often know why before the person is even done describing it. You've seen this exact failure. You know what causes it. You know how to fix it. People start coming to you first because going to you saves them an hour of flailing.\n\nAnd the best part: what you teach actually works when other people do it. Not a watered-down version that only works when you're standing there—the real thing. Your way of doing it isn't tied to your personal magic. It transfers. Which means your impact reaches way past your own two hands.",

  "blindSpot": "You'll run a method that worked great somewhere onto a situation where it doesn't actually fit—because it worked so well last time that you stop checking whether the ground underneath is the same. The approach that was perfect at the old job can quietly tank at the new one, not because it's wrong, but because the conditions changed and your confidence didn't get the memo.\n\nYou assume people learn the way you learn—by doing, by being shown the proven path. But some people genuinely have to make their own mistake before a lesson lands. When you hand them the answer to save them the pain, it can land as you robbing them of the exact experience they needed. What feels like generosity on your end can feel like being denied a chance to find out for themselves.\n\nAnd you can underestimate when something's actually new. Your pattern library, even this young, is deep enough that almost everything looks like something you've seen before—usually a strength, occasionally a trap. It can hand you false confidence about a situation that's genuinely unprecedented. The match feels real even when there's nothing really matching.\n\nTwo more live close to the surface. Feedback on your way of doing things can feel like an attack on you, because your competence and your methods have basically fused—but they're tools, not your whole self, and someone questioning the tool isn't a verdict on you. And you can hoard what you know without meaning to: if nobody asks, you might not offer, and a head full of useful stuff just stays locked up because nobody knew to ask for the key.",

  "frictionPatterns": "You rub up against the person who wants to reinvent the whole thing from scratch—who'd rather rederive it from zero than learn from the experience sitting right in front of them. The big-idea friend who waves off your actual history as \"just one example\" while building confidently on no examples at all is your sharpest friction. To you that's not bold, it's choosing to relearn at full price what you already paid for.\n\nThe people who want to debate the concept while you want to talk about the actual application are a quieter, steadier grind. They trust the elegant theory; you trust the record of how it actually went when somebody ran it. Neither of you is exactly wrong—you're just standing at different ends of the same problem, one holding the theory and one holding the receipts.\n\nFamily can do it too. The relative who keeps making the same plan in the same hopeful tone you've heard before, the one you already know how it ends. You want to believe it. You also remember the last few times. And anyone who treats your practicality like you just lack vision gets under your skin, because you've watched plenty of \"vision\" fold the second it touched a real Tuesday.\n\nWhat you bring to all of it is solid ground—you keep the hyped-up idea honest about what it'll actually take, and you can hand someone a shortcut you earned the slow way. Your growth edge is remembering that the dreamers and the start-from-scratch people aren't always being arrogant. Sometimes the thing really is new, and the experience you trust so completely is a starting point to test against, not the last word.",

  "energyPatterns": "What drains you:\n- Reinventing the thing that already works fine\n- Theory debates that never touch how it'd actually go\n- A job that treats the stuff you've learned like it's worthless\n- Having to justify a method that obviously works\n- People who ask for your advice and then ignore it\n- Watching a preventable mess unfold right on schedule\n\nWhat charges you:\n- Walking someone through a challenge you've already mastered\n- Refining a process until it's nearly perfect\n- Being the person who actually knows how to do the thing\n- Seeing your way of doing it get adopted and proven right\n- Building something meant to last longer than this semester\n- Working with people who respect that you've put in the reps",

  "workEnvironments": "Where you thrive:\n- Places that value what you've actually learned on the job\n- Trades, kitchens, ops, quality, training—anywhere skill is the currency\n- Apprenticeship-style setups where you learn by doing under someone good\n- Crews that respect putting in time and showing up consistent\n- Building on what works instead of disrupting just to disrupt\n\nWhere you suffocate:\n- \"Move fast and break things,\" when you're the one cleaning up the break\n- Places that prize a flashy new idea over actually getting it done\n- All theory, no practice\n- New-and-shiny valued over reliable-and-proven\n- Getting treated like your experience is baggage because you're young",

  "topCareers": [
    {
      "title": "Skilled Trade / Apprenticeship",
      "description": "You learn by doing the thing, messing it up, and refining it until it actually delivers—which is the entire basis of how a trade works. An apprenticeship is built for you: you build real skill through reps, you remember the mistake so you never repeat it, and you get judged on what you can pull off, not how you talk about it. You're probably already the one at your first job who quietly knew the right way before anyone showed you. The trades pay you to be that person on purpose, and the experience some classrooms ignored becomes the whole asset."
    },
    {
      "title": "Trainer / Shift Lead / Onboarding Role",
      "description": "You watch new people skip the way that works to \"find their own way,\" and you already feel where they're headed. Training, onboarding, and shift-lead roles turn that into the actual job—handing over what you've proven so the next person doesn't pay full tuition for it. You're not controlling; you're efficient, giving someone the shortcut you earned slow. Even young, you become the person who keeps the standard from slipping because you remember the order things have to be learned in. The practical wisdom you stacked up becomes the thing you're trusted to pass on."
    },
    {
      "title": "Operations / Quality Role",
      "description": "You build on what works instead of disrupting for its own sake, because you've already felt what disruption costs. Entry-level ops and quality work reward exactly that judgment: consistency, reliability, the refined process that delivers every single time. You trust the tested way over the new way because you've watched the new way break on the same rocks twice. In a world that's obsessed with moving fast, you're the one who quietly keeps the fast-movers from blowing it up—and the steadiness others discount is precisely what these roles are built to value."
    }
  ],

  "blockIndicators": "Your Parser Profile suggests the following CBI block accessibility pattern:\n\nLikely High-Accessibility Blocks:\n- Perceptual Discrimination (concrete detail processing)\n- Sequential Processing (method development and procedural knowledge)\n- Pattern Recognition (across experienced situations)\n\nLikely Moderate-Accessibility Blocks:\n- Self-Reference Processing (balanced, accessible)\n- Social Signal Processing (balanced reference enables awareness)\n\nLikely Lower-Accessibility Blocks:\n- Generative Creation (preference for proven over novel)\n- Symbolic Manipulation (abstract reasoning without concrete grounding)\n\nThis pattern suggests your cognitive architecture is optimized for building real skill, developing methods that work, and passing on practical knowledge—with room to grow in giving genuinely new approaches a clean shot before your experience decides for you.\n\nSEASONED",

  "strengths": [
    {
      "title": "You Build Methods, Not Just Habits",
      "description": "You don't just do things—you figure out a way of doing them that you can repeat. Through running the same thing over and over, you pull out a process that actually holds. Your way isn't a random preference; it's a solution you found by trying it, breaking it, and fixing it until it delivered."
    },
    {
      "title": "Pattern Matching From Real Results",
      "description": "Your read on what works runs on actual outcomes, not predictions. You've seen enough things actually play out—jobs, plans, people—to know what holds and what crumbles. Not in theory, in practice. That grounding is why your gut calls tend to land, even when you're the youngest one in the room."
    },
    {
      "title": "You Can Actually Teach It",
      "description": "You can hand off what you know in a form someone can use. Your way of doing things is teachable—you know what to learn first, what mistakes to warn about, which messes someone has to make themselves. That makes you the person who trains the new hire better than the manual does."
    },
    {
      "title": "Always Tweaking It Better",
      "description": "You keep refining based on what actually happens. Small adjustments stack up into a real upgrade over time. When you find a genuinely better way, you take it. Your methods get sharper as you go instead of hardening into something you can't change."
    },
    {
      "title": "It Works for Other People Too",
      "description": "Your systems work for you and for whoever else has to use them. You don't build stuff that only makes sense in your own head. That balance is why your way of doing things actually transfers—your roommate, your coworker, the new kid all get something usable, not just you."
    },
    {
      "title": "You Do What You Said You'd Do",
      "description": "When you commit to doing it a certain way, you execute it the same way every time. Your grounding keeps you steady; your track record gives you confidence that's actually earned. People learn that your word holds up under pressure when other people's fold, and that makes you someone they can count on."
    }
  ],

  "challenges": [
    {
      "title": "The New Way That Would've Actually Worked",
      "challenge": "Your trust in the proven way made you slow to try something genuinely better. Your skepticism—usually justified—occasionally blocked a real upgrade. The thing that's always worked isn't automatically the thing that works best forever.",
      "remedy": "Run a tiny experiment. Low stakes, real data—try the new way on something small and watch what happens. Let the actual result update what you trust, instead of letting what you trust veto the experiment before it starts."
    },
    {
      "title": "The Situation That Wasn't the Same",
      "challenge": "A method that crushed it in one spot bombed in another—not because the method was wrong, but because the conditions were different. You force-fit something that needed adjusting, because last time it just worked.",
      "remedy": "Before you run a proven approach, do a quick check: what actually made this work before? Are those same conditions here right now? Your methods are strong—they're stronger when you match them to the situation instead of assuming."
    },
    {
      "title": "The Person Who Needed to Fail",
      "challenge": "You know the right way, and watching a friend fumble through a mistake you already made is genuinely frustrating. But handing them the answer sometimes robs them of an experience they actually needed. Your efficiency shut down their growth.",
      "remedy": "Sort the lessons. Some can be transmitted; some only land by living them. Ask which kind you're looking at. Your job isn't always to prevent the mistake—sometimes it's to be the person who helps them make sense of their own."
    },
    {
      "title": "The Abstract Problem With No Handle",
      "challenge": "A purely theoretical assignment with nothing concrete to grab onto frustrates you fast. With no real situation, no experience to reference, you struggle to even start. Some problems genuinely require working in the abstract before there's anything to touch.",
      "remedy": "Build a bridge to something real. Ask: \"what would this actually look like in practice?\" Find the tangible hook that lets your brain lock in. Your need for something concrete is legit—it can also be stretched a little further than feels comfortable."
    },
    {
      "title": "The Genuinely Unprecedented",
      "challenge": "Your focus on what's already happened gave you a deep library, but a thin ability to project into the totally new. When the situation is actually unprecedented—not just similar to something old—your experience doesn't have the pattern, and you don't always notice it's missing.",
      "remedy": "Call it out loud. \"This doesn't match anything I've seen\" is useful information, not a failure. In genuinely new territory, treat your pattern-match as a hypothesis to test, not a conclusion to bank on."
    },
    {
      "title": "Feedback That Felt Like an Attack",
      "challenge": "Someone questioned your way of doing things and it felt like they were questioning you. Your competence and your methods have basically merged this young, so defending them got automatic—even when staying open would've served you better.",
      "remedy": "Pull the method off your identity. Your approach is a tool, not your worth. When someone questions it, the question is about whether the tool fits, not whether you're good enough. You're the one who built the skill, not the skill itself."
    }
  ]
};
