// SENTIMENTAL Profile — Young Adult (18–29)
// Parser Profile™ © 2026 Cognition Blocks LLC

export const sentimentalyaProfile = {
  "name": "SENTIMENTAL",
  "tagline": "The one who keeps the meaning, not just the memory",

  "overview": "A song comes on—the one from that summer, the one that was playing in someone's car when you were 17 and everything still felt possible—and you don't just remember that time, you're back in it. The whole texture of who you were, what you wanted, what mattered before you knew how any of it turned out. Other people store the past like a list of facts. You store it as feeling, and the feeling stays alive.\n\nYou're not really cataloging what happened. You're pulling out what it meant. The exact details might blur—you can't always remember the date or who said what first—but the significance stays razor sharp. You remember how the friendship felt right before it broke. You remember what that move across the country actually cost you, long after you've forgotten the logistics.\n\nYour attention naturally drifts backward. The thing happening right now instantly connects to the thing it echoes from before. A new crush rhymes with an old one. A present loss reopens one you already half-processed. You carry your history around like a roommate who never moved out—not a closed folder, but a living presence shaping how you feel about right now.\n\nAnd it's personal. You're not a history buff archiving the world; you're excavating your own life, trying to understand yourself through everything you've already lived. The result is someone with more emotional depth and self-knowledge than most people your age have gotten around to building. This isn't sitting around being sad about the past—it's the ongoing, active work of figuring out your own story.",

  "howYouLearn": "Learning lands for you when you can hook it onto something you already feel. A class that connects to stuff you've actually been through—extending what you already get, adding a layer to a feeling you already had—absorbs fast. Information with nothing to hook onto, just facts floating in space, can't find anywhere to live in your head.\n\nYou need to know what something means, not just what it is. \"Okay, but what does this actually signify?\" is the question running under everything you study. Hand you raw data with no interpretation and you'll build your own meaning around it. Hand you the meaning directly and you'll absorb it almost instantly.\n\nYou learn best from people's actual stories—memoirs, biographies, the long late-night version of how someone got to where they are. That mirrors how your own head works, and it gives you models for the self-excavation you're already doing on yourself. A real human story will stick to you when a textbook chapter evaporates by morning.\n\nYour self-referential wiring means you'll run everything through yourself. \"How does this relate to me?\" isn't you being self-absorbed—it's literally your learning filter, the way the material gets a place to land. The one watch-out: some genuinely useful stuff points forward, toward experiences you haven't had yet and can't feel a connection to. Stay open to learning that's preparing you for territory you haven't lived in.",

  "howYouCommunicate": "You communicate with a kind of emotional precision most people your age don't have. You can name an inner state that someone else can only gesture at. You can describe an experience with the meaning still attached, not flattened into \"it was fine.\" When you talk about something that happened, the feeling of it comes through, not just the summary—and people feel that.\n\nYou tell stories. It's your main way of getting something important across. When you really want someone to understand, you don't give them the bullet points—you reach for the narrative. Here's what happened, here's what it meant, here's what it taught me. Stories are how you carry meaning from your head into someone else's.\n\nBecause you process the abstract emotional layer, you might be way more comfortable with feelings than with facts. You'll remember exactly how a night felt years later but blank on what day it was or who else was there. The meaning stays; the logistics dissolve.\n\nIn close, one-on-one conversations, your depth is a gift. You can meet someone right in the middle of what they're feeling, help them put words to it, and hold space for them to process at a level a lot of people can't reach. The catch: someone who's all about where they're going next can find your where-I've-been mode frustrating. They want the plan; you want to understand the thing you're walking away from first.",

  "phrase": "You're not stuck in the past—you're still learning from it. What people call 'holding on' is actually holding open, keeping an experience available until you've fully understood it.",

  "secret": "Sometimes you're scared you've already lived your best moments. At 24, which sounds insane to say out loud.\n\nYour past is so vivid, so processed, that the present can feel pale next to it. Not because things were objectively better back then, but because you've had years to extract the meaning from those old memories while right now is still raw and messy and unprocessed. The old stuff has been refined into pure significance. The new stuff is still just... happening, with no shape to it yet.\n\nSo you secretly wonder: what if the most meaningful things already happened? What if the friendships that mattered most, the version of yourself you liked best, the story worth telling—what if all of that's behind you, and everything ahead is just the aftermath? It's a hard thing to say because it sounds like depression, and maybe sometimes it is. But often it's something else—the strange grief of carrying the past so fully that the future seems like it could never compete.\n\nDeeper: part of why you prefer the past is that it's finished. You know how it ends. The uncertainty's resolved. The present and future are wide open, unwritten, capable of becoming anything—and that's terrifying. The past is safe because it's already become what it's going to be. And deepest: some days you stay back there because you're not sure you can survive more meaning. You've already felt so much, processed so much. The idea of more experience needing more integration just feels exhausting. None of that makes your depth fake. It just shows you what it costs.",

  "whatOthersGetWrong": "They assume you're sad because you look backward so much. They see your attention drifting to what was and decide you must be unhappy now, unable to let go, trapped. They mix up depth with depression—reading your emotional archaeology as some kind of pathology, when it's just how your mind is built.\n\nWhat they miss is that processing the past isn't the same as wanting to live there. You're not trying to go back. You're trying to understand. The past is your lab for figuring yourself out, not a hiding spot from the present.\n\nThey also assume that because you remember things emotionally, you remember them accurately. They think your vivid access to how it felt means you've got reliable access to how it actually went down. But emotional memory and factual memory are two different things, and yours runs heavy on the first one.\n\nSome people treat your sentimentality as weakness—like feeling things deeply means you can't be tough or logical or get stuff done. They don't get that your depth is a form of intelligence, that processing feeling is what builds wisdom. And some read your self-focus as you being self-absorbed. Your attention to your own experience looks like narcissism to them, when it's actually just the cognitive wiring you came with.",

  "hiddenSuperpower": "You can pull meaning out of experiences that most people just waste.\n\nMost people go through their twenties collecting experiences without ever really processing them. Stuff happens, feelings come up, time passes—but the significance never gets extracted. They live a lot and learn a little. Their past is a closet stuffed with unprocessed material that never got examined, never got integrated, never turned into anything useful.\n\nYou're different. Nothing's wasted on you. Every experience becomes material for understanding. Every relationship teaches you something real about relationships. Every loss deepens what you actually know about loss. Every good night reveals something about what made it good. While your friends are still saying \"that was crazy\" about a year that genuinely changed them, you've already worked out what it changed.\n\nThis is a superpower because wisdom is rare and it doesn't come automatically with age. Anyone can rack up experiences. Almost nobody learns from them at depth. Anyone can feel things. Almost nobody understands what the feelings mean.\n\nAnd it compounds. The more meaning you pull out, the more framework you've got for pulling meaning out of the next thing. Your old understanding lights up new experiences; new experiences deepen your understanding of the old ones. And it's not just for you—when you share what you've worked out, when you put words to it, other people get the benefit of processing they never did. Your private excavation becomes a gift the second you bring the insight back to the surface.",

  "blindSpot": "You might not catch when your meaning-making is actually just rewriting the past to fit who you are now. Your strength is pulling significance out of experience—but sometimes the significance you pull says more about present-you than about what actually happened back then. You'll retrofit meaning onto a chaotic stretch of your life, building a clean story out of something that was really just random and messy at the time.\n\nThis becomes a blind spot when you believe your version is simply the accurate one—when you can't see that you're actively writing the story, not just remembering it. Watch for the resistance you feel when a friend or sibling remembers a shared thing completely differently. If your version feels like the truth and theirs feels like a distortion, sit with the possibility that you're both constructing it. Memory is creative, and emotional memory most of all.\n\nWatch too for a life story that's gotten too clean. Real lives are messy, contradictory, full of loose ends and things that never resolved. If your story of yourself is too neat—if everything means something, if every hard thing was secretly a lesson—you might be inventing more than you're remembering. Not everything that happened to you at 19 was building toward who you are now. Some of it was just bad luck.\n\nYour blind spot isn't the meaning-making itself. That's the gift. It's the gap between meaning you actually discovered and meaning you quietly imposed.",

  "frictionPatterns": "You'll clash with the people locked onto concrete future plans for the whole group—the deliverable, the schedule, the next step for everyone. Their \"what has to happen next for the team\" runs straight into your \"wait, what did this actually mean for me.\" You can come off as irrelevant and self-absorbed to them; they can come off as shallow and dismissive to you.\n\nYou'll grind against the heavily future-focused people too—the ones already three plans ahead who experience your looking-back as being stuck. They want to move; you want to understand what you're moving away from first. To them you're dragging an anchor. To you they're skipping the part that actually matters.\n\nAnd the very concrete, just-the-facts people find your meaning-making frustrating. They want to know what happened—the timeline, the details. You want to explore what it meant. You're both holding different ends of the same memory and neither end feels like enough to the other person.\n\nYour gift inside these frictions: your depth can help someone process a thing they rushed straight past without ever understanding it. Your growth edge: recognizing that forward motion and concrete focus aren't avoidance or shallowness—they're just different ways a mind can be built, optimizing for a different part of time than you do.",

  "energyPatterns": "What drains you:\n- Being told to \"just move on\" before you've actually processed anything\n- A pace that's all forward, no room to reflect on what just happened\n- Surface-level hangs where nobody goes past \"it's fine\"\n- Having your looking-back treated like a problem to fix\n- Relationships where your meaning-making gets brushed off\n- Small talk that never once goes anywhere real\n\nWhat charges you:\n- A deep conversation that actually processes an experience for what it meant\n- Time alone to sit with things and reflect\n- Music, art, and stories that capture an emotional truth you recognize\n- A friend whose depth matches yours and meets you there\n- The moment something finally clicks into real understanding\n- Looking back at an old photo or playlist and feeling the whole thing again",

  "workEnvironments": "Where you thrive:\n- Places that value depth, reflection, and emotional intelligence\n- Writing, peer support, coaching, anything working with people's real stories\n- Creative fields where emotional truth is the actual point\n- Roles built around personal narrative or helping people make sense of their lives\n- Permission to process—depth valued over pure speed\n\nWhere you suffocate:\n- Constant forward motion with zero room to reflect\n- Cultures that treat feelings as soft, weak, or beside the point\n- Fast-paced grinds that never once pause to ask what anything meant\n- Being rushed to the next thing before this one's even landed\n- Rooms where the only thing that counts is the metric, not the meaning",

  "topCareers": [
    {
      "title": "Writer / Content Creator / Storyteller",
      "description": "You don't just remember—you feel backward through time and store the past as meaning that stays alive in you. Writing, personal essays, video storytelling, anything narrative is exactly that gift made visible: you take a remembered moment and turn it over until it gives up what it meant. You can put words to who you were before you knew how things turned out, and make whoever's reading or watching recognize themselves in it. The depth other people rushed straight past becomes the whole substance of what you make—and it's the rare thing that actually connects."
    },
    {
      "title": "Peer Support / Counseling Track",
      "description": "A song from years ago doesn't remind you of a time—it puts you back inside it, complete. Peer support, mentoring, and the early steps toward counseling run on exactly that ability to sit in emotional history and pull the meaning out of it. You help people make their own past make sense because you've always processed yours for significance, not just sequence. The \"too much feeling, too much looking back\" that fast-moving rooms dismissed is, in this kind of work, literally the instrument you work with."
    },
    {
      "title": "Creative / Community Guide",
      "description": "You pull the significance out from under events—what they meant, what they revealed—where other people just log what happened. Helping run a creative workshop, a community space, a group where people process their experiences together is built for that meaning-making: helping someone find the thread running through their own lived story. You give the past somewhere to land instead of letting it sit as a pile of inert facts. The reflective depth that needed permission to exist becomes the entire point of the role."
    }
  ],

  "blockIndicators": "Your Parser Profile suggests the following CBI block accessibility pattern:\n\nLikely High-Accessibility Blocks:\n- Self-Reference Processing (continuous self-excavation)\n- Pattern Recognition (seeing meaning patterns across time and experience)\n- Symbolic Manipulation (working with abstract emotional meaning)\n\nLikely Moderate-Accessibility Blocks:\n- Social Signal Processing (accessible when you extend attention to others)\n- Generative Creation (generating narrative meaning from experience)\n\nLikely Lower-Accessibility Blocks:\n- Sequential Processing (concrete step-by-step may be less emphasized)\n- Perceptual Discrimination (present-moment sensory detail may be under-attended)\n- Spatial Relationships (concrete spatial processing may be less developed)\n\nThis pattern suggests your cognitive architecture is optimized for emotional wisdom and deep self-knowledge unusual for your age, with room to grow in present-moment awareness and leaning into the future.\n\nSENTIMENTAL",

  "strengths": [
    {
      "title": "You Pull Meaning Out of Everything",
      "description": "You don't just experience things—you understand what they meant. While your friends move through a wild year without ever processing it, you naturally extract the deeper lesson, the emotional truth, the thing it taught you about life and about yourself. Nothing you live through goes to waste."
    },
    {
      "title": "Memory That Holds the Feeling",
      "description": "Your recall isn't just facts—it's the actual feeling. You can get back to how something felt, not just what happened. That emotional depth gives you unusual self-knowledge for your age; you understand your own patterns because you remember them from the inside, not just on paper."
    },
    {
      "title": "You See Your Patterns Over Time",
      "description": "Because you carry your past around as a living thing, you catch patterns across your own life that other people miss in theirs. You notice when you're repeating a dynamic with someone, when a new situation is echoing an old one, what you tend to do—because you've been watching yourself across years."
    },
    {
      "title": "You Actually Integrate the Hard Stuff",
      "description": "You do the real work of weaving experience into who you are. Instead of shoving a hard thing in a box and never opening it, you process it—pull out the meaning, understand how it hit you, fold it into your ongoing story. That's why you carry your history instead of just dragging it."
    },
    {
      "title": "You Can Name What Others Can't",
      "description": "Your way of processing feeling gives you language for inner states most people can't articulate. You can name a subtle emotion, tell two similar feelings apart, and describe what's happening inside you with a precision that makes friends say \"yes, that, exactly that\"—the thing they couldn't put words to."
    },
    {
      "title": "You Know Yourself Deep",
      "description": "You know yourself at a level most people don't reach until way later, if ever. Your ongoing excavation of your own life has mapped your internal landscape—your triggers, your patterns, your wounds, your gifts. That self-knowledge is the foundation you get to build an actually authentic adult life on."
    }
  ],

  "challenges": [
    {
      "title": "Stuck on Replay",
      "challenge": "Your gift for processing the past becomes a trap when the processing never finishes. You replay the same painful thing—the breakup, the falling-out, the version of yourself you cringe at—over and over, pulling the same meaning each time, never reaching closure. It just loops.",
      "remedy": "Tell the difference between processing and just looping. Processing moves toward something—each pass adds understanding or releases some of the charge. Looping covers the same ground with no progress. When you catch yourself circling, ask: \"what new understanding am I actually getting here?\" If the answer is none, redirect your attention on purpose."
    },
    {
      "title": "Not Really Here",
      "challenge": "Your backward-pulling attention yanks you out of what's happening right now. You're physically at the dinner, the party, the date—but emotionally you're somewhere else, in a memory that feels more vivid than the actual moment in front of you.",
      "remedy": "Practice being present as a deliberate counterweight. Your past-orientation is valuable and doesn't need to be killed—but building the present-moment muscle gives you a choice about where your attention goes. Sensory grounding, putting the phone down, or just deciding \"this next hour I'm here\" can create the balance."
    },
    {
      "title": "The Golden-Age Trap",
      "challenge": "Your processing of the past can quietly idealize it—you remember the meaning and forget the difficulty. Some past stretch becomes a golden age that the messy present can never live up to, even though that stretch had its own struggles you've conveniently dropped.",
      "remedy": "Put the shadow back in. When you catch yourself idealizing a past time, deliberately remember what was also hard then—the fears, the loneliness, the stuff you've since edited out. That era wasn't better. It was just different, and you've smoothed off the rough parts."
    },
    {
      "title": "Dodging the Future",
      "challenge": "Your comfort with the past can turn into real discomfort with the future. What's coming is unknown, unmapped, with none of the meaning you've already extracted from what's done. So you avoid planning ahead, because forward feels more threatening than backward.",
      "remedy": "Reframe the future as meaning-that-hasn't-arrived-yet. The experiences ahead are just the next batch of material you'll get to process, the source of new understanding, the next chapter of the story you're already making sense of. The future is just past that hasn't happened yet."
    },
    {
      "title": "Alone in Your Own Head",
      "challenge": "Your focus on your own experience can cut you off from everyone else's. You'll mine your own history endlessly while never really learning from what the people around you have been through. The excavation stays solo when it could be shared.",
      "remedy": "Aim your meaning-extraction at other people's stories too. When a friend shares something real, process it with the same depth you'd bring to your own stuff. The gift you have for emotional archaeology turns into actual connection the second you start digging into someone else's history alongside yours."
    },
    {
      "title": "Understanding Instead of Feeling",
      "challenge": "Processing what an experience means can become a way of not actually feeling it. If you're always busy figuring out what an emotion signifies, you might never fully feel the emotion. The analysis becomes a shield against the raw thing.",
      "remedy": "Notice when understanding is sneaking in to replace feeling. Sometimes the actual work is to stay in the emotion before making sense of it—to just feel it without immediately analyzing, to let it move through you first. Meaning-making is valuable and it can wait. First, let yourself actually feel the thing."
    }
  ]
};
