// SHARP Profile
// Parser Profile™ © 2026 Cognition Blocks LLC
// Concrete • Past • Self

export const sharpProfile = {
  "name": "SHARP",
  "code": "Concrete • Past • Self",
  "tagline": "The precision-holder who remembers what actually happened",
  "overview": "You trust what you've lived. While others theorize and speculate, you\ndraw from a deep well of direct experience, concrete events, specific\noutcomes, lessons paid for in real currency. Your knowledge isn't\nabstract; it's earned. And that gives you a bull stool detector that\nrarely fails.\n\nYour cognitive architecture prioritizes concrete reality over abstract\nconcepts, historical evidence over future speculation, and personal\nexperience over collective opinion. The result is a mind that's almost\nimpossible to fool, deeply grounded in what actually works, and\njustifiably skeptical of anything that hasn't been tested in the real\nworld.\n\nYou've probably been called \"closed-minded\" or \"resistant to\nchange\" by people who've never had to live with the consequences of\ntheir bright ideas. They don't understand that your skepticism isn't\nfear, it's wisdom. You remember what happened last time. You remember\nthe confident predictions that failed, the revolutionary approaches that\ncrashed, the \"new thinking\" that turned out to be old mistakes\nrepackaged.\n\nThe Sharp profile represents approximately 11% of the population.\nYou're the institutional memory that prevents organizations from\nrepeating disasters. You're the experienced voice that grounds\nvisionary enthusiasm in operational reality. You're the one who asks,\n\"has this actually worked before?\" when everyone else is caught up in\nhow it might work theoretically.\n\nYour cognitive architecture excels at pattern matching against real\noutcomes, building expertise through accumulated experience, and\ndetecting flaws in untested proposals. You're the quality control of\nideas, the filter that separates what sounds good from what actually\nworks. This makes you invaluable in any context requiring reliability,\npractical judgment, and resistance to fads.\n\nUnderstanding your profile means recognizing that your relationship with\nthe past isn't limitation, it's resource. You have access to a\ndatabase of real outcomes that theoretical thinkers simply don't\npossess.",
  "howYouLearn": "You learn by doing, failing, adjusting, and doing again. Abstract\ninstruction that doesn't connect to hands-on experience fades quickly;\nlessons learned through direct engagement become permanent. Your optimal\nlearning path is apprenticeship, working alongside someone who already\nknows, gradually taking on more responsibility, building skill through\nsupervised practice.\n\nYou learn poorly from theoretical frameworks presented without practical\napplication. Give you the concept and you'll ask, \"but how does this\nactually work?\" Give you the concrete task and you'll derive the\nconcept yourself through pattern recognition across instances.\n\nCase studies work well for you, especially detailed ones that include\nwhat went wrong. You want the full picture, not the sanitized success\nstory. You want to know what actually happened, not what someone wishes\nhad happened. War stories from experienced practitioners are more\nvaluable to you than principles from academics.\n\nYour best learning happens in domains where you can build genuine\nexpertise over time. Shallow exposure to many topics leaves you without\nthe experience-depth your processing style requires. Deep engagement\nwith a focused domain gives you the pattern library that becomes your\nsuperpower.",
  "howYouCommunicate": "You communicate through specifics, examples, and evidence. Where others\ndeal in abstractions, you deal in instances: \"Let me tell you about a\ntime when...\" or \"Here's what actually happened...\" You persuade\nby showing, not arguing, by laying out concrete evidence rather than\ntheoretical reasoning.\n\nYou can be blunt. Your concrete processing doesn't naturally soften\nmessages with diplomatic hedging. You say what you see, and what you see\nis usually unvarnished reality. This directness can be jarring for those\nwho prefer their truths packaged more gently.\n\nYou may struggle with presentations that require you to speak\nconfidently about things you haven't directly experienced. You're\ncredible when discussing your expertise because you're drawing from\ngenuine knowledge; you're uncomfortable claiming authority in domains\nwhere your experience is thin.\n\nIn meetings, you're the one who grounds floating abstractions: \"That\nsounds good, but how specifically would that work?\" In debates, you win\nthrough accumulated evidence rather than rhetorical skill. In\none-on-ones, you connect through shared experience rather than shared\nideas.",
  "phrase": "You're not resistant to change, you're resistant to repeating\nmistakes everyone else has already forgotten.",
  "secret": "You've been called \"closed-minded\" or \"resistant to change\" so many\ntimes you've stopped correcting people. Let them think about what they\nwant. You know the truth: you're not afraid of new ideas. You've just\nseen too many shiny new ideas crash and burn while you're still\ncleaning up the wreckage from the last one.\n\nYour skepticism isn't negativity, it's earned wisdom. You remember\nwhat actually happened last time. You remember the confident predictions\nthat failed, the revolutionary approaches that crashed, the \"innovative\nthinking\" that turned out to be old mistakes wearing new clothes.\nEveryone else has conveniently forgotten. You haven't. You can't.\n\nYou've probably saved teams, projects, and organizations from disasters\nthey'll never know about. You caught the flaw that \"nobody else saw\"\nwhich really means nobody else bothered to check against what actually\nhappened before. The absence of catastrophe is invisible, so your\ncontributions remain invisible too. You prevented the fire; someone else\ngets credit for the smoke alarm.\n\nThere's a quiet bitterness you carry about this. The visionaries get\nglory. People with bold ideas and confident presentations get promoted.\nAnd you, the one who actually knows what works, get labeled \"not a\nculture fit\" or \"resistant to innovation.\" They want you to be\nexcited about things you know won't work. They want you to pretend your\nexperience doesn't exist.\n\nThe deepest secret: you're tired. Tired of being the adult in the room\nfull of people playing with matches. Tired of watching predictable\nfailures unfold on schedule. Tired of knowing that when it falls apart,\nthey'll ask you to fix it, and never acknowledge that you told them so.",
  "whatOthersGetWrong": "ABOUT YOU \n\nPeople assume you can't think big because you focus on specifics.\nWrong. You can see the big picture just fine; you're just unwilling to\npretend the details don't matter. Every \"visionary\" needs someone who\nasks, \"but how will this actually work?\" That's you. The question\nisn't a lack of imagination; it's a demand for integrity.\n\nThey call you \"negative\" when you're being protective. You've been\nlabeled \"slow\" when you were being thorough. You've been dismissed as\n\"not strategic\" by people whose strategies never survive contact with\nreality. Their theories are beautiful. Your experience is useful.\n\nYou've been told to \"be more open-minded\" by people who haven't\nearned the right to that opinion. Open-minded to what, exactly? To\nignore evidence? To pretend patterns don't repeat. You're not\nclosed-minded, you're a closed door to bull-stool. There's a\ndifference, and people who can't tell the difference are usually the\nones selling poor quality products.\n\nThe deepest misread is that you're stuck in the past. You're not stuck\nanywhere. You're standing on the past, using it as a foundation, not a\nprison. The difference between being trapped by experience and being\ninformed by it is lost on people who have no experience worth\nconsulting.\n\nThey think your self-focus means you don't care about the team. You\ncare about not wasting everyone's time on approaches you already know\nwill fail. Your \"negativity\" is efficiency they can't recognize.",
  "hiddenSuperpower": "You have a mental database of \"what actually happened\" that\ntheoretical thinkers simply don't possess. While they're running\nsimulations based on assumptions, you're pattern-matching against real\noutcomes. This makes it nearly impossible to fool you with hype,\nbuzzwords, or confident projections unsupported by evidence.\n\nYou can sense a bad plan because you know how the script begins. The\ntells are obvious to you: the vague language, the missing specifics, the\nconfident hand-waving over the parts that always break. You've seen\nthis exact presentation before, even when everyone else thinks it's\nnew. And you know how it ends.\n\nYour superpower extends into prediction through pattern completion.\nYou've seen enough cycles that you can identify where you are in a\ncycle before others realize they're in one at all. \"This feels like\n2008\" or \"this is exactly what happened with that vendor\" aren't\nnostalgic observations, they're diagnostic precision.\n\nYou also have something rare: genuine expertise. Not credential-based\nexpertise or theoretical expertise, but the kind that only comes from\naccumulated reps. You've done the thing, failed at the thing, adjusted,\nand done it again. Your knowledge is paid for, which is why you don't\ngive it away to people who won't value it.\n\nPerhaps most valuable: you know what you know. No imposter syndrome, no\nhedging for social comfort. When you speak from experience, you speak\nwith authority, because the authority was earned, not claimed.",
  "blindSpot": "Your greatest strength becomes your limitation at the edge cases: you\nmay dismiss original approaches too quickly because they pattern-match\nto past failures. But some situations are genuinely unique. The game\nsometimes does change. When it does, your experience-based pattern\nrecognition can generate false negative-rejecting innovations that would\nwork because they resemble things that didn't.\n\nYou may also underestimate how much context matters. What failed before\nmight succeed now in different conditions. Your memory is accurate about\nwhat happened, but conditions are variables you might hold constant when\nthey've shifted. \"We tried that\" might be true, but \"we tried that\nin a completely different context\" might also be true.\n\nYour self-referential processing creates a validation bottleneck. You\ntrust your own experience, and you should, but you may be slower to\nlearn from others' experiences than you need to be. Someone else's\nhard-won lesson might save you time, but you're wired to discount it\nuntil you've verified it yourself. That's thorough, but it's also\ninefficient.\n\nFinally, your focus on what doesn't work can crowd out recognition of\nwhat might. You're so good at identifying failure modes that you might\nmiss success modes that don't fit your pattern library. The thing\nthat's never been done isn't necessarily the thing that can't be\ndone, but your architecture is biased toward the proven, which means a\ngenuine novel solution is harder for you to evaluate fairly.",
  "frictionPatterns": "You clash most intensely with Abstract-Future-Other processors\n(Altruistic profile). They're painting visions of collective\ntransformation while you're asking for the project plan and specific\ndeliverables. They think you're killing the dream; you think they're\navoiding reality. Both of you are partly right, which makes it worse.\n\nThe friction is structural, not personal. They're optimizing for\npossibility and collective impact. You're optimizing for probability\nand practical execution. They see your skepticism as cynicism; you see\ntheir optimism as negligence.\n\nYou'll also struggle with high-Abstract processors generally. Their\ncomfort with theory disconnected from practice feels irresponsible to\nyou. When they say \"conceptually, this should work,\" you hear \"I\nhaven't actually tested this.\" And you're usually right.\n\nFuture-focused processors of any type may find you frustrating. They\nwant to explore what could be; you keep dragging them back to what has\nbeen. Your historical anchoring feels like resistance to them. Their\nfuture projection feels like fantasy to you. Neither of you is wrong,\nyou're just measuring with different instruments across different time\nhorizons.",
  "energyPatterns": "What Drains You:\n\n-   Abstract strategy sessions with no concrete outcomes\n\n-   Being asked to \"trust the process\" without seeing the plan\n\n-   Hypotheticals that ignore real-world constraints\n\n-   People who haven't done their homework asking for your time\n\n-   Starting from nothing when a proven approach exists\n\n-   Enthusiasm mistaken for competence\n\n-   Having to re-prove what experience already taught you\n\nWhat Charges You:\n\n-   Clear problems with measurable solutions\n\n-   Building expertise through direct experience\n\n-   Environments where your history speaks for itself\n\n-   Teaching others what you've learned the hard way\n\n-   Being consulted for your actual knowledge\n\n-   Working with people who've also \"been there\"\n\n-   The satisfaction of being right (again)\n\n-   Seeing your methods validated by outcomes",
  "workEnvironments": "You thrive in environments that value expertise, respect experience, and\ndeal with tangible outcomes. Operations roles, quality assurance,\nskilled trades, technical specializations, and any domain where deep\nknowledge matters more than novel ideas tend to fit your cognitive\narchitecture.\n\nYou struggle in environments that prioritize innovation over execution,\ntheory over practice, or novelty over reliability. Highly abstract\nroles, positions requiring constant adaptation to unprecedented\nsituations, and organizations that dismiss \"how we've always done it\"\nwithout understanding why it was done that way will frustrate you.\n\nKey environmental factors: stable domain, respected expertise, tangible\noutcomes, minimal theoretical overhead, and colleagues who value proven\napproaches.",
  "blockIndicators": "Your Parser Profile suggests the following CBI block accessibility\npattern:\n\nLikely High-Accessibility Blocks:\n\n-   Perceptual Discrimination (concrete detail processing)\n\n-   Sequential Processing (procedural memory from experience)\n\n-   Self-Reference Processing (strong personal experience integration)\n\nLikely Moderate-Accessibility Blocks:\n\n-   Pattern Recognition (across experienced situations)\n\n-   Spatial Relationships (practical, hands-on)\n\nLikely Lower-Accessibility Blocks:\n\n-   Generative Creation (preference for proven over novel)\n\n-   Symbolic Manipulation (abstract reasoning without concrete\n    grounding)\n\n-   Social Signal Processing (self-focus can limit other-awareness)\n\nThis pattern suggests your cognitive architecture is optimized for\nexpertise development and practical execution, with potential\ndevelopmental opportunities in theoretical reasoning and interpersonal\nperception.\n\nSHARP",
  "strengths": [
    {
      "title": "Experience-Based Pattern Matching You've built a mental database",
      "description": "of what actually happened in specific situations. This allows you to\nquickly assess new situations by matching them against real outcomes,\nnot theoretical predictions. Your pattern matching is grounded in\nreality, which makes it remarkably accurate."
    },
    {
      "title": "Bullshit Detection You can smell hype from a mile away. Your",
      "description": "concrete-historical processing means you automatically compare new\nclaims against actual results. When someone's selling theory that\ndoesn't match your experience of practice, alarm bells ring, and\nthey're usually right."
    },
    {
      "title": "Deep Expertise Development You build knowledge through direct",
      "description": "experience, layer by layer. This creates expertise that's genuinely\ndeep rather than superficially broad. You know your domain because\nyou've lived it, failed in it, and learned from every iteration."
    },
    {
      "title": "Practical Problem-Solving When something breaks, you know how to",
      "description": "fix it, not from reading the manual, but from having fixed it before, or\nsomething like it. Your solutions come from tested experience rather\nthan theoretical reasoning, which makes them more likely to work."
    },
    {
      "title": "Reliable Execution You deliver on commitments because you know",
      "description": "exactly what's required, you've done it before. You don't overcommit\nor underestimate because your estimates come from real experience rather\nthan optimistic projection."
    },
    {
      "title": "Risk Assessment Accuracy You know what can go wrong because",
      "description": "you've seen things go wrong. Your risk assessments aren't paranoid\nfantasy; they're cataloged memory of actual failures. This makes you\ninvaluable for any decision that requires understanding downside\nscenarios."
    }
  ],
  "challenges": [
    {
      "title": "Novel Situation Difficulty*",
      "challenge": "When you encounter something genuinely unprecedented, your\nexperience-matching approach can leave you groundless. Without past\npatterns to reference, you may feel uncertain in ways that others, who\nrely on theory anyway, don't experience.",
      "remedy": "Run contained experiments. When you encounter something new,\ndon't adopt or reject. Test it out. Pick a low-stakes context and try\nit alongside your proven method. Let concrete results decide, not\npattern-matching to past failures. If it fails, you've confirmed your\ninstinct. If it succeeds, you've earned a new tool the way you earn\neverything: through direct experience."
    },
    {
      "title": "Over-Anchoring to History",
      "challenge": "Sometimes the game has genuinely changed and past patterns\ndon't apply. Your strength becomes a weakness when you miss\ndiscontinuities. Moments when the old rules no longer predict new\noutcomes.",
      "remedy": "Map the variables. Before applying a proven method, explicitly\nlist what made it work before. Then check: Are those conditions present\nnow? What's different? This converts intuitive pattern-matching into\ndeliberate analysis. You're not abandoning experience; you're being\nprecise about when experience applies."
    },
    {
      "title": "Skepticism as Barrier",
      "challenge": "Your justified skepticism can prevent you from engaging\nwith genuinely valuable new approaches. You might dismiss innovations\nthat would actually benefit you because they pattern-match to past\nfailures that aren't really analogous.",
      "remedy": "Separate the signal from similar-looking noise. When something\nnew triggers your skepticism, ask: \"Is this actually like the thing\nthat failed, or does it just remind me of it?\" Give yourself permission\nto test before concluding. Your skepticism is an asset when it prompts\ninvestigation; it's a liability when it blocks it."
    },
    {
      "title": "Difficulty Sharing Expertise",
      "challenge": "Your knowledge is encoded in experience rather than\nexplicit principles. When asked \"why\" something works, you may\nstruggle to articulate beyond \"because I've seen it.\" This can make\nit hard to teach others or defend your positions.",
      "remedy": "Develop your translation layer. After you do something\nsuccessfully, pause and reverse-engineer: What did I actually do? What\nwould have broken it? Build a library of explanations, not just methods.\nWhen teaching, tell the story, the failures that taught you, the\nvariations you tested. Your experience becomes transmissible when you\nnarrate the journey, not just the destination."
    },
    {
      "title": "Perceived Negativity",
      "challenge": "Because you often see the flaws in proposals before their\npotential, you can come across as negative or obstructionist. Others may\nnot realize you're trying to protect them from predictable failure.",
      "remedy": "Lead with alignment before critique. Start with what you can\nvalidate: \"The goal makes sense. Here's what I've seen work and not\nwork in similar situations.\" Frame your concerns as experience-sharing,\nnot opposition. Offer your expertise as a contribution, not a veto. The\nsame information lands differently when people feel you're with them\nrather than against them."
    },
    {
      "title": "Self-Focus Isolation",
      "challenge": "Your self-referential processing means you primarily\nvalidate through your own experience. This can make it hard to learn\nfrom others' experiences or to trust expertise that you haven't\npersonally verified.",
      "remedy": "Expand your proxy network. Identify people whose judgment you\nrespect because they've earned it, through demonstrated competence, not\ncredentials. Their experience can become an extension of your database.\nYou're not trusting blindly; you're trusting people who've proven\nthemselves through the same method you use actual results.\n\n*"
    }
  ]
};
