// VISIONARY Profile
// Parser Profile™ © 2026 Cognition Blocks LLC
// Abstract • Future • Self

export const visionaryProfile = {
  "name": "VISIONARY",
  "code": "Abstract • Future • Self",
  "tagline": "The one who sees where things are going before anyone else",

  "overview": "You don't just think—you compute. While others are processing what's in front of them, your mind has already mapped the territory ahead, connected it to seven other concepts, and begun exploring implications that won't become obvious to anyone else for months.\n\nThis isn't a choice you make. It's how your mind is wired. Your thinking prioritizes abstract pattern recognition over concrete detail, future possibilities over present circumstances, and personal meaning over group consensus. The result is a consciousness that naturally operates at a different temporal and conceptual altitude than most people around you.\n\nYou've probably spent your life being told to \"focus\" and \"pay attention\" when the truth is you were already paying attention—just to something three levels deeper than what everyone else was tracking. Teachers saw distraction where there was actually advanced computation. Colleagues saw disengagement where there was parallel processing. Partners saw absence where there was profound presence, just not to the immediately visible.\n\nYour thinking excels at synthesis, abstraction, and projection. You naturally compress complex information into elegant principles, then project those principles forward to anticipate their implications. This makes you extraordinarily valuable in any context requiring strategic foresight, innovative thinking, or conceptual problem-solving.\n\nBut it can also make you feel perpetually out of sync with environments that reward execution over insight, compliance over creativity, and present-focus over future-orientation. Understanding your profile isn't about fixing what's \"wrong\" with you. It's about recognizing that you're running different cognitive software than most people, and learning to leverage that difference rather than apologize for it.",

  "howYouLearn": "You learn by constructing mental models, not by accumulating facts. When encountering new information, you immediately begin mapping it to existing frameworks, identifying underlying principles, and projecting implications. Details that don't connect to a larger pattern tend to slip away; insights that reveal structure become permanent.\n\nYou need concepts first, examples second. You want to understand the \"why\" before the \"what,\" and the principle before the procedure. Give you the framework and you'll fill in the specifics yourself. Force you through the specifics without the framework and you'll feel like you're drowning in noise.\n\nYou learn poorly from rote memorization, step-by-step tutorials, or heavily supervised instruction. You learn powerfully from exposure to experts thinking out loud, challenging problems with no clear solution path, and freedom to explore tangentially. Your best insights come when you're allowed to make connections on your own rather than having them pre-made for you.\n\nDiscussion works when it's with intellectual equals who can keep up with your pace. Hands-on learning works only when you understand the conceptual foundation—without that, physical manipulation feels random and frustrating.",

  "howYouCommunicate": "You communicate in compressed bursts that assume shared context. What feels complete to you often leaves others missing steps—you've unconsciously skipped the scaffolding they need to follow your thought. Learning to unpack your compression without losing your patience is a lifelong practice.\n\nYou're most articulate when thinking out loud to a receptive audience. The presence of an engaged listener helps you externalize your internal processing in ways that even surprise you. But you struggle with formal presentations, written reports, and any format that requires you to linearize your naturally networked thinking.\n\nIn conversation, you tend to jump topics—following connections that are invisible to others. You may interrupt, not from rudeness, but because you've already seen where they're heading and want to accelerate to the interesting part. You may also go silent for lengthy periods, deep in internal processing that looks like absence but is actually intense engagement.\n\nYou communicate best in environments that tolerate ambiguity, value ideas over polish, and allow for iteration. You communicate worst in formal settings that demand precision, completeness, and linear structure before you've had time to fully develop your thinking.",

  "phrase": "You're not scattered—you're parallel processing. The problem isn't your attention; it's that linear environments punish your architecture.",

  "secret": "You've spent your whole life being told \"focus\" and \"pay attention to details\" when the truth is you were already three steps ahead. While everyone else was still reading the instructions, you'd already seen where this was going—and you were right more often than anyone gave you credit for.\n\nThe secret isn't that you're smarter. It's that you're processing on a different timeline. You see the implications before the evidence arrives. You feel the pattern before you can prove it. And you've learned to keep quiet about what you see, because explaining it exhausts you and being right too early just makes people defensive.\n\nYou've probably abandoned more half-finished projects than most people have started. Not because you lack discipline, but because once you've solved the interesting part in your head, the execution feels like paperwork. The dopamine was in the discovery. The implementation is just... accounting.\n\nThere's a loneliness to this that you've rarely named. You've sat in meetings knowing exactly where a decision would lead, watched it unfold over months exactly as you predicted, and felt no satisfaction—only the familiar ache of having seen it coming and been unable to stop it.\n\nYou've also carried the weight of your own unrealized potential. You know what you're capable of. You've seen flashes of it. But the gap between your vision and your output haunts you. Not because you're lazy, but because the world doesn't have an interface for the way you think. You've spent years trying to translate yourself into a language that loses everything that matters in translation.",

  "whatOthersGetWrong": "They assume you're not listening when you're quiet. The reality is you've already processed what they said, mapped it into seven other concepts, and are now exploring implications they haven't considered yet. Your silence isn't disengagement—it's computation running at a depth they can't see.\n\nThey call you \"scattered\" when you're actually parallel processing. They see you jump between topics and assume lack of focus, missing that you're following connections that are invisible to linear thinkers. The threads you're weaving look like chaos until the pattern suddenly clicks—and then they act like they saw it all along.\n\nThey say you're not a team player when the truth is you just process faster alone. Group brainstorming feels like running through water. You're not antisocial; you're computationally mismatched. The latency of group consensus is genuinely painful when you've already seen the answer.\n\nThey think you don't care about execution because you're more excited by ideas. What they miss is that execution without vision is just motion. You care intensely about outcomes—you just can't stay interested in implementing ideas that shouldn't have been started in the first place.\n\nThe deepest misread: they think your future-focus means you're not present. You are profoundly present—just to a larger slice of time than they can perceive.",

  "hiddenSuperpower": "You can see the second and third-order effects of decisions that others treat as simple. While they're solving for today, you're already watching how this plays out in six months, modeling the cascade of consequences they'll call \"unforeseeable\" when they arrive exactly as you foresaw.\n\nThis isn't anxiety—it's pattern recognition operating on a longer timeline. You've probably known certain relationships, jobs, or projects were doomed long before the evidence was obvious to anyone else. You felt structural instability while others were still admiring the architecture.\n\nYour superpower extends beyond prediction into synthesis. You can take concepts from completely unrelated domains and find the isomorphic structure beneath them. While specialists see their field, you see the meta-patterns that connect fields. This makes you capable of innovations that domain experts dismiss as impossible—until you build them.\n\nYou also have an unusual capacity for holding uncertainty productively. Where others need to resolve ambiguity quickly, you can let multiple possibilities coexist, allowing the pattern to emerge rather than forcing premature closure.\n\nPerhaps most valuably: you can imagine futures that don't yet exist and work backward to find the path. This isn't daydreaming—it's reverse-engineering possibility space. You see the destination clearly enough to navigate toward it through fog that stops others completely.",

  "blindSpot": "You assume others see the connections you see. When they don't act on what seems obvious, you read it as stubbornness or stupidity when it's actually a different perceptual reality. They're not ignoring the pattern—they literally cannot see it without concrete evidence you consider unnecessary.\n\nYou also underestimate how much your future-focus can feel like dismissiveness of present concerns. When someone brings you a current problem and you immediately start talking about long-term implications, they may feel unheard. Their present is real to them.\n\nYour self-referential processing creates another blind spot: you may over-trust your own pattern recognition. The same capacity that lets you see what others miss can also generate false patterns—compelling connections that feel true but aren't. Without external validation, you can build elaborate castles on foundations that don't exist.\n\nFinally, you may systematically undervalue execution and executors. The people who finish things, maintain things, and handle details aren't failing to see the big picture—they're holding reality together while you explore possibility space. Your tendency to dismiss implementation as \"just execution\" blinds you to a form of intelligence you don't possess and genuinely need.",

  "frictionPatterns": "You'll clash most intensely with people anchored in concrete past experience and collective wisdom. They want case studies; you want principles. They ask \"has this worked before?\"; you ask \"could this work now?\" They're thinking about how this affects the group and what history teaches; you've already personalized the application and projected it forward.\n\nThis isn't just disagreement—it's mutual incomprehension. They see your future-focus as reckless disregard for hard-won wisdom. You see their past-focus as anchor-drag on necessary evolution. Neither is wrong; you're optimizing for different temporal horizons.\n\nYou'll also experience friction with processors who need step-by-step linearity. Your network-thinking looks like chaos to them; their linear processing feels like being trapped in a tunnel to you.\n\nYour gift in these frictions: Your vision can give direction to their grounded wisdom.\n\nYour growth edge: Recognizing that their experience-based caution isn't failure to see—it's a different form of seeing that catches things you miss.",

  "energyPatterns": "What drains you:\n- Detailed status meetings where nothing is decided\n- Being asked to \"show your work\" when the answer is obvious\n- Environments that reward process compliance over outcomes\n- Historical deep-dives that don't connect to future application\n- Executing on visions that aren't yours\n\nWhat charges you:\n- Whiteboard sessions where ideas build on each other\n- Problems that have never been solved before\n- Being given the goal and trusted to find the path\n- Intellectual peers who keep up with your pace\n- That moment when someone finally sees what you've been seeing\n- Freedom to explore without justifying every tangent",

  "workEnvironments": "Where you thrive:\n- Environments that value innovation over execution, autonomy over supervision\n- Startups in the exploration phase, research institutions, think tanks, strategic consulting\n- Any role labeled \"visionary,\" \"architect,\" or \"strategist\"\n- High novelty, minimal process overhead, problems without known solutions\n\nWhere you suffocate:\n- Environments that prioritize compliance, standardization, and detailed execution\n- Large bureaucratic organizations\n- Roles focused on maintenance rather than creation\n- Any position where the \"what\" is predetermined and you're only responsible for the \"how\"",

  "blockIndicators": "Your Parser Profile suggests the following CBI block accessibility pattern:\n\nLikely High-Accessibility Blocks:\n- Pattern Recognition (your native mode)\n- Generative Creation (constant ideation)\n- Symbolic Manipulation (abstract reasoning)\n\nLikely Moderate-Accessibility Blocks:\n- Self-Reference Processing (strong but sometimes unexamined)\n- Spatial Relationships (for systems visualization)\n\nLikely Lower-Accessibility Blocks:\n- Sequential Processing (execution and follow-through)\n- Perceptual Discrimination (concrete details)\n- Social Signal Processing (may miss present-moment interpersonal cues)\n\nThis pattern suggests your cognitive architecture is optimized for insight generation and strategic thinking, with developmental opportunities in execution systems and present-moment awareness.\n\nVISIONARY",

  "strengths": [
    {
      "title": "Pattern Recognition Across Domains",
      "description": "You see connections that others miss entirely. Where most people see separate events, you see the underlying structure that connects them. This ability to perceive cross-domain patterns makes you exceptionally good at identifying trends, predicting outcomes, and finding non-obvious solutions to complex problems."
    },
    {
      "title": "Strategic Foresight",
      "description": "Your mind naturally projects current trajectories into the future. You don't just see what is—you see what's likely to become. This temporal reach gives you an almost precognitive ability to anticipate problems before they manifest, and opportunities before they're obvious to others."
    },
    {
      "title": "Conceptual Compression",
      "description": "You can take vast amounts of information and compress it into elegant principles. Where others get lost in the details, you extract the essential structure. This makes you valuable for simplifying complexity, creating frameworks, and teaching others to see what you see."
    },
    {
      "title": "Independent Synthesis",
      "description": "You don't need external validation to trust your insights. Your self-referential processing means you can evaluate ideas on their internal coherence rather than their social acceptance. This cognitive independence makes you resistant to groupthink and capable of holding unpopular positions that later prove correct."
    },
    {
      "title": "Rapid Ideation",
      "description": "Ideas come to you faster than you can capture them. Your abstract-future orientation means you're constantly generating possibilities, variations, and innovations. You're never short on concepts—only on time to develop them all."
    },
    {
      "title": "Systems Thinking",
      "description": "You naturally think in terms of systems rather than components. You see how parts interact, how changes propagate, and how interventions create ripple effects. This holistic perspective makes you invaluable for strategy, design, and any work requiring understanding of complex interdependencies."
    }
  ],

  "challenges": [
    {
      "title": "Execution Gap",
      "challenge": "You generate ideas far faster than you can implement them. Once you've solved a problem conceptually, the actual execution feels like paperwork. This can lead to a pattern of brilliant starts and abandoned middles—not from lack of discipline, but because your brain has already moved to the next interesting problem.",
      "remedy": "Partner deliberately. Find someone who gets energy from execution—what drains you charges them. Alternatively, design systems where execution generates new data that feeds your pattern recognition. Make finishing a source of insight, not just closure."
    },
    {
      "title": "Communication Friction",
      "challenge": "What's obvious to you often requires extensive explanation for others. You can see the destination clearly, but articulating the path is tedious. This leads to frustration on both sides—you feel slowed down, others feel lost.",
      "remedy": "Develop translation protocols. Before sharing an insight, ask: \"What do they need to see first?\" Build a bridge backward from your conclusion. Use concrete examples and analogies—borrow Concrete language deliberately. Treat communication as a design problem worth solving."
    },
    {
      "title": "Detail Blindness",
      "challenge": "Your abstract orientation can cause you to miss or dismiss important specifics. You're so focused on the forest that individual trees become invisible—even when those trees matter. This can create blind spots in execution where critical details fall through the cracks.",
      "remedy": "Create detail checkpoints. Before finalizing any plan, run it past someone with Concrete processing and actually listen. Build checklists for domains where details matter—not because you'll naturally use them, but because you'll forget things without them."
    },
    {
      "title": "Present-Moment Disconnection",
      "challenge": "Living in the future means you can miss what's happening now. Relationships, experiences, and opportunities that exist in the present may feel less compelling than the possibilities you're tracking ahead. This temporal displacement can cost you connection and joy.",
      "remedy": "Schedule presence. Literally block time where future-thinking is off-limits. Use physical anchors—exercise, cooking, hands-on activities—to pull you into now. When with people you care about, practice noticing: What are they feeling right now? Treat presence as a skill to develop."
    },
    {
      "title": "Impatience with Process",
      "challenge": "You see where things need to go and struggle to tolerate the slow path of getting there. Meetings, consensus-building, and incremental progress feel painfully inefficient when you've already seen the answer. This impatience can damage relationships and derail your influence.",
      "remedy": "Reframe process as data. Others' slower processing isn't obstruction—it's information about implementation challenges you may have missed. Their questions reveal gaps in your model. Use process as a stress-test for your vision rather than a delay of it."
    },
    {
      "title": "Validation Isolation",
      "challenge": "Your ideas often exist in a space where others can't yet evaluate them. You may spend years knowing something is true without anyone else understanding or agreeing. This intellectual loneliness is a genuine cost of running ahead of the pack.",
      "remedy": "Find your wavelength. Seek communities—online, professional, intellectual—where others operate at similar altitude. You don't need everyone to understand; you need a few people who do. Also practice documenting your predictions with timestamps. When you're eventually proven right, that record provides validation your environment couldn't."
    }
  ]
};
