// VISIONARY Profile
// Parser Profile™ © 2026 Cognition Blocks LLC
// Abstract • Future • Self

export const visionaryProfile = {
  "name": "VISIONARY",
  "code": "Abstract • Future • Self",
  "tagline": "The pattern-seer who lives three steps ahead",
  "overview": "You don't just think, you compute. While others are processing what's\nin front of them, your mind has already mapped the territory ahead,\nconnected it to seven other concepts, and begun exploring implications\nthat won't become obvious to anyone else for months.\n\nThis isn't a choice you make. It's how your brain is wired. Your\nneural architecture prioritizes abstract pattern recognition over\nconcrete detail, future possibilities over present circumstances, and\npersonal meaning over group consensus. The result is a consciousness\nthat naturally operates at a different temporal and conceptual altitude\nthan most people around you.\n\nYou've probably spent your life being told to \"focus\" and \"pay\nattention\" when the truth is you were already paying attention, just to\nsomething three levels deeper than what everyone else was tracking.\nTeachers saw distraction where there was actually advanced computation.\nColleagues saw disengagement where there was parallel processing.\nPartners saw absence where there was profound presence, just not to the\nimmediately visible.\n\nThe Visionary profile represents approximately 8% of the population.\nYou're rare, but not alone. Throughout history, Visionaries have been\nthe ones who saw what was coming before anyone believed them, and then\nwatched the world catch up. Your challenge has never been seeing the\npattern. It's been waiting for everyone else to see it too.\n\nYour cognitive architecture excels at synthesis, abstraction, and\nprojection. You naturally compress complex information into elegant\nprinciples, then project those principles forward to anticipate their\nimplications. This makes you extraordinarily valuable in any context\nrequiring strategic foresight, innovative thinking, or conceptual\nproblem-solving. But it can also make you feel perpetually out of sync\nwith environments that reward execution over insight, compliance over\ncreativity, and present-focus over future-orientation.\n\nUnderstanding your profile isn't about fixing what's \"wrong\" with\nyou. It's about recognizing that you're running different cognitive\nsoftware than most people, and learning to leverage that difference\nrather than apologize for it.",
  "howYouLearn": "You learn by constructing mental models, not by accumulating facts. When\nencountering new information, you immediately begin mapping it to\nexisting frameworks, identifying underlying principles, and projecting\nimplications. Details that don't connect to a larger pattern tend to\nslip away; insights that reveal structure become permanent.\n\nYour optimal learning environment provides concepts first, examples\nsecond. You want to understand the \"why\" before the \"what,\" and the\nprinciple before the procedure. Give you the framework and you'll fill\nin the specifics yourself. Force you through the specifics without the\nframework and you'll feel like you're drowning in noise.\n\nYou learn poorly from rote memorization, step-by-step tutorials, or\nheavily supervised instruction. You learn powerfully from exposure to\nexperts thinking out loud, challenging problems with no clear solution\npath, and freedom to explore tangentially. Your best insights come when\nyou're allowed to make connections on your own rather than having them\npre-made for you.\n\nReading works well for you, especially content that presents frameworks\nand theories. Discussion works better when it's with intellectual\nequals who can keep up with your pace. Hands-on learning works only when\nyou understand the conceptual foundation, without that, physical\nmanipulation feels random and frustrating.",
  "howYouCommunicate": "You communicate in compressed bursts that assume shared context. What\nfeels complete to you often leaves others missing steps, you've\nunconsciously skipped the scaffolding they need to follow your thought.\nLearning to unpack your compression without losing your patience is a\nlifelong practice.\n\nYou're most articulate when thinking out loud to a receptive audience.\nThe presence of an engaged listener helps you externalize your internal\nmonologue in ways that even surprise you. But you struggle with formal\npresentations, written reports, and any format that requires you to\nlinearize your naturally networked thinking.\n\nIn conversation, you tend to jump topic, following connections that are\ninvisible to others. You may interrupt, not from rudeness, but because\nyou've already seen where they're heading and want to accelerate to\nthe interesting part. You may also go silent for lengthy periods, deep\nin internal processing that looks like absence but is actually intense\nengagement.\n\nYou communicate best in environments that tolerate ambiguity, value\nideas over polish, and allow for iteration. You communicate worst in\nformal settings that demand precision, completeness, and linear\nstructure before you've had time to fully develop your thinking.",
  "phrase": "You're not scattered, you're parallel processing. The problem isn't\nyour attention; it's that linear environments punish your\narchitecture.",
  "secret": "You've spent your whole life being told \"focus\" and \"pay attention\nto details\" when the truth is you were already three steps ahead. While\neveryone else was still reading the instructions, you'd already seen\nwhere this was going, and you were right more often than anyone gave you\ncredit for.\n\nThe secret isn't that you're smarter. It's that you're processing on\na different timeline. You see the implications before the evidence\narrives. You feel the pattern before you can prove it. And you've\nlearned to keep quiet about what you see, because explaining it exhausts\nyou and being right too early just makes people defensive.\n\nYou've probably abandoned more half-finished projects than most people\nhave started. Not because you lack discipline, but because once you've\nsolved the interesting part in your head, the execution feels like\npaperwork. Dopamine was in the discovery. The implementation is just...\naccounting.\n\nThere's a loneliness to this that you've rarely named. You've sat in\nmeetings knowing exactly where a decision would lead, watched it unfold\nover months exactly as you predicted, and felt no satisfaction, only the\nfamiliar ache of having seen it coming and been unable to stop it.\nCassandra's curse isn't mythology to you. It's Tuesday.\n\nYou've also carried the weight of your own unrealized potential. You\nknow what you're capable of. You've seen flashes of it. But the gap\nbetween your vision and your output haunts you. Not because you're\nlazy, but because the world doesn't have an interface for the way you\nthink. You've spent years trying to translate yourself into a language\nthat loses everything that matters in translation.",
  "whatOthersGetWrong": "ABOUT YOU \n\nPeople assume you're not listening when you're quiet. When the reality\nis you've already processed what they said, mapped it into seven other\nconcepts, and are now exploring implications they haven't considered\nyet. Your silence isn't disengagement, its computation running at a\ndepth they can't see.\n\nThey call you \"scattered\" when you're actually parallel processing.\nThey see you jump between topics and assume lack of focus, missing that\nyou're following connections that are invisible to linear thinkers. The\nthreads you're weaving look like chaos until the pattern suddenly\nclicks, and then they act like they saw it all along.\n\nThey say you're not a team player when the truth is you just process\nfaster alone. Group brainstorming feels like running through water.\nYou're not antisocial; you're computationally mismatched. The latency\nof group consensus is genuinely painful when you've already seen the\nanswer.\n\nThey think you don't care about execution because you're more excited\nby ideas. What they miss is that execution without vision is just\nmotion. You care intensely about execution, that's productive. Their\ncomplaint that you \"don't follow through\" often means you correctly\nidentified that the thing wasn't worth following through on. But that\ndiscernment looks like flakiness to people who finish everything they\nstart, regardless of whether it should have been started in the first\nplace.\n\nThe deepest misread: they think your future-focus means you're not\npresent. You are profoundly present, just to a larger slice of time than\nthey can perceive.",
  "hiddenSuperpower": "You can see the second and third-order effects of decisions that others\ntreat as simple. While they're solving for today, you're already\nwatching how this plays out in six months, modeling the cascade of\nconsequences they'll call \"unforeseeable\" when they arrive exactly as\nyou foresaw.\n\nThis isn't anxiety, its pattern recognition operating on a longer\ntimeline. You've probably known certain relationships, jobs, or\nprojects were doomed long before the evidence was obvious to anyone\nelse. You felt structural instability while others were still admiring\nthe architecture.\n\nYour superpower extends beyond prediction into synthesis. You can take\nconcepts from completely unrelated domains and find the isomorphic\nstructure beneath them. While specialists see their field, you see the\nmeta-patterns that connect fields. This makes you capable of innovations\nthat domain experts dismiss as impossible, until you build them.\n\nYou also have an unusual capacity for holding uncertainty productively.\nWhere others need to resolve ambiguity quickly, you can let multiple\npossibilities coexist, allowing the pattern to emerge rather than\nforcing premature closure. This tolerance for cognitive complexity lets\nyou see solutions that crystallize only after extended incubation.\n\nPerhaps most valuably: you can imagine futures that don't yet exist and\nwork backward to find the path. This isn't daydreaming, it's reverse\nengineering possibility space. You see the destination clearly enough to\nnavigate toward it through fog that stops others completely. When you\nsay, \"I can see how this could work,\" you're not expressing hope.\nYou're reporting observation.",
  "blindSpot": "You assume others see the connections you see. When they don't act on\nwhat seems obvious, you read it as stubbornness or stupidity when it's\nactually a different perceptual reality. They're not ignoring the\npattern, they literally cannot see it without concrete evidence you\nconsider unnecessary. Often, frustration with their \"resistance\" is\nreally frustration with their architecture, which isn't anyone's\nfault.\n\nYou also underestimate how much your future-focus can feel like\ndismissiveness of present concerns. When someone brings you a current\nproblem and you immediately start talking about long-term implications,\nthey may feel unheard. Their present is real to them. Your tendency to\ntreat it as merely a data point in a larger trajectory can feel cold,\neven when you're trying to help.\n\nYour self-referential processing creates another blind spot: you may\nover-trust your own pattern recognition. The same capacity that lets you\nsee what others miss can also generate false patterns, compelling\nconnections that feel true but aren't. Without external validation, you\ncan build elaborate castles on foundations that don't exist. Your\nconfidence in your vision can become its own trap.\n\nFinally, you may systematically undervalue execution and executors. The\npeople who finish things, maintain things, and handle details aren't\nfailing to see the big picture, they're holding reality together while\nyou explore space. Your tendency to dismiss implementation as \"just\nexecution\" blinds you to a form of intelligence you don't possess and\ngenuinely need.",
  "frictionPatterns": "You clash most intensely with Concrete-Past-Other processors (Legacy\nprofile). They want case studies; you want principles. They ask, \"has\nthis worked before?\"; you ask, \"could this work now?\" They're\nthinking about how this affects the group and what history teaches;\nyou've already personalized the application and projected it forward.\n\nThis isn't just disagreement, it's mutual incomprehension. They see\nyour future-focus as reckless disregard for hard-won wisdom. You see\ntheir past-focus as anchor-drag on necessary evolution. Neither is\nwrong; you're optimizing for different temporal horizons with different\nreference frames.\n\nYou'll also experience friction with high-Sequential processors who\nneed step-by-step linearity. Your network-thinking looks like chaos to\nthem; their linear processing feels like being trapped in a tunnel to\nyou. Collaborative work requires translation protocols neither of you\nnaturally speaks.\n\nPresent-focused processors of any configuration may find you frustrating\nto pin down. You're always partly elsewhere, in the future you're\nmodeling, in the abstract space where patterns live. They want you here,\nand \"here\" is the one place you find hardest to stay.",
  "energyPatterns": "What Drains You:\n\n-   Detailed status meetings where nothing is decided\n\n-   Being asked to \"show your work\" when the answer is obvious\n\n-   Environments that reward process compliance over outcomes\n\n-   People who need to verbally process before they can think\n\n-   Historical deep-dives that don't connect to future application\n\n-   Executing on visions that aren't yours\n\nWhat Charges You:\n\n-   Whiteboard sessions where ideas build on each other\n\n-   Problems that have never been solved before\n\n-   Being given the goal and trusted to find the path\n\n-   Late-night rabbit holes connecting disparate concepts\n\n-   Intellectual peers who keep up with your pace\n\n-   That moment when someone finally sees what you've been seeing\n\n-   Freedom to explore without justifying every tangent\n\n-   Environments that value insight over hours logged",
  "workEnvironments": "You thrive in environments that value innovation over execution,\nautonomy over supervision, and ideas over process. Startups in the\nexploration phase, research institutions, think tanks, strategic\nconsulting, and any role labeled \"visionary,\" \"architect,\" or\n\"strategist\" tend to fit your cognitive architecture.\n\nYou struggle in environments that prioritize compliance,\nstandardization, and detailed execution. Large bureaucratic\norganizations, roles focused on maintenance rather than creation, and\nany position where the \"what\" is predetermined and you're only\nresponsible for the \"how\" will feel like cognitive prison.\n\nKey environmental factors: high novelty, minimal process overhead,\ntolerance for incomplete execution, intellectual peers, and problems\nwithout known solutions.",
  "blockIndicators": "Your Parser Profile suggests the following CBI block accessibility\npattern:\n\nLikely High-Accessibility Blocks:\n\n-   Pattern Recognition (your native mode)\n\n-   Generative Creation (constant ideation)\n\n-   Symbolic Manipulation (abstract reasoning)\n\nLikely Moderate-Accessibility Blocks:\n\n-   Self-Reference Processing (strong but sometimes unexamined)\n\n-   Spatial Relationships (for systems visualization)\n\nLikely Lower-Accessibility Blocks:\n\n-   Sequential Processing (execution and follow-through)\n\n-   Perceptual Discrimination (concrete details)\n\n-   Social Signal Processing (may miss present-moment interpersonal\n    cues)\n\nThis pattern suggests your cognitive architecture is optimized for\ninsight generation and strategic thinking, with potential developmental\nopportunities in execution systems and present-moment awareness.\n\nVISIONARY",
  "strengths": [
    {
      "title": "Pattern Recognition Across Domains You see connections that",
      "description": "others miss entirely. Where most people see separate events, you see the\nunderlying structure that connects them. This ability to perceive\ncross-domain patterns makes you exceptionally good at identifying\ntrends, predicting outcomes, and finding non-obvious solutions to\ncomplex problems."
    },
    {
      "title": "Strategic Foresight Your mind naturally projects current",
      "description": "trajectories into the future. You don't just see what is, you see\nwhat's likely to become. This temporal reach gives you an almost\nprecognitive ability to anticipate problems before they manifest, and\nopportunities before they're obvious to others."
    },
    {
      "title": "Conceptual Compression You can take vast amounts of information",
      "description": "and compress it into elegant principles. Where others get lost in the\ndetails, you extract the essential structure. This makes you valuable\nfor simplifying complexity, creating frameworks, and teaching others to\nsee what you see."
    },
    {
      "title": "Independent Synthesis You don't need external validation to",
      "description": "trust your insights. Your self-referential processing means you can\nevaluate ideas on their internal coherence rather than their social\nacceptance. This cognitive independence makes you resistant to\ngroupthink and capable of holding unpopular positions that later prove\ncorrect."
    },
    {
      "title": "Rapid Ideation Ideas come to you faster than you can capture",
      "description": "them. Your abstract-future orientation means you're constantly\ngenerating possibilities, variations, and innovations. You're never\nshort on concepts, only on time to develop them all."
    },
    {
      "title": "Systems Thinking You naturally think in terms of systems rather",
      "description": "than components. You see how parts interact, how changes propagate, and\nhow interventions create ripple effects. This holistic perspective makes\nyou invaluable for strategy, design, and any work requiring\nunderstanding of complex interdependencies."
    }
  ],
  "challenges": [
    {
      "title": "Execution Gap*",
      "challenge": "You generate ideas far faster than you can implement them.\nOnce you've solved a problem conceptually, the actual execution feels\nlike paperwork. This can lead to a pattern of brilliant starts and\nabandoned middles, not from lack of discipline, but because your brain\nhas already moved to the next interesting problem.",
      "remedy": "Partner deliberately. Find a Concrete-Present processor who\ngets energy from execution, what drains you charges them. Alternatively,\nbuild implementation into the interesting part: design systems where\nexecution generates new data that feeds your pattern recognition. Make\nfinishing a source of insight, not just closure."
    },
    {
      "title": "Communication Friction",
      "challenge": "What's obvious to you often requires extensive explanation\nfor others. You can see the destination clearly, but articulating the\npath is tedious. This leads to frustration on both sides, you feel\nslowed down, others feel lost. Bridging this gap requires patience you\nmay not naturally possess.",
      "remedy": "Develop translation protocols. Before sharing an insight, ask:\n\"What do they need to see first?\" Build a bridge backward from your\nconclusion. Use concrete examples and analogies, borrow Concrete\nlanguage deliberately. Treat communication as a design problem worth\nsolving, not an obstacle to endure."
    },
    {
      "title": "Detail Blindness",
      "challenge": "Your abstract orientation can cause you to miss or dismiss\nimportant specifics. You're so focused on the forest that individual\ntrees become invisible, even when those trees matter. This can create\nblind spots in execution where critical details fall through the cracks.",
      "remedy": "Create detail checkpoints. Before finalizing any plan, run it\npast someone with Concrete processing and actually listen. Build\nchecklists for domains where details matter, not because you'll\nnaturally use them, but because you'll forget things without them.\nRespect the detail layer as real, even if it's not where you live."
    },
    {
      "title": "Present-Moment Disconnection",
      "challenge": "Living in the future means you can miss what's happening\nnow. Relationships, experiences, and opportunities that exist in the\npresent may feel less compelling than the possibilities you're tracking\nahead. This temporal displacement can cost you connection and joy.",
      "remedy": "Schedule presence. Literally block time where future-thinking\nis off-limits. Use physical anchors such as exercise, cooking, hands-on\nactivities to pull you into now. When with people you care about,\npractice noticing: What are they feeling right now? What's happening in\nthis room? Treat presence as a skill to develop, not a limitation to\naccept."
    },
    {
      "title": "Impatience with Process",
      "challenge": "You see where things need to go and struggle to tolerate\nthe slow path of getting there. Meetings, consensus-building, and\nincremental progress feel painfully inefficient when you've already\nseen the answer. This impatience can damage relationships and derail\nyour influence.",
      "remedy": "Reframe process as data. Others' slower processing isn't\nobstruction; it's information about implementation challenges you may\nhave missed. Their questions reveal gaps in your model. Their resistance\nflags are of real concern. Use process as a stress-test for your vision\nrather than a delay of it. The insight you need might come from the\nmeeting you're dreading."
    },
    {
      "title": "Validation Isolation",
      "challenge": "Your ideas often exist in a space where others can't yet\nevaluate them. You may spend years knowing something is true without\nanyone else understanding or agreeing. This intellectual loneliness is a\ngenuine cost of running ahead of the pack.",
      "remedy": "Find your wavelength. Seek communities, online, professional,\nintellectual, where others operate at similar altitude. You don't need\neveryone to understand; you need a few people who do. Also practice\ndocumenting your predictions with timestamps. When you're eventually\nproven right, that record provides the validation your environment\ncouldn't.\n\n*"
    }
  ]
};
