// VISIONARY Profile — Young Adult (18–29)
// Parser Profile™ © 2026 Cognition Blocks LLC

export const visionaryyaProfile = {
  "name": "VISIONARY",
  "tagline": "The one who already saw where this was going",

  "overview": "While the group's still arguing about which apartment to tour, you've already mapped how this whole living situation plays out—who's going to flake on rent by month three, which two roommates are going to stop speaking, the whole arc of it. You're not psychic. Your brain just runs ahead automatically, connecting this to seven other things and exploring where it all lands months before it's obvious to anyone else.\n\nThis isn't a choice you make. It's how you're wired. Your mind reaches for the pattern over the detail, the future over right now, what something means to you over what the group agrees on. The result is that you're basically operating at a different altitude than most people in the room, on a different timeline.\n\nYou've spent your whole life getting told to \"focus\" and \"pay attention\"—when the truth is you were paying attention, just to something three levels deeper than what everyone else was tracking. Teachers saw a kid staring out the window; there was actually heavy computation happening. Group projects saw you checked out; you'd already solved the interesting part and couldn't fake interest in the rest.\n\nYou're great at synthesis—taking a pile of messy stuff and compressing it into one clean idea, then shooting that idea forward to see what it leads to. That makes you genuinely valuable anywhere that needs someone to see around the next corner. It also makes you feel permanently out of sync with classes, jobs, and group chats that reward doing the assigned thing over seeing the bigger thing. This isn't about fixing what's wrong with you. You're running different software than most people, and the move is to leverage that, not apologize for it.",

  "howYouLearn": "You learn by building a mental model, not by collecting facts. New information hits and you immediately start mapping it onto stuff you already understand, hunting for the underlying principle, projecting where it leads. Details that don't connect to a bigger pattern just slide off and vanish by the next day. The insight that reveals how something actually works becomes permanent.\n\nYou need the concept first, the examples second. You want the \"why\" before the \"what,\" the principle before the steps. Give you the framework and you'll fill in the specifics yourself, fast. Drag you through the specifics with no framework—the way most lectures and onboarding docs are built—and you feel like you're drowning in random noise.\n\nYou learn badly from pure memorization, step-by-step tutorials, and heavily supervised \"do exactly this\" instruction. You learn powerfully from watching someone who's brilliant think out loud, from a problem nobody's solved yet, from being handed the freedom to wander down a tangent. Your best insights show up when you get to make the connection yourself instead of having it pre-chewed for you.\n\nDiscussion works when it's with people who can actually keep up with your pace—the friend or the professor who can volley. Hands-on learning works only once you've got the conceptual foundation; without the why underneath it, doing the steps feels random and makes you want to quit.",

  "howYouCommunicate": "You talk in compressed bursts that assume the other person already has your context. What feels complete to you leaves people missing steps—you skipped the scaffolding in your head without realizing it. Learning to unpack that compression without getting impatient is going to be a lifelong project for you.\n\nYou're sharpest thinking out loud to someone who's actually engaged. The right listener pulls your internal processing out of you in a way that even surprises you mid-sentence. But formal stuff—the presentation, the written report, the structured email—is brutal, because it forces you to linearize a brain that runs more like a web than a line.\n\nIn conversation you jump topics, following links nobody else can see. You'll interrupt—not to be rude, but because you already saw where they were going and want to skip to the interesting part. You'll also go silent for long stretches, deep in processing that looks like you've left the chat but is actually you locked all the way in.\n\nYou communicate best where ambiguity is fine, ideas matter more than polish, and iteration is expected. You communicate worst in formal settings that demand precision and completeness and a clean linear structure before you've even had room to fully develop the idea.",

  "phrase": "You're not scattered—you're parallel processing. The problem was never your attention. It's that linear classrooms and jobs punish the way your brain is actually built.",

  "secret": "You've spent your whole life getting told to focus and sweat the details, when the truth is you were already three steps ahead. While everyone was still reading the instructions, you'd seen where it was going—and you were right way more often than anyone gave you credit for.\n\nThe secret isn't that you're smarter. It's that you're running on a different timeline. You see the implications before the proof shows up. You feel the pattern before you can explain it. And you've learned to shut up about what you see, because explaining it wears you out and being right too early just makes people defensive and weird with you.\n\nYou've probably abandoned more half-finished projects than most people have started. Not because you're lazy—because once you solved the interesting part in your head, the actual execution feels like paperwork. The hit was in the discovery. The build-out is just... data entry. You'll start the thing on fire and lose the spark the second it stops being a puzzle.\n\nThere's a loneliness to this you've barely named. You've sat in a group project or a job knowing exactly where a decision was headed, watched it play out over weeks exactly like you called it, and felt zero satisfaction—just the familiar ache of having seen it coming and not been able to stop it. And you carry the weight of your own potential. You know what you're capable of. You've felt flashes of it. But the gap between what you can see in your head and what you actually produce haunts you—because the world doesn't have an interface for how you think, and you've spent years trying to translate yourself into a language that loses everything that mattered.",

  "whatOthersGetWrong": "They assume you're not listening when you go quiet. The reality is you already processed what they said, mapped it onto seven other things, and you're off exploring implications they haven't even reached yet. Your silence isn't you checking out—it's computation running deeper than they can see.\n\nThey call you scattered when you're actually running parallel. They watch you jump between topics and assume you can't focus, missing that you're following real connections that are invisible to linear thinkers. The threads you're weaving look like chaos right up until the pattern snaps into place—and then they act like they saw it the whole time.\n\nThey say you're not a team player when the truth is you just process faster alone. Group brainstorms feel like sprinting through water. You're not antisocial—you're computationally mismatched, and the lag of waiting for a group to reach a conclusion you got to ten minutes ago is genuinely painful. And they think you don't care about getting things done because you're more lit up by ideas. What they miss is that execution without vision is just motion. You care intensely about outcomes—you just can't force yourself to grind on implementing an idea that shouldn't have been started.\n\nThe deepest misread: they think your future-focus means you're not present. You're profoundly present—just to a way bigger slice of time than they can perceive.",

  "hiddenSuperpower": "You can see the second- and third-order effects of decisions everyone else treats as simple. While they're solving for tonight, you're already watching how it plays out over the next semester, modeling the chain of consequences they'll call \"unforeseeable\" when it arrives exactly the way you foresaw.\n\nThis isn't anxiety—it's pattern recognition running on a longer timeline. You've probably known a relationship, a friend group, or a plan was doomed long before the evidence was obvious to anyone. You felt the structural instability while everyone else was still admiring how good it looked.\n\nYour superpower goes past prediction into synthesis. You can take ideas from totally unrelated places—a thing from a game, a thing from a class, a thing from a job—and find the identical structure hiding underneath both. While specialists see only their lane, you see the meta-pattern connecting lanes. That's what makes you capable of ideas that experts call impossible right up until someone builds them.\n\nYou've also got an unusual ability to hold uncertainty without panicking. Where most people need to lock down an answer fast, you can let several possibilities sit open and let the pattern emerge instead of forcing it shut early. And maybe most valuably: you can imagine a future that doesn't exist yet and work backward to find the path to it. That's not daydreaming—it's reverse-engineering possibility. You can see the destination clearly enough to navigate toward it through fog that stops other people cold.",

  "blindSpot": "You assume other people see the connections you see. So when they don't act on what's obvious to you, you read it as them being stubborn or slow—when it's actually that they live in a different perceptual reality. They're not ignoring the pattern. They literally can't see it without the concrete evidence you consider unnecessary.\n\nYou also underestimate how much your future-focus can feel like you're blowing off someone's present. A friend brings you a problem that's eating them right now, and you immediately jump to long-term implications and what it means six months out—and they walk away feeling unheard. Their right-now is real and urgent to them, even if you've already mentally skipped past it.\n\nYour self-referential wiring sets another trap: you can over-trust your own pattern recognition. The same machinery that lets you see what others miss can also generate false patterns—connections that feel completely true but aren't real. With nobody to check you, you can build an elaborate castle on a foundation that doesn't exist, and be totally certain the whole time.\n\nAnd you systematically undervalue the people who execute. The friend who actually finishes things, handles the details, shows up and maintains stuff—they're not failing to see the big picture. They're holding reality together while you go explore possibility space. Writing them off as \"just doing the boring part\" blinds you to a kind of intelligence you don't have and genuinely need.",

  "frictionPatterns": "You clash hardest with people anchored in concrete past experience and what the group already knows. They want examples; you want principles. They ask \"has this worked before?\"; you ask \"could this work now?\" They're thinking about how it affects everyone and what history says; you've already personalized it and shot it forward into the future. To them your future-focus looks reckless, like you're ignoring hard-won wisdom. To you their past-focus feels like an anchor dragging on something that obviously needs to change. Neither of you is wrong—you're just optimizing for different stretches of time.\n\nYou'll also grind against the people who need everything step-by-step and in order. Your web-thinking looks like pure chaos to them; their linear processing feels like being trapped in a tunnel to you. Group projects where one person needs the whole plan locked before starting can make you want to walk into the sea.\n\nAnd anyone who treats your ideas as \"unrealistic\" without engaging with them gets under your skin, because you've watched plenty of \"realistic\" plans crawl when they could've leapt. The fast no from someone who didn't actually think about it is its own specific frustration.\n\nYour gift inside these frictions: your vision can give direction to their grounded steadiness—you point at where to go, they make sure you actually get there. Your growth edge: realizing their caution isn't a failure to see. It's a different kind of seeing that catches the exact things you miss.",

  "energyPatterns": "What drains you:\n- Long status meetings or group check-ins where nothing actually gets decided\n- Being told to \"show your work\" when the answer's already obvious to you\n- Classes and jobs that reward following the process over getting the outcome\n- Deep-dives into how it was always done that never connect to what's next\n- Grinding out execution on someone else's vision you don't even believe in\n- Waiting for a group to slowly arrive at the answer you saw ten minutes ago\n\nWhat charges you:\n- A whiteboard or late-night session where ideas keep building on each other\n- A problem nobody's solved before\n- Being handed the goal and trusted to find the path yourself\n- People who can actually keep up with your pace\n- The moment someone finally sees what you've been seeing all along\n- Freedom to chase a tangent without justifying every turn",

  "workEnvironments": "Where you thrive:\n- Places that value new ideas over rote execution, autonomy over being supervised\n- Early-stage startups, research, creative and strategy work, anything in the exploration phase\n- Roles where the whole point is figuring out what should exist, not maintaining what does\n- High novelty, low process overhead, problems with no known answer\n- Teams that hand you the goal and trust you to find the path\n\nWhere you suffocate:\n- Places that prize compliance, standardization, and exact execution above all\n- Big, slow, bureaucratic organizations with a rule for everything\n- Roles that are all maintenance and zero creation\n- Any job where the \"what\" is already decided and you're only on the hook for the \"how\"\n- Settings that punish a tangent instead of seeing where it leads",

  "topCareers": [
    {
      "title": "Startup Early Hire / Founder Track",
      "description": "While the room is still defining the problem, you've already mapped where it leads and connected it to six things nobody's named yet. Early-stage startups—or starting your own thing—run on exactly that. You're not built to execute a plan someone hands you; you're built to author the plan that doesn't exist yet, the one that reads as obvious only after you've drawn it. You thrive in the exploration phase, before the path is paved, where the question is \"what could this be\" instead of \"how do we maintain it.\" The restlessness that made every normal job feel like a cage is the same drive that starts the thing from nothing."
    },
    {
      "title": "Strategy / Innovation / Product Role",
      "description": "You compress a pile of messy information into one clean idea and then shoot it forward to see where it lands—which is the actual job of the person companies pay to see around the next bend. Entry points in strategy, product, and innovation reward that synthesis: seeing the trajectory, spotting the move nobody else has, framing the problem so the answer becomes obvious. The pattern you can't stop noticing becomes the thing an organization finally pays you to notice on purpose, instead of the thing teachers told you to stop doing."
    },
    {
      "title": "Research / Creative Generalist",
      "description": "You see the shape of things before they fully form and you've spent your life arriving at conclusions other people reach months later. In research, writing, design, or any creative generalist track, that earliness stops being a social liability and becomes the product. You get paid to operate at the altitude that always felt lonely—tracking where things are heading, connecting fields nobody connects, generating more ideas than you have time to build. What got called distraction in school was advanced computation; here it's just called insight, and it's the whole point of the role."
    }
  ],

  "blockIndicators": "Your Parser Profile suggests the following CBI block accessibility pattern:\n\nLikely High-Accessibility Blocks:\n- Pattern Recognition (your native mode)\n- Generative Creation (constant ideation)\n- Symbolic Manipulation (abstract reasoning)\n\nLikely Moderate-Accessibility Blocks:\n- Self-Reference Processing (strong but sometimes unexamined)\n- Spatial Relationships (for systems visualization)\n\nLikely Lower-Accessibility Blocks:\n- Sequential Processing (execution and follow-through)\n- Perceptual Discrimination (concrete details)\n- Social Signal Processing (may miss present-moment interpersonal cues)\n\nThis pattern suggests your cognitive architecture is optimized for generating insight and seeing where things are going, with room to grow in actually finishing things and tuning into the present moment in front of you.\n\nVISIONARY",

  "strengths": [
    {
      "title": "Connecting Things Nobody Else Connects",
      "description": "You see links other people miss entirely. Where most see separate, unrelated stuff, you see the structure underneath that ties it together. That cross-domain wiring is why you're so good at spotting a trend early, calling where something's headed, and finding the non-obvious answer to a problem everyone else is stuck on."
    },
    {
      "title": "Seeing Around the Corner",
      "description": "Your mind automatically takes the current trajectory and runs it forward. You don't just see what is—you see what it's about to become. That reach into the future gives you an almost eerie ability to call a problem before it shows up and spot an opportunity before it's obvious to anyone else in the room."
    },
    {
      "title": "Compressing the Chaos",
      "description": "You can take a giant pile of information and crush it down into one clean idea. Where others get lost in the details, you grab the essential structure underneath. That's what makes you the person who can simplify something complicated and finally make a confused group go \"oh, that's all it is.\""
    },
    {
      "title": "You Don't Need the Crowd to Agree",
      "description": "You don't need everyone else to validate an idea before you trust it. Your self-referential wiring lets you judge a thing on whether it actually holds together, not on whether it's popular. That independence makes you resistant to going along with the group and capable of holding an unpopular take that turns out to be right."
    },
    {
      "title": "Ideas Faster Than You Can Catch Them",
      "description": "Ideas come at you faster than you can write them down. Your abstract-future wiring means you're constantly generating possibilities, variations, what-ifs. You're never short on concepts—only on the time and focus to actually build them all out, which is its own problem, but a good one to have."
    },
    {
      "title": "You Think in Systems",
      "description": "You naturally think in whole systems, not separate parts. You see how the pieces interact, how a change in one spot ripples out everywhere else, how one small move sets off a chain reaction. That whole-picture view makes you genuinely valuable for anything that requires understanding how a bunch of moving parts actually fit together."
    }
  ],

  "challenges": [
    {
      "title": "The Abandoned-Project Graveyard",
      "challenge": "You generate ideas way faster than you can build them. Once you've solved the interesting part in your head, the actual execution feels like paperwork, so you've got a trail of brilliant starts and abandoned middles. Not from lack of discipline—your brain already left for the next puzzle.",
      "remedy": "Partner up on purpose. Find someone who actually gets energy from finishing—what drains you charges them. Or build it so the boring execution generates new data that feeds your pattern recognition. Make finishing a source of fresh insight, not just closure, and your brain will actually want to stay."
    },
    {
      "title": "Nobody's Following You",
      "challenge": "What's obvious to you takes a paragraph of explaining for everyone else. You can see the destination clearly, but spelling out the path is tedious, so you skip it—and end up frustrated that people feel lost and they feel like you're talking down to them.",
      "remedy": "Build a bridge backward from your conclusion. Before you drop an insight, ask: \"what do they need to see first?\" Use a concrete example or a comparison they already get—borrow plain, grounded language on purpose. Treat communication like a design problem worth solving instead of an annoying tax."
    },
    {
      "title": "Details Falling Through the Cracks",
      "challenge": "Your big-picture wiring makes you miss or wave off important specifics. You're so locked onto the forest that individual trees go invisible—even the ones that matter. That's how critical little details slip through and quietly wreck an otherwise great plan.",
      "remedy": "Build detail checkpoints. Before you lock anything in, run it past someone who's wired for the concrete stuff and actually listen. Make a checklist for the areas where details bite—not because you'll naturally want to use it, but because you'll forget things without it. The checklist isn't an insult to your intelligence; it's insurance for it."
    },
    {
      "title": "Living Ahead of Right Now",
      "challenge": "Living in the future means missing what's actually happening now. The relationship, the experience, the friend in front of you can feel less compelling than the possibilities you're tracking ahead—and that costs you real connection and real joy you can't get back.",
      "remedy": "Schedule presence on purpose. Literally block time where future-thinking is off the table. Use physical anchors—a workout, cooking, anything hands-on—to drag you into now. When you're with people you care about, practice actually noticing: what are they feeling right now? Treat presence like a skill you're building, because it is one."
    },
    {
      "title": "Impatient With the Slow Path",
      "challenge": "You see where things need to go and can't stand the slow grind of getting there. Group consensus, meetings, incremental progress—it all feels painfully inefficient when you already saw the answer. That impatience leaks out and can wreck relationships and torch your own influence.",
      "remedy": "Reframe the slow path as data. Other people's slower processing isn't them obstructing you—it's information about real implementation problems you skipped over. Their questions expose gaps in your model. Use the process as a stress-test for your vision instead of treating it as a delay of your obviously-correct plan."
    },
    {
      "title": "Right Too Early, Alone",
      "challenge": "Your ideas often live in a space where no one around you can even evaluate them yet. You can spend months knowing something's true while nobody understands or agrees. That intellectual loneliness is a real cost of running ahead of the pack, and it wears on you.",
      "remedy": "Find your wavelength. Hunt for the communities—online, in a club, in a field—where people run at a similar altitude. You don't need everyone to get you; you need a few who do. And start documenting your predictions with a timestamp. When you turn out right, that record is the validation your immediate environment couldn't give you."
    }
  ]
};
