// Builds mobile/www — the Capacitor webDir — from the static frontend at the
// repo root. Self-contained: copies only client assets (HTML + profile data
// modules), never server.js, node_modules, or anything backend.
//
// Two run modes for the app (see MOBILE.md):
//   1. LIVE (recommended): capacitor.config.json `server.url` loads the deployed
//      Railway site. www/ is just a fallback shell. All relative /api calls work.
//   2. BUNDLED (advanced): remove `server.url`, ship these assets in the binary,
//      and set window.PARSER_API_BASE (see app-config.js below) so the bundled
//      pages call the remote API.

import { readdirSync, mkdirSync, copyFileSync, writeFileSync, rmSync, statSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..', '..');      // repo root
const WWW = join(__dirname, '..', 'www');      // mobile/www

// Client files to bundle. We copy every .html and .js EXCEPT the backend.
const EXCLUDE = new Set(['server.js']);
const INCLUDE_EXT = ['.html', '.js'];

rmSync(WWW, { recursive: true, force: true });
mkdirSync(WWW, { recursive: true });

let copied = 0;
for (const name of readdirSync(ROOT)) {
  const src = join(ROOT, name);
  if (!statSync(src).isFile()) continue;
  if (EXCLUDE.has(name)) continue;
  if (!INCLUDE_EXT.some((e) => name.endsWith(e))) continue;
  copyFileSync(src, join(WWW, name));
  copied++;
}

// Capacitor requires an index.html entry point. The web app's home is
// assessment.html (the server redirects / → /assessment.html), so mirror that.
writeFileSync(
  join(WWW, 'index.html'),
  `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8">
<meta http-equiv="refresh" content="0; url=assessment.html">
<title>Parser Profile</title></head>
<body style="background:#0C2340"></body></html>\n`
);

// Bundled-mode API base. Harmless in LIVE mode (same-origin). In BUNDLED mode,
// set this to your Railway origin and update the frontend fetch() calls to
// prefix window.PARSER_API_BASE (see MOBILE.md → "Bundled mode").
writeFileSync(
  join(WWW, 'app-config.js'),
  `// Auto-generated by build-www.mjs. Edit the value for BUNDLED mode.\n` +
  `window.PARSER_API_BASE = window.PARSER_API_BASE || "";\n`
);

console.log(`build:www → copied ${copied} client files into ${WWW}`);
